force-app/main/default/objects/Card_Payment_Plan_Settings__c/Card_Payment_Plan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Card Payment Plan Settings</label>
</CustomObject>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Min_Days_Before_First_Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Min_Days_Before_First_Recurring_Payment__c</fullName>
    <description>Represents the number of days before the end of the current month to decide when the first recurring payment will happen:
1. If today is equal or less days before the 1st day of the next month (comparing to the number) then the first recurring payment will be paid on the 1st day of the month that is next to the next month.
2. Otherwise, the first recurring payment will be paid on the 1st day of the next month.</description>
    <label>Min Days Before First Recurring Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Min_Days_Fully_Paid_Before_Course_Start__c.field-meta.xml
<CustomField>
    <fullName>Min_Days_Fully_Paid_Before_Course_Start__c</fullName>
    <description>Represents the number of days the course fee must be fully paid before the course starts. Otherwise, the payment option is not available.
This applies to all course types.</description>
    <label>Min Days Fully Paid Before Course Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_First_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_First_Amount__c</fullName>
    <description>Represents the minimal possible amount of the intial payment when calculating payment plan options</description>
    <label>Minimum First Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_Recurring_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Recurring_Amount__c</fullName>
    <description>Represents the minimal possible amount of the recurring payment when calculating payment plan options</description>
    <label>Minimum Recurring Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentPlanOptionsControllerTest.cls
@isTest
public with sharing class PaymentPlanOptionsControllerTest {
    @isTest
    static void paymentPlanOptionsTest() {

        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        cardPaymentPlanSettings.Min_Days_Fully_Paid_Before_Course_Start__c = 28;
        cardPaymentPlanSettings.Minimum_First_Amount__c = 10;
        cardPaymentPlanSettings.Minimum_Recurring_Amount__c = 30;
        insert cardPaymentPlanSettings;

        Test.startTest();
            Decimal courseFee = 250;
            Date courseStartDate = System.today().addMonths(5);
            List<PaymentPlanOption> paymentPlanOptionList = PaymentPlanOptionsController.getOptions(courseFee, courseStartDate);
            System.assertEquals(3, paymentPlanOptionList.size(), 'expecting three payment options');

            courseFee = 100;
            courseStartDate = System.today().addMonths(3);
            paymentPlanOptionList = PaymentPlanOptionsController.getOptions(courseFee, courseStartDate);
            System.assertEquals(1, paymentPlanOptionList.size(), 'expecting one payment option');
        Test.stopTest();

    }

}