force-app/main/default/objects/Card_Payment_Plan_Settings__c/Card_Payment_Plan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Card Payment Plan Settings</label>
</CustomObject>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Maximum_Days_Before_Paid__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Days_Before_Paid__c</fullName>
    <description>Represents the number of days the course fee must be fully paid before the course starts. Otherwise, the payment option is not available.
This applies to all course types.</description>
    <label>Maximum Days Before Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Min_Days_Before_First_Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Min_Days_Before_First_Recurring_Payment__c</fullName>
    <description>Represents the number of days before the end of the current month to decide when the first recurring payment will happen:
1. If today is equal or less days before the 1st day of the next month (comparing to the number) then the first recurring payment will be paid on the 1st day of the month that is next to the next month.
2. Otherwise, the first recurring payment will be paid on the 1st day of the next month.</description>
    <label>Min Days Before First Recurring Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_First_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_First_Amount__c</fullName>
    <description>Represents the minimal possible amount of the intial payment when calculating payment plan options</description>
    <label>Minimum First Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_Recurring_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Recurring_Amount__c</fullName>
    <description>Represents the minimal possible amount of the recurring payment when calculating payment plan options</description>
    <label>Minimum Recurring Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentPlanOptionsTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
@isTest
public class PaymentPlanOptionsTest {
    @testSetup
    static void createTestData() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimum_First_Amount__c = 30;
        cardPaymentPlanSettings.Minimum_Recurring_Amount__c = 10;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
    }
    @isTest
    static void CourseFeeLessThanMinimum_CourseFeeTooSmall_NoOptionsGenerated() {
        Integer courseFee = 20;
        Date courseStartDate = Date.newInstance(2020, 6, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 0);
        Test.stopTest();
    }
    @isTest
    static void NextMonthFirstRecurringPayment_InitialPaymentEarlyDayOfTheMonth_FirstPaymentNextMonth() {
        Integer courseFee = 200;
        Date courseStartDate = Date.newInstance(2020, 6, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 1, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 1, 31));
        System.assertEquals(options[0].displayLabel, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].endDate, Date.newInstance(2020, 2, 29));
        System.assertEquals(options[1].displayLabel, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        System.assertEquals(options[2].endDate, Date.newInstance(2020, 3, 31));
        System.assertEquals(options[2].displayLabel, '4 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void AfterNextMonthFirstRecurringPayment_InitialPaymentLaterDayOfTheMonth_FirstPaymentAfterNextMonth() {
        Integer courseFee = 200;
        Date courseStartDate = Date.newInstance(2020, 6, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 25));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 2, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 2, 29));
        System.assertEquals(options[0].displayLabel, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].endDate, Date.newInstance(2020, 3, 31));
        System.assertEquals(options[1].displayLabel, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        System.assertEquals(options[2].endDate, Date.newInstance(2020, 4, 30));
        System.assertEquals(options[2].displayLabel, '4 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void DatesOneRecurringPayment_TwoMonthBefore_OneOptionGenerated() {
        Integer courseFee = 200;
        Date courseStartDate = Date.newInstance(2020, 2, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 1);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 1, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 1, 31));
        System.assertEquals(options[0].displayLabel, '2 monthly payment of £ 100.00');
        Test.stopTest();
    }
    @isTest
    static void DatesTwoRecurringPayment_TwoMonthBefore_TwoOptionGenerated() {
        Integer courseFee = 200;
        Date courseStartDate = Date.newInstance(2020, 3, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 2);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 1, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 1, 31));
        System.assertEquals(options[0].displayLabel, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].endDate, Date.newInstance(2020, 2, 29));
        System.assertEquals(options[1].displayLabel, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        Test.stopTest();
    }
    @isTest
    static void FeeOneRecurringPayment_FeeSmall_OneOptionGenerated() {
        Integer courseFee = 45;
        Date courseStartDate = Date.newInstance(2020, 6, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 1);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 1, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 1, 31));
        System.assertEquals(options[0].displayLabel, '1 payment of £ 30.00 and 1 monthly payment of £ 15.00');
        Test.stopTest();
    }
    @isTest
    static void FeeTwoRecurringPayment_FeeMedium_TwoOptionsGenerated() {
        Integer courseFee = 55;
        Date courseStartDate = Date.newInstance(2020, 6, 1);
        PaymentPlanGenerator.clock = new PaymentPlanMockClock(Date.newInstance(2019, 12, 5));
        Test.startTest();
        List<PaymentPlanOption> options = PaymentPlanGenerator.getOptions(courseFee, courseStartDate);
        System.assertEquals(options.size(), 2);
        System.assertEquals(options[0].startDate, Date.newInstance(2020, 1, 1));
        System.assertEquals(options[0].endDate, Date.newInstance(2020, 1, 31));
        System.assertEquals(options[0].displayLabel, '1 payment of £ 30.00 and 1 monthly payment of £ 25.00');
        System.assertEquals(options[1].endDate, Date.newInstance(2020, 2, 29));
        System.assertEquals(options[1].displayLabel, '1 payment of £ 30.00 and 2 monthly payment of £ 12.50');
        Test.stopTest();
    }
}