force-app/main/default/objects/Card_Payment_Plan_Settings__c/Card_Payment_Plan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Card Payment Plan Settings</label>
</CustomObject>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Maximum_Days_Before_Paid__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Days_Before_Paid__c</fullName>
    <description>Represents the number of days the course fee must be fully paid before the course starts. Otherwise, the payment option is not available.
This applies to all course types.</description>
    <label>Maximum Days Before Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Min_Days_Before_First_Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Min_Days_Before_First_Recurring_Payment__c</fullName>
    <description>Represents the number of days before the end of the current month to decide when the first recurring payment will happen:
1. If today is equal or less days before the 1st day of the next month (comparing to the number) then the first recurring payment will be paid on the 1st day of the month that is next to the next month.
2. Otherwise, the first recurring payment will be paid on the 1st day of the next month.</description>
    <label>Min Days Before First Recurring Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_First_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_First_Amount__c</fullName>
    <description>Represents the minimal possible amount of the intial payment when calculating payment plan options</description>
    <label>Minimum First Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimum_Recurring_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Recurring_Amount__c</fullName>
    <description>Represents the minimal possible amount of the recurring payment when calculating payment plan options</description>
    <label>Minimum Recurring Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentPlanGenerator.cls
public with sharing class PaymentPlanGenerator {
    @TestVisible private static IClock clock = new SystemClock();
    private static Date initialPaymentDate;
    private static final Integer MAX_DAYS_BEFORE_PAID = Integer.valueOf(Card_Payment_Plan_Settings__c.getOrgDefaults().Maximum_Days_Before_Paid__c);
    private static final Integer MAX_RECURRING_INSTALLMENTS_NUMBER = 3;
    private static final Integer MIN_DAYS_BEFORE_FIRST_RECURRING_PAYMENT = Integer.valueOf(Card_Payment_Plan_Settings__c.getOrgDefaults().Min_Days_Before_First_Recurring_Payment__c);
    private static final Decimal MIN_FIRST_AMOUNT = Card_Payment_Plan_Settings__c.getOrgDefaults().Minimum_First_Amount__c;
    private static final Decimal MIN_REC_AMOUNT = Card_Payment_Plan_Settings__c.getOrgDefaults().Minimum_Recurring_Amount__c;
    public static List<PaymentPlanOption> getOptions(Decimal courseFee, Date courseStartDate) {
        initialPaymentDate = clock.today();
        Date firstRecurringPaymentDate = getFirstRecurringPaymentDate();
        List<PaymentPlanOption> paymentPlanOptions = new List<PaymentPlanOption>();
        for(Integer i = 1; i <= MAX_RECURRING_INSTALLMENTS_NUMBER; i++) {
            if(isPaidBeforeCourseStartDate(i, courseStartDate, firstRecurringPaymentDate)) {
                PaymentPlanOption paymentPlanOption = calculateAmounts(courseFee, i);
                if(paymentPlanOption != null) {
                    Date lastPaymentDate = firstRecurringPaymentDate.addMonths(i - 1);
                    paymentPlanOption.startDate = firstRecurringPaymentDate.toStartOfMonth();
                    paymentPlanOption.endDate = lastPaymentDate.toStartOfMonth() + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1;
                    paymentPlanOption.label = createOptionLabel(paymentPlanOption, i);
                    paymentPlanOption.value = String.valueOf(i);
                    paymentPlanOptions.add(paymentPlanOption);
                }
            }
        }
        return paymentPlanOptions;
    }
    private static Date getFirstRecurringPaymentDate() {
        Date firstRecurringPaymentDate;
        Integer daysInCurrentMonth = Date.daysInMonth(initialPaymentDate.year(), initialPaymentDate.month());
        Integer daysToday = initialPaymentDate.day();
        firstRecurringPaymentDate = initialPaymentDate.addDays(daysInCurrentMonth - daysToday + 1);
        if(daysInCurrentMonth - daysToday <= MIN_DAYS_BEFORE_FIRST_RECURRING_PAYMENT) {
            firstRecurringPaymentDate = firstRecurringPaymentDate.addMonths(1);
        }
        return firstRecurringPaymentDate;
    }
    private static Boolean isPaidBeforeCourseStartDate(Integer monthCount, Date courseStartDate, Date firstRecurringPaymentDate) {
        return firstRecurringPaymentDate.addMonths(monthCount - 1).addDays(MAX_DAYS_BEFORE_PAID) < courseStartDate;
    }
    @TestVisible
    private static PaymentPlanOption calculateAmounts(Decimal courseFee, Integer monthCount) {
        PaymentPlanOption paymentPlanOption = new PaymentPlanOption();
        if(courseFee >= MIN_FIRST_AMOUNT + MIN_REC_AMOUNT * monthCount && courseFee < MIN_FIRST_AMOUNT * (monthCount + 1)) {
            paymentPlanOption.amountFirst = MIN_FIRST_AMOUNT;
        } else
        if(courseFee >= MIN_FIRST_AMOUNT * (monthCount + 1)) {
            paymentPlanOption.amountFirst = courseFee/(monthCount + 1);
        } else {
            return null;
        }
        paymentPlanOption.amountFirst = paymentPlanOption.amountFirst.setScale(2, System.RoundingMode.CEILING);
        Decimal amountRest = courseFee - paymentPlanOption.amountFirst;
        paymentPlanOption.amountRecurring = (amountRest/monthCount).setScale(2, System.RoundingMode.DOWN);
        paymentPlanOption.amountFirst += (amountRest - paymentPlanOption.amountRecurring * monthCount);
        return paymentPlanOption;
    }
    private static String createOptionLabel(PaymentPlanOption paymentPlanOption, Integer monthCount) {
        String labelText;
        if(paymentPlanOption.amountFirst == paymentPlanOption.amountRecurring) {
            String labelTemplate = Label.Payment_Plan_Equal_Amounts_Option_Template;
            labelText = String.format(labelTemplate, new List<Object> {monthCount + 1, paymentPlanOption.amountRecurring});
        } else {
            String labelTemplate = Label.Payment_Plan_Different_Amounts_Option_Template;
            labelText = String.format(labelTemplate, new List<Object> {paymentPlanOption.amountFirst, monthCount, paymentPlanOption.amountRecurring});
        }
        return labelText;
    }
}