force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Contact__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Invoice_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Zumzum__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Type__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase Invoice</fullName>
            </value>
            <value>
                <fullName>Purchase Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Order__c/Zumzum__Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPurchaseInvoiceBuilder.cls
@IsTest
public class TestPurchaseInvoiceBuilder {

	private Id accountId;
	private Id contactId;
	private Date dueDate;
	private Boolean insertRecord = false;
	private Date invoiceDate;
	private Id purchaseOrderId;
	private String status;
	private String type;

	public TestPurchaseInvoiceBuilder withAccount(Id accountId) {
		this.accountId = accountId;
		return this;
	}

	public TestPurchaseInvoiceBuilder withContact(Id contactId) {
		this.contactId = contactId;
		return this;
	}

	public TestPurchaseInvoiceBuilder withInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
		return this;
	}

	public TestPurchaseInvoiceBuilder withDueDate(Date dueDate) {
		this.dueDate = dueDate;
		return this;
	}

	public TestPurchaseInvoiceBuilder withPurchaseOrder(Id purchaseOrderId) {
		this.purchaseOrderId = purchaseOrderId;
		return this;
	}

	public TestPurchaseInvoiceBuilder withStatus(String status) {
		this.status = status;
		return this;
	}

	public TestPurchaseInvoiceBuilder withType(String type) {
		this.type = type;
		return this;
	}

	public TestPurchaseInvoiceBuilder insertRecord(Boolean insertRecord) {
		this.insertRecord = insertRecord;
		return this;
	}

	public Zumzum__Purchase_Invoice__c build(){

		Zumzum__Purchase_Invoice__c testPurchaseInvoice = new Zumzum__Purchase_Invoice__c (
				Zumzum__Account__c = this.accountId,
				Zumzum__Contact__c = this.contactId,
				Zumzum__Invoice_Date__c =this.invoiceDate,
				Zumzum__Invoice_Due_Date__c =  this.dueDate,
				Zumzum__Purchase_Order__c = this.purchaseOrderId,
				Zumzum__Status__c = this.status,
				Zumzum__Type__c = type
		);

		if(insertRecord) {
			insert testPurchaseInvoice;
		}

		return testPurchaseInvoice;
	}
}