force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Total_Gross__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Gross__c</fullName>
    <label>Total Gross</label>
    <summarizedField>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Total_Gross__c</summarizedField>
    <summaryForeignKey>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Purchase_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Total_Net__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Net__c</fullName>
    <label>Total Net</label>
    <summarizedField>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Total_Net__c</summarizedField>
    <summaryForeignKey>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Purchase_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Amount__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Narrative__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Narrative__c</fullName>
    <label>Narrative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Quantity__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Total_Gross__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Gross__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Total_Net__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Net__c</fullName>
    <label>Total Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestPurchaseInvoiceLineItemBuilder.cls
@IsTest
public class TestPurchaseInvoiceLineItemBuilder {

	private Decimal amount;
	private Decimal totalAmount;
	private Decimal gross;
	private Boolean insertRecord = false;
	private String narrative;
	private Decimal net;
	private Id purchaseInvoiceId;
	private Integer quantity;
	
	public TestPurchaseInvoiceLineItemBuilder withAmount(Decimal amount) {
		this.amount = amount;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withTotalAmount(Decimal totalAmount) {
		this.totalAmount = totalAmount;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withPurchaseInvoice(Id purchaseInvoiceId) {
		this.purchaseInvoiceId = purchaseInvoiceId;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withQuantity(Integer quantity) {
		this.quantity = quantity;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withGross(Decimal gross) {
		this.gross = gross;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withNet(Decimal net) {
		this.net = net;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder withNarrative(String narrative) {
		this.narrative = narrative;
		return this;
	}

	public TestPurchaseInvoiceLineItemBuilder insertRecord(Boolean insertRecord) {
		this.insertRecord = insertRecord;
		return this;
	}

	public Zumzum__Purchase_Invoice_Line_Item__c build(){
		Zumzum__Purchase_Invoice_Line_Item__c testPurchaseInvoiceLineItem = new Zumzum__Purchase_Invoice_Line_Item__c (
				Zumzum__Quantity__c = this.quantity,
				Zumzum__Amount__c = this.amount,
				Zumzum__Total_Amount__c = this.totalAmount,
				Zumzum__Total_Net__c = this.net,
				Zumzum__Narrative__c = this.narrative,
				Zumzum__Purchase_Invoice__c = this.purchaseInvoiceId,
				Zumzum__Total_Gross__c = this.gross
		);

		if(insertRecord) {
			insert testPurchaseInvoiceLineItem;
		}

		return testPurchaseInvoiceLineItem;
	}
}