force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/Zumzum__Batch_Bank_Payment__c.object-meta.xml
<CustomObject>
    <label>Batch Bank Payment</label>
    <nameField>
        <displayFormat>BBPUID-{0000000000}</displayFormat>
        <label>Batch Bank Payment UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Bank Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>File Generated</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBatchBankPaymentBuilder.cls
@IsTest
public class TestBatchBankPaymentBuilder {

	private Boolean insertRecord = false;
	private String paymentType;
	private String status;
	private String type;

	public TestBatchBankPaymentBuilder withPaymentType(String paymentType) {
		this.paymentType = paymentType;
		return this;
	}

	public TestBatchBankPaymentBuilder withStatus(String status) {
		this.status = status;
		return this;
	}

	public TestBatchBankPaymentBuilder withType(String type) {
		this.type = type;
		return this;
	}


	public TestBatchBankPaymentBuilder insertRecord(Boolean insertRecord) {
		this.insertRecord = insertRecord;
		return this;
	}

	public Zumzum__Batch_Bank_Payment__c build(){
		Zumzum__Batch_Bank_Payment__c testBatchBankPayment = new Zumzum__Batch_Bank_Payment__c (
				Zumzum__Type__c = this.type,
				Zumzum__Status__c = this.status,
				Zumzum__Payment_Type__c = this.paymentType);

		if(insertRecord) {
			insert testBatchBankPayment;
		}

		return testBatchBankPayment;
	}

}