force-app/main/default/objects/Course_Settings__c/Course_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Course Settings</label>
</CustomObject>

force-app/main/default/objects/Course_Settings__c/fields/Venue_Schedule_Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Venue_Schedule_Report_ID__c</fullName>
    <label>Venue Schedule Report ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CourseSettingsService.cls
public with sharing class CourseSettingsService {

	public static void setVenueScheduleReportId(String reportName) {

		List<Report> venueReport = [SELECT Id
			FROM Report
			WHERE Name = :reportName
			LIMIT 1
		];

		if (venueReport.size() == 0) {
			return;
		}

		Course_Settings__c courseSettings = [SELECT Id, Venue_Schedule_Report_ID__c
			FROM Course_Settings__c
			LIMIT 1];
		courseSettings.Venue_Schedule_Report_ID__c = venueReport[0].id;

		update courseSettings;

	}

}