force-app/main/default/objects/Batch_Receipt_Report__c/Batch_Receipt_Report__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report</label>
    <nameField>
        <displayFormat>BRR-{000000}</displayFormat>
        <label>Batch Receipt Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/Total_Matched__c.field-meta.xml
<CustomField>
    <fullName>Total_Matched__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Matched</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/Batch_Receipt_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report Item</label>
    <nameField>
        <displayFormat>BRRI-{0000000}</displayFormat>
        <label>Batch Receipt Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Bank_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Bank_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Receipt</label>
    <referenceTo>Zumzum__Bank_Receipt__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Batch_Receipt_Report__c.field-meta.xml
<CustomField>
    <fullName>Batch_Receipt_Report__c</fullName>
    <label>Batch Receipt Report</label>
    <referenceTo>Batch_Receipt_Report__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/Zumzum__Bank_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Receipt</label>
    <nameField>
        <displayFormat>BRUID-{0000000000}</displayFormat>
        <label>Bank Receipt UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Batch_Bank_Receipt__c/Zumzum__Batch_Bank_Receipt__c.object-meta.xml
<CustomObject>
    <label>Batch Bank Receipt</label>
    <nameField>
        <displayFormat>BBRUID-{0000000000}</displayFormat>
        <label>Batch Bank Receipt UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Bank Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchReceiptReportItem_TDTM_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #134 - https://confluence.nct.org.uk:8443/x/EoSO

@IsTest
public with sharing class BatchReceiptReportItem_TDTM_Test {

    private static final String STATUS_DRAFT = 'Draft';

    private static final Map<String, String> TRIGGER_PARAMS = new Map<String, String> {
        'triggerHandlerName' => 'BatchReceiptReportItem_TDTM',
        'className' => 'BatchReceiptReportItem_TDTM',
        'objectAPIName' => 'Batch_Receipt_Report_Item__c',
        'triggerActions' => 'AfterInsert;AfterUpdate;AfterDelete',
        'isActive' => 'true',
        'loadOrder' => '0',
        'isAsynchronous' => 'false'
    };

    @TestSetup
    private static void SetupTestData() {
        TestDataFactory.createTriggerSystemHandlerRecord(TRIGGER_PARAMS);

        Batch_Receipt_Report__c batchReceiptReportRecord = new TestBatchReceiptReportBuilder().insertRecord(true).build();

        Zumzum__Batch_Bank_Receipt__c batchBankReceipt = new Zumzum__Batch_Bank_Receipt__c (
            Zumzum__Status__c = STATUS_DRAFT
        );

        insert batchBankReceipt;

        Zumzum__Bank_Receipt__c bankReceiptInstanse = new Zumzum__Bank_Receipt__c (
            Zumzum__Amount__c = 10,
            Zumzum__Status__c = STATUS_DRAFT,
            Zumzum__Batch_Bank_Receipt__c = batchBankReceipt.Id
        );

        insert bankReceiptInstanse;

        TestBatchReceiptReportItemBuilder batchReceiptReportItemInstanse = new TestBatchReceiptReportItemBuilder();
        batchReceiptReportItemInstanse.withBatchReceiptReport(batchReceiptReportRecord.Id)
            .withBankReceipt(bankReceiptInstanse.Id)
            .insertRecord(true)
            .build();
    }

    @IsTest
    public static void BRReportItemCheckAfterDeleting_DeletedBRRepotItemRecord_TotalMatchedShouldBeZero() {

        Batch_Receipt_Report_Item__c batchReceiptReportItem = [SELECT Id FROM Batch_Receipt_Report_Item__c LIMIT 1];
        Batch_Receipt_Report__c batchReceiptReportRecordBeforeDelete = [SELECT Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];

        System.assertEquals(1, batchReceiptReportRecordBeforeDelete.Total_Matched__c, 'Should be equals 1');

        Test.startTest();
            delete batchReceiptReportItem;
        Test.stopTest();

        Batch_Receipt_Report__c batchReceiptReportRecordAfterDeleted = [SELECT Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];
        System.assertEquals(0, batchReceiptReportRecordAfterDeleted.Total_Matched__c, 'Should be equals 0');
    }

    @IsTest
    public static void BRReportItemCheckAfterUpdating_UpdateBRRepotItemRecord_TotalMatchedShouldBeZero() {

        Batch_Receipt_Report_Item__c batchReceiptReportItem = [SELECT Id, Bank_Receipt__c FROM Batch_Receipt_Report_Item__c LIMIT 1];
        Batch_Receipt_Report__c batchReceiptReportRecordBeforeUpdate = [SELECT Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];

        System.assertEquals(1, batchReceiptReportRecordBeforeUpdate.Total_Matched__c, 'Should be equals 1');

        Test.startTest();
            batchReceiptReportItem.Bank_Receipt__c = null;
            update batchReceiptReportItem;
        Test.stopTest();

        Batch_Receipt_Report__c batchReceiptReportRecordAfterUpdate = [SELECT Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];
        System.assertEquals(0, batchReceiptReportRecordAfterUpdate.Total_Matched__c, 'Should be equals 0');
    }

    @IsTest
    public static void BRReportItemCheckAfterInsert_InsertBRRepotItemRecord_TotalMatchedShouldBeTwo() {

        Batch_Receipt_Report__c batchReceiptReportRecordBeforeInsert = [SELECT Id, Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];

        System.assertEquals(1, batchReceiptReportRecordBeforeInsert.Total_Matched__c, 'Should be equals 1');

        Zumzum__Batch_Bank_Receipt__c batchBankReceipt = new Zumzum__Batch_Bank_Receipt__c (
            Zumzum__Status__c = STATUS_DRAFT
        );

        insert batchBankReceipt;

        Zumzum__Bank_Receipt__c bankReceiptInstanse = new Zumzum__Bank_Receipt__c (
            Zumzum__Amount__c = 20,
            Zumzum__Status__c = STATUS_DRAFT,
            Zumzum__Batch_Bank_Receipt__c = batchBankReceipt.Id
        );

        insert bankReceiptInstanse;

        Test.startTest();
            TestBatchReceiptReportItemBuilder batchReceiptReportItemInstanse = new TestBatchReceiptReportItemBuilder();
            batchReceiptReportItemInstanse.withBatchReceiptReport(batchReceiptReportRecordBeforeInsert.Id)
                .withBankReceipt(bankReceiptInstanse.Id)
                .insertRecord(true)
                .build();
        Test.stopTest();

        Batch_Receipt_Report__c batchReceiptReportRecordAfterInsert = [SELECT Total_Matched__c FROM Batch_Receipt_Report__c LIMIT 1];
        System.assertEquals(2, batchReceiptReportRecordAfterInsert.Total_Matched__c, 'Should be equals 2');
    }

}