force-app/main/default/objects/Batch_Receipt_Report__c/Batch_Receipt_Report__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report</label>
    <nameField>
        <displayFormat>BRR-{000000}</displayFormat>
        <label>Batch Receipt Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/BankReconcile__c.field-meta.xml
<CustomField>
    <fullName>BankReconcile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BankReconcile</label>
    <referenceTo>Zumzum__BankReconcile__c</referenceTo>
    <relationshipLabel>Batch Receipt Reports</relationshipLabel>
    <relationshipName>Batch_Receipt_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Not Created</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/Batch_Receipt_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report Item</label>
    <nameField>
        <displayFormat>BRRI-{0000000}</displayFormat>
        <label>Batch Receipt Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Bank_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bank_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Payment</label>
    <referenceTo>Zumzum__Bank_Payment__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Bank_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Bank_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Receipt</label>
    <referenceTo>Zumzum__Bank_Receipt__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Batch_Receipt_Report__c.field-meta.xml
<CustomField>
    <fullName>Batch_Receipt_Report__c</fullName>
    <label>Batch Receipt Report</label>
    <referenceTo>Batch_Receipt_Report__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/cpm__Payment__c.object
<CustomObject>
    <description>Payments are actual amounts of money transfered to our organisation, either spontaneously or as the result of a Recurring Payment.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpm__Amount__c</fullName>
        <description>The amount of the payment.</description>
        <inlineHelpText>The amount of this payment.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cpm__Installment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The installment this payment originated from.</description>
        <inlineHelpText>The installment this payment originated from.</inlineHelpText>
        <label>Installment</label>
        <referenceTo>cpm__Installment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Payment_Reference__c</fullName>
        <description>The payment reference given by the debitor.</description>
        <inlineHelpText>The payment reference given by the debitor.</inlineHelpText>
        <label>Payment Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0}</displayFormat>
        <label>Payment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Account__c/Zumzum__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/Zumzum__Bank_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Receipt</label>
    <nameField>
        <displayFormat>BRUID-{0000000000}</displayFormat>
        <label>Bank Receipt UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cpm__Payment__c</referenceTo>
    <relationshipLabel>Bank Receipts</relationshipLabel>
    <relationshipName>Bank_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__BankReconcile__c/Zumzum__BankReconcile__c.object-meta.xml
<CustomObject>
    <label>BankReconcile</label>
    <nameField>
        <label>Bank Rec UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BankReconcile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Ledger__c/Zumzum__Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Ledger_Payment_History__c/Zumzum__Ledger_Payment_History__c.object-meta.xml
<CustomObject>
    <label>Ledger Payment History</label>
    <nameField>
        <label>Ledger Payment History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledger Payment History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ReconcilePaymentsBatchHelper.cls
public class ReconcilePaymentsBatchHelper {
    public static final String CREATED_STATUS = 'Created';
    private static final String DRAFT_STATUS = 'Draft';
    private static final Integer BANK_NOMINAL_ACCOUNT_CODE = 9401;

    public static void processBatchReceiptReportItems(List<Batch_Receipt_Report_Item__c> receiptReportItems) {
        List<Batch_Receipt_Report__c> receiptReports = [
            SELECT Id, Status__c, Batch_Id__c, From_Date__c, To_Date__c
            FROM Batch_Receipt_Report__c
            WHERE Id = :receiptReportItems[0].Batch_Receipt_Report__c
        ];

        Set<String> receiptIds = new Set<String>();
        Set<String> paymentIds = new Set<String>();

        for (Batch_Receipt_Report_Item__c item : receiptReportItems) {
            if (item.Amount__c > 0) {
                receiptIds.add(item.Payment_Id__c);
            } else if (item.Amount__c < 0) {
                paymentIds.add(item.Payment_Id__c);
            }
        }

        List<cpm__Payment__c> cpmPayments = getCpmPaymentsByTransactionIdAndAmount(paymentIds);
        Map<Id, cpm__Payment__c> salesInvoicesPaymentsMap = new Map<Id, cpm__Payment__c>();
        Map<String, Id> paymentsReferenceSalesInvoiceIdMap = new Map<String, Id>();

        for (cpm__Payment__c payment : cpmPayments) {
            salesInvoicesPaymentsMap.put(payment.cpm__Installment__r.Sales_Invoice__c, payment);
            paymentsReferenceSalesInvoiceIdMap.put(payment.cpm__Payment_Reference__c, payment.cpm__Installment__r.Sales_Invoice__c);
        }
        
        List<Zumzum__Bank_Payment__c> bankPayments = getBankPaymentsBySalesCredits(salesInvoicesPaymentsMap.keySet());
        Map<Id, Id> salesInvoicesBankPaymentsMap = new Map<Id, Id>();

        for (Zumzum__Bank_Payment__c bankPayment : bankPayments) {
            for (Zumzum__Ledger_Payment_History__c salesCreditAllocation : bankPayment.Zumzum__Ledger_Payment_History__r) {
                if (salesCreditAllocation.Zumzum__Amount__c == salesInvoicesPaymentsMap.get(salesCreditAllocation.Zumzum__Sales_Credit__r.Zumzum__Sales_Invoice_to_Credit__c).cpm__Amount__c) {
                    salesInvoicesBankPaymentsMap.put(salesCreditAllocation.Zumzum__Sales_Credit__r.Zumzum__Sales_Invoice_to_Credit__c, bankPayment.Id);
                }              
            }
        }

        Zumzum__BankReconcile__c bankReconcile = getBankReconcile(receiptReports[0]);
        List<Zumzum__Ledger__c> ledgers = getLedgers(receiptIds, new Set<Id>(salesInvoicesBankPaymentsMap.values()));
        Map<String, Id> paymentsBankReceiptsMap = getpaymentsBankReceiptsMap(ledgers);

        for (Zumzum__Ledger__c ledger : ledgers) {
            ledger.Zumzum__BankReconcile__c = bankReconcile.Id;
            ledger.Zumzum__Bank_Reconcile__c = 'N';
        }
        update ledgers;

        for (Batch_Receipt_Report_Item__c reportItem : receiptReportItems) {
            if (reportItem.Amount__c > 0) {
                reportItem.Bank_Receipt__c = paymentsBankReceiptsMap.get(reportItem.Payment_Id__c);
            } else if (reportItem.Amount__c < 0) {
                reportItem.Bank_Payment__c = salesInvoicesBankPaymentsMap.get(paymentsReferenceSalesInvoiceIdMap.get(reportItem.Payment_Id__c));
            }
        }
        update receiptReportItems;

        receiptReports[0].BankReconcile__c = bankReconcile.Id;
        update receiptReports[0];
    }

    private static List<cpm__Payment__c> getCpmPaymentsByTransactionIdAndAmount(Set<String> paymentIds) {
        return [
            SELECT 
                cpm__Amount__c, 
                cpm__Installment__c, 
                cpm__Installment__r.Sales_Invoice__c, 
                cpm__Payment_Reference__c
            FROM cpm__Payment__c
            WHERE cpm__Payment_Reference__c IN :paymentIds
        ];
    }

    private static List<Zumzum__Bank_Payment__c> getBankPaymentsBySalesCredits(Set<Id> salesInvoicesIds) {
        return [
            SELECT 
                Id, 
                (SELECT Zumzum__Amount__c, Zumzum__Sales_Credit__r.Zumzum__Sales_Invoice_to_Credit__c FROM Zumzum__Ledger_Payment_History__r)
            FROM Zumzum__Bank_Payment__c
            WHERE
                Id IN (
                    SELECT Zumzum__Bank_Payment__c
                    FROM Zumzum__Ledger_Payment_History__c
                    WHERE Zumzum__Sales_Credit__r.Zumzum__Sales_Invoice_to_Credit__c IN :salesInvoicesIds 
                )
        ];
    }

    private static Zumzum__BankReconcile__c getBankReconcile(Batch_Receipt_Report__c receipt) {
        Zumzum__BankReconcile__c bankReconcile = new Zumzum__BankReconcile__c(
            Zumzum__Status__c = DRAFT_STATUS,
            Zumzum__Bank_Account__c = getBankAccountIdByNominalAccountCode(BANK_NOMINAL_ACCOUNT_CODE),
            Zumzum__Statement_Date__c = Date.today(),
            Zumzum__Transaction_Start_Date__c = receipt.From_Date__c,
            Zumzum__Transaction_End_Date__c = receipt.To_Date__c
        );
        insert bankReconcile;
        return bankReconcile;
    }

    private static List<Zumzum__Ledger__c> getLedgers(Set<String> receiptIds, Set<Id> bankPaymentIds) {
        return [
            SELECT
                Zumzum__BankReconcile__c,
                Zumzum__Bank_Reconcile__c,
                Zumzum__Bank_Receipt__r.Payment__r.cpm__Payment_Reference__c,
                Zumzum__Bank_Receipt__c
            FROM Zumzum__Ledger__c
            WHERE
                (Zumzum__Bank_Receipt__r.Payment__r.cpm__Payment_Reference__c IN :receiptIds OR Zumzum__Bank_Payment__c IN :bankPaymentIds)
                AND Zumzum__Sub_Account_Nominal_Link__r.Zumzum__Account_Code__c = :BANK_NOMINAL_ACCOUNT_CODE
            WITH SECURITY_ENFORCED
        ];
    }

    private static Id getBankAccountIdByNominalAccountCode(Integer code) {
        Zumzum__Bank_Account__c bankAccount = [
            SELECT Name
            FROM Zumzum__Bank_Account__c
            WHERE Zumzum__Nominal_Account__r.Zumzum__Account_Code__c = :code
            LIMIT 1
        ];
        return bankAccount.Id;
    }

    private static Map<String, Id> getpaymentsBankReceiptsMap(List<Zumzum__Ledger__c> ledgers) {
        Map<String, Id> paymentsBankReceiptsMap = new Map<String, Id>();
        for (Zumzum__Ledger__c ledger : ledgers) {
            if (String.isNotBlank(ledger.Zumzum__Bank_Receipt__c)) {
                paymentsBankReceiptsMap.put(ledger.Zumzum__Bank_Receipt__r.Payment__r.cpm__Payment_Reference__c, ledger.Zumzum__Bank_Receipt__c);                
            }
        }
        return paymentsBankReceiptsMap;
    }
}