force-app/main/default/objects/Batch_Receipt_Report__c/Batch_Receipt_Report__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report</label>
    <nameField>
        <displayFormat>BRR-{000000}</displayFormat>
        <label>Batch Receipt Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/BankReconcile__c.field-meta.xml
<CustomField>
    <fullName>BankReconcile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BankReconcile</label>
    <referenceTo>Zumzum__BankReconcile__c</referenceTo>
    <relationshipLabel>Batch Receipt Reports</relationshipLabel>
    <relationshipName>Batch_Receipt_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorldPay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Not Created</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBatchReceiptReportBuilder.cls
@isTest
public class TestBatchReceiptReportBuilder {
    private Id bankReconcile;
    private String batchId;
    private Date fromDate = Date.today() - 30;
    private Date toDate = Date.today();
    private String provider = 'WorldPay';
    private String status = 'Not Created';
    private Boolean insertRecord = false;

    public TestBatchReceiptReportBuilder withBankReconcile(Id bankReconcile) {
        this.bankReconcile = bankReconcile;
        return this;
    }

    public TestBatchReceiptReportBuilder withBatchId(String batchId) {
        this.batchId = batchId;
        return this;
    }

    public TestBatchReceiptReportBuilder withFromDate(Date fromDate) {
        this.fromDate = fromDate;
        return this;
    }

    public TestBatchReceiptReportBuilder withToDate(Date toDate) {
        this.toDate = toDate;
        return this;
    }

    public TestBatchReceiptReportBuilder withProvider(String provider) {
        this.provider = provider;
        return this;
    }

    public TestBatchReceiptReportBuilder withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public TestBatchReceiptReportBuilder insertRecord(Boolean insertRecord) {
        this.insertRecord = insertRecord;
        return this;
    }

    public Batch_Receipt_Report__c build() {
        Batch_Receipt_Report__c batchReceiptReport = new Batch_Receipt_Report__c(
            BankReconcile__c = this.bankReconcile,
            Batch_Id__c = this.batchId,
            From_Date__c = this.fromDate,
            To_Date__c = this.toDate,
            Provider__c = this.provider,
            Status__c = this.status
        );
        
        if (insertRecord) {
            insert batchReceiptReport;
        }
        
        return batchReceiptReport;
    }

}