force-app/main/default/objects/Batch_Receipt_Report__c/Batch_Receipt_Report__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report</label>
    <nameField>
        <displayFormat>BRR-{000000}</displayFormat>
        <label>Batch Receipt Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/Batch_Receipt_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report Item</label>
    <nameField>
        <displayFormat>BRRI-{0000000}</displayFormat>
        <label>Batch Receipt Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Acquirer_Account__c.field-meta.xml
<CustomField>
    <fullName>Acquirer_Account__c</fullName>
    <label>Acquirer Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Bank_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Bank_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Receipt</label>
    <referenceTo>Zumzum__Bank_Receipt__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Batch_Receipt_Report__c.field-meta.xml
<CustomField>
    <fullName>Batch_Receipt_Report__c</fullName>
    <label>Batch Receipt Report</label>
    <referenceTo>Batch_Receipt_Report__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Captured_On__c.field-meta.xml
<CustomField>
    <fullName>Captured_On__c</fullName>
    <label>Captured On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Order_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Code__c</fullName>
    <label>Order Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBatchReceiptReportItemBuilder.cls
public with sharing class TestBatchReceiptReportItemBuilder {
    private Id bankReceipt;
    private Id batchReceiptReport;
    private String reference;
    private String acquirerAccount = 'Acquirer Account';
    private Decimal amount = 100.00;
    private Date capturedOn = Date.today();
    private String currencyCode = 'GBP';
    private String orderCode = 'X333X';
    private String paymentId = '123456';
    private String paymentMethod = 'Card';
    private Boolean insertRecord = false;

    public TestBatchReceiptReportItemBuilder withBankReceipt(Id bankReceipt) {
        this.bankReceipt = bankReceipt;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withBatchReceiptReport(Id batchReceiptReport) {
        this.batchReceiptReport = batchReceiptReport;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withReference(String reference) {
        this.reference = reference;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withAcquirerAccount(String acquirerAccount) {
        this.acquirerAccount = acquirerAccount;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withAmount(Decimal amount) {
        this.amount = amount;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withCapturedOn(Date capturedOn) {
        this.capturedOn = capturedOn;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withOrderCode(String orderCode) {
        this.orderCode = orderCode;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withPaymentId(String paymentId) {
        this.paymentId = paymentId;
        return this;
    }

    public TestBatchReceiptReportItemBuilder withPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }

    public TestBatchReceiptReportItemBuilder insertRecord(Boolean insertRecord) {
        this.insertRecord = insertRecord;
        return this;
    }

    public Batch_Receipt_Report_Item__c build() {
        Batch_Receipt_Report_Item__c batchReceiptReportItem = new Batch_Receipt_Report_Item__c(
            Acquirer_Account__c = this.acquirerAccount,
            Amount__c = this.amount,
            Batch_Receipt_Report__c = this.batchReceiptReport,
            Captured_On__c = this.capturedOn,
            Currency_Code__c = this.currencyCode,
            Bank_Receipt__c = bankReceipt,
            Order_Code__c = this.orderCode,
            Payment_Id__c = this.paymentId,
            Payment_Method__c = this.paymentMethod,
            Reference__c = this.reference
        );

        if (insertRecord) {
            insert batchReceiptReportItem;
        }
        return batchReceiptReportItem;
    }
}