force-app/main/default/objects/Batch_Receipt_Report__c/Batch_Receipt_Report__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report</label>
    <nameField>
        <displayFormat>BRR-{000000}</displayFormat>
        <label>Batch Receipt Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Not Created</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/Batch_Receipt_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report Item</label>
    <nameField>
        <displayFormat>BRRI-{0000000}</displayFormat>
        <label>Batch Receipt Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Batch_Receipt_Report__c.field-meta.xml
<CustomField>
    <fullName>Batch_Receipt_Report__c</fullName>
    <label>Batch Receipt Report</label>
    <referenceTo>Batch_Receipt_Report__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Ledger__c.field-meta.xml
<CustomField>
    <fullName>Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ledger</label>
    <referenceTo>Zumzum__Ledger__c</referenceTo>
    <relationshipLabel>Batch Receipt Report Items</relationshipLabel>
    <relationshipName>Batch_Receipt_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReconcilePaymentsBatch.cls
public class ReconcilePaymentsBatch implements Database.Batchable<sObject>{
    public Id recordId;

    public ReconcilePaymentsBatch(Id recordId) {
        this.recordId = recordId;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Status__c, Batch_Id__c, From_Date__c, To_Date__c,
                (
                    SELECT Id, Amount__c, Ledger__c, Payment_Id__c
                    FROM Batch_Receipt_Report_Items__r
                )
            FROM Batch_Receipt_Report__c
            WHERE Id =: recordId
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Batch_Receipt_Report__c> receipts) {
        for (Batch_Receipt_Report__c receipt : receipts) {
            system.debug('Receipt: ' + receipt);
            ReconcilePaymentsBatchHelper.processBatchReceiptReport(receipt);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

    @InvocableMethod(
        label='Reconcile Payments'
    )
    public static void runBatch(List<Id> batchReceiptReportId) {
        ReconcilePaymentsBatch reconcileBatch = new ReconcilePaymentsBatch(batchReceiptReportId[0]);
        Id batchId = Database.executeBatch(reconcileBatch, 1);
    }

}