force-app/main/default/objects/Zumzum__Sales_Invoice__c/Zumzum__Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>SI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/Zumzum__Sales_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line Item</label>
    <nameField>
        <label>Sales Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/fields/Allocate_To__c.field-meta.xml
<CustomField>
    <fullName>Allocate_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocate To</label>
    <referenceTo>Zumzum__Sales_Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/fields/Zumzum__Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Line Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DM_SalesAllocationBatch.cls
public class DM_SalesAllocationBatch implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Zumzum__Sales_Invoice__r.Zumzum__Account__c, Allocate_To__c FROM Zumzum__Sales_Invoice_Line_Item__c ' +
                'WHERE Allocate_To__c != NULL AND Zumzum__Sales_Invoice__r.Zumzum__Total_Unpaid_Amount__c > 0 ';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Zumzum__Sales_Invoice_Line_Item__c> siLineItems){
        DM_SIPIAllocation.allocateSI(siLineItems);
    }

    public void finish(Database.BatchableContext bc){
    }
}