force-app/main/default/objects/Zumzum__Sales_Invoice__c/Zumzum__Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>SI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ZumzumPostSalesInvoiceHelperTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')

@isTest
public with sharing class ZumzumPostSalesInvoiceHelperTest {
    private static final String ACCOUNT_TYPE_CUSTOMER = 'Customer';

    @testSetup
    static void testSetup() {
        TestFinanceDataFactory financeDataFactory = TestFinanceDataFactory.getInstance();
        financeDataFactory.createZumzumData();

        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account customer = accountBuilder
                                .withRecordType('Household Account')
                                .withName('Test Customer')
                                .withType(ACCOUNT_TYPE_CUSTOMER)
                                .withAccountNumber('12345678')
                                .withBillingEmail('testbilling@nonsense.noemails')
                                .insertRecord(true)
                                .build();
        
        TestFinanceDataFactory.updateHouseholdAccountsToCustomerType();
        TestFinanceDataFactory.createProducts();

        List<List<ZumzumSalesInvoiceParameters>> zumzumSalesInvoiceParameters = TestFinanceDataFactory.getZumzumSalesInvoiceParameters();
        List<Zumzum__Sales_Invoice__c> salesInvoiceList = ZumzumCreatePostSalesInvoice.createSI(zumzumSalesInvoiceParameters);

    }

    @isTest
    static void PostSalesInvoice_ExecutePostSalesInvoiceApiMethod_ReturnSalesInvoicesWithStatusPosted() {
        Zumzum__Sales_Invoice__c salesInvoiceRecordBefore = [select Zumzum__Status__c from Zumzum__Sales_Invoice__c LIMIT 1];
        System.assertEquals('Draft', salesInvoiceRecordBefore.Zumzum__Status__c, 'return SI with status Draft');

        Test.startTest();
            ZumzumPostSalesInvoiceHelper.postSalesInvoice(new List<Zumzum__Sales_Invoice__c> { salesInvoiceRecordBefore });
        Test.stopTest();

        Zumzum__Sales_Invoice__c salesInvoiceRecordAfter = [select Zumzum__Status__c from Zumzum__Sales_Invoice__c LIMIT 1];
        System.assertEquals('Posted', salesInvoiceRecordAfter.Zumzum__Status__c, 'return SI with status Posted');
    }

}