force-app/main/default/objects/Bacs_Send_Remittance_Emails_Settings__c/Bacs_Send_Remittance_Emails_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bacs Send Remittance Emails Settings</label>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Is_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <formula>IF(NOT( ISBLANK(Purchase_Invoice__r.Zumzum__POP_Number__c) ), &#39;Your reference: &#39; + Purchase_Invoice__r.Zumzum__POP_Number__c + '. ', &#39;&#39;) +
&#39;Our reference: &#39; + Purchase_Invoice__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Supplier_Account_Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account_Billing_Email__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Account Billing Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BacsSendRemittanceEmailsBatch.cls
global class BacsSendRemittanceEmailsBatch implements Database.Batchable<Payment_Run_Line_Item__c>, Database.AllowsCallouts {
    private OrgWideEmailAddress orgWideEmailAddress = [
        SELECT Id 
        FROM OrgWideEmailAddress 
        WHERE Address =: Bacs_Send_Remittance_Emails_Settings__c.getOrgDefaults().Org_Wide_Email_Address__c LIMIT 1
    ];
    private EmailTemplate emailTemplate = [
        SELECT Id, Body, Subject 
        FROM EmailTemplate 
        WHERE DeveloperName =: Bacs_Send_Remittance_Emails_Settings__c.getOrgDefaults().Email_Template_Developer_Name__c
    ];
    private List<Payment_Run_Line_Item__c> prliList;

    global BacsSendRemittanceEmailsBatch(List<Payment_Run_Line_Item__c> prliList) {
        this.prliList = prliList;
    }

    global Iterable<Payment_Run_Line_Item__c> start(Database.BatchableContext BC) {
        return (Iterable<Payment_Run_Line_Item__c>)prliList;
    }

    global void execute(Database.BatchableContext BC, List<Payment_Run_Line_Item__c> scope) {
        List<Messaging.SingleEmailMessage> singleEmailMessageList = new List<Messaging.SingleEmailMessage>();
        for(Payment_Run_Line_Item__c prli : scope) {
            Messaging.SingleEmailMessage singleEmailMessage = new Messaging.SingleEmailMessage();
            singleEmailMessage.setSubject(emailTemplate.Subject);
            singleEmailMessage.setPlainTextBody(createEmailBody(emailTemplate.Body, prli));
            singleEmailMessage.setToAddresses(new List<String>{prli.Supplier_Account_Billing_Email__c});
            singleEmailMessage.setOrgWideEmailAddressId(orgWideEmailAddress.Id);
            singleEmailMessageList.add(singleEmailMessage);
            prli.Is_Email_Sent__c = true;
        }
        if (TestEmailUtility.emailsFeatureEnabled()) {
            Messaging.sendEmail(singleEmailMessageList);
        }
        update scope;
    }

    private String createEmailBody(String body, Payment_Run_Line_Item__c prli) {
        return String.format(body, new List<String> {String.valueOf(prli.Paid_Amount__c), prli.Reference_Info__c});
    }

    global void finish(Database.BatchableContext BC) {

    }
}