force-app/main/default/objects/Zumzum__Nominal_Account__c/Zumzum__Nominal_Account__c.object-meta.xml
<CustomObject>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Nominal_Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Nominal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nominal Account</label>
    <referenceTo>Zumzum__Nominal_Account__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ZumzumPurchaseInvoiceCreatorTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')

@isTest
public without sharing class ZumzumPurchaseInvoiceCreatorTest {

    static final Boolean EXECUTE_IN_BATCH_PROCESSING = false;
    static final String PURCHASE_INVOICE_STATUS_POSTED = 'Posted';
    static final String PURCHASE_INVOICE_STATUS_DRAFT = 'Draft';
    static final String PURCHASE_INVOICE_RESPONSE_STATUS_SUCCESS = 'Success';

    @TestSetup
    static void createTestData() {

    TestDataFactory.getInstance()
        .buildBranchAccount()
        .buildOrganizationAccount('acc5');

    TestFinanceDataFactory.createZumzumPurchaseInvoiceWithLineItems(2);
    }

    @isTest
    public static void PurchaseInvoicePost_PassPIRecordWithStatusDraft_ReturnPIRecordWithSatatusPosted() {
        Zumzum__Purchase_Invoice__c purchaseInvoiceRecordBeforePost = [SELECT Id FROM Zumzum__Purchase_Invoice__c LIMIT 1];
        Zumzum.PurchaseInvoiceService.Response postPurchaseInvoiceResponse = new Zumzum.PurchaseInvoiceService.Response();

        Test.startTest();
            Set<Id> purchaseInvoiceIds = new Set<Id>{ purchaseInvoiceRecordBeforePost.Id };
            postPurchaseInvoiceResponse = ZumzumPurchaseInvoiceCreator.postPurchaseInvoice(purchaseInvoiceIds, EXECUTE_IN_BATCH_PROCESSING);
        Test.stopTest();

        Zumzum__Purchase_Invoice__c purchaseInvoiceAfterPostRecord = [SELECT Zumzum__Status__c FROM Zumzum__Purchase_Invoice__c LIMIT 1];

        System.assertEquals(postPurchaseInvoiceResponse.ResponseMessage, PURCHASE_INVOICE_RESPONSE_STATUS_SUCCESS, 'Response message should be Success');
        System.assertEquals(purchaseInvoiceAfterPostRecord.Zumzum__Status__c, PURCHASE_INVOICE_STATUS_POSTED , 'Status should be Posted');
    }

    @isTest
    public static void PurchaseInvoicePost_PassPIRecordWithNotValidRecord_ReturnPIRecordWithSatatusDraftAndNotSuccess() {
        Zumzum__Purchase_Invoice__c purchaseInvoiceRecordBeforePost = [SELECT Id FROM Zumzum__Purchase_Invoice__c LIMIT 1];

        Zumzum__Purchase_Invoice_Line_Item__c purchaseInvoiceLineItemsRecord = [
            SELECT Id
            FROM Zumzum__Purchase_Invoice_Line_Item__c 
            WHERE Zumzum__Purchase_Invoice__c = :purchaseInvoiceRecordBeforePost.Id
            LIMIT 1
        ];

        purchaseInvoiceLineItemsRecord.Zumzum__Nominal_Account__c = null;
        update purchaseInvoiceLineItemsRecord;

        Zumzum.PurchaseInvoiceService.Response postPurchaseInvoiceResponse = new Zumzum.PurchaseInvoiceService.Response();

        Test.startTest();
            Set<Id> purchaseInvoiceIds = new Set<Id>{ purchaseInvoiceRecordBeforePost.Id};
            postPurchaseInvoiceResponse = ZumzumPurchaseInvoiceCreator.postPurchaseInvoice(purchaseInvoiceIds, EXECUTE_IN_BATCH_PROCESSING);
        Test.stopTest();

        Zumzum__Purchase_Invoice__c purchaseInvoiceAfterPostRecord = [SELECT Zumzum__Status__c FROM Zumzum__Purchase_Invoice__c LIMIT 1];

        System.assert(postPurchaseInvoiceResponse.ResponseMessage != PURCHASE_INVOICE_RESPONSE_STATUS_SUCCESS, 'Response message should be not Success');
        System.assertEquals(purchaseInvoiceAfterPostRecord.Zumzum__Status__c, PURCHASE_INVOICE_STATUS_DRAFT , 'Status should be Draft');
    }
}