force-app/main/default/objects/Zumzum__Expense_Sheet__c/Zumzum__Expense_Sheet__c.object-meta.xml
<CustomObject>
    <label>Expense Sheet</label>
    <nameField>
        <label>Claim No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Sheet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Expense_Sheet_Detail__c/Zumzum__Expense_Sheet_Detail__c.object-meta.xml
<CustomObject>
    <label>Expense Sheet Detail</label>
    <nameField>
        <label>Expense Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Sheet Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Expense_Sheet_Detail__c/fields/Zumzum__Expense_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Expense_Sheet__c</fullName>
    <label>Expense Sheet</label>
    <referenceTo>Zumzum__Expense_Sheet__c</referenceTo>
    <relationshipLabel>Expense Sheet Detail</relationshipLabel>
    <relationshipName>Expense_Sheet_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Total_Gross__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Gross__c</fullName>
    <label>Total Gross</label>
    <summarizedField>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Total_Gross__c</summarizedField>
    <summaryForeignKey>Zumzum__Purchase_Invoice_Line_Item__c.Zumzum__Purchase_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Total_Gross__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Gross__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ZumzumEStoPIConverterMock.cls
public with sharing class ZumzumEStoPIConverterMock implements IExpenseSheetToPurchaseInvoiceConverter {
    public void convert(Set<Id> expenseSheetIds) {
        List<Id> expenseSheetIdsList = new List<Id>();
        expenseSheetIdsList.addAll(expenseSheetIds);
        Zumzum__Purchase_Invoice__c purchaseInvoice = new Zumzum__Purchase_Invoice__c();
        purchaseInvoice.Zumzum__Expense_Sheet__c = expenseSheetIdsList[0];
        insert purchaseInvoice;
        Zumzum__Purchase_Invoice_Line_Item__c purchaseInvoiceLineItem = new Zumzum__Purchase_Invoice_Line_Item__c();
        purchaseInvoiceLineItem.Zumzum__Purchase_Invoice__c = purchaseInvoice.Id;
        purchaseInvoiceLineItem.Zumzum__Total_Gross__c = 10;
        purchaseInvoiceLineItem.Zumzum__Expense_Sheet__c = expenseSheetIdsList[0];
        purchaseInvoiceLineItem.Zumzum__Expense_Sheet_Detail__c = 
            [SELECT Id FROM Zumzum__Expense_Sheet_Detail__c WHERE Zumzum__Expense_Sheet__c =: expenseSheetIdsList[0]].Id;
        insert purchaseInvoiceLineItem;
    }
}