src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Zumzum__Currency__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Currency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Zumzum__Currency__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Nominal_Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Nominal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nominal Account</label>
    <referenceTo>Zumzum__Nominal_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Tax_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rate</label>
    <referenceTo>Zumzum__Tax_Rate__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/Batch_Receipt_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Receipt Report Item</label>
    <nameField>
        <displayFormat>BRRI-{0000000}</displayFormat>
        <label>Batch Receipt Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Receipt Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Receipt_Report_Item__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Actual_Fee_Charged__c.field-meta.xml
<CustomField>
    <fullName>Actual_Fee_Charged__c</fullName>
    <label>Actual Fee Charged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Total_Course_Booking_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Course_Booking_Income__c</fullName>
    <formula>Total_Course_Fee_Income__c + Total_Other_Income__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Course Booking Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Total_Course_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Course_Fee_Income__c</fullName>
    <label>Total Course Fee Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Total_Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Other_Income__c</fullName>
    <label>Total Other Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Account__c/Zumzum__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Company__c/Zumzum__Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Currency__c/Zumzum__Currency__c.object-meta.xml
<CustomObject>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Nominal_Account__c/Zumzum__Nominal_Account__c.object-meta.xml
<CustomObject>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/Zumzum__Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>SI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/fields/Course_Place_Total__c.field-meta.xml
<CustomField>
    <fullName>Course_Place_Total__c</fullName>
    <label>Course Place Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/Zumzum__Sales_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line Item</label>
    <nameField>
        <label>Sales Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.Status__c</field>
            <operation>equals</operation>
            <value>Final</value>
        </filterItems>
        <infoMessage>Only courses with &#39;Final&#39; type are available.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Sales Invoice Line Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/fields/Zumzum__Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Line Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Tax_Rate__c/Zumzum__Tax_Rate__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/dlrs_Zumzum_Sales_InvoiceTest.cls
@SuppressWarnings('PMD.ClassNamingConventions')
//Incident #143 - https://confluence.nct.org.uk:8443/x/EoSO
@IsTest
private class dlrs_Zumzum_Sales_InvoiceTest {
    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String PRACTITIONER_EMAIL_ADDRESS = 'partnerCommunityUser@ncttest.com';
    private static final String HOST_LASTNAME = 'Black';
    private static final String HOST_LASTNAME_TWO = 'Brown';
    private static final String HOST_EMAIL_ADDRESS = 'User@ncttest.com';
    private static final String ACCOUNT_TYPE_CUSTOMER = 'Customer';
    private static final String CREDIT_CARD_NUMBER = '1111-2222-3333-4444';
    private static final String PAYMENT_PROFILE_CREDIT_CARD_RECORD_TYPE = 'Credit Card';
    private static final String SALES_INVOICE_TYPE_SI = 'Sales Invoice';
    private static final String SALES_INVOICE_STATUS_POSTED = 'Posted';
    private static final String PRODUCT_NAME_COURSE_PLACE = 'Course Place';
    private static final String PRODUCT_NAME_MEMBERSHIP_18_MONTH = 'Membership - 18 month';
    private static final Integer BANK_NOMINAL_ACCOUNT_CODE = 9401;
    private static final Integer LINE_ITEM_QUANTITY = 1;
    private static final Decimal LINE_ITEM_AMOUNT_30 = 30.00;
    private static final Decimal LINE_ITEM_AMOUNT_40 = 40.00;
    private static final Decimal LINE_ITEM_AMOUNT_50 = 50.00;
    private static final Map<String, String> BOOKING_TRIGGER_PARAMS = new Map<String, String>{
        'triggerHandlerName' => 'Booking_Rollups_TDTM',
        'className' => 'Booking_Rollups_TDTM',
        'objectAPIName' => 'Booking__c',
        'triggerActions' => 'AfterInsert;AfterUpdate',
        'isActive' => 'true',
        'loadOrder' => '1',
        'isAsynchronous' => 'false'
    };
    private static final Map<String, String> SI_TRIGGER_PARAMS = new Map<String, String>{
        'triggerHandlerName' => 'SalesInvoice_Rollups_TDTM',
        'className' => 'SalesInvoice_Rollups_TDTM',
        'objectAPIName' => 'Zumzum__Sales_Invoice__c',
        'triggerActions' => 'AfterInsert;AfterUpdate',
        'isActive' => 'true',
        'loadOrder' => '1',
        'isAsynchronous' => 'false'
    };
    private static final Map<String, String> SILI_TRIGGER_PARAMS = new Map<String, String>{
        'triggerHandlerName' => 'SalesInvoiceLineItem_Rollups_TDTM',
        'className' => 'SalesInvoiceLineItem_Rollups_TDTM',
        'objectAPIName' => 'Zumzum__Sales_Invoice_Line_Item__c',
        'triggerActions' => 'AfterInsert;AfterUpdate',
        'isActive' => 'true',
        'loadOrder' => '1',
        'isAsynchronous' => 'false'
    };

    @testSetup
    static void testSetup() {
        TestDataFactory.createTriggerSystemHandlerRecord(BOOKING_TRIGGER_PARAMS);
        TestDataFactory.createTriggerSystemHandlerRecord(SI_TRIGGER_PARAMS);
        TestDataFactory.createTriggerSystemHandlerRecord(SILI_TRIGGER_PARAMS);
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .buildBranchAccount()
                    .buildPractitioner(PRACTITIONER_LASTNAME, PRACTITIONER_EMAIL_ADDRESS)
                    .buildPractitionerFeeRate()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildParentHost(HOST_LASTNAME, HOST_EMAIL_ADDRESS)
                    .buildPartnertHost(HOST_LASTNAME_TWO, HOST_EMAIL_ADDRESS)
                    .buildBooking('Enquiry');
        TestFinanceDataFactory financeDataFactory = TestFinanceDataFactory.getInstance();
        financeDataFactory.createZumzumData();
        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account customer = accountBuilder
                                .withRecordType('Household Account')
                                .withName('Test Customer')
                                .withType(ACCOUNT_TYPE_CUSTOMER)
                                .withAccountNumber('123456')
                                .withBillingEmail('testbilling@nonsense.noemails')
                                .insertRecord(true)
                                .build();
        
        TestFinanceDataFactory.updateHouseholdAccountsToCustomerType();
        TestFinanceDataFactory.createProducts();

        Zumzum__Bank_Account__c bankAccount = [SELECT Id FROM Zumzum__Bank_Account__c WHERE Name = 'Reconcile Bank' LIMIT 1];
        Zumzum__Company__c company = [SELECT Id FROM Zumzum__Company__c WHERE Name = 'NCT' LIMIT 1];
        Zumzum__Currency__c transactionCurrency = [SELECT Id FROM Zumzum__Currency__c WHERE Name = 'GBP' LIMIT 1];
        Product2 productCourse = [SELECT Id FROM Product2 WHERE Name =: PRODUCT_NAME_COURSE_PLACE LIMIT 1];
        Product2 productMembership = [SELECT Id FROM Product2 WHERE Name =: PRODUCT_NAME_MEMBERSHIP_18_MONTH LIMIT 1];
        Zumzum__Nominal_Account__c nominalAccount = [SELECT Id FROM Zumzum__Nominal_Account__c WHERE Zumzum__Account_Code__c = :BANK_NOMINAL_ACCOUNT_CODE LIMIT 1];
        Zumzum__Tax_Rate__c taxRate = [SELECT Id FROM Zumzum__Tax_Rate__c LIMIT 1];
        Set<String> paymentIds = financeDataFactory.createBatchReceiptReportWithItems(2, 100.00, true);
        List<Batch_Receipt_Report_Item__c> receiptReportItems = [SELECT Amount__c, Payment_Id__c FROM Batch_Receipt_Report_Item__c];
        Booking__c booking = [SELECT Id, Primary_Contact__c FROM Booking__c LIMIT 1];
        
        Zumzum__Sales_Invoice__c salesInvoicePosted = new Zumzum__Sales_Invoice__c(
            Booking__c = booking.Id,
            Zumzum__Contact__c = booking.Primary_Contact__c,
            Zumzum__Account__c = customer.Id,
            Zumzum__Company__c = company.Id,
            Zumzum__Invoice_Date__c = Date.today(),
            Zumzum__Transaction_Currency__c = transactionCurrency.Id,
            Zumzum__Type__c = SALES_INVOICE_TYPE_SI
        );
        insert salesInvoicePosted;

        Zumzum__Sales_Invoice__c salesInvoice = new Zumzum__Sales_Invoice__c(
            Booking__c = booking.Id,
            Zumzum__Contact__c = booking.Primary_Contact__c,
            Zumzum__Account__c = customer.Id,
            Zumzum__Company__c = company.Id,
            Zumzum__Invoice_Date__c = Date.today(),
            Zumzum__Transaction_Currency__c = transactionCurrency.Id,
            Zumzum__Type__c = SALES_INVOICE_TYPE_SI
        );
        insert salesInvoice;

        Zumzum__Sales_Invoice_Line_Item__c salesInvoiceLineItem1 = new Zumzum__Sales_Invoice_Line_Item__c(
            Zumzum__Product__c = productCourse.Id,
            Zumzum__Nominal_Account__c = nominalAccount.Id,
            Zumzum__Company__c = company.Id,
            Zumzum__Quantity__c = LINE_ITEM_QUANTITY,
            Zumzum__Tax_Rate__c = taxRate.Id,
            Zumzum__Foreign_Net_Amount__c = LINE_ITEM_AMOUNT_30,
            Zumzum__Amount__c = LINE_ITEM_AMOUNT_30,
            Zumzum__Foreign_Net_Total__c = LINE_ITEM_AMOUNT_30,
            Zumzum__Foreign_Gross__c = LINE_ITEM_AMOUNT_30,
            Zumzum__Total_Gross__c = LINE_ITEM_AMOUNT_30,
            Zumzum__Sales_Invoice__c = salesInvoicePosted.Id
        );
        Zumzum__Sales_Invoice_Line_Item__c salesInvoiceLineItem2 = new Zumzum__Sales_Invoice_Line_Item__c(
            Zumzum__Product__c = productMembership.Id,
            Zumzum__Nominal_Account__c = nominalAccount.Id,
            Zumzum__Company__c = company.Id,
            Zumzum__Quantity__c = LINE_ITEM_QUANTITY,
            Zumzum__Tax_Rate__c = taxRate.Id,
            Zumzum__Foreign_Net_Amount__c = LINE_ITEM_AMOUNT_40,
            Zumzum__Amount__c = LINE_ITEM_AMOUNT_40,
            Zumzum__Foreign_Net_Total__c = LINE_ITEM_AMOUNT_40,
            Zumzum__Foreign_Gross__c = LINE_ITEM_AMOUNT_40,
            Zumzum__Total_Gross__c = LINE_ITEM_AMOUNT_40,
            Zumzum__Sales_Invoice__c = salesInvoicePosted.Id
        );
        Zumzum__Sales_Invoice_Line_Item__c salesInvoiceLineItem3 = new Zumzum__Sales_Invoice_Line_Item__c(
            Zumzum__Product__c = productCourse.Id,
            Zumzum__Nominal_Account__c = nominalAccount.Id,
            Zumzum__Company__c = company.Id,
            Zumzum__Quantity__c = LINE_ITEM_QUANTITY,
            Zumzum__Tax_Rate__c = taxRate.Id,
            Zumzum__Foreign_Net_Amount__c = LINE_ITEM_AMOUNT_50,
            Zumzum__Amount__c = LINE_ITEM_AMOUNT_50,
            Zumzum__Foreign_Net_Total__c = LINE_ITEM_AMOUNT_50,
            Zumzum__Foreign_Gross__c = LINE_ITEM_AMOUNT_50,
            Zumzum__Total_Gross__c = LINE_ITEM_AMOUNT_50,
            Zumzum__Sales_Invoice__c = salesInvoice.Id
        );
        insert new List<Zumzum__Sales_Invoice_Line_Item__c>{salesInvoiceLineItem1, salesInvoiceLineItem2, salesInvoiceLineItem3};
        salesInvoicePosted.Zumzum__Status__c = SALES_INVOICE_STATUS_POSTED;
        update salesInvoicePosted;
    }
    @IsTest
    private static void testTrigger() {
        Test.startTest();
        Zumzum__Sales_Invoice__c salesInvoicePosted = [SELECT Id, Course_Place_Total__c FROM Zumzum__Sales_Invoice__c WHERE Zumzum__Status__c =: SALES_INVOICE_STATUS_POSTED LIMIT 1];
        Zumzum__Sales_Invoice__c salesInvoice = [SELECT Id, Course_Place_Total__c FROM Zumzum__Sales_Invoice__c WHERE Zumzum__Status__c !=: SALES_INVOICE_STATUS_POSTED LIMIT 1];
        Booking__c booking = [SELECT Id, Status__c, Actual_Fee_Charged__c FROM Booking__c LIMIT 1];
        System.assertEquals(salesInvoicePosted.Course_Place_Total__c, 30);
        System.assertEquals(salesInvoice.Course_Place_Total__c, 50);
        System.assertEquals(booking.Actual_Fee_Charged__c, 30);
        booking.Status__c = 'Confirmed';
        update booking;
        Course__c courseAfterRecalculations = [
            SELECT Id, Total_Course_Booking_Income__c, Total_Course_Fee_Income__c, Total_Other_Income__c
            FROM Course__c
            LIMIT 1
        ];
        System.assertEquals(courseAfterRecalculations.Total_Course_Fee_Income__c + courseAfterRecalculations.Total_Other_Income__c, courseAfterRecalculations.Total_Course_Booking_Income__c);
        Test.stopTest();
    }
}