src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <label>PSA Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PSA_Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Account_No__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Account_No__c</fullName>
    <description>The organisation&#39;s bank account number</description>
    <label>Bank Account No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Sort_Code__c</fullName>
    <label>Bank Sort Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Branch)</relationshipLabel>
        <relationshipName>Branch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/Zumzum__Batch_Bank_Payment__c.object-meta.xml
<CustomObject>
    <label>Batch Bank Payment</label>
    <nameField>
        <displayFormat>BBPUID-{0000000000}</displayFormat>
        <label>Batch Bank Payment UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Bank Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>File Generated</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Zumzum__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Amount__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Zumzum__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Order__c/Zumzum__Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/PSA_Areas.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1C</fullName>
    </customValue>
    <customValue>
        <fullName>5K</fullName>
    </customValue>
    <customValue>
        <fullName>5H</fullName>
    </customValue>
    <customValue>
        <fullName>6D</fullName>
    </customValue>
    <customValue>
        <fullName>6E</fullName>
    </customValue>
    <customValue>
        <fullName>6C</fullName>
    </customValue>
    <customValue>
        <fullName>3E</fullName>
    </customValue>
    <customValue>
        <fullName>3B</fullName>
    </customValue>
    <customValue>
        <fullName>3D</fullName>
    </customValue>
    <customValue>
        <fullName>2B</fullName>
    </customValue>
    <customValue>
        <fullName>7A</fullName>
    </customValue>
    <customValue>
        <fullName>7B</fullName>
    </customValue>
    <customValue>
        <fullName>4S</fullName>
    </customValue>
    <customValue>
        <fullName>4P</fullName>
    </customValue>
    <customValue>
        <fullName>4R</fullName>
    </customValue>
    <customValue>
        <fullName>4J</fullName>
    </customValue>
    <customValue>
        <fullName>4I</fullName>
    </customValue>
    <customValue>
        <fullName>5G</fullName>
    </customValue>
    <customValue>
        <fullName>5F</fullName>
    </customValue>
    <customValue>
        <fullName>1W</fullName>
    </customValue>
    <customValue>
        <fullName>2C</fullName>
    </customValue>
    <customValue>
        <fullName>5I</fullName>
    </customValue>
    <customValue>
        <fullName>5J</fullName>
    </customValue>
    <customValue>
        <fullName>4A</fullName>
    </customValue>
    <customValue>
        <fullName>4N</fullName>
    </customValue>
    <customValue>
        <fullName>4C</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
    </customValue>
    <customValue>
        <fullName>7C</fullName>
    </customValue>
    <customValue>
        <fullName>7D</fullName>
    </customValue>
    <customValue>
        <fullName>6B</fullName>
    </customValue>
    <masterLabel>PSA Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GeneratePaymentFileExtensionTest.cls
@IsTest
private class GeneratePaymentFileExtensionTest {

	@TestSetup
	static void setup(){

		TestAccountBuilder accountBuilder = new TestAccountBuilder();
		Account supplierAccount = accountBuilder.WithRecordType('Organization')
				.withName('Tom Genet')
				.withType('Supplier')
				.withAccountNumber('869344')
				.withBillingEmail('tets@gmail.com')
				.withBankSortCode('572899')
				.withBankAccountNumber('03456123')
				.withBankAccountName('American Bank Account')
				.insertRecord(true)
				.build();

		TestPurchaseOrderBuilder purchaseOrderBuilder = new TestPurchaseOrderBuilder();
		Zumzum__Purchase_Order__c purchaseOrder = purchaseOrderBuilder
				.withStatus('Approved')
				.withOrderDate(Date.today())
				.withSupplier(supplierAccount.Id)
				.withType('Stock PO')
				.insertRecord(true)
				.build();

		TestProductBuilder productBuilder = new TestProductBuilder();
		Product2 product = productBuilder
				.withName('Doll')
				.insertRecord(true)
				.build();

		TestPurchaseOrderLineItemBuilder purchaseOrderLineItemBuilder = new TestPurchaseOrderLineItemBuilder();
		Zumzum__Purchase_Order_Line_Items__c purchaseOrderLineItems = purchaseOrderLineItemBuilder
				.withAmount(120)
				.withGross(120)
				.withNarrative('Doll')
				.withProduct(product.id)
				.withPurchaseOrder(purchaseOrder.Id)
				.withQuantity(1)
				.insertRecord(true)
				.build();

		TestPurchaseInvoiceBuilder purchaseInvoiceBuilder = new TestPurchaseInvoiceBuilder();
		Zumzum__Purchase_Invoice__c purchaseInvoice = purchaseInvoiceBuilder
				.withPurchaseOrder(purchaseOrder.Id)
				.withStatus('Approved')
				.withAccount(supplierAccount.Id)
				.withDueDate(Date.today().addDays(20))
				.withInvoiceDate(Date.today())
				.insertRecord(true)
				.build();

		TestPurchaseInvoiceLineItemBuilder purchaseInvoiceLineItemBuilder = new TestPurchaseInvoiceLineItemBuilder();
		Zumzum__Purchase_Invoice_Line_Item__c purchaseInvoiceLineItems = purchaseInvoiceLineItemBuilder
				.withAmount(120)
				.withGross(120)
				.withGross(120)
				.withNet(120)
				.withNarrative('Doll')
				.withQuantity(1)
				.withPurchaseInvoice(purchaseInvoice.Id)
				.insertRecord(true)
				.build();

		TestBatchBankPaymentBuilder batchBankPaymentBuilder = new TestBatchBankPaymentBuilder();
		Zumzum__Batch_Bank_Payment__c batchBankPayment = batchBankPaymentBuilder
				.withStatus('Approved')
				.withPaymentType('Bulk list debit')
				.withType('Cash')
				.insertRecord(true)
				.build();


		TestBankPaymentBuilder bankPaymentBuilder = new TestBankPaymentBuilder();
		Zumzum__Bank_Payment__c bankPayment = bankPaymentBuilder
				.withStatus('Approved')
				.withAmount(120)
				.withSupplier(supplierAccount.Id)
				.withBatchBankPayment(batchBankPayment.id)
				.insertRecord(true)
				.build();
	}

	@IsTest
	public static void generatePaymentFile_BankPaymentApproved_FileGenerated() {

		Zumzum__Batch_Bank_Payment__c batchBankPayment = [
				SELECT Id
				FROM Zumzum__Batch_Bank_Payment__c
				LIMIT 1
		];

		ApexPages.StandardController ctrl = new ApexPages.StandardController(batchBankPayment);
		GeneratePaymentFileExtension generatePaymentCtrl = new GeneratePaymentFileExtension(ctrl);

		PageReference paymentFileRef = Page.GeneratePaymentFile;
		Test.setCurrentPage(paymentFileRef);

		generatePaymentCtrl.init();

		String txtContent =  generatePaymentCtrl.getTxtString();
		String contentType =  generatePaymentCtrl.getCntType();

		System.assert(!generatePaymentCtrl.showError);

		Date cd = Date.today();
		String day = String.valueOf(cd.day()).leftPad(2, '0');
		String month = String.valueOf(cd.month()).leftPad(2, '0');
		String fileName = GeneratePaymentFileUtil.FILE_PREFIX + day + month + cd.year() + GeneratePaymentFileUtil.FILE_EXTENSION;

		System.assertEquals(contentType, 'text/plain#' + fileName);

		List<Zumzum__Bank_Payment__c> payments =  [
				SELECT Id,
						Zumzum__Supplier__r.Zumzum__Bank_Sort_Code__c,
						Zumzum__Supplier__r.Zumzum__Bank_Account_No__c,
						Zumzum__Amount__c,
						Zumzum__Supplier__r.Zumzum__Bank_Account_Name__c,
						Name,
						Zumzum__Supplier__r.Branch__r.Name,
						Zumzum__Supplier__r.PSA_Area__c
				FROM Zumzum__Bank_Payment__c
				WHERE Zumzum__Batch_Bank_Payment__c = :batchBankPayment.id];


		String[] rows = new String[payments.size()];

		for(Zumzum__Bank_Payment__c payment: payments){
			String[] columns = new String[5];
			columns.add(payment.Zumzum__Supplier__r.Zumzum__Bank_Sort_Code__c);
			columns.add(payment.Zumzum__Supplier__r.Zumzum__Bank_Account_No__c);
			columns.add(String.valueOf(payment.Zumzum__Amount__c).leftPad(11, '0'));
			columns.add(payment.Zumzum__Supplier__r.Zumzum__Bank_Account_Name__c.leftPad(18, ' '));

			String reference = GeneratePaymentFileUtil.PAYMENT_REFERENCE_PREFIX + ' ' + GeneratePaymentFileUtil.PSA_REFERENCE_PREFIX +
					' ' + payment.Zumzum__Supplier__r.PSA_Area__c + '/' + payment.Name.split('-')[1];
			columns.add(reference.rightPad(18, ' '));
			String lineStr = String.join(columns, ' ').trim();
			rows.add(lineStr);
		}
		String txtString = String.join(rows,'\n').trim();

		System.assertEquals(txtContent, txtString);
	}

	@IsTest
	public static void generatePaymentFile_BankPaymentNotApproved_ShowErrorMessage() {

		Zumzum__Batch_Bank_Payment__c batchBankPayment = [
				SELECT Id, Zumzum__Status__c
				FROM Zumzum__Batch_Bank_Payment__c
				LIMIT 1
		];

		batchBankPayment.Zumzum__Status__c = 'Draft';

		update batchBankPayment;

		ApexPages.StandardController ctrl = new ApexPages.StandardController(batchBankPayment);
		GeneratePaymentFileExtension generatePaymentCtrl = new GeneratePaymentFileExtension(ctrl);

		PageReference paymentFileRef = Page.GeneratePaymentFile;
		Test.setCurrentPage(paymentFileRef);

		generatePaymentCtrl.init();

		String txtContent =  generatePaymentCtrl.getTxtString();
		String contentType =  generatePaymentCtrl.getCntType();

		System.assert(generatePaymentCtrl.showError);
		System.assertEquals(contentType, 'text/html');
		System.assertEquals(txtContent, '');
	}
}