src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Capacity_PSA__c.field-meta.xml
<CustomField>
    <fullName>Capacity_PSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity PSA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capacity_PSA_Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Capacity_PSA_Email__c.field-meta.xml
<CustomField>
    <fullName>Capacity_PSA_Email__c</fullName>
    <label>Capacity PSA Email</label>
    <type>Email</type>
</CustomField>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToBranch1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <formula>Primary_Contact__r.MailingStreet</formula>
    <label>Street Address</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practitioner?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Branch)</relationshipLabel>
        <relationshipName>Branch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <formula>CASE(WEEKDAY(Date__c), 
     1, &quot;Sunday&quot;, 
     2, &quot;Monday&quot;,  
     3, &quot;Tuesday&quot;, 
     4, &quot;Wednesday&quot;, 
     5, &quot;Thursday&quot;, 
     6, &quot;Friday&quot;, 
     7, &quot;Saturday&quot;,
     &quot;Error&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day of Week</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Branch does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Venues</relationshipLabel>
    <relationshipName>Branch_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Map_Url__c.field-meta.xml
<CustomField>
    <fullName>Map_Url__c</fullName>
    <formula>IF(ISBLANK(Host__c),
 &quot;https://www.google.co.uk/maps?q=&quot; &amp;  Postcode__c,
 &quot;https://www.google.co.uk/maps?q=&quot; &amp;  Host__r.MailingPostalCode
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Map Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Street_address__c.field-meta.xml
<CustomField>
    <fullName>Street_address__c</fullName>
    <label>Street address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>Town</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/Venue_Contact__c.object-meta.xml
<CustomObject>
    <label>Venue Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>Alternate Bookings</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Alternate Emergency</fullName>
            </value>
            <value>
                <fullName>Parent Host</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Venue Contacts</relationshipLabel>
    <relationshipName>Venue_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseLeaderTemplateComponentController.cls
/**
 * Created by User on 07.10.2019.
 */
public with sharing class CourseLeaderTemplateComponentController {
    public static Id sessionId {
        get;
        set {
            sessionId = value;
            getSessionInfo(value);
        }
    }
    public static Session__c sessionInfo { get; set; }
    public static Venue__c venueInfo { get; set; }
    public static String sessionStartTime { get; set; }
    public static String sessionEndTime { get; set; }
    public static String sessionDate { get; set; }
    public static Course__c courseInfo { get; set; }
    public static Id courseId;

    public static void getSessionInfo(Id sessionId) {
        List<Session__c> confirmedSessionList = [
                SELECT Id, Name, Type__c, Start__c, End__c, Practitioner__r.FirstName, Venue__c, Day_of_Week__c, Date__c, Course__c
                FROM Session__c
                WHERE Id = :sessionId
                LIMIT 1
        ];

        sessionInfo = confirmedSessionList[0];
        courseId = sessionInfo.Course__c;
        sessionDate = sessionInfo.Date__c.format();
        String sessionStartHour = sessionInfo.Start__c.hour() < 9 ? '0' + String.valueOf(sessionInfo.Start__c.hour()) : String.valueOf(sessionInfo.Start__c.hour());
        String sessionEndHour = sessionInfo.End__c.hour() < 9 ? '0' + String.valueOf(sessionInfo.End__c.hour()) : String.valueOf(sessionInfo.End__c.hour());
        String sessionStartMinute = sessionInfo.Start__c.minute() < 9 ? '0' + String.valueOf(sessionInfo.Start__c.minute()) : String.valueOf(sessionInfo.Start__c.minute());
        String sessionEndMinute = sessionInfo.End__c.minute() < 9 ? '0' + String.valueOf(sessionInfo.End__c.minute()) : String.valueOf(sessionInfo.End__c.minute());
        sessionStartTime = sessionStartHour + ':' + sessionStartMinute;
        sessionEndTime = sessionEndHour + ':' + sessionEndMinute;

        List<Venue__c> venueOfSession = [
                SELECT Id, Name, Map_Url__c, Town__c, Street_Address__c, Type__c
                FROM Venue__c
                WHERE Id = :sessionInfo.Venue__c
                LIMIT 1
        ];
        venueInfo = venueOfSession[0];

        List<Course__c> coursesList = [
                SELECT Id, Name, Sub_Type__c, Branch__r.Capacity_PSA__r.Name, Branch__r.Capacity_PSA_Email__c, Branch__r.Capacity_PSA_Phone__c,
                        Branch__r.Enquiries_PSA__r.Name, Branch__r.Enquiries_PSA_Email__c, Branch__r.Enquiries_PSA_Phone__c
                FROM Course__c
                WHERE Id = :sessionInfo.Course__c
                LIMIT 1
        ];
        courseInfo = coursesList[0];

        List<Booking__c> bookings = [
                SELECT Id, Name, Primary_Contact__c, Primary_Contact_Email__c, First_Name_Partner__c, Course__c, First_Name__c
                FROM Booking__c
                WHERE Course__c = :courseId
        ];
    }

    public static String getHostClientNames(Id venueId) {
        Venue_Contact__c venueContact = [
                SELECT Venue__c, Contact__c
                FROM Venue_Contact__c
                WHERE Venue__c = :venueId
        ];

        return null;
    }

}