src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Branch_Weighting__c/Branch_Weighting__c.object-meta.xml
<CustomObject>
    <label>Branch Weighting</label>
    <nameField>
        <displayFormat>BW{00000}</displayFormat>
        <label>Branch Weighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branch Weightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Weighting__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Weightings</relationshipLabel>
    <relationshipName>Branch_Weightings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Branch_Weighting__c/fields/Geographical_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Geographical_Weighting__c</fullName>
    <label>Geographical Weighting</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geographical_Weightings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Geographical_Weightings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>London,</fullName>
    </customValue>
    <customValue>
        <fullName>Fringe,</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Geographical Weightings</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestBranchWeightingBuilder.cls
@isTest
public with sharing class TestBranchWeightingBuilder {
    private Boolean insertRecord = false;
    private Account branch;
    private String geographicalWeighting = 'Standard';
    private Date startDate = Date.today() - 5;
    private Date endDate = null;

    public TestBranchWeightingBuilder insertRecord(Boolean insertRecord){
        this.insertRecord = insertRecord;
        return this;
    }

    public TestBranchWeightingBuilder branch(Account branch){
        this.branch = branch;
        return this;
    }

    public TestBranchWeightingBuilder geographicalWeighting(String geographicalWeighting){
        this.geographicalWeighting = geographicalWeighting;
        return this;
    }

    public TestBranchWeightingBuilder startDate(Date startDate){
        this.startDate = startDate;
        return this;
    }

    public TestBranchWeightingBuilder endDate(Date endDate){
        this.endDate = endDate;
        return this;
    }

    public Branch_Weighting__c build() {
        Branch_Weighting__c testWeighting = new Branch_Weighting__c(
            Branch__c = this.branch.Id,
            Geographical_Weighting__c = this.geographicalWeighting,
            Start_Date__c = this.startDate,
            End_Date__c = this.endDate
        );

		if(insertRecord)
		{
			insert testWeighting;
		}

		return testWeighting;
    }
}