src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>CARE_Payment_Frequency__c</fullName>
        <label>CARE_Payment_Frequency</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Payment__c</fullName>
        <label>First Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_type__c</fullName>
        <label>Membership type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 year standard - Individual</fullName>
                </value>
                <value>
                    <fullName>1 year standard - Joint</fullName>
                </value>
                <value>
                    <fullName>18 month - Individual</fullName>
                </value>
                <value>
                    <fullName>18 month - Joint</fullName>
                </value>
                <value>
                    <fullName>4 year - Individual</fullName>
                </value>
                <value>
                    <fullName>4 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>Life Joint Membership</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Ind</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Individual</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Joint</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Individual</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Joint</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Ind</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Jnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>Sets the installment period for your recurring donations.  WARNING: Changing the Installment Period for an existing open-ended Recurring Donation can cause open Opportunities to be deleted and recreated. Any associated data may not be retained.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp4hub__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactUtilitiesTest.cls
/*ContactUtilitiesTest Class: Used to check the Code Coverage.
    **
    * Author        : Ujwal Theja
    * Created Date  : 18-12-2018
    * (c) Copyright by CSS Corp.
    **
*/
@isTest
private class ContactUtilitiesTest {
	@isTest static void positiveMethod() {
		// Implement test code
        RecordType recordtype = [SELECT Id, Name FROM RecordType where name='staff'];
		Contact con = new Contact();
        con.FirstName = 'Test FirstName';
        con.LastName = 'Test LastName';
        con.Email = 'testemail@test.com';
        con.RecordTypeId = recordtype.id;
        insert con;
        
        Contact secCon = new Contact();
        secCon.FirstName = 'Test FirstName';
        secCon.LastName = 'Test LastName';
        secCon.Email = 'sectestemail@test.com';
        secCon.Parent_Contact__c = con.id;
        insert secCon;
        Boolean isContactExisting = ContactUtilities.isContactExisting(con.Email);
        System.assert(true,isContactExisting);
        
        Account a = new Account();
        a.RecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
        a.Name ='Test Account';
        Insert a;
        
        con.AccountId =a.Id;
        upsert con;
        
   		npe03__Recurring_Donation__c recDon = new npe03__Recurring_Donation__c();
        recDon.Name = 'Credit/Debit Card Membership';
        recDon.npe03__Amount__c = 60;
        recDon.npe03__Contact__c = con.Id;
        recDon.CARE_Payment_Frequency__c = 'One Time';
        recDon.First_Contact__c = con.Id;
        recDon.npe03__Installment_Period__c = 'Yearly';
        recDon.npsp4hub__Payment_Method__c = 'Credit/Debit Card';
        
        recDon.Membership_Status__c = 'Pending';
        
        Insert recDon;
        
        AccountContactRelation[] acr = [Select id, roles from AccountContactRelation where ContactId = :con.id];
        list<AccountContactRelation> lstac = new list<AccountContactRelation>();
        for(AccountContactRelation ac: acr){
            ac.Roles ='Branch Coordinator';
        	lstac.add(ac);
        }
        upsert lstac;
       	
        Profile portalProfile = [SELECT Id,Name FROM Profile WHERE Name ='Office Staff' Limit 1];
        User usr = new User();
        string alias = 'Test User';
        usr.Username = 'testuser1@test.com.test';
        usr.Email = 'testuser@test.com';
        usr.FirstName = 'Test';
        usr.LastName = 'User';
        usr.Alias = alias.substring(1, 6);
        usr.TimeZoneSidKey = 'GMT';
        usr.LocaleSidKey = 'en_GB';
        usr.EmailEncodingKey = 'ISO-8859-1';
        usr.LanguageLocaleKey = 'en_US';
        usr.ProfileId = portalProfile.Id;
        usr.Phone = '123456789';
        insert usr;
        
        Boolean isStaffs = true;
        Boolean isVolunteer = true;
        Boolean isPractitioner = true;
        Boolean twomems = true;
        Boolean isCompanionContactExisting = ContactUtilities.isCompanionContactExisting(con.Id);
        Boolean isVolunteerExisting = ContactUtilities.isVolunteerExisting(con.Id);
        System.assert(true,isVolunteerExisting);
        
        Id userId = usr.id;
        Boolean isStaff = ContactUtilities.isStaff(con.id);
        System.assert(true,isStaff);
        
        List<Boolean> targetCustomerList = new List<Boolean>{isStaffs,isVolunteer,isPractitioner,twomems};
        String targetCustomer = ContactUtilities.targetCustomer(targetCustomerList);
		System.assertEquals(true, isStaffs);
        System.assertEquals(true, isVolunteer);
        System.assertEquals(true, isPractitioner);
        System.assertEquals(true, twomems);
        
        Boolean isStaffsf = false;
        List<Boolean> targetCustomersList = new List<Boolean>{isStaffsf,isVolunteer,isPractitioner,twomems};
        String targetCustomers = ContactUtilities.targetCustomer(targetCustomersList);
        
        System.assertEquals(false, isStaffsf);
        System.assertEquals(true, isVolunteer);
        System.assertEquals(true, isPractitioner);
        System.assertEquals(true, twomems);
        
        Boolean isMembershipExists = ContactUtilities.isMembershipExists(con.Id, con.Email);
        System.assert(true,isMembershipExists);
	}
	
	@isTest static void negativeMethod() {
		// Implement test code
		Contact con = new Contact();
        con.FirstName = 'Test FirstName';
        con.LastName = 'Test LastName';
        con.Email = 'testemail@test.com';
        insert con;
        String str = 'testemails@test.com';
		Boolean isContactExisting = ContactUtilities.isContactExisting(str);
        System.assert(true,isContactExisting);
        
        Account a = new Account();
        a.RecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
        a.Name ='Test Account';
        Insert a;
        
        con.AccountId =a.Id;
        upsert con;
        
        Profile portalProfile = [SELECT Id,Name FROM Profile WHERE Name ='Enquiries Team' Limit 1];
        User usr = new User();
        string alias = 'Test User';
        usr.Username = 'testuser2@test.com.test';
        usr.Email = 'testuser@test.com';
        usr.FirstName = 'Test';
        usr.LastName = 'User';
        usr.Alias = alias.substring(1, 6);
        usr.TimeZoneSidKey = 'GMT';
        usr.LocaleSidKey = 'en_GB';
        usr.EmailEncodingKey = 'ISO-8859-1';
        usr.LanguageLocaleKey = 'en_US';
        usr.ProfileId = portalProfile.Id;
        usr.Phone = '123456789';
        insert usr;
        
        npe03__Recurring_Donation__c recDonate = new npe03__Recurring_Donation__c();
        recDonate.Name = 'NCT Child';
        recDonate.npe03__Amount__c = 60;
        recDonate.npe03__Installment_Period__c = 'Monthly';
        recDonate.CARE_Payment_Frequency__c = 'NCT CHILD TRUST';
        recDonate.First_Payment__c = system.today();
        recDonate.First_Contact__c = con.id; 
        recDonate.Membership_Status__c = 'Confirmed'; 
        recDonate.Membership_type__c = '18 month - Joint';
        recDonate.npe03__Contact__c = con.id;
        insert recDonate;

        Boolean isStaffs = false;
        Boolean isVolunteer = false;
        Boolean isPractitioner = false;
        Boolean twomems = true;
        Boolean isCompanionContactExisting = ContactUtilities.isCompanionContactExisting(con.Id);
        Boolean isVolunteerExisting = ContactUtilities.isVolunteerExisting(con.Id);
        System.assert(true,isVolunteerExisting);
       	Id userId = usr.id;
        Boolean isStaff = ContactUtilities.isStaff(con.id);
        System.assert(true,isStaff);
        List<Boolean> targetCustomerList = new List<Boolean>{isStaffs,isVolunteer,isPractitioner,twomems};
        String targetCustomer = ContactUtilities.targetCustomer(targetCustomerList);
		System.assertEquals(false, isStaffs);
        System.assertEquals(false, isVolunteer);
        System.assertEquals(false, isPractitioner);
        System.assertEquals(true, twomems);
        
        Boolean twomemsf = false;
        List<Boolean> targetCustomersList = new List<Boolean>{isStaffs,isVolunteer,isPractitioner,twomems};
        String targetCustomers = ContactUtilities.targetCustomer(targetCustomersList);
        
        System.assertEquals(false, isStaffs);
        System.assertEquals(false, isVolunteer);
        System.assertEquals(false, isPractitioner);
        System.assertEquals(false, twomemsf);
        
        Boolean isMembershipExists = ContactUtilities.isMembershipExists(con.id, null);
        System.assert(true,isMembershipExists);
	}
    @isTest static void permissionCheck() {

		Profile p = [SELECT Id FROM Profile WHERE Name='Read Only'];
      	User u = new User(Alias = 'newUsers', Email='newusers@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newusers@testorg.com');

        System.runAs(u) {
            Account acc = new Account();
            acc.RecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
            acc.Name ='Test Account';
            Insert acc;
            Contact con = new Contact();
            con.FirstName = 'Test FirstName';
            con.LastName = 'Test LastName';
            con.Email = 'testemail@test.com';
            con.MailingPostalCode = 'SE1';
            con.Phone ='01234567890';
            con.Salutation = 'Mr.';
            con.Branch__c = acc.id;
            insert con;
            String str = 'testemails@test.com';
            Boolean isContactExisting = ContactUtilities.isContactExisting(str);
            System.assert(true,isContactExisting);
            
            Account a = new Account();
            a.RecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
            a.Name ='Test Account';
            Insert a;
            
            con.AccountId =a.Id;
            upsert con;
            
            Profile portalProfile = [SELECT Id,Name FROM Profile WHERE Name ='Enquiries Team' Limit 1];
            User usr = new User();
            
            Boolean isStaffs = false;
            Boolean isVolunteer = false;
            Boolean isPractitioner = false;
            Boolean twomems = false;
            Boolean isCompanionContactExisting = ContactUtilities.isCompanionContactExisting(con.Id);
            Boolean isVolunteerExisting = ContactUtilities.isVolunteerExisting(con.Id);
            System.assert(true,isVolunteerExisting);
            Id userId = usr.id;
            Boolean isStaff = ContactUtilities.isStaff(con.id);
            System.assert(true,isStaff);
            List<Boolean> targetCustomerList = new List<Boolean>{isStaffs,isVolunteer,isPractitioner,twomems};
            String targetCustomer = ContactUtilities.targetCustomer(targetCustomerList);
            System.assertEquals(false, isStaffs);
            System.assertEquals(false, isVolunteer);
            System.assertEquals(false, isPractitioner);
            System.assertEquals(false, twomems);
            
            Boolean twomemsf = false;
            List<Boolean> targetCustomersList = new List<Boolean>{isStaffs,isVolunteer,isPractitioner,twomems};
            String targetCustomers = ContactUtilities.targetCustomer(targetCustomersList);
            
            System.assertEquals(false, isStaffs);
            System.assertEquals(false, isVolunteer);
            System.assertEquals(false, isPractitioner);
            System.assertEquals(false, twomemsf);
            
            Boolean isMembershipExists = ContactUtilities.isMembershipExists(con.id, con.Email);
            System.assert(true,isMembershipExists);
        }
	}
}