src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>Intrabiz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
     <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>Intrabiz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefered_First_Name__c</fullName>
        <label>Prefered First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/classes/MembershipConditionHelper.cls
public without sharing class MembershipConditionHelper {

    public static String companionCheck(Boolean twomems){
        String contactType;
        if(twomems == true){
            contactType = MembershipConstants.JOINT;
        }
        else{
            contactType = MembershipConstants.INDIVIDUAL;
        }
        return contactType;
    }
    public static Contact contactFinder( Id contId, String email){
        Contact primaryContact;
         if(!Schema.sObjectType.Contact.fields.Data_Source__c.isAccessible()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,MembershipConstants.INSUFFICIENT_ACCESS));
        }
        if(contId != null){
             primaryContact =[SELECT Id,Salutation,Gender__c, LastName, FirstName, Email, Phone,MailingStreet,MailingState,MailingCity,MailingPostalCode,Prefered_First_Name__c,AccountId FROM Contact WHERE Id =:contId limit 1];
        }
        else{
            primaryContact =[SELECT Id,Salutation,Gender__c, LastName, FirstName, Email, Phone,MailingStreet,MailingState,MailingCity,MailingPostalCode,Prefered_First_Name__c,AccountId FROM Contact WHERE Email = :email AND Email != '' limit 1];
        }
        return primaryContact;
    }
    public static void duplicateFinder(Database.Error duplicateError){
        if(duplicateError instanceof Database.DuplicateError) {
            Datacloud.DuplicateResult duplicateResult = 
                ((Database.DuplicateError)duplicateError).getDuplicateResult();
            System.debug('Duplicate records have been detected by ' + 
                         duplicateResult.getDuplicateRule());
            System.debug(duplicateResult.getErrorMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,MembershipConstants.DUPLICATE_RECORDS_FOUND));
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,''+duplicateError));
        }
    }
    public static void saveResultCheck(Database.SaveResult sr){
        if (!sr.isSuccess()) {
            
            // Insertion failed due to duplicate detected
            for(Database.Error duplicateError : sr.getErrors()){
                DuplicateFinder(duplicateError);
            }
        }
    }
    public static map<string, list<sObject>> assignBranchValues(Id branch){
        List<Account> acc;
        Map<String, list<sObject>> nearestBranchs;
        if(branch!= null){
            acc = Database.Query('SELECT id,name,Data_Source__c FROM account WHERE ID =\''+branch+'\' LIMIT 1');
            String strs = '';
            map<string, list<account>> accmap = new map<string, list<account>>();
            accmap.put(strs,acc);
            nearestBranchs = accmap; 
        }    
        return nearestBranchs;
    }
}