src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_Latitude__c</fullName>
        <formula>BillingLatitude</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address_Latitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address_Longitude__c</fullName>
        <formula>BillingLongitude</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address_Longitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Antenatal</fullName>
                </value>
                <value>
                    <fullName>Postnatal</fullName>
                </value>
                <value>
                    <fullName>Breastfeeding</fullName>
                </value>
                <value>
                    <fullName>Drop-ins</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Days (postnatal)</fullName>
                </value>
                <value>
                    <fullName>NCT Signature antenatal</fullName>
                </value>
                <value>
                    <fullName>NCT Baby Massage</fullName>
                </value>
                <value>
                    <fullName>NCT antenatal refresher</fullName>
                </value>
                <value>
                    <fullName>NCT Essentials antenatal</fullName>
                </value>
                <value>
                    <fullName>Twins and Multiples Workshop</fullName>
                </value>
                <value>
                    <fullName>Yoga for Pregnancy</fullName>
                </value>
                <value>
                    <fullName>Waterbirth</fullName>
                </value>
                <value>
                    <fullName>Introducing Solid Foods Workshop</fullName>
                </value>
                <value>
                    <fullName>NCT Parent</fullName>
                </value>
                <value>
                    <fullName>NCT Mother and Baby Yoga</fullName>
                </value>
                <value>
                    <fullName>Drop in</fullName>
                </value>
                <value>
                    <fullName>One to One</fullName>
                </value>
                <value>
                    <fullName>Combined Antenatal and Early Days (Postnatal)</fullName>
                </value>
                <value>
                    <fullName>Mantenatal</fullName>
                </value>
                <value>
                    <fullName>Birth and Beyond Antenatal</fullName>
                </value>
                <value>
                    <fullName>Early Pregnancy</fullName>
                </value>
                <value>
                    <fullName>Caesarean Workshop</fullName>
                </value>
                <value>
                    <fullName>Homebirth Workshop</fullName>
                </value>
                <value>
                    <fullName>Breathing and Relaxation</fullName>
                </value>
                <value>
                    <fullName>Breastfeeding – Antenatal</fullName>
                </value>
                <value>
                    <fullName>Breastfeeding – Postnatal</fullName>
                </value>
                <value>
                    <fullName>Relax, Stretch &amp; Breathe</fullName>
                </value>
                <value>
                    <fullName>Twins and Multiples</fullName>
                </value>
                <value>
                    <fullName>Introducing Solid Foods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FAddress_Latitude__c</fullName>
        <description>Venue__r.Address_Latitude__c</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAddress_Latitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAddress_Longitude__c</fullName>
        <description>Venue__r.Address_Longitude__c</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAddress_Longitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FEnd_Date__c</fullName>
        <formula>DATEVALUE( End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FEnd Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FStart_Date__c</fullName>
        <formula>DATEVALUE( Start_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FStart Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Branch)</relationshipLabel>
        <relationshipName>Branch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PostCode_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PostCode Allocation</relationshipLabel>
        <relationshipName>PostCode_Allocation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PLatitude__c</fullName>
        <formula>Branch__r.Address_Latitude__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PLatitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLongitude__c</fullName>
        <formula>Branch__r.Address_Longitude__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PLongitude</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>PostCode Allocation</label>
    <nameField>
        <label>PostalCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PostCode Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Branch does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Venues</relationshipLabel>
    <relationshipName>Branch_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/CourseVenueInRadiusDraftController.cls
public with sharing class CourseVenueInRadiusDraftController {
    public Decimal miles {get; set;}
    public String courseTypes {get; set;}
    private integer totalRecs = 0;
    private static Boolean geocodingCalled = false;
    public String currentPosition { get; set;}
        /*get {
            if (String.isBlank(currentPosition)) {
                currentPosition = ''; // San Francisco 51.4376,-0.0927
            }
            return currentPosition;
        }
        set; */
    //}  
    public Boolean resultsAvailable {
        get {
            if(courses == Null) {
                return false;
            }
            return true;
        }
    }
    public Boolean lstresultsAvailable {
        get {
            if(courses == Null) {
                return false;
            }
            return true;
        }
    }
    public list<String> postCode {get; set;}
    public Date bDate {get; set;}
    public Course__c cs{get; set;}
    public List<Course__c> courses {get; private set;}
    //lat = 51.5032;
    
    //list<PostCode_Allocation__c> postcodes = [SELECT Branch__r.Name FROM PostCode_Allocation__c where Name = :postCode limit 1];                         
   // public final Decimal lat =[SELECT Branch__r.Address_Latitude__c FROM PostCode_Allocation__c where Name = :postCode];
    //lon = -0.1262;
    
    public boolean match{get; set;}
    String units ='mi';
    //Date CBDate = bDate.format('YYYY-MM-DD');
    //Integer dist;
    //lt = [SELECT Branch__r.Address_Latitude__c,Branch__r.Address_Longitude__c, Id FROM PostCode_Allocation__c where Name =:postCode limit 1];
 	
 
	//Decimal lat = lt.Branch__r.Address_Latitude__c;
   // Decimal lon = lt.Branch__r.Address_Longitude__c;
    public CourseVenueInRadiusDraftController(){
       
        List<Course__c> courses = new List<Course__c>();
        cs = new Course__c();
        miles = 0;
        //lat = 51.5032;
        //lon = -0.1262;
        
            //e1 = e;
        
       // courses =[SELECT Id, Name,Course_Name__c ,Course_Type__c, Venue__c, Venue__r.BillingLatitude, Venue__r.BillingLongitude FROM Course__c WHERE DISTANCE(Venue__r.BillingAddress,GEOLOCATION(:lat,:lon), 'mi')< 5 ORDER BY DISTANCE(Venue__r.BillingAddress,GEOLOCATION(:lat,:lon), 'mi')];
    }
    public void courseList(){
        match=false;
        Decimal lat;
        Decimal lon;
        if(courses!=Null){
            courses.clear();
        }
        
        // FRAGILE: You'll want a better lat/long parsing routine
        // Format: "<latitude>,<longitude>" (must have comma, but only one comma)
        List<PostCode_Allocation__c> latlon = [SELECT Id, PLatitude__c, PLongitude__c, Name FROM PostCode_Allocation__c where Name =:currentPosition];
        if(currentPosition == NULL || currentPosition == ''){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please enter a Postal Code'));
        }
        else if(latlon.isEmpty()){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please enter a valid Postal Code'));
        }
        if(latlon.size()>0){
        lat = latlon[0].PLatitude__c;
        lon = latlon[0].PLongitude__c;
       
       /* Decimal lt = Decimal.valueOf(lat);
        Decimal ln = Decimal.valueOf(lon);
        //lat =51.5032;
        //lon =-0.1262;*/
        System.debug('lat: '+lat);
        System.debug('lon: '+lon);
		System.debug('Test:'+miles);
        System.debug('Test Date:'+bDate);
        
         String queryString =
        'SELECT Id, Name,Course_Name__c ,Course_Type__c,Status__c, FAddress_Latitude__c, FAddress_Longitude__c ' +
        'FROM Course__c ' +
        'WHERE (DISTANCE(Branch__r.BillingAddress,GEOLOCATION('+lat+','+lon+'), \'mi\')< :miles) and ((FEnd_Date__c  >= :bDate and FEnd_Date__c   <= :bDate)or(FStart_Date__c  >= :bDate and FStart_Date__c <= :bDate)or(FStart_Date__c  <= :bDate and FEnd_Date__c >= :bDate)) and (Course_Name__c = :courseTypes) ORDER BY DISTANCE(Branch__r.BillingAddress,GEOLOCATION('+lat+','+lon+'), \'mi\')';
        
        System.Debug('>>>> the value of queryString is ' + queryString);
        // Run the query
        
        courses = database.query(queryString); 
        }
        else{
            
          
        //return null;
        }
        
      	//return null;
        //return null;
        //if(distances==20){
        	//courses =[SELECT Id, Name,Course_Name__c ,Course_Type__c,Status__c, Venue__c, Venue__r.BillingLatitude, Venue__r.BillingLongitude FROM Course__c WHERE (DISTANCE(Venue__r.BillingAddress,GEOLOCATION(:lt,:ln), 'mi')< :miles) and ((FEnd_Date__c  >= :bDate and FEnd_Date__c   <= :bDate)or(FStart_Date__c  >= :bDate and FStart_Date__c <= :bDate)or(FStart_Date__c  <= :bDate and FEnd_Date__c >= :bDate)) and (Course_Name__c = :courseTypes) ORDER BY DISTANCE(Venue__r.BillingAddress,GEOLOCATION(:lat,:lon), 'mi')];
		//}
        /*if(courses.size()>0){
            match=true;
        }
        return null;*/
    }
    
}