src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Zumzum__Debit__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Debit__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Planned to be deprecated 25/10/2015</inlineHelpText>
    <label>Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Nominal_Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Nominal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nominal Account</label>
    <referenceTo>Zumzum__Nominal_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account_Settings__c/Bank_Account_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bank Account Settings</label>
</CustomObject>

force-app/main/default/objects/Bank_Account_Settings__c/fields/Worldpay_Bank_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Bank_Account_Id__c</fullName>
    <label>Worldpay Bank Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/cpm__Payment__c.object
<CustomObject>
    <description>Payments are actual amounts of money transfered to our organisation, either spontaneously or as the result of a Recurring Payment.</description>
    <fields>
        <fullName>cpm__Amount__c</fullName>
        <description>The amount of the payment.</description>
        <inlineHelpText>The amount of this payment.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cpm__Installment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The installment this payment originated from.</description>
        <inlineHelpText>The installment this payment originated from.</inlineHelpText>
        <label>Installment</label>
        <referenceTo>cpm__Installment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Recurring_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Recurring Payment that resulted in this payment.</description>
        <inlineHelpText>The Recurring Payment that resulted in this payment.</inlineHelpText>
        <label>Recurring Payment</label>
        <referenceTo>cpm__Recurring_Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0}</displayFormat>
        <label>Payment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Recurring_Payment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Recurring Payments</relationshipLabel>
    <relationshipName>Recurring_Payments_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/Zumzum__Bank_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Receipt</label>
    <nameField>
        <displayFormat>BRUID-{0000000000}</displayFormat>
        <label>Bank Receipt UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cpm__Payment__c</referenceTo>
    <relationshipLabel>Bank Receipts</relationshipLabel>
    <relationshipName>Bank_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Ledger__c/Zumzum__Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Nominal_Account__c/Zumzum__Nominal_Account__c.object-meta.xml
<CustomObject>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/Zumzum__Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>SI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/Zumzum__Sales_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line Item</label>
    <nameField>
        <label>Sales Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Sales_Invoice_Line_Item__c/fields/Zumzum__Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Line Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddBankReceiptForPaymentHandler.cls
public with sharing class AddBankReceiptForPaymentHandler {
    private static final String DEBTOR_NOMINAL_CODE = '9300';
    private static final String MEMBERSHIP_NOMINAL_CODE = '1003';
    private static final String SALES_INVOICE_STATUS = 'Posted';
    private static final String IS_PAID = 'Y';
    private static final Id BANK_ACCOUNT_ID = Bank_Account_Settings__c.getOrgDefaults().Worldpay_Bank_Account_Id__c;

    public static void addBankReceipts(List<cpm__Payment__c> payments) {
        try {
            if (String.isBlank(BANK_ACCOUNT_ID)) {
                throw new ListException('Set Bank Account Id custom setting');
            }

            Zumzum.BankCustomerReceiptService bankCustomerReceiptService = new Zumzum.BankCustomerReceiptService();
            Zumzum.BankCustomerReceiptService.BankCustomerReceiptWrapper receiptWrapper = new Zumzum.BankCustomerReceiptService.BankCustomerReceiptWrapper();
            Map<Id, List<cpm__Payment__c>> salesInvoicesPaymentsMap = new Map<Id, List<cpm__Payment__c>>();

            for (cpm__Payment__c payment : payments) {
                if (payment.cpm__Installment__r.Sales_Invoice__c != null) {
                    if (salesInvoicesPaymentsMap.containsKey(payment.cpm__Installment__r.Sales_Invoice__c)) {
                        salesInvoicesPaymentsMap.get(payment.cpm__Installment__r.Sales_Invoice__c).add(payment);
                    } else {
                        salesInvoicesPaymentsMap.put(payment.cpm__Installment__r.Sales_Invoice__c, new List<cpm__Payment__c>{payment});
                    }
                } else if (payment.cpm__Installment__r.cpm__Recurring_Payment__r.Sales_Invoice__c <> null) {
                    if (salesInvoicesPaymentsMap.containsKey(payment.cpm__Installment__r.cpm__Recurring_Payment__r.Sales_Invoice__c)) {
                        salesInvoicesPaymentsMap.get(payment.cpm__Installment__r.cpm__Recurring_Payment__r.Sales_Invoice__c).add(payment);
                    } else {
                        salesInvoicesPaymentsMap.put(payment.cpm__Installment__r.cpm__Recurring_Payment__r.Sales_Invoice__c, new List<cpm__Payment__c>{payment});
                    }
                }
            }

            for (Zumzum__Sales_Invoice__c salesInvoice : [
                    SELECT Zumzum__Account__c, (
                            SELECT Name,
                                   Zumzum__Debit__c,
                                   Zumzum__Sub_Account_Nominal__c,
                                   Zumzum__Sales_Invoice_Line_Item__c,
                                   Zumzum__Sales_Invoice_Line_Item__r.Zumzum__Nominal_Account__r.Zumzum__Nominal_Code__c
                            FROM Zumzum__Ledger__r
                            WHERE Zumzum__Sub_Account_Nominal__c = :DEBTOR_NOMINAL_CODE AND Zumzum__Paid__c <> :IS_PAID
                    )
                    FROM Zumzum__Sales_Invoice__c
                    WHERE Id IN :salesInvoicesPaymentsMap.keySet() AND Zumzum__Status__c = :SALES_INVOICE_STATUS AND Zumzum__Paid__c <> :IS_PAID
                    WITH SECURITY_ENFORCED
            ]) {
                for (cpm__Payment__c payment : salesInvoicesPaymentsMap.get(salesInvoice.Id)) {
                    receiptWrapper.AccountId = salesInvoice.Zumzum__Account__c;
                    receiptWrapper.BankAccountId = BANK_ACCOUNT_ID;
                    receiptWrapper.PostingDate = Date.Today();
                    receiptWrapper.WrapperAPICustomFields = new List<Zumzum.APICustomFieldWrapper>();
                    receiptWrapper.WrapperAPICustomFields.add(new Zumzum.APICustomFieldWrapper('Zumzum__Bank_Receipt__c', 'Payment__c', payment.Id));
                    receiptWrapper.BankReceiptLines = createBankReceiptLines(payment, salesInvoice);
                    Zumzum.BankCustomerReceiptService.Response response = bankCustomerReceiptService.CreateBankCustomerReceipt(receiptWrapper);
                }
            }
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }

    private static List<Zumzum.BankCustomerReceiptService.BankReceiptLine> createBankReceiptLines(cpm__Payment__c payment, Zumzum__Sales_Invoice__c salesInvoice) {
        List<Zumzum.BankCustomerReceiptService.BankReceiptLine> listBankReceiptLines = new List<Zumzum.BankCustomerReceiptService.BankReceiptLine>();
        Zumzum.BankCustomerReceiptService.BankReceiptLine courseBankReceiptLine = new Zumzum.BankCustomerReceiptService.BankReceiptLine();
        if (salesInvoice.Zumzum__Ledger__r.size() > 1) {
            Zumzum.BankCustomerReceiptService.BankReceiptLine membershipBankReceiptLine = new Zumzum.BankCustomerReceiptService.BankReceiptLine();
            for (Zumzum__Ledger__c ledger : salesInvoice.Zumzum__Ledger__r) {
                if (ledger.Zumzum__Sales_Invoice_Line_Item__r.Zumzum__Nominal_Account__r.Zumzum__Nominal_Code__c == MEMBERSHIP_NOMINAL_CODE) {
                    membershipBankReceiptLine.Amount = ledger.Zumzum__Debit__c;
                    membershipBankReceiptLine.LedgerName = ledger.Name;
                } else {
                    courseBankReceiptLine.LedgerName = ledger.Name;
                }                
            }
            courseBankReceiptLine.Amount = payment.cpm__Amount__c - membershipBankReceiptLine.Amount;
            listBankReceiptLines.add(membershipBankReceiptLine);
            listBankReceiptLines.add(courseBankReceiptLine);
        } else {
            courseBankReceiptLine.Amount = payment.cpm__Amount__c;
            courseBankReceiptLine.LedgerName = salesInvoice.Zumzum__Ledger__r[0].Name;
            listBankReceiptLines.add(courseBankReceiptLine);
        }
        return listBankReceiptLines;
    }
}