src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>An account representing a venue</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/Card_Payment_Plan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Card Payment Plan Settings</label>
</CustomObject>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Maximum_Days_Before_Paid__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Days_Before_Paid__c</fullName>
    <description>Represents the number of days the course fee must be fully paid before the course starts. Otherwise, the payment option is not available.
This applies to all course types.</description>
    <label>Maximum Days Before Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Min_Days_Before_First_Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Min_Days_Before_First_Recurring_Payment__c</fullName>
    <description>Represents the number of days before the end of the current month to decide when the first recurring payment will happen:
1. If today is equal or less days before the 1st day of the next month (comparing to the number) then the first recurring payment will be paid on the 1st day of the month that is next to the next month.
2. Otherwise, the first recurring payment will be paid on the 1st day of the next month.</description>
    <label>Min Days Before First Recurring Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimal_First_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimal_First_Amount__c</fullName>
    <description>Represents the minimal possible amount of the intial payment when calculating payment plan options</description>
    <label>Minimal First Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Payment_Plan_Settings__c/fields/Minimal_Recurring_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimal_Recurring_Amount__c</fullName>
    <description>Represents the minimal possible amount of the recurring payment when calculating payment plan options</description>
    <label>Minimal Recurring Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentPlanOptionsHandlerTest.cls
@isTest
public class PaymentPlanOptionsHandlerTest {
    private static final Integer COURSE_FEE = 200;
    private static Integer initialPaymentDayNumber = 5;
    private static Date THIS_MONTH_START_DATE = Date.today().toStartOfMonth();
    private static Integer thisMonthDiff = 0;
    private static final Integer START_DATE_MONTHS_LEFT = 6;
    @testSetup
    static void createPaymentParamRecords() {
        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account branch =  accountBuilder.withRecordType('Branch')
            .withName('Test Branch')
            .withBillingPostalCode('AB12 3CD')
            .insertRecord(true)
            .build();
        Account account =  accountBuilder
            .withRecordType('Household Account')
            .insertRecord(true)
            .build();
        Account organization = accountBuilder.withRecordType('Organization')
            .withName('Test Organization')           
            .withType('Supplier')
            .insertRecord(true)
            .withBillingEmail('test@test.com')
            .withAccountNumber('123456')
            .build();
        TestContactBuilder contactBuilder = new TestContactBuilder();
        Contact primaryContact = contactBuilder.withRecordType('Client')
            .withAccount(account)
            .withFirstName('John')
            .withLastName('Primary')
            .insertRecord(true)
            .build();
        Contact partnerContact = contactBuilder.withRecordType('Client')
            .withAccount(account)
            .withFirstName('Jane')
            .withLastName('Partner')
            .insertRecord(true)
            .build();
        Contact practitioner = contactBuilder.withRecordType('Practitioner')
            .withAccount(organization)
            .withFirstName('Jack')
            .withLastName('Practitioner')
            .insertRecord(true)
            .build();
        TestLicenceToPracticeBuilder lisenceBuilder = new TestLicenceToPracticeBuilder();
        Licence_To_Practice__c lisence = lisenceBuilder.withContact(practitioner)
            .withStartDate(THIS_MONTH_START_DATE)
            .withStatus('Full')
            .withLicence('Signature Antenatal Teacher')
            .insertRecord(true)
            .build();
        TestVenueBuilder venueBuilder = new TestVenueBuilder();
        Venue__c venue = venueBuilder.withName('Venue1')
            .insertRecord(true)
            .build();
        TestCourseBuilder courseBuilder = new TestCourseBuilder();
        Course__c course = courseBuilder.withType('Postnatal')
            .withSubType('NCT Baby Massage')
            .withFee(COURSE_FEE)
            .withNumberOfPlaces(15)
            .withStatus('Draft')
            .withAccount(branch)
            .withLicenceToPractice(lisence)
            .withPractitioner(practitioner)
            .withMainVenue(venue)
            .insertRecord(true)
            .build();
        TestBookingBuilder bookingBuilder = new TestBookingBuilder();
        Booking__c bookings = bookingBuilder.withCourse(course)
            .withStatus('Reserved')
            .withPrimaryContact(primaryContact)
            .withPartnerContact(partnerContact)
            .withBookingExpiryDate(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber))
            .insertRecord(true)
            .build();
        TestRoomBuilder roomBuilder = new TestRoomBuilder();
        Room__c room = roomBuilder.withVenue(venue)
            .insertRecord(true)
            .build();
        TestSessionBuilder sessionBuilder = new TestSessionBuilder();
        sessionBuilder.withPractitioner(practitioner)
            .withType('Standard')
            .withDate(THIS_MONTH_START_DATE.addMonths(START_DATE_MONTHS_LEFT))
            .withPractitionerLicence(lisence)
            .withVenue(venue)
            .withCourse(course)
            .withRoom(room)
            .insertRecord(true)
            .build();
    }
    @isTest
    static void testCourseFeeLessThanMinimum() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 300;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 100;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 0);
        Test.stopTest();
    }
    @isTest
    static void testNextMonthFirstRecurringPayment() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 30;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 10;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addMonths(1)));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(3);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        System.assertEquals(options[2].label, '4 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void testAfterNextMonthFirstRecurringPayment() {
        initialPaymentDayNumber = 25;
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 30;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 10;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(2).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(4);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        System.assertEquals(options[2].label, '4 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void testDatesOneRecurringPayment() {
        thisMonthDiff = 4;
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 30;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 10;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 1);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(thisMonthDiff + 1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(5);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        Test.stopTest();
    }
    @isTest
    static void testDatesTwoRecurringPayment() {
        thisMonthDiff = 3;
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 30;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 10;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 2);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(thisMonthDiff + 1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(5);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        Test.stopTest();
    }
    @isTest
    static void testFeeOneRecurringPayment() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 150;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 49;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 1);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(1);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '1 payment of £ 150.00 and 1 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void testFeeTwoRecurringPayments() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 100;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 49;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 2);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(2);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 100.00 and 2 monthly payment of £ 50.00');
        Test.stopTest();
    }
    @isTest
    static void testFeeThreeRecurringPayments() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 80;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 39;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(3);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 80.00 and 2 monthly payment of £ 60.00');
        System.assertEquals(options[2].label, '1 payment of £ 80.00 and 3 monthly payment of £ 40.00');
        Test.stopTest();
    }
    @isTest
    static void testFeeThreeEqualRecurringPayments() {
        Card_Payment_Plan_Settings__c cardPaymentPlanSettings = new Card_Payment_Plan_Settings__c();
        cardPaymentPlanSettings.Maximum_Days_Before_Paid__c = 28;
        cardPaymentPlanSettings.Minimal_First_Amount__c = 50;
        cardPaymentPlanSettings.Minimal_Recurring_Amount__c = 40;
        cardPaymentPlanSettings.Min_Days_Before_First_Recurring_Payment__c = 14;
        insert cardPaymentPlanSettings;
        PaymentPlanOptionsHandler.firstPaymentDate = THIS_MONTH_START_DATE.addMonths(thisMonthDiff);
        Test.startTest();
        Booking__c booking = [SELECT Id, Course__c, Primary_Contact__c FROM Booking__c LIMIT 1];
        Course__c course = [SELECT Id, Start_Date__c, Fee__c FROM Course__c WHERE Id =: booking.Course__c LIMIT 1];
        PaymentPlanParameters paymentPlanParameters = new PaymentPlanParameters();
        paymentPlanParameters.bookingId = booking.Id;
        paymentPlanParameters.courseFee = course.Fee__c;
        paymentPlanParameters.contactId = booking.Primary_Contact__c;
        paymentPlanParameters.startDate = course.Start_Date__c;
        List<PaymentPlanOption> options = PaymentPlanOptionsHandler.getOptions(new List<PaymentPlanParameters> {paymentPlanParameters})[0];
        System.assertEquals(options.size(), 3);
        System.assertEquals(options[0].startDate, String.valueOf(THIS_MONTH_START_DATE.addDays(initialPaymentDayNumber).addMonths(1).toStartOfMonth()));
        Date lastPaymentDate = THIS_MONTH_START_DATE.addMonths(3);
        System.assertEquals(options[0].endDate, String.valueOf(lastPaymentDate + Date.daysInMonth(lastPaymentDate.year(), lastPaymentDate.month()) - 1));
        System.assertEquals(options[0].label, '2 monthly payment of £ 100.00');
        System.assertEquals(options[1].label, '1 payment of £ 66.68 and 2 monthly payment of £ 66.66');
        System.assertEquals(options[2].label, '4 monthly payment of £ 50.00');
        Test.stopTest();
    }
}