src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Venue</fullName>
        <active>true</active>
        <description>An account representing a venue</description>
        <label>Venue</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public without sharing class TestDataFactory {
    public static List<Venue__c> venues = [SELECT Id FROM Venue__c LIMIT 5];
    public static List<Account> accounts = [SELECT Id FROM Account LIMIT 5];
    public static List<Room__c> rooms = [SELECT Id FROM Room__c LIMIT 5];
    public static List<Licence_To_Practice__c> licenceToPractices = [SELECT Id FROM Licence_To_Practice__c LIMIT 5];
    public static List<Course__c> courses;
    public static Course__c course0;
    public static Course__c course1;
    public static Course__c course2;
    public static Course__c course3;

    public static void createCourses() {
        TestCourseBuilder courseBuilder = new TestCourseBuilder();
        course0 = courseBuilder
            .WithAccount(accounts[0])
            .WithLicenceToPractice(licenceToPractices[0])
            .InsertRecord(true)
            .Build();
        course1 = courseBuilder
            .WithAccount(accounts[0])
            .WithLicenceToPractice(licenceToPractices[0])
            .InsertRecord(true)
            .Build();
        course2 = courseBuilder
            .WithAccount(accounts[0])
            .WithLicenceToPractice(licenceToPractices[0])
            .InsertRecord(true)
            .Build();
        course3 = courseBuilder
            .WithAccount(accounts[0])
            .WithLicenceToPractice(licenceToPractices[0])
            .InsertRecord(true)
            .Build();
    }

    public static void createSessions(){
        TestSessionBuilder sessionBuilder = new TestSessionBuilder();
        sessionBuilder
            .WithCourse(course0)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course0)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course1)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course1)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course2)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course2)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course3)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
        sessionBuilder
            .WithCourse(course3)
            .WithVenue(venues[0])
            .WithPractitionerLicence(licenceToPractices[0])
            .WithRoom(rooms[0])
            .InsertRecord(true)
            .Build();
    }

    public static void createEstimatedCosts(){
        TestEstimatedCostsBuilder estimatedCostsBuilder = new TestEstimatedCostsBuilder();
        estimatedCostsBuilder
            .WithCourse(course0)
            .WithType('Travel')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course0)
            .WithType('Venue')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course0)
            .WithType('Practitioner Fee')
            .InsertRecord(true)
            .Build();

        estimatedCostsBuilder
            .WithCourse(course1)
            .WithType('Travel')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course1)
            .WithType('Venue')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course1)
            .WithType('Practitioner Fee')
            .InsertRecord(true)
            .Build();

        estimatedCostsBuilder
            .WithCourse(course2)
            .WithType('Travel')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course2)
            .WithType('Venue')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course2)
            .WithType('Practitioner Fee')
            .InsertRecord(true)
            .Build();

        estimatedCostsBuilder
            .WithCourse(course3)
            .WithType('Travel')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course3)
            .WithType('Venue')
            .InsertRecord(true)
            .Build();
        estimatedCostsBuilder
            .WithCourse(course3)
            .WithType('Practitioner Fee')
            .InsertRecord(true)
            .Build();
    }

}