src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Account_No__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Account_No__c</fullName>
    <description>The organisation&#39;s bank account number</description>
    <label>Bank Account No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Bank_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Bank_Sort_Code__c</fullName>
    <label>Bank Sort Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Total_Unpaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Total_Unpaid_Amount__c</fullName>
    <formula>Zumzum__Total_Gross__c -  Zumzum__Total_Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Unpaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ZumzumBACSpaymentActions.cls
public with sharing class ZumzumBACSpaymentActions {
    @invocableMethod(label='Link Purchase Invoices')
    public static List<Response> linkPurchaseInvoices(List<Request> requests) {
        List<Response> result = new List<Response>();
        String paymentRunId = requests[0].recordId;
        
        Set<Id> linkedPIids = new Set<Id>();
        List<Payment_Run_Line_Item__c> existingPrliList = [
            SELECT Id, Purchase_Invoice__c
            FROM Payment_Run_Line_Item__c
            WITH SECURITY_ENFORCED
        ];
        for (Payment_Run_Line_Item__c prli : existingPrliList) {
            linkedPIids.add(prli.Purchase_Invoice__c);
        }

        List<Payment_Run_Line_Item__c> prliList = new List<Payment_Run_Line_Item__c>();
        for (Zumzum__Purchase_Invoice__c pi : [
            SELECT Id 
            FROM Zumzum__Purchase_Invoice__c 
            WHERE Id NOT IN :linkedPIids
              AND Zumzum__Status__c <> 'Paid'
              AND Zumzum__Total_Unpaid_Amount__c > 0
                    AND Zumzum__Account__r.Zumzum__Bank_Account_Name__c <> ''
                    AND Zumzum__Account__r.Zumzum__Bank_Account_No__c <> ''
                    AND Zumzum__Account__r.Zumzum__Bank_Sort_Code__c <> ''
        ]) {
            Payment_Run_Line_Item__c prli = new Payment_Run_Line_Item__c();
            prli.Payment_Run__c = paymentRunId;
            prli.Purchase_Invoice__c = pi.Id;
            prliList.add(prli);
        }
        if (prliList.isEmpty()) {
            result.add(new Response(
                false, 
                'There is no Purchase Invoices matching the action criteria'
            ));
        } else {
            if (Payment_Run_Line_Item__c.sObjectType.getDescribe().isCreateable()) {
                insert prliList;
                result.add(new Response(true));
            } else {
                result.add(new Response(
                    false, 
                    'The user has no access rights to create Payment Run Line Items'
                ));
            }
        }
        return result;
    }
    
    public class Request {
        @invocableVariable(
            label='Payment Run Id'
            required=true
        )
        public String recordId;
    }
    
    public class Response {
        @invocableVariable
        public Boolean isSuccess;
        @invocableVariable
        public String message;
        
        public Response(Boolean isSuccess) {
            this(isSuccess, null);
        }
        
        public Response(Boolean isSuccess, String message) {
            this.isSuccess = isSuccess;
            this.message = message;
        }
    }
}