src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner_Licence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Number_of_places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_places__c</fullName>
    <label>Number of places</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Returning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCourseBuilder.cls
@isTest
public with sharing class TestCourseBuilder {
    private String type = 'Antenatal';
    private String subType  ='One to One';
    private Integer fee = 100;
    private Integer numberOfPlaces = 1;
    private String status = 'Draft';
    private Account account;
    private Licence_To_Practice__c licenceToPractice;
    private Boolean insertRecord = false;

    public TestCourseBuilder WithType(String type)
    {
        this.type = type;
        return this;
    }

    public TestCourseBuilder WithSubType(String subType)
    {
        this.subType = subType;
        return this;
    }

    public TestCourseBuilder WithSFee(Integer fee)
    {
        this.fee = fee;
        return this;
    }
    public TestCourseBuilder WithNumberOfPlaces(Integer numberOfPlaces)
    {
        this.numberOfPlaces = numberOfPlaces;
        return this;
    }

    public TestCourseBuilder WithStatus(String status)
    {
        this.status = status;
        return this;
    }
    public TestCourseBuilder WithAccount(Account account)
    {
        this.account = account;
        return this;
    }
    public TestCourseBuilder WithLicenceToPractice(Licence_To_Practice__c licenceToPractice)
    {
        this.licenceToPractice = licenceToPractice;
        return this;
    }
    public TestCourseBuilder InsertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public Course__c Build()
    {
        Course__c course = new Course__c(
            Type__c = this.type,
            Sub_Type__c = this.subType,
            Fee__c = this.fee,
            Status__c = this.status,
            Number_of_places__c = this.numberOfPlaces,
            Branch__c = this.account.Id,
            Main_Practitioner_Licence__c = this.licenceToPractice.Id
        );

        if(insertRecord)
        {
            insert course;
        }

        return course;
    }
}