src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefered_First_Name__c</fullName>
        <label>Prefered First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card(£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 10)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Membership_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                    <isActive>false</isActive>
                    <label>Practitioner</label>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                    <isActive>false</isActive>
                    <label>Volunteer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Gift_Aid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Gift Aid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GiftAid_Acquisition_Method__c</fullName>
        <label>GiftAid Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oral</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GiftAid_Type__c</fullName>
        <label>GiftAid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
                <value>
                    <fullName>99 Years</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>18 month membership</fullName>
                </value>
                <value>
                    <fullName>12 month membership</fullName>
                </value>
                <value>
                    <fullName>Reduced 12 month membership</fullName>
                </value>
                <value>
                    <fullName>4 year membership</fullName>
                </value>
                <value>
                    <fullName>10 year membership</fullName>
                </value>
                <value>
                    <fullName>Life Membership</fullName>
                </value>
                <value>
                    <fullName>Staff Membership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No. of Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <label>Payment Processor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentHub-BACS</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-Stripe</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-WorldPay</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-GiftAid</fullName>
                    <isActive>false</isActive>
                    <label>PaymentHub-GiftAid</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Target__c</fullName>
        <label>Payment Target</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NCT Membership Collections - S18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card (£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£10)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£250)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£250)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£6.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Life Membership - Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recursive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recursive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Multiply By</fullName>
                    <default>true</default>
                    <label>Multiply By</label>
                </value>
                <value>
                    <fullName>Divide By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Customer__c</fullName>
        <label>Target Customer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer/Practitioner</fullName>
                </value>
                <value>
                    <fullName>Parent on benefits</fullName>
                </value>
                <value>
                    <fullName>Staff only</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Parent, Companion</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Membership Type</label>
    <pluralLabel>Membership Types</pluralLabel>
</CustomObject>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NctETMembershipPaymentPageControllerTest.cls
@isTest
private class NctETMembershipPaymentPageControllerTest {
    private static PaymentHubApiSettings__c paymentHubApiSettings = PaymentHubApiSettings__c.getInstance();
    Static contact newCont;
    @isTest static void contactIdExists() {
        Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt
                                                WHERE Payment_Method__c = 'Credit/Debit Card' limit 1];
        
		Account acc = new Account();
		acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();       
        acc.Name ='Test Branch';
        insert acc;
        Contact con = new Contact();
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();

        con.Branch__c = acc.id; 
        con.MailingStreet = 'Test address';
        con.MailingState = 'Test State';
        con.MailingCity = 'Test City';
        con.Prefered_First_Name__c = 'Test FirstName';
        con.LastName = 'Test LastName';
        con.Email = 'testemail@test.com';
        con.Phone = '123456789';
        con.MailingPostalCode = 'SW123';
        con.salutation = 'Mr';
        con.Gender__c = 'Male';
        insert con;

		npe03__Recurring_Donation__c recDonate = new npe03__Recurring_Donation__c();
        recDonate.Name = 'NCT Child';
        recDonate.npe03__Amount__c = 60;
        recDonate.npe03__Installment_Period__c = 'Monthly';
        recDonate.CARE_Payment_Frequency__c = 'NCT CHILD TRUST';
        recDonate.First_Payment__c = system.today();
        recDonate.First_Contact__c = con.id; 
        recDonate.Membership_Status__c = 'Pending'; 
        recDonate.Membership_type__c = '18 month - Joint';
        recDonate.npe03__Contact__c = con.id;

        insert recDonate; 
 

       
        PageReference pageRef = Page.nctETMembershipPaymentPage; 
        Id contId = pageRef.getParameters().put('Id', String.valueOf(con.Id));
        Test.setCurrentPage(pageRef); 

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        nctETMembershipPaymentPageController controller = new nctETMembershipPaymentPageController();
        ApexPages.currentPage().getParameters().put('seltdName',membershipDetails.Id);
        ApexPages.currentPage().getParameters().put('seltAmountdName',membershipDetails.Id);
        ApexPages.currentPage().getParameters().put('emailsVal','testemail@test.com');
        ApexPages.currentPage().getParameters().put('postVal','SE1 3XF');
        ApexPages.currentPage().getParameters().put('emailDupeVal','testemail@test.com');

        controller.FirstName = con.id;
        controller.LastName = con.id;
        controller.Email = con.Id;
        controller.phone = con.Id;
        controller.postCode = con.Id;
        controller.selectBranch = con.Id; 
        controller.salutation = con.id;
        controller.genderValue = con.id;
        controller.streetValue = con.Id;
        controller.stateValue = con.Id;
        controller.streetValue1 = con.Id;
        controller.streetValue2 = con.Id;
        controller.cityValue = con.Id;
        controller.primaryContact = con;
        controller.accountNumber = '12345';
        controller.accountName ='Test';
        controller.sortCode = '';
        controller.acquistion ='';
        controller.membershipSource ='';
        controller.sessionProfile = 'guest';
        controller.twomem = true;
        controller.expDate = System.Date.today();

        controller.receiveInput();
        controller.onCompleteContactInfo();
        controller.nctBranchs();
        controller.membershipDupeChecker();
        controller.giftAidCreation();
        controller.PaymentSave();     
        Test.stopTest();
        system.assertEquals(1,1);
       
    }
    @isTest static void contactIdNotExists(){
         Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt 
                                                WHERE Payment_Method__c = 'Credit/Debit Card' limit 1];
        
		Account acc = new Account();
		acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();       
        acc.Name ='Test Branch';
        insert acc;
        Contact con = new Contact();
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();

        con.Branch__c = acc.id; 
        con.MailingStreet = 'Test address';
        con.MailingState = 'Test State';
        con.MailingCity = 'Test City';
        con.Prefered_First_Name__c = 'Test FirstName';
        con.LastName = 'Test LastName';
        con.Email = 'testemail@test.com';
        con.Phone = '123456789';
        con.MailingPostalCode = 'SW123';
        con.salutation = 'Mr';
        con.Gender__c = 'Male';
        insert con;

		npe03__Recurring_Donation__c recDonate = new npe03__Recurring_Donation__c();
        recDonate.Name = 'NCT Child';
        recDonate.npe03__Amount__c = 60;
        recDonate.npe03__Installment_Period__c = 'Monthly';
        recDonate.CARE_Payment_Frequency__c = 'NCT CHILD TRUST';
        recDonate.First_Payment__c = system.today();
        recDonate.First_Contact__c = con.id; 
        recDonate.Membership_Status__c = 'Pending'; 
        recDonate.Membership_type__c = '18 month - Joint';
        recDonate.npe03__Contact__c = con.id;

        insert recDonate; 
 

       
        PageReference pageRef = Page.nctETMembershipPaymentPage; 
        Id contId = pageRef.getParameters().put('Id', String.valueOf(con.Id));
        Test.setCurrentPage(pageRef); 
        
        
        PaymentHubApiSettings__c paymentHubApiSettings = new PaymentHubApiSettings__c();
        paymentHubApiSettings.Payment_Status_Root_Url__c = 'https://test.salesforce.com/nctMembershipPaymentPage';
        paymentHubApiSettings.Credit_Card_Payment_API_Token__c = '1234567890123';
        insert paymentHubApiSettings; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        nctETMembershipPaymentPageController controller = new nctETMembershipPaymentPageController();
         ApexPages.currentPage().getParameters().put('emailsVal','testemail@test.com');
        ApexPages.currentPage().getParameters().put('postVal','SE1 3XF');
        ApexPages.currentPage().getParameters().put('emailDupeVal','testemail@test.com');

        controller.FirstName = con.id;
        controller.LastName = con.id;
        controller.Email = con.Id;
        controller.phone = con.Id;
        controller.postCode = con.Id;
        controller.selectBranch = con.Id; 
        controller.salutation = con.id;
        controller.genderValue = con.id;
        controller.streetValue = con.Id;
        controller.stateValue = con.Id;
        controller.streetValue1 = con.Id;
        controller.streetValue2 = con.Id;
        controller.cityValue = con.Id;
        controller.primaryContact = con;
        controller.feeAmount = membershipDetails.Id;
        controller.accountNumber = '12345';
        controller.accountName ='Test';
        controller.sortCode = '';
        controller.acquistion ='';
        controller.membershipSource ='';
        controller.sessionProfile = 'guest';
        controller.twomem = true;
        controller.expDate = System.Date.today();

        controller.receiveInput();
        controller.nctBranchs();
        controller.contactInfo();
        controller.giftAidCreation();
        Test.stopTest();
        system.assertEquals(1,1);
    }
    @isTest static void secondContactIdNotExists(){
         Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt 
                                                WHERE Payment_Method__c = 'Credit/Debit Card' limit 1];
        
		Account acc = new Account();
		acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();       
        acc.Name ='Test Branch';
        insert acc;
        Contact con = new Contact();
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();

        con.Branch__c = acc.id; 
        con.MailingStreet = 'Test address';
        con.MailingState = 'Test State';
        con.MailingCity = 'Test City';
        con.Prefered_First_Name__c = 'Test FirstName';
        con.LastName = 'Test LastName';
        con.Email = 'testemail@test.com';
        con.Phone = '123456789';
        con.MailingPostalCode = 'SW123';
        con.salutation = 'Mr';
        con.Gender__c = 'Male';
        insert con;

		npe03__Recurring_Donation__c recDonate = new npe03__Recurring_Donation__c();
        recDonate.Name = 'NCT Child';
        recDonate.npe03__Amount__c = 60;
        recDonate.npe03__Installment_Period__c = 'Monthly';
        recDonate.CARE_Payment_Frequency__c = 'NCT CHILD TRUST';
        recDonate.First_Payment__c = system.today();
        recDonate.First_Contact__c = con.id; 
        recDonate.Membership_Status__c = 'Pending'; 
        recDonate.Membership_type__c = '18 month - Joint';
        recDonate.npe03__Contact__c = con.id;

        insert recDonate; 
 

       
        PageReference pageRef = Page.nctETMembershipPaymentPage; 
        Id contId = pageRef.getParameters().put('Id', String.valueOf(con.Id));
        Test.setCurrentPage(pageRef); 
              
        PaymentHubApiSettings__c paymentHubApiSettings = new PaymentHubApiSettings__c();
        paymentHubApiSettings.Payment_Status_Root_Url__c = 'https://test.salesforce.com/nctMembershipPaymentPage';
        paymentHubApiSettings.Credit_Card_Payment_API_Token__c = '1234567890123';
        insert paymentHubApiSettings; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        nctETMembershipPaymentPageController controller = new nctETMembershipPaymentPageController();
        ApexPages.currentPage().getParameters().put('emailsVal','testemail@test.com');
        ApexPages.currentPage().getParameters().put('postVal','SE1 3XF');
        ApexPages.currentPage().getParameters().put('emailDupeVal','testemail@test.com');

        controller.FirstName = con.id;
        controller.LastName = con.id;
        controller.Email = con.Id;
        controller.phone = con.Id;
        controller.postCode = con.Id;
        controller.selectBranch = con.Id; 
        controller.salutation = con.id;
        controller.genderValue = con.id;
        controller.streetValue = con.Id;
        controller.stateValue = con.Id;
        controller.streetValue1 = con.Id;
        controller.streetValue2 = con.Id;
        controller.cityValue = con.Id;
        controller.primaryContact = con;
        controller.feeAmount = membershipDetails.Id;
        
        controller.secondContactFirstName = con.Id;
        controller.secondContactLastName = con.Id;
        controller.secondContactEmail = con.Id;
        controller.secondContactPhone = con.Id;
        controller.salutationSecondary = con.Id;
        controller.secondContactGenders = con.Id;
        controller.secondaryContact = con;
        controller.accountNumber = '12345';
        controller.accountName ='Test';
        controller.sortCode = '';
        controller.acquistion ='';
        controller.membershipSource ='';
        controller.sessionProfile = 'guest';
        controller.receiveInput();
        controller.nctBranchs();
        controller.contactInfo();
        controller.onCompleteContactInfo();
        controller.giftAidCreation();     
        Test.stopTest();
        system.assertEquals(1,1);
    }
     @isTest static void negativeTesting(){
         Profile p = [SELECT Id FROM Profile WHERE Name='Read Only']; 
      	User u = new User(Alias = 'newUsers', Email='newusers@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newusers@testorg.com');

        System.runAs(u) {
             Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                    No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                    Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                    GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt 
                                                    WHERE Payment_Method__c = 'Direct Debit' limit 1];
            
            Account acc = new Account();
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();       
            acc.Name ='Test Branch';
            insert acc;
            Contact primaryContact = new Contact();
            Contact con = new Contact();
            con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
    
            con.Branch__c = acc.id; 
            con.MailingStreet = 'Test address';
            con.MailingState = 'Test State';
            con.MailingCity = 'Test City';
            con.Prefered_First_Name__c = 'Test FirstName';
            con.LastName = 'Test LastName';
            con.Email = 'testemail@test.com';
            con.Phone = '123456789';
            con.MailingPostalCode = 'SW123';
            con.salutation = 'Mr';
            con.Gender__c = 'Male';
            insert con;
            
     
    
           
            PageReference pageRef = Page.nctETMembershipPaymentPage; 
            Id contId = pageRef.getParameters().put('Id', String.valueOf(primaryContact.Id));
            Test.setCurrentPage(pageRef); 
                  
            PaymentHubApiSettings__c paymentHubApiSettings = new PaymentHubApiSettings__c();
            paymentHubApiSettings.Payment_Status_Root_Url__c = 'https://test.salesforce.com/nctMembershipPaymentPage';
            paymentHubApiSettings.Credit_Card_Payment_API_Token__c = '1234567890123';
            insert paymentHubApiSettings; 
            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            nctETMembershipPaymentPageController controller = new nctETMembershipPaymentPageController();
            ApexPages.currentPage().getParameters().put('emailsVal','testemail@test.com');
            ApexPages.currentPage().getParameters().put('postVal','SE1 3XF');
            ApexPages.currentPage().getParameters().put('emailDupeVal','testemail@test.com');
            ApexPages.currentPage().getParameters().put('seltAmountdName',membershipDetails.Id);
            controller.contId = contId;
            controller.FirstName = 'Test FirstName';
            controller.LastName = 'Test Last Nane';
            controller.Email = 'testemail@test.com';
            controller.phone = '12345678901';
            controller.postCode = 'SW123';
            controller.selectBranch = con.Id; 
            controller.salutation = 'Mr.';
            controller.genderValue = 'female';
            controller.streetValue = '';
            controller.stateValue = '';
            controller.streetValue1 = '';
            controller.streetValue2 = '';
            controller.cityValue = '';
            controller.feeAmount = membershipDetails.Id;
            controller.etSpecific = false;
            controller.eDate = '2050-03-31';
            controller.secondContactFirstName = 'Test Second Name';
            controller.secondContactLastName = 'Test Second Last Name';
            controller.secondContactEmail = 'test.secondlast@test.com';
            controller.secondContactPhone = '12345678901';
            controller.salutationSecondary = 'Mr.';
            controller.secondContactGenders = 'Male';
            controller.accountNumber = '12345';
            controller.accountName ='Test';
            controller.sortCode = '';
            controller.acquistion ='';
            controller.membershipSource ='';
            controller.sessionProfile = 'guest';
            controller.isGiftAid = 'true';
            controller.primaryContact = primaryContact;
            controller.receiveInput();
            controller.nctBranchs();
            controller.contactInfo();
            controller.onCompleteContactInfo();
            controller.giftAidCreation();     
            Test.stopTest();
            system.assertEquals(1,1);
        }
    }
    @isTest static void permissionCheck(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Payment Profile'];
      	User u = new User(Alias = 'newUsers', Email='newusers@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newusers@testorg.com');

        System.runAs(u) {
             Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                    No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                    Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                    GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt 
                                                    WHERE Payment_Method__c = 'Credit/Debit Card' limit 1];
            
            Account acc = new Account();
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();       
            acc.Name ='Test Branch';
            insert acc;
            Contact primaryContact = new Contact();
            Contact con = new Contact();
            con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
    
            con.Branch__c = acc.id; 
            con.MailingStreet = 'Test address';
            con.MailingState = 'Test State';
            con.MailingCity = 'Test City';
            con.Prefered_First_Name__c = 'Test FirstName';
            con.LastName = 'Test LastName';
            con.Email = 'testemail@test.com';
            con.Phone = '123456789';
            con.MailingPostalCode = 'SW123';
            con.salutation = 'Mr';
            con.Gender__c = 'Male';
            insert con;
            
            npe03__Recurring_Donation__c recDonate = new npe03__Recurring_Donation__c();
           
           
            PageReference pageRef = Page.nctETMembershipPaymentPage; 
            Id contId = pageRef.getParameters().put('Id', String.valueOf(primaryContact.Id));
            Test.setCurrentPage(pageRef); 
                  
            PaymentHubApiSettings__c paymentHubApiSettings = new PaymentHubApiSettings__c();
            paymentHubApiSettings.Payment_Status_Root_Url__c = 'https://test.salesforce.com/nctMembershipPaymentPage';
            paymentHubApiSettings.Credit_Card_Payment_API_Token__c = '1234567890123';
            insert paymentHubApiSettings; 
            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            nctETMembershipPaymentPageController controller = new nctETMembershipPaymentPageController();
            ApexPages.currentPage().getParameters().put('emailsVal','testemail@test.com');
            ApexPages.currentPage().getParameters().put('postVal','SE1 3XF');
            ApexPages.currentPage().getParameters().put('emailDupeVal','testemail@test.com');
            ApexPages.currentPage().getParameters().put('seltAmountdName',membershipDetails.Id);
            controller.contId = contId;
            controller.FirstName = 'Test FirstName';
            controller.LastName = 'Test Last Nane';
            controller.Email = 'testemail@test.com';
            controller.phone = '12345678901';
            controller.postCode = 'SW123';
            controller.selectBranch = con.Id; 
            controller.salutation = 'Mr.';
            controller.genderValue = 'female';
            controller.streetValue = '';
            controller.stateValue = '';
            controller.streetValue1 = '';
            controller.streetValue2 = '';
            controller.cityValue = '';
            controller.feeAmount = membershipDetails.Id;
            controller.etSpecific = false;
            controller.eDate = '2050-03-31';
            controller.secondContactFirstName = 'Test Second Name';
            controller.secondContactLastName = 'Test Second Last Name';
            controller.secondContactEmail = 'test.secondlast@test.com';
            controller.secondContactPhone = '12345678901';
            controller.salutationSecondary = 'Mr.';
            controller.secondContactGenders = 'Male';
            controller.accountNumber = '12345';
            controller.accountName ='Test';
            controller.sortCode = '';
            controller.acquistion ='';
            controller.membershipSource ='';
            controller.sessionProfile = 'guest';
            controller.isGiftAid = 'true';
            controller.primaryContact = primaryContact;
            controller.nctBranchs();
            controller.contactInfo();
            controller.receiveInput();
            controller.onCompleteContactInfo();
            controller.giftAidCreation();     
            Test.stopTest();
            system.assertEquals(1,1);
        }
    }
}