src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Branch_Key__c.field-meta.xml
<CustomField>
    <fullName>Branch_Key__c</fullName>
    <label>Branch Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enquiries_PSA__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiries PSA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiries_PSA_Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enquiries_PSA_Email__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Email__c</fullName>
    <label>Enquiries PSA Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enquiries_PSA_Phone__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Phone__c</fullName>
    <label>Enquiries PSA Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <label>PSA Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PSA_Areas</valueSetName>
    </valueSet>
</CustomField>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToBranch1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Enquiries_PSA_Email__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Email__c</fullName>
    <formula>Course__r.Branch__r.Enquiries_PSA_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enquiries PSA Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Enquiries_PSA_Phone__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Phone__c</fullName>
    <formula>Course__r.Branch__r.Enquiries_PSA_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enquiries PSA Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <label>PSAArea</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch_Key__c</fullName>
        <label>Branch Key</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Couples_Allowed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Couples Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Women_Only__c</fullName>
        <label>Women Only?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>CARE N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Enquiries_PSA_Email__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Email__c</fullName>
    <formula>Branch__r.Enquiries_PSA_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enquiries PSA Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Enquiries_PSA_Phone__c.field-meta.xml
<CustomField>
    <fullName>Enquiries_PSA_Phone__c</fullName>
    <formula>Branch__r.Enquiries_PSA_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enquiries PSA Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Main_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Number_of_places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_places__c</fullName>
    <label>Number of places</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Remaining_Places__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Places__c</fullName>
    <formula>Number_of_places__c - (Reserved_Places__c + Confirmed_Places__c + Enquiries__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Branch)</relationshipLabel>
        <relationshipName>Branch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Women_Only__c</fullName>
        <label>Women Only?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>CARE N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>Course__r.PSA_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Branch does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Venues</relationshipLabel>
    <relationshipName>Branch_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PSA_Areas.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1C</fullName>
    </customValue>
    <customValue>
        <fullName>5K</fullName>
    </customValue>
    <customValue>
        <fullName>5H</fullName>
    </customValue>
    <customValue>
        <fullName>6D</fullName>
    </customValue>
    <customValue>
        <fullName>6E</fullName>
    </customValue>
    <customValue>
        <fullName>6C</fullName>
    </customValue>
    <customValue>
        <fullName>3E</fullName>
    </customValue>
    <customValue>
        <fullName>3B</fullName>
    </customValue>
    <customValue>
        <fullName>3D</fullName>
    </customValue>
    <customValue>
        <fullName>2B</fullName>
    </customValue>
    <customValue>
        <fullName>7A</fullName>
    </customValue>
    <customValue>
        <fullName>7B</fullName>
    </customValue>
    <customValue>
        <fullName>4S</fullName>
    </customValue>
    <customValue>
        <fullName>4P</fullName>
    </customValue>
    <customValue>
        <fullName>4R</fullName>
    </customValue>
    <customValue>
        <fullName>4J</fullName>
    </customValue>
    <customValue>
        <fullName>4I</fullName>
    </customValue>
    <customValue>
        <fullName>5G</fullName>
    </customValue>
    <customValue>
        <fullName>5F</fullName>
    </customValue>
    <customValue>
        <fullName>1W</fullName>
    </customValue>
    <customValue>
        <fullName>2C</fullName>
    </customValue>
    <customValue>
        <fullName>5I</fullName>
    </customValue>
    <customValue>
        <fullName>5J</fullName>
    </customValue>
    <customValue>
        <fullName>4A</fullName>
    </customValue>
    <customValue>
        <fullName>4N</fullName>
    </customValue>
    <customValue>
        <fullName>4C</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
    </customValue>
    <customValue>
        <fullName>7C</fullName>
    </customValue>
    <customValue>
        <fullName>7D</fullName>
    </customValue>
    <customValue>
        <fullName>6B</fullName>
    </customValue>
    <masterLabel>PSA Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseSearchUtility.cls
public without sharing class CourseSearchUtility {

    private static List<String> howHeard = getHowHeardValues();

    public static Course__c getCourseById(String courseName, Boolean isFromWebSite){
        Course__c result = null;

        List<Course__c> inCourses = [
            SELECT Name, Sub_Type__c, PSA_Area__c, Type__c, Couples_Allowed__c, Women_Only__c, Number_of_places__c,
                    Branch__r.Name, Branch__r.Branch_Key__c, Branch__r.Enquiries_PSA__r.Name, Branch__r.Enquiries_PSA_Email__c,
                    Fee__c, Remaining_Places__c, Main_Practitioner__r.Name, Branch__r.Enquiries_PSA_Phone__c,
                    Main_Practitioner__r.Email, Main_Practitioner__r.Phone, Main_Venue__r.Name, Main_Venue__r.Town__c,
                    Main_Venue__r.County__c, Main_Venue__r.Location__c, Branch__c, Hide_From_Course_Finder__c, Main_Venue__r.Postcode__c,
                    Start_Date__c, End_Date__c,
                    (
                        SELECT Name, Contact_Hours__c, Day_of_Week__c, Date__c, Start__c, End__c, Type__c, Specific_Attendee_Type__c
                        FROM Sessions__r
                    )
            FROM Course__c
            WHERE Name =: courseName
            AND Status__c != 'Cancelling'
            AND Status__c != 'Cancelled'
            AND Start_Date__c > TODAY
            AND (Remaining_Places__c > 0 OR (Remaining_Places__c <= 0 AND Overbooking_allowed__c = true))
            WITH SECURITY_ENFORCED
        ];
        
        if(!inCourses.isEmpty()) {
            if(isFromWebSite == true) {
                if (inCourses[0].Hide_From_Course_Finder__c != true ) {
                    result = inCourses[0];
                }
            } else {
                result = inCourses[0];
            }
        } 

        return result;
    }
    
    public static RestResponse getCourseById(String courseName){
        RestResponse response = new RestResponse();
        Course__c course = getCourseById(courseName, true);
        if (course != null) {
            CourseFinderModel model = new CourseFinderModel(course);
            model.HowHeardTexts = howHeard;
            response.statusCode = 200;
            response.responseBody = Blob.valueOf(JSON.serializePretty(model));
        } else {
            response.statusCode = 404;
            response.responseBody = Blob.valueOf(System.Label.CourseAPIcourseNotExists);
        }       
        return response;
    }
    
    public static List<Course__c> getCoursesByBranch(String branchId, Boolean isFromWebSite){

        List<Course__c> inCourses = [
            SELECT Name, Sub_Type__c, PSA_Area__c, Type__c, Couples_Allowed__c, Women_Only__c, Number_of_places__c,
                    Branch__r.Name, Branch__r.Branch_Key__c, Branch__r.Enquiries_PSA__r.Name, Branch__r.Enquiries_PSA_Email__c,
                    Fee__c, Remaining_Places__c, Main_Practitioner__r.Name, Branch__r.Enquiries_PSA_Phone__c,
                    Main_Practitioner__r.Email, Main_Practitioner__r.Phone, Main_Venue__r.Name, Main_Venue__r.Town__c,
                    Main_Venue__r.County__c, Main_Venue__r.Location__c, Branch__c, Hide_From_Course_Finder__c, Main_Venue__r.Postcode__c,
                    Start_Date__c, End_Date__c,
            (
                    SELECT Name, Contact_Hours__c, Day_of_Week__c, Date__c, Start__c, End__c, Type__c, Specific_Attendee_Type__c
                    FROM Sessions__r
            )
            FROM Course__c
            WHERE Branch__c =: branchId
            AND Status__c != 'Cancelling'
            AND Status__c != 'Cancelled'
            AND Start_Date__c > TODAY
            AND (Remaining_Places__c > 0 OR (Remaining_Places__c <= 0 AND Overbooking_allowed__c = true))
            WITH SECURITY_ENFORCED
        ];
        
        List<Course__c> courses = new List<Course__c>();

        if(!inCourses.isEmpty()) {
            for (Course__c course : inCourses) {
                if(isFromWebSite == true) {
                    if (course.Hide_From_Course_Finder__c != true) {
                        courses.add(course);
                    }
                } else {
                    courses.add(course);
                }
            } 
        }
        return courses;
    }
    
    public static RestResponse getCoursesByBranch(String branchId) {
        RestResponse response = new RestResponse();
        List<Course__c> courses = getCoursesByBranch(branchId, true);
        
        if (!courses.isEmpty()) {
            List<CourseFinderModel> models = new List<CourseFinderModel>();
            for (Course__c course : courses) {
                CourseFinderModel model = new CourseFinderModel(course);
                model.HowHeardTexts = howHeard;
                models.add(model);
            }
            response.statusCode = 200;
            response.responseBody = Blob.valueOf(JSON.serializePretty(models));
        } else {
            response.statusCode = 404;
            response.responseBody = Blob.valueOf(System.Label.CourseAPIcourseNotExists);
        }        
        return response;
    }

    private static List<String> getHowHeardValues() {
        List<String> howHeardValues= new List<String>();
        Schema.DescribeFieldResult fieldResult = Booking__c.How_Heard__c.getDescribe();
        for (Schema.PicklistEntry value : fieldResult.getPicklistValues()) {
            howHeardValues.add(value.getLabel());
        }     
        return howHeardValues;
    }

    public static List<Course__c> getCoursesByDateDistance(Location location, Integer radius, Date birthDueDate, Boolean isFromWebSite){
        final Integer DEFAULT_RADIUS = 100; // from Intrabiz API
        if (location == null){
            return null;
        }
        
        if (radius == null || radius <= 0) {
            radius = DEFAULT_RADIUS; 
        }

        List<Course__c> inCourses;

        if (isFromWebSite) {
            inCourses = [
                SELECT Name, Sub_Type__c, PSA_Area__c, Type__c, Couples_Allowed__c, Women_Only__c, Number_of_places__c,
                    Branch__r.Name, Branch__r.Branch_Key__c, Branch__r.Enquiries_PSA__r.Name, Branch__r.Enquiries_PSA_Email__c,
                    Fee__c, Remaining_Places__c, Main_Practitioner__r.Name, Branch__r.Enquiries_PSA_Phone__c,
                    Main_Practitioner__r.Email, Main_Practitioner__r.Phone, Main_Venue__r.Name, Main_Venue__r.Town__c,
                    Main_Venue__r.County__c, Main_Venue__r.Location__c, Branch__c, Hide_From_Course_Finder__c, Main_Venue__r.Postcode__c, 
                    Start_Date__c, End_Date__c,
                (
                    SELECT Name, Contact_Hours__c, Day_of_Week__c, Date__c, Start__c, End__c, Type__c, Specific_Attendee_Type__c
                    FROM Sessions__r
                )
                FROM Course__c
                WHERE Distance(Course__c.Main_Venue__r.Location__c, :location, 'mi') < :radius
                AND Status__c != 'Cancelling'
                AND Status__c != 'Cancelled'
                AND Start_Date__c > TODAY
                AND (Remaining_Places__c > 0 OR (Remaining_Places__c <= 0 AND Overbooking_allowed__c = true))
                AND ((Type__c = 'Antenatal' AND End_Date__c < :birthDueDate) OR (Type__c = 'Postnatal' AND Start_Date__c > :birthDueDate))
                WITH SECURITY_ENFORCED
            ];
        } else {
            inCourses = [
                SELECT Name, Sub_Type__c, PSA_Area__c, Type__c, Couples_Allowed__c, Women_Only__c, Number_of_places__c,
                    Branch__r.Name, Branch__r.Branch_Key__c, Branch__r.Enquiries_PSA__r.Name, Branch__r.Enquiries_PSA_Email__c,
                    Fee__c, Remaining_Places__c, Main_Practitioner__r.Name, Branch__r.Enquiries_PSA_Phone__c,
                    Main_Practitioner__r.Email, Main_Practitioner__r.Phone, Main_Venue__r.Name, Main_Venue__r.Town__c,
                    Main_Venue__r.County__c, Main_Venue__r.Location__c, Branch__c, Hide_From_Course_Finder__c, Main_Venue__r.Postcode__c,
                    Start_Date__c, End_Date__c,
                (
                    SELECT Name, Contact_Hours__c, Day_of_Week__c, Date__c, Start__c, End__c, Type__c, Specific_Attendee_Type__c
                    FROM Sessions__r
                )
                FROM Course__c
                WHERE Distance(Main_Venue__r.Location__c, :location, 'mi') < :radius
                AND Status__c != 'Cancelled'
                WITH SECURITY_ENFORCED
            ];
        }

        List<Course__c> courses = new List<Course__c>();

        if(!inCourses.isEmpty()) {
            for (Course__c course : inCourses) {
                if(isFromWebSite == true){
                    if (course.Hide_From_Course_Finder__c != true) {
                        courses.add(course);
                    }
                } else {
                    courses.add(course);
                }
            }
        }
        return courses;
    }
    

    public static RestResponse getCoursesByDateDistance(Map <String, String> params){
        RestResponse response = new RestResponse();
        if (params == null){
            return getWrongResponse();
        }

        Location location;
        try {
            location = validateLocation(params.get('location'));
        } catch (TypeException te){
            return getWrongResponse();
        }
        
        Date birthDueDate;
        try {
            birthDueDate = validateBirthDueDate(params.get('birth'));
        } catch (TypeException te){
            return getWrongResponse();
        } 

        Integer radius;
        try {
            radius = validateRadius(params.get('radius'));
        } catch (TypeException te){
            return getWrongRadiusResponse();
        }
        
        List<Course__c> courses = getCoursesByDateDistance(location, radius, birthDueDate, true);        
        
        if (courses != null && !courses.isEmpty()) {
            List<CourseFinderModelOrdered> models = new List<CourseFinderModelOrdered>();
            Integer i = 0;
            Integer LowestRankIncluded = 1;
            for (Course__c course : courses) {
                CourseFinderModelOrdered model = new CourseFinderModelOrdered(course, birthDueDate);
                i++;

                model.HowHeardTexts = howHeard;

                if (model.Rank <= 5) { // filtering by rank
                models.add(model);
                    if (LowestRankIncluded > model.Rank){
                        LowestRankIncluded = model.Rank;
                    }
                }

            }
            
            // Sort models according rank, group rank and date;
            models.sort();
            // update Orders accorting to the sorting order;
            i = 0;
            for (CourseFinderModelOrdered model : models){
                i++;
                model.Order = i;
            }
            
            CoursesDateDistanceModel sortedModel = new CoursesDateDistanceModel();
            sortedModel.Courses = models;
            sortedModel.LowestRankIncluded = LowestRankIncluded;
            sortedModel.SuggestedLowestRank = getSuggestedLowestRank(LowestRankIncluded, radius);
            sortedModel.viewPort = new ViewPort(params.get('viewports')).getViewport();
            
            response.statusCode = 200;
            response.responseBody = Blob.valueOf(JSON.serializePretty(sortedModel));
        } else {
            response.statusCode = 404;
            response.responseBody = Blob.valueOf(System.Label.CourseAPIcourseNotExists);
        }        
        return response;
    }
    
    private static Integer getSuggestedLowestRank(Integer radius, Integer LowestRankIncluded){
        Integer result;
        
        if (radius <= 10) {
            result = 3;
        } else if (radius <= 20) {
            result = 4;
        } else {
            result = 5;
        }
        
        if (result > LowestRankIncluded) {
            result = LowestRankIncluded;
        }
        
        return result;
    }

    private static Location validateLocation(String strLocation){
        Location result;
        if (String.isEmpty(strLocation)){
            return null;
        }
            
        List<String> latLong = strLocation.split(',');
        
        if (latLong.size() == 2){
            try {
                Double latitude = Double.valueOf(latLong[0]);
                Double longitude = Double.valueOf(latLong[1]);
                result = Location.newInstance(latitude, longitude);
            } catch (Exception e){
                throw new TypeException(e);
            }
        }
        
        return result;
    }
    
    private static Integer validateRadius(String strRadius){
        Integer result;
        if (String.isEmpty(strRadius)){
            return null;
        }
        
        try {
            result = Integer.valueOf(strRadius);
            if (result <= 0) {
                throw new TypeException();
            }
        } catch (Exception e){
            throw new TypeException(e);
        }
        
        return result;
    }

    private static Date validateBirthDueDate(String strBirthDueDate) {
        Date result;
        if (String.isEmpty(strBirthDueDate)){
            return getDefaultBirthDueDate();
        }

        try {
            result = Date.valueOf(strBirthDueDate);
        } catch (Exception e){
            throw new TypeException(e);
        }

        return result;
    }


    private static Date getDefaultBirthDueDate(){
        final Integer DIFFERENCE_FROM_TODAY = 30;
        return Date.today() + DIFFERENCE_FROM_TODAY;
    }


    
    private static RestResponse getWrongResponse(){
        RestResponse response = new RestResponse();
        response.statusCode = 404;
        response.responseBody = Blob.valueOf(Label.CourseAPIcourseNotExists);
        return response;
    }

    private static RestResponse getWrongRadiusResponse(){
        RestResponse response = new RestResponse();
        response.statusCode = HttpStatusCode.SERVER_ERROR;
        response.responseBody = Blob.valueOf(Label.CourseAPIradiusIsNotValid);
        return response;
    }
}