src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Birth_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Due_Date__c</fullName>
    <label>Birth due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToBranch1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <formula>Primary_Contact__r.NCT_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NCT number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Clients</fullName>
        <active>true</active>
        <description>A contact representing someone who will attend a course</description>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner_Licence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Number_of_places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_places__c</fullName>
    <label>Number of places</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence__c/Licence__c.object-meta.xml
<CustomObject>
    <label>Licence</label>
    <nameField>
        <label>Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Licences can only be applied to Practitioners.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licences To Practice</relationshipLabel>
    <relationshipName>Licences_To_Practice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <label>Licence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Signature Antenatal Teacher</fullName>
            </value>
            <value>
                <fullName>Essentials Antenatal Teacher</fullName>
            </value>
            <value>
                <fullName>Breastfeeding Counsellor</fullName>
            </value>
            <value>
                <fullName>Postnatal Practitioner</fullName>
            </value>
            <value>
                <fullName>Baby Massage Practitioner</fullName>
            </value>
            <value>
                <fullName>Twins and Multiples</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Returning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parentforce_Community_Settings__c/Parentforce_Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Parentforce Community Settings</label>
</CustomObject>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlowPaymentHandlerTest.cls
@IsTest
public class FlowPaymentHandlerTest 
{
    @testSetup   
    static void setup()
    {
        Parentforce_Community_Settings__c parentforceCommunitySettings = new Parentforce_Community_Settings__c();
        parentforceCommunitySettings.Base_Url__c = 'http://mynct.test.com';
        parentforceCommunitySettings.API_Token__c = '12345';
        parentforceCommunitySettings.SetupOwnerId = UserInfo.getOrganizationId();
        insert parentforceCommunitySettings;

        Account testBranch = new Account();
        testBranch.Name = 'testBranch';
        testBranch.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Branch'].Id;
        insert testBranch;
        Contact testPractitioner = new Contact();
        testPractitioner.AccountId = testBranch.Id;
        testPractitioner.LastName = 'testPractitioner';
        testPractitioner.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = 'Practitioner'].Id;
        insert testPractitioner;
        Licence_To_Practice__c testLicense = new Licence_To_Practice__c();
        testLicense.Contact__c = testPractitioner.Id;
        testLicense.Licence__c = 'Breastfeeding Counsellor';
        testLicense.Start_Date__c = Date.today() - 30;
        testLicense.Status__c = 'Full';
        insert testLicense;
        Course__c testCourse = new Course__c();
        testCourse.Branch__c = testBranch.Id;
        testCourse.Number_of_places__c = 5;
        testCourse.Sub_Type__c = 'Waterbirth';
        testCourse.Type__c = 'Antenatal';
        testCourse.Main_Practitioner_Licence__c = testLicense.Id;
        insert testCourse;
        Contact testContact = new Contact();
        testContact.FirstName = 'test';
        testContact.LastName = 'testContact';
        testContact.MailingCity = 'London';
        testContact.MailingPostalCode = '533537';
        testContact.Email = 'test@test.com';
        testContact.MailingCountry = 'GB';
        testContact.MailingStreet = 'test 1';
        testContact.MailingState = 'test';
        testContact.Phone = '11111111';
        testContact.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = 'Clients'].Id;
        insert testContact;
        cpm__Payment_Profile__c testPaymentProfile = new cpm__Payment_Profile__c();
        testPaymentProfile.cpm__Contact__c = testContact.Id;
        insert testPaymentProfile;
        Booking__c testBooking = new Booking__c();
        testBooking.Birth_Due_Date__c = Date.today() + 30;
        testBooking.Course__c = testCourse.Id;
        testBooking.Primary_Contact__c = testContact.Id;
        insert testBooking;
    }
    @IsTest
    static void testCourseCardOneoff(){
        String responseBody = '{"ResponseCode":"001","IsSuccess":true,"SourceConnector":{"Name":"PaymentHub for NPSP"},"RedirectURL":"http://mynct.test.com/apex/wpayc__worldpaycheckout","PaymentMethod":{"Processor":"PaymentHub-WorldPay","Name":"CreditCard"},"Payment":{"InstallmentId":""},"Payer":{"ContactId":"","ContactDeduplicated":false,"AccountDeduplicated":false}}';
        Test.setMock(HttpCalloutMock.class, new FlowPaymentHandlerHttpResponseMock(responseBody, null, null, null));
        Test.startTest();
        Booking__c testBooking = [SELECT Id FROM Booking__c LIMIT 1];
        List<String> result = FlowPaymentHandler.invokePaymentMethod(new List<List<String>> {new List<String>{'course', testBooking.Id, 'card', 'false'}});
        system.assertEquals(result[0], 'http://mynct.test.com/apex/wpayc__worldpaycheckout');
        Test.stopTest();
    }
    @IsTest
    static void testCourseCardRecurring(){
        String responseBody = '{"ResponseCode":"001","IsSuccess":true,"SourceConnector":{"Name":"PaymentHub for NPSP"},"RedirectURL":"http://mynct.test.com/apex/wpayc__worldpaycheckout","PaymentMethod":{"Processor":"PaymentHub-WorldPay","Name":"CreditCard"},"Payment":{"InstallmentId":""},"Payer":{"ContactId":"","ContactDeduplicated":false,"AccountDeduplicated":false}}';
        Test.setMock(HttpCalloutMock.class, new FlowPaymentHandlerHttpResponseMock(responseBody, null, null, null));
        Test.startTest();
        Booking__c testBooking = [SELECT Id FROM Booking__c LIMIT 1];
        List<String> result = FlowPaymentHandler.invokePaymentMethod(new List<List<String>> {new List<String>{'course', testBooking.Id, 'card', 'true'}});
        system.assertEquals(result[0], 'http://mynct.test.com/apex/wpayc__worldpaycheckout');
        Test.stopTest();
    }
    @IsTest
    static void testCourseDdRecurring(){
        String responseContact = '{"Contact": {"Action":"Update","AddressNumber": "26663333","ContactKey": "3325458","ContactNumber": "3325458","EmailAddress": "ncttst+alexandr.popok_greencouchconsulting.com@gmail.com","EmailInvalid": "N","PrimaryPhoneNumber": "","SecondaryPhoneNumber": "","AmendedBy": "xNCT_ORG_UK","AmendedOn": "2019-08-15 00:00:00.000"}}';
        String responseBank = '{"ContactBankAccount": {"ContactKey": "3325458","BankDetailNumber": "346278","Information": "Matched existing account!"}}';
        Test.setMock(HttpCalloutMock.class, new FlowPaymentHandlerHttpResponseMock(null, responseContact, responseBank, null));
        Test.startTest();
        Booking__c testBooking = [SELECT Id FROM Booking__c LIMIT 1];
        List<String> result = FlowPaymentHandler.invokePaymentMethod(new List<List<String>> {new List<String>{'course', testBooking.Id, 'dd', 'true'}});
        system.assertEquals(result[0], '');
        system.assertEquals([SELECT NCT_Number__c FROM Contact WHERE LastName = 'testContact' LIMIT 1].NCT_Number__c, '3325458');
        Test.stopTest();
    }
    @IsTest
    static void testMembershipCardOneoff(){
        String responseBody = '{"ResponseCode":"001","IsSuccess":true,"SourceConnector":{"Name":"PaymentHub for NPSP"},"RedirectURL":"http://mynct.test.com/apex/wpayc__worldpaycheckout","PaymentMethod":{"Processor":"PaymentHub-WorldPay","Name":"CreditCard"},"Payment":{"InstallmentId":""},"Payer":{"ContactId":"","ContactDeduplicated":false,"AccountDeduplicated":false}}';
        String responseContact = '{"Contact": {"Action":"Update","AddressNumber": "26663333","ContactKey": "3325458","ContactNumber": "3325458","EmailAddress": "ncttst+alexandr.popok_greencouchconsulting.com@gmail.com","EmailInvalid": "N","PrimaryPhoneNumber": "","SecondaryPhoneNumber": "","AmendedBy": "xNCT_ORG_UK","AmendedOn": "2019-08-15 00:00:00.000"}}';
        String responseBank = '{"ContactBankAccount": {"ContactKey": "3325458","BankDetailNumber": "346278","Information": "Matched existing account!"}}';
        String responseMembership = '{"Membership": {"Status": "Success","ContactNumber_1": "3325458","MembershipType": "EJ","Amount": "57","RenewalDate": "2020-07-10","AmountTendered": "57"}}';
        Test.setMock(HttpCalloutMock.class, new FlowPaymentHandlerHttpResponseMock(responseBody, responseContact, responseBank, responseMembership));
        Test.startTest();
        Booking__c testBooking = [SELECT Id FROM Booking__c LIMIT 1];
        List<String> result = FlowPaymentHandler.invokePaymentMethod(new List<List<String>> {new List<String>{'membership', testBooking.Id, 'card', 'false', 'E', '57', '00000'}});
        system.assertEquals(result[0], 'http://mynct.test.com/apex/wpayc__worldpaycheckout');
        system.assertEquals([SELECT NCT_Number__c FROM Contact WHERE LastName = 'testContact' LIMIT 1].NCT_Number__c, '3325458');
        Test.stopTest();
    }
    @IsTest
    static void testMembershipDdRecurring(){
        String responseBody = '{"ResponseCode":"001","IsSuccess":true,"SourceConnector":{"Name":"PaymentHub for NPSP"},"RedirectURL":"http://mynct.test.com/apex/wpayc__worldpaycheckout","PaymentMethod":{"Processor":"PaymentHub-WorldPay","Name":"CreditCard"},"Payment":{"InstallmentId":""},"Payer":{"ContactId":"","ContactDeduplicated":false,"AccountDeduplicated":false}}';
        String responseContact = '{"Contact": {"Action":"Update","AddressNumber": "26663333","ContactKey": "3325458","ContactNumber": "3325458","EmailAddress": "ncttst+alexandr.popok_greencouchconsulting.com@gmail.com","EmailInvalid": "N","PrimaryPhoneNumber": "","SecondaryPhoneNumber": "","AmendedBy": "xNCT_ORG_UK","AmendedOn": "2019-08-15 00:00:00.000"}}';
        String responseBank = '{"ContactBankAccount": {"ContactKey": "3325458","BankDetailNumber": "346278","Information": "Matched existing account!"}}';
        String responseMembership = '{"Membership": {"Status": "Success","ContactNumber_1": "3325458","MembershipType": "EJ","Amount": "57","RenewalDate": "2020-07-10","AmountTendered": "57"}}';
        Test.setMock(HttpCalloutMock.class, new FlowPaymentHandlerHttpResponseMock(responseBody, responseContact, responseBank, responseMembership));
        Test.startTest();
        Booking__c testBooking = [SELECT Id FROM Booking__c LIMIT 1];
        List<String> result = FlowPaymentHandler.invokePaymentMethod(new List<List<String>> {new List<String>{'membership', testBooking.Id, 'dd', 'true', 'E', '57', '00000'}});
        system.assertEquals(result[0], '');
        system.assertEquals([SELECT NCT_Number__c FROM Contact WHERE LastName = 'testContact' LIMIT 1].NCT_Number__c, '3325458');
        Test.stopTest();
    }
}