src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/PostCode_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PostCode Allocation</relationshipLabel>
        <relationshipName>PostCode_Allocation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Roles__c</fullName>
        <label>PSA Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity PSA</fullName>
                </value>
                <value>
                    <fullName>Enquiry PSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PostCode Allocation</label>
    <nameField>
        <label>PostalCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PostCode Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/dupOutcodeHandlerTest.cls
@isTest
public class dupOutcodeHandlerTest {

    static testMethod Void outcodeDuplicateCap(){
        Boolean result = false;
        //Id branch =[SELECT Id FROM Account where Name= 'Bournemouth 2'];
        PostCode_Allocation__c firstPA = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Capacity PSA',Branch__c ='0010E00000MmsfLQAR');
        insert firstPA;
        
        
        
        try{
            PostCode_Allocation__c secPA = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Capacity PSA',Branch__c ='0010E00000MmsfLQAR');
            insert secPA;
            
        }
        catch(DmlException ex){ 
            
            result = true;
        }

      	System.assert(result);

    }
    static testMethod Void outcodeDuplicateEnq(){
    	Boolean result = false;
        
        PostCode_Allocation__c firstPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsfLQAR');
        insert firstPA1;
        
        try{
            PostCode_Allocation__c secPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsfLQAR');
            insert secPA1;
        }
        catch(DmlException ex){
            result = true;
        }
        System.assert(result);
    }
    static testMethod Void outcodeDuplicateBranch(){
    	Boolean result = false;
        
        PostCode_Allocation__c firstPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsfLQAR');
        insert firstPA1;
        
        try{
            PostCode_Allocation__c secPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsWOQAZ');
            insert secPA1;
        }
        catch(DmlException ex){
            result = true;
        }
        System.assert(result);
    }
    static testMethod Void outcodeDuplicatePostcode(){
    	Boolean result = false;
        
        PostCode_Allocation__c firstPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsfLQAR');
        insert firstPA1;
        
        try{
            PostCode_Allocation__c secPA1 = new PostCode_Allocation__c(Name = 'TestPost',PSA_Roles__c = 'Enquiry PSA',Branch__c ='0010E00000MmsfLQAR');
            insert secPA1;
        }
        catch(DmlException ex){
            result = true;
        }
        System.assert(result);
    }
}