src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Branch)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Branch_Weighting__c/Branch_Weighting__c.object-meta.xml
<CustomObject>
    <label>Branch Weighting</label>
    <nameField>
        <displayFormat>BW{00000}</displayFormat>
        <label>Branch Weighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branch Weightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Weighting__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Weightings</relationshipLabel>
    <relationshipName>Branch_Weightings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Branch_Weighting__c/fields/Geographical_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Geographical_Weighting__c</fullName>
    <label>Geographical Weighting</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geographical_Weightings</valueSetName>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/Practitioner_Fee_Rate__c.object-meta.xml
<CustomObject>
    <label>Practitioner Fee Rate</label>
    <nameField>
        <displayFormat>PF{000000}</displayFormat>
        <label>Practitioner Fee Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Fee Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Geographical_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Geographical_Weighting__c</fullName>
    <label>Geographical Weighting</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geographical_Weightings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Practitioner_Band__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Band__c</fullName>
    <label>Practitioner Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Fee_Rate__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Fee_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Fee Rate</label>
    <referenceTo>Practitioner_Fee_Rate__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Geographical_Weightings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>London,</fullName>
    </customValue>
    <customValue>
        <fullName>Fringe,</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Geographical Weightings</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practitioner_Bands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A,</fullName>
    </customValue>
    <customValue>
        <fullName>B,</fullName>
    </customValue>
    <customValue>
        <fullName>C,</fullName>
    </customValue>
    <customValue>
        <fullName>D,</fullName>
    </customValue>
    <customValue>
        <fullName>ZERO</fullName>
    </customValue>
    <masterLabel>Practitioner Bands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BranchWeightingHelperTest.cls
@isTest
public with sharing class BranchWeightingHelperTest {

    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String PRACTITIONER_RECORDTYPE_NAME  = 'Practitioner';
    private static final String BRANCH_RECORDTYPE_NAME  = 'Branch';
    private static final String PRACTITIONER_BAND = 'B';
    private static final String BRANCH_WEIGHTING = 'London';

    private static Integer daysBeforeToday = 3;
    private static Integer daysAfterToday = 15;
    
    @TestSetup
    private static void SetupTestData(){
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .buildBranchAccount()
                    .buildPractitioner(PRACTITIONER_LASTNAME)
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession();
    }

    @isTest
    private static void PractitionerHasExistingSession_BranchWeightingRecordCreated_SessionGetsAssignedToAppropriateFeeRate(){
    
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildPractitionerFeeRate();
        
        List<Branch_Weighting__c> branchWeightings = [SELECT Id, Branch__c, Start_Date__c FROM Branch_Weighting__c];
        List<Practitioner_Fee_Rate__c> practitionerFeeRates = [SELECT Id FROM Practitioner_Fee_Rate__c];

        Test.startTest();
        BranchWeightingHelper.updateFeesOnAffectedSessions(branchWeightings);
        Test.stopTest();

        List<Session__c> sessionsTestResult = [SELECT Id, Practitioner_Fee_Rate__c FROM Session__c];
        System.assertEquals(practitionerFeeRates[0].Id, sessionsTestResult[0].Practitioner_Fee_Rate__c);

    }

    @isTest
    private static void PractitionerHasExistingSession_BranchWeightingFutureDatedAtNewGeographicalWeighting_SessionGetsReassignedToAppropriateFeeRate(){
    
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildPractitionerFeeRateSet();

        List<Session__c> sessionsToTest = [SELECT Id FROM Session__c];
        List<Contact> practitioners = [SELECT Id FROM Contact WHERE RecordType.Name =:PRACTITIONER_RECORDTYPE_NAME];
        List<Account> branches = [SELECT Id FROM Account WHERE RecordType.Name =:BRANCH_RECORDTYPE_NAME];
        List<Practitioner_Fee_Rate__c> practitionerFeeRates = [SELECT Id, Practitioner_Band__c, Geographical_Weighting__c FROM Practitioner_Fee_Rate__c];
        Practitioner_Fee_Rate__c standardARate = practitionerFeeRates[0];
        Practitioner_Fee_Rate__c londonBRate = practitionerFeeRates[9];

        for (Session__c session : sessionsToTest) {
            session.Practitioner_Fee_Rate__c = standardARate.Id;
        }

        update sessionsToTest;

        List<Practitioner_Band__c> practitionerBands = new List<Practitioner_Band__c>();
        TestPractitionerBandBuilder practitionerBandBuilder = new TestPractitionerBandBuilder();
        for(Contact practitioner : practitioners){
            practitionerBands.add(practitionerBandBuilder
                                    .withPractitionerContact(practitioner)
                                    .withBand(PRACTITIONER_BAND)
                                    .withStartDate(Date.today() - daysBeforeToday)
                                    .insertRecord(false)
                                    .build());
        }

        insert practitionerBands;

        List<Branch_Weighting__c> branchWeightings = new List<Branch_Weighting__c>();
        TestBranchWeightingBuilder branchWeightingBuilder = new TestBranchWeightingBuilder();
        for(Account branch : branches) {
            branchWeightings.add(branchWeightingBuilder
                                    .withBranch(branch)
                                    .withWeighting(BRANCH_WEIGHTING)
                                    .withStartDate(Date.today() - daysBeforeToday)
                                    .insertRecord(false)
                                    .build());
        }

        insert branchWeightings;
        
        Test.startTest();
        BranchWeightingHelper.updateFeesOnAffectedSessions(branchWeightings);
        Test.stopTest();

        List<Session__c> sessionsTestResult = [SELECT Id, Practitioner_Fee_Rate__c FROM Session__c];
        System.assertNotEquals(standardARate.Id, sessionsTestResult[0].Practitioner_Fee_Rate__c);
        System.assertEquals(londonBRate.Id, sessionsTestResult[0].Practitioner_Fee_Rate__c);

    }

    @isTest
    private static void PractitionerHasExistingSession_BranchWeightingRecordBackedDatedCreated_SessionFeeRateRemainsNull(){
    
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildPractitionerFeeRate();
        
        List<Branch_Weighting__c> branchWeightings = [SELECT Id, Branch__c, Start_Date__c FROM Branch_Weighting__c];
        branchWeightings[0].Start_Date__c = Date.today() + daysAfterToday;
        update branchWeightings;

        Test.startTest();
        BranchWeightingHelper.updateFeesOnAffectedSessions(branchWeightings);
        Test.stopTest();

        List<Session__c> sessionsTestResult = [SELECT Id, Practitioner_Fee_Rate__c FROM Session__c];
        System.assertEquals(null, sessionsTestResult[0].Practitioner_Fee_Rate__c);
    }
}