src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <label>PSA Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PSA_Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zumzum__Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Tax_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rate</label>
    <referenceTo>Zumzum__Tax_Rate__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Fees__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Fees__c</fullName>
    <formula>IF(ISBLANK(Session_Fee_Override__c), Calculated_Practitioner_Fees__c, Session_Fee_Override__c)</formula>
    <label>Practitioner Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>Course__r.PSA_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Tax_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rate</label>
    <referenceTo>Zumzum__Tax_Rate__c</referenceTo>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Tax_Rate__c/Zumzum__Tax_Rate__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/PSA_Areas.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1C</fullName>
    </customValue>
    <customValue>
        <fullName>5K</fullName>
    </customValue>
    <customValue>
        <fullName>5H</fullName>
    </customValue>
    <customValue>
        <fullName>6D</fullName>
    </customValue>
    <customValue>
        <fullName>6E</fullName>
    </customValue>
    <customValue>
        <fullName>6C</fullName>
    </customValue>
    <customValue>
        <fullName>3E</fullName>
    </customValue>
    <customValue>
        <fullName>3B</fullName>
    </customValue>
    <customValue>
        <fullName>3D</fullName>
    </customValue>
    <customValue>
        <fullName>2B</fullName>
    </customValue>
    <customValue>
        <fullName>7A</fullName>
    </customValue>
    <customValue>
        <fullName>7B</fullName>
    </customValue>
    <customValue>
        <fullName>4S</fullName>
    </customValue>
    <customValue>
        <fullName>4P</fullName>
    </customValue>
    <customValue>
        <fullName>4R</fullName>
    </customValue>
    <customValue>
        <fullName>4J</fullName>
    </customValue>
    <customValue>
        <fullName>4I</fullName>
    </customValue>
    <customValue>
        <fullName>5G</fullName>
    </customValue>
    <customValue>
        <fullName>5F</fullName>
    </customValue>
    <customValue>
        <fullName>1W</fullName>
    </customValue>
    <customValue>
        <fullName>2C</fullName>
    </customValue>
    <customValue>
        <fullName>5I</fullName>
    </customValue>
    <customValue>
        <fullName>5J</fullName>
    </customValue>
    <customValue>
        <fullName>4A</fullName>
    </customValue>
    <customValue>
        <fullName>4N</fullName>
    </customValue>
    <customValue>
        <fullName>4C</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
    </customValue>
    <customValue>
        <fullName>7C</fullName>
    </customValue>
    <customValue>
        <fullName>7D</fullName>
    </customValue>
    <customValue>
        <fullName>6B</fullName>
    </customValue>
    <masterLabel>PSA Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClaimFeeHelperTest.cls
@isTest
private class ClaimFeeHelperTest {
    private static final String PRACTITIONER_TAX_RATE = 'Exempt Transactions (0%)';

    @testSetup
    static void createTestData(){
         TestDataFactory.getInstance()
            .buildBranchAccount()
            .buildOrganizationAccount('acc5')
            .buildPractitioner('Smith')
            .buildPractitionerFeeRate()
            .buildVenue()
            .buildRoom()
            .buildLicenceToPractice()
            .buildCoursesWithSessions(2, 2);
    }

    static void createCommunityPractitionerUser() {
        User portalAccountOwner = createPortalAccountOwner();
        System.runAs(portalAccountOwner) {

            Account organiztaion = [
                SELECT Id, AccountNumber, OwnerId
                FROM Account
                WHERE Name = 'John Smith'
                    AND Type = 'Supplier'
                LIMIT 1
            ];

            Contact practitioner = [
                SELECT Id, Name, AccountId
                FROM Contact
                WHERE LastName = 'Smith'
                LIMIT 1
            ];

            organiztaion.OwnerId = portalAccountOwner.Id;
            practitioner.AccountId = organiztaion.Id;

            update organiztaion;
            update practitioner;

            Profile p = [SELECT Id FROM Profile WHERE Name = 'Practitioner'];
            String uniqueUserName = 'practitioner' + DateTime.now().getTime() + '@testorg.com';

            User u = new User(
                Alias = 'practu',
                Email='practitioner@testorg.com',
                EmailEncodingKey='UTF-8',
                LastName='practitionerTesting',
                LanguageLocaleKey='en_US',
                LocaleSidKey='en_GB',
                ProfileId = p.Id,
                TimeZoneSidKey='Europe/London',
                UserName=uniqueUserName,
                ContactId = practitioner.Id,
                CommunityNickname = 'pract123'
            );
            insert u;
        }
    }

    private static User createPortalAccountOwner() { 
        UserRole portalRole = [
            SELECT Id, Name 
            FROM UserRole 
            WHERE PortalType = 'None' 
            LIMIT 1
        ];  

        Profile sysAdminProfile = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'System Administrator'
        ];  
        User portalAccountOwner = new User(  
            UserRoleId = portalRole.Id,  
            ProfileId = sysAdminProfile.Id,
            Username = 'portalOwner' + System.currentTimeMillis() + '@test.com',  
            Alias = 'Alias',  
            Email='portal.owner@test.com',  
            EmailEncodingKey='UTF-8',  
            Firstname='Portal',  
            Lastname='Owner',  
            LanguageLocaleKey='en_US',  
            LocaleSidKey='en_GB',  
            TimeZoneSidKey = 'Europe/London'  
        );  

        insert portalAccountOwner;  

        return portalAccountOwner;  
   }

    static User getPractitionerUser() {
        return [
            SELECT Id, AccountId, ContactId
            FROM User
            WHERE Email = 'practitioner@testorg.com'
            LIMIT 1
        ];
    }

    @isTest
    static void createPurchaseInvoice() {
        createCommunityPractitionerUser();
        ClaimFeeHelper.ClaimFeeWrapper flowData = new ClaimFeeHelper.ClaimFeeWrapper();
        flowData.sessions = [
            SELECT Id, Name, Practitioner_Fees__c, PSA_Area__c, Course__c
            FROM Session__c
            LIMIT 1
        ];
        flowData.registrationFee = 5;
        System.runAs(getPractitionerUser()) {
            TestFinanceDataFactory financeDataFactory = TestFinanceDataFactory.getInstance();
            financeDataFactory.createZumzumData();
        }    
        Test.startTest();
            System.runAs(getPractitionerUser()) {
                ClaimFeeHelper.createPurchaseInvoice(new List<ClaimFeeHelper.ClaimFeeWrapper> {flowData});
            }
        Test.stopTest();

        Zumzum__Tax_Rate__c zumzumExemptTransactions = [
            SELECT Id, Name 
            FROM Zumzum__Tax_Rate__c 
            WHERE Name =: PRACTITIONER_TAX_RATE
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        System.assertEquals(2, [
            SELECT Id
            FROM Zumzum__Purchase_Invoice__c
        ].size()); 
        
        System.assertEquals(zumzumExemptTransactions.Id, [
            SELECT Zumzum__Tax_Rate__r.Name
            FROM Zumzum__Purchase_Invoice_Line_Item__c
        ][0].Zumzum__Tax_Rate__r.Id);    
    }
}