src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

force-app/main/default/objects/Account/fields/Zumzum__Nominal_Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Nominal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nominal Account</label>
    <referenceTo>Zumzum__Nominal_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Total_Venue_Costs__c.field-meta.xml
<CustomField>
    <fullName>Total_Venue_Costs__c</fullName>
    <label>Total Venue Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Nominal_Account__c/Zumzum__Nominal_Account__c.object-meta.xml
<CustomObject>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Type__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase Invoice</fullName>
            </value>
            <value>
                <fullName>Purchase Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Nominal_Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Nominal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nominal Account</label>
    <referenceTo>Zumzum__Nominal_Account__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ZumPurchaseInvoiceLine_Rollups_TDTM_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #131 - https://confluence.nct.org.uk:8443/x/EoSO

@IsTest
public with sharing class ZumPurchaseInvoiceLine_Rollups_TDTM_Test {
    private static final String SUPPLIER_ACCOUNT_NUMBER = '123456';
    private static final String PURCHASE_INVOICE_STATUS = 'Posted';
    private static final String PURCHASE_INVOICE_TYPE = 'Purchase Credit';

    private static final Map<String, String> TRIGGER_PARAMS = new Map<String, String> {
        'triggerHandlerName' => 'ZumzumPurchaseInvoiceLine_Rollups_TDTM',
        'className' => 'ZumzumPurchaseInvoiceLine_Rollups_TDTM',
        'objectAPIName' => 'Zumzum__Purchase_Invoice_Line_Item__c',
        'triggerActions' => 'AfterInsert;AfterUpdate;AfterDelete;AfterUndelete',
        'isActive' => 'true',
        'loadOrder' => '0',
        'isAsynchronous' => 'false'
    };

    @TestSetup
    private static void TestSetup() {

        TestDataFactory dataFactory = TestDataFactory.getInstance();
            TestDataFactory.getInstance()
                .buildBranchAccount()
                .buildOrganizationAccount(SUPPLIER_ACCOUNT_NUMBER)
                .createFinanceUser()
                .buildPractitioner('John Practitioner')
                .buildPractitionerFeeRate()
                .buildVenue()
                .buildRoom()
                .buildLicenceToPractice()
                .buildCoursesWithSessions(1, 1);

        Account supplierAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Organization' LIMIT 1];

        TestFinanceDataFactory financeDataFactory = TestFinanceDataFactory.getInstance();
        financeDataFactory.createZumzumData();
        financeDataFactory.createZumzumPurchaseInvoiceWithLineItems(1);
        TestDataFactory.createTriggerSystemHandlerRecord(TRIGGER_PARAMS);
    }

    @IsTest
    private static void CheckPurchaseInvoiceLa4VTDTM_UpdatedPurchaseInvoiceLa4V_RecompiledWasSuccess() {
        Course__c courseRecordBeforeUpdated = [SELECT Id, Total_Venue_Costs__c FROM Course__c];

        Zumzum__Purchase_Invoice__c purchaseInvoiceRecord = [
            SELECT Id, Zumzum__Status__c
            FROM Zumzum__Purchase_Invoice__c
        ];

        Zumzum__Nominal_Account__c nominalAccount = [
            SELECT Id
            FROM Zumzum__Nominal_Account__c
            WHERE Zumzum__Nominal_Code__c = '5157'
        ];

        Zumzum__Purchase_Invoice_Line_Item__c purchaseInvoceLineItemsRecord = [
            SELECT Id, Zumzum__Nominal_Account__c, Course__c
            FROM Zumzum__Purchase_Invoice_Line_Item__c 
            WHERE Zumzum__Purchase_Invoice__c = :purchaseInvoiceRecord.Id
        ];

        Test.startTest();
            purchaseInvoiceRecord.Zumzum__Status__c = PURCHASE_INVOICE_STATUS;
            purchaseInvoiceRecord.Zumzum__Type__c = PURCHASE_INVOICE_TYPE;
            update purchaseInvoiceRecord;

            purchaseInvoceLineItemsRecord.Zumzum__Nominal_Account__c = nominalAccount.Id;
            purchaseInvoceLineItemsRecord.Course__c = courseRecordBeforeUpdated.Id;
            update purchaseInvoceLineItemsRecord;
        Test.stopTest();

        Course__c courseRecordAfterUpdated = [SELECT Id, Total_Venue_Costs__c FROM Course__c];

        System.assertEquals(-10, courseRecordAfterUpdated.Total_Venue_Costs__c, 'Should be equals');

    }
}