src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Is_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <formula>IF(NOT( ISBLANK(Purchase_Invoice__r.Zumzum__POP_Number__c) ), &#39;Your reference: &#39; + Purchase_Invoice__r.Zumzum__POP_Number__c + '. ', &#39;&#39;) +
&#39;Our reference: &#39; + Purchase_Invoice__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Supplier_Account_Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account_Billing_Email__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Account Billing Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BacsSendRemittanceEmailsTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #135 - https://confluence.nct.org.uk:8443/x/EoSO
@isTest
private class BacsSendRemittanceEmailsTest {
    private final static String TYPE_PURCHASE_INVOICE = 'Purchase Invoice';
    @TestSetup
    static void setupTestData(){
        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account supplierAccount = accountBuilder.WithRecordType('Organization')
            .withName('Tom Genet')
            .withType('Supplier')
            .withAccountNumber('869343')
            .withBillingEmail('tets@gmail.com')
            .withBankSortCode('572899')
            .withBankAccountNumber('03456123')
            .withBankAccountName('TEST BANK ACCOUNT')
            .insertRecord(true)
            .build();

        Account account = accountBuilder
            .withRecordType('Household Account')
            .withBranchNumber('777')
            .withAccountNumber('869341')
            .insertRecord(true)
            .build();

        TestContactBuilder contactBuilder = new TestContactBuilder();
            Contact contact = contactBuilder
                .withRecordType('Client')
                .withAccount(account)
                .withFirstName('John')
                .withLastName('Smith')
                .withNctNumber('123123')
                .insertRecord(true)
                .build();
        
        TestPurchaseInvoiceBuilder purchaseInvoiceBuilder = new TestPurchaseInvoiceBuilder();
            Zumzum__Purchase_Invoice__c purchaseInvoice = purchaseInvoiceBuilder
            .withType(TYPE_PURCHASE_INVOICE)
            .withStatus('Posted')
            .withAccount(supplierAccount.Id)
            .withContact(contact.Id)
            .withDueDate(Date.today().addDays(20))
            .withInvoiceDate(Date.today())
            .insertRecord(true)
            .build();

        TestPaymentRunBuilder paymentRunBuilder = new TestPaymentRunBuilder();
        Payment_Run__c paymentRun = paymentRunBuilder
            .insertLineItem(purchaseInvoice.Id)
            .build();
        paymentRun.Status__c = 'Completed';
        update paymentRun;
    }
    @isTest
    static void BacsSendRemittanceEmails_EmailSent_CheckboxSentTrue() {
        Test.startTest();
        List<Payment_Run_Line_Item__c> prliList = [SELECT Id, Paid_Amount__c, Reference_Info__c, Supplier_Account_Billing_Email__c FROM Payment_Run_Line_Item__c];
        BacsSendRemittanceEmailsHelper.sendEmails(new List<List<Payment_Run_Line_Item__c>> {prliList});
        Test.stopTest();
        List<Payment_Run_Line_Item__c> prliUpdatedList = [SELECT Is_Email_Sent__c FROM Payment_Run_Line_Item__c WHERE Id IN : prliList];
        for(Payment_Run_Line_Item__c prli : prliUpdatedList) {
            System.assertEquals(prli.Is_Email_Sent__c, true);
        }
    }
}