src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Branches of NCT</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practitioner?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Licences can only be applied to Practitioners.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licences To Practice</relationshipLabel>
    <relationshipName>Licences_To_Practice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Practitioner_Licence__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Practitioner Licence</relationshipLabel>
        <relationshipName>Practitioner_Licence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Practitioner Licence</label>
    <nameField>
        <label>Practitioner Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Licence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Licence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Venue</relationshipLabel>
        <relationshipName>Venue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/recordTypes/Virtual.recordType-meta.xml
<RecordType>
    <fullName>Virtual</fullName>
    <active>true</active>
    <label>Virtual</label>
</RecordType>

force-app/main/default/classes/SESSION_ParentCourseSharing_TDTM_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #149 - https://confluence.nct.org.uk:8443/x/EoSO
@isTest
public class SESSION_ParentCourseSharing_TDTM_Test {
    private static final String ACCOUNT_BRANCH_RECORDTYPE = 'Branch';
    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String PRACTITIONER_LASTNAME_TWO = 'Jones';
    private static final String PRACTITIONER_LASTNAME_THREE = 'White';
    private static final String PRACTITIONER_EMAIL_ADDRESS = 'partnerCommunityUser@ncttest.com';
    private static final String PRACTITIONER_PROFILE_NAME = 'Practitioner';
    private static final String PRACTITIONER_RECORDTYPE_NAME = 'Practitioner';
    private static final String SESSION_STATUS_PROVISIONAL = 'Provisional';
    private static final String SESSION_TYPE_STANDARD = 'Standard';
    private static final Integer COURSES_TO_CREATE = 1;
    private static final Integer SESSIONS_TO_CREATE = 3;
    private static final Map<String, String> TRIGGER_PARAMS = new Map<String, String>{
        'triggerHandlerName' => 'SESSION_ParentCourseSharing_TDTM',
        'className' => 'SESSION_ParentCourseSharing_TDTM',
        'objectAPIName' => 'Session__c',
        'triggerActions' => 'AfterInsert;AfterUpdate;AfterDelete',
        'isActive' => 'true',
        'loadOrder' => '0',
        'isAsynchronous' => 'false'
    };

    @TestSetup
    private static void SetupTestData() {
        TestDataFactory.createTriggerSystemHandlerRecord(TRIGGER_PARAMS);
        TestDataFactory dataFactory = TestDataFactory.getInstance();
            dataFactory .buildOrganizationAccount('acc1')
                        .buildBranchAccount()
                        .buildPractitioner(PRACTITIONER_LASTNAME, PRACTITIONER_EMAIL_ADDRESS)
                        .buildPractitioner(PRACTITIONER_LASTNAME_TWO, PRACTITIONER_EMAIL_ADDRESS)
                        .buildPractitioner(PRACTITIONER_LASTNAME_THREE, PRACTITIONER_EMAIL_ADDRESS);
            TestDataFactory.convertPractitionerToPartnerCommunityUser();
            dataFactory .buildPractitionerFeeRate()
                        .buildVenue()
                        .buildVirtualVenue('Virtual')
                        .buildRoom()
                        .buildLicenceToPractice()
                        .buildLicenceToPracticeForAllPractitioners()
                        .buildCoursesWithSessionsWithNotMainPractitioner(COURSES_TO_CREATE, SESSIONS_TO_CREATE, false);
    }

    @isTest
    static void CourseDoesNotHaveSessions_SessionAssignedMainPractitionerInserted_CourseShareNotCreated() {
        List<Account> branchAccounts = [SELECT Id FROM Account WHERE RecordType.Name = :ACCOUNT_BRANCH_RECORDTYPE];
        List<Contact> practitioners = [SELECT Id FROM Contact WHERE RecordType.Name = :PRACTITIONER_RECORDTYPE_NAME];
        List<Venue__c> venues = [SELECT Id FROM Venue__c];
        List<Licence_To_Practice__c> licencesToPractice = [SELECT Id FROM Licence_To_Practice__c WHERE Contact__c = :practitioners[0].Id];

        TestCourseBuilder courseBuilder = new TestCourseBuilder();
        Course__c course = courseBuilder
            .withAccount(branchAccounts[0])
            .withPractitioner(practitioners[0])
            .withMainVenue(venues[0])
            .withLicenceToPractice(licencesToPractice[0])
            .insertRecord(true)
            .build();

        TestSessionBuilder sessionBuilder = new TestSessionBuilder();
        Session__c session = sessionBuilder
            .withCourse(course)
            .withType(SESSION_TYPE_STANDARD)
            .withStatus(SESSION_STATUS_PROVISIONAL)
            .withPractitioner(practitioners[0])
            .withPractitionerLicence(licencesToPractice[0])
            .insertRecord(false)
            .build();

        List<Course__Share> courseSharesBeforeSessionInserted = [SELECT Id FROM Course__Share WHERE ParentId = :course.Id];

        Test.startTest();
        insert session;
        Test.stopTest();

        List<Course__Share> courseSharesAfterSessionInserted = [SELECT Id FROM Course__Share WHERE ParentId = :course.Id];
        System.assertEquals(0, courseSharesBeforeSessionInserted.size());
        System.assertEquals(0, courseSharesAfterSessionInserted.size());
    }
    
    @isTest
    static void PractitionerHasSessionsOnCourse_SessionAssignedPractitionerInserted_CourseShareNotCreated() {
        List<Course__c> courses = [SELECT Id FROM Course__c];
        List<Contact> practitioners = [SELECT Id FROM Contact WHERE LastName = :PRACTITIONER_LASTNAME_TWO AND recordType.Name = :PRACTITIONER_RECORDTYPE_NAME];
        List<Licence_To_Practice__c> licencesToPractice = [SELECT Id FROM Licence_To_Practice__c WHERE Contact__c = :practitioners[0].Id];

        TestSessionBuilder sessionBuilder = new TestSessionBuilder();
        Session__c session = sessionBuilder
            .withCourse(courses[0])
            .withType(SESSION_TYPE_STANDARD)
            .withStatus(SESSION_STATUS_PROVISIONAL)
            .withPractitioner(practitioners[0])
            .withPractitionerLicence(licencesToPractice[0])
            .insertRecord(false)
            .build();

        List<Course__Share> courseSharesBeforeSessionInserted = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];

        Test.startTest();
        insert session;
        Test.stopTest();

        List<Course__Share> courseSharesAfterSessionInserted = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];
        System.assertEquals(1, courseSharesBeforeSessionInserted.size());
        System.assertEquals(1, courseSharesAfterSessionInserted.size());
        
    }

    @isTest
    static void PractitionersChangedOnCourseSessions_CourseShares_AssignedNewPractitionersInserted_AssignedOldPractitionersDeleted() {
        List<Course__c> courses = [SELECT Id, Main_Practitioner__c FROM Course__c];
        Contact practitionerThree = [SELECT Id, FirstName, LastName, Email FROM Contact WHERE LastName = :PRACTITIONER_LASTNAME_THREE LIMIT 1];
        User user = [SELECT Id FROM User WHERE ContactId = :practitionerThree.Id LIMIT 1];
        Account partnerAccount = [SELECT Id FROM Account WHERE IsPartner = true LIMIT 1];
        List<Licence_To_Practice__c> licencesToPractice = [SELECT Id FROM Licence_To_Practice__c WHERE Contact__c = :practitionerThree.Id];

        practitionerThree.AccountId = partnerAccount.Id;
        update practitionerThree;

        List<Course__Share> courseSharesBeforeSessionsUpdated = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];
        List<Session__c> sessions = [SELECT Id, Practitioner__c, Practitioner_Licence__c FROM Session__c WHERE Course__c IN :courses];

        Test.startTest();
        for (Session__c session : sessions) {
            session.Practitioner__c = practitionerThree.Id;
            session.Practitioner_Licence__c = licencesToPractice[0].Id;
        }
        update sessions;
        Test.stopTest();

        List<Course__Share> courseSharesAfterSessionsUpdated = [SELECT UserOrGroupId FROM Course__Share WHERE ParentId IN :courses];
        System.assertEquals(1, courseSharesBeforeSessionsUpdated.size());
        System.assertEquals(1, courseSharesAfterSessionsUpdated.size());
        for (Course__Share courseShare : courseSharesAfterSessionsUpdated) {
            System.assertEquals(user.Id, courseShare.UserOrGroupId);            
        }
    }

    @isTest
    static void PractitionerHasSessionsOnCourse_NotLastSessionDeleted_CourseShareNotDeleted() {
        List<Course__c> courses = [SELECT Id FROM Course__c];
        List<Course__Share> courseSharesBeforeSessionDeleted = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];
        List<Session__c> sessions = [SELECT Id FROM Session__c WHERE Course__c IN :courses];

        Test.startTest();
        delete sessions[0];
        Test.stopTest();

        List<Course__Share> courseSharesAfterSessionDeleted = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];
        System.assertEquals(1, courseSharesBeforeSessionDeleted.size());
        System.assertEquals(1, courseSharesAfterSessionDeleted.size());
    }

    @isTest
    static void PractitionerHasSessionsOnCourse_AllSessionsDeleted_CourseShareDeleted() {
        List<Course__c> courses = [SELECT Id FROM Course__c];
        List<Session__c> sessions = [SELECT Id FROM Session__c WHERE Course__c IN :courses];

        Test.startTest();
        delete sessions;
        Test.stopTest();

        List<Course__Share> courseSharesAfterSessionsDeleted = [SELECT Id FROM Course__Share WHERE ParentId IN :courses];
        System.assertEquals(0, courseSharesAfterSessionsDeleted.size());
    }
}