src/objects/Account.object
<CustomObject>
    <!---->
    <!---->
    <!---->
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>npe01__HomeEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <inlineHelpText>See Preferred Email field.</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Is_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/Zumzum__Purchase_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice Line Item</label>
    <nameField>
        <label>Purchase lnvoice Lineitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice_Line_Item__c/fields/Zumzum__Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Purchase_Invoice__c</fullName>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Purchase Invoice Line Items</relationshipLabel>
    <relationshipName>Purchase_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ZumzumBACSremittanceEmailsActionTest.cls
@isTest
public with sharing class ZumzumBACSremittanceEmailsActionTest {
    private static final String OWA_VALUE = 'nctcourses@nct.org.uk';
    private static final String CONTACT_EMAIL = 'john.black@example.com';
    private static final String TEMPLATE_NAME = 'test';
    private static final String TEMPLATE_DEV_NAME = 'temp';

    @testSetup
    public static void setup() {
        Id folderId = [SELECT Id FROM Folder WHERE Type = 'Email' LIMIT 1].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs ( thisUser ) {
            EmailTemplate template = new EmailTemplate(
                DeveloperName = TEMPLATE_DEV_NAME,
                HtmlValue = '<html></html>',
                FolderId = folderId,
                TemplateType= 'custom', 
                Name = TEMPLATE_NAME,
                IsActive = true
            );
            insert template;
        }

        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account supplierAccount = accountBuilder.WithRecordType('Organization')
                .withName('Tom Genet')
                .withType('Supplier')
                .withAccountNumber('869344')
                .withBillingEmail('tets@gmail.com')
                .withBankSortCode('572899')
                .withBankAccountNumber('03456123')
                .withBankAccountName('TEST BANK ACCOUNT')
                .insertRecord(true)
                .build();
        Account account = accountBuilder
                .withRecordType('Household Account')
                .withBranchNumber('777')
                .insertRecord(true)
                .build();
        TestContactBuilder contactBuilder = new TestContactBuilder();
        Contact contact = contactBuilder
            .withRecordType('Client')
            .withAccount(account)
            .withFirstName('John')
            .withLastName('Smith')
            .withNctNumber('123123')
            .insertRecord(true)
            .build();

        Contact contactNoEmail = contactBuilder
            .withRecordType('Client')
            .withAccount(account)
            .withFirstName('James')
            .withLastName('Smith')
            .withNctNumber('123124')
            .insertRecord(true)
            .build();
        contactNoEmail.Email = null;
        contactNoEmail.npe01__HomeEmail__c = null;
        update contactNoEmail;

        TestPurchaseInvoiceBuilder purchaseInvoiceBuilder = new TestPurchaseInvoiceBuilder();
        Zumzum__Purchase_Invoice__c pi1 = purchaseInvoiceBuilder
                .withStatus('Posted')
                .withAccount(supplierAccount.Id)
                .withContact(contact.Id)
                .withDueDate(Date.today().addDays(20))
                .withInvoiceDate(Date.today())
                .insertRecord(true)
                .build();
        TestPurchaseInvoiceLineItemBuilder purchaseInvoiceLineItemBuilder = new TestPurchaseInvoiceLineItemBuilder();
        Zumzum__Purchase_Invoice_Line_Item__c purchaseInvoiceLineItems = purchaseInvoiceLineItemBuilder
                .withAmount(120)
                .withGross(120)
                .withGross(120)
                .withNet(120)
                .withNarrative('Doll')
                .withQuantity(1)
                .withPurchaseInvoice(pi1.Id)
                .insertRecord(true)
                .build();

        Zumzum__Purchase_Invoice__c piContactNoEmail1 = purchaseInvoiceBuilder
                .withStatus('Posted')
                .withAccount(supplierAccount.Id)
                .withContact(contactNoEmail.Id)
                .withDueDate(Date.today().addDays(20))
                .withInvoiceDate(Date.today())
                .insertRecord(true)
                .build();
        Zumzum__Purchase_Invoice_Line_Item__c purchaseContactNoEmailInvoiceLineItems = purchaseInvoiceLineItemBuilder
                .withAmount(120)
                .withGross(120)
                .withGross(120)
                .withNet(120)
                .withNarrative('Doll')
                .withQuantity(1)
                .withPurchaseInvoice(piContactNoEmail1.Id)
                .insertRecord(true)
                .build();
        
        TestPaymentRunBuilder paymentRunBuilder = new TestPaymentRunBuilder();
        Payment_Run__c pr1 = paymentRunBuilder
            .insertLineItem(pi1.Id, true)
            .insertLineItem(pi1.Id)
            .insertLineItem(piContactNoEmail1.Id, true)
            .insertLineItem(piContactNoEmail1.Id)
            .build();
    }

    @isTest
    static void testAction() {
        List<OrgWideEmailAddress> orgEmailObject = [
            SELECT Id, Address 
            FROM OrgWideEmailAddress
            WHERE Address = :OWA_VALUE
            LIMIT 1
        ];
        Id paymentRunId = [
            SELECT Id FROM Payment_Run__c LIMIT 1
        ].Id;

        if (TestEmailUtility.emailsFeatureEnabled() && !orgEmailObject.isEmpty()) {
            Id templateId = [
                SELECT Id 
                FROM EmailTemplate 
                WHERE DeveloperName = :TEMPLATE_DEV_NAME
                    AND Name = :TEMPLATE_NAME
                LIMIT 1
            ].Id;
            Integer sentCount = [
                SELECT count() 
                FROM Payment_Run_Line_Item__c 
                WHERE Payment_Run__c =: paymentRunId AND Is_Email_Sent__c = true
            ];
            Integer itemsToProcessCount = [
                SELECT count() 
                FROM Payment_Run_Line_Item__c 
                WHERE Payment_Run__c =: paymentRunId AND Is_Email_Sent__c = false
            ];

            ZumzumBACSremittanceEmailsAction.Request testReq = new ZumzumBACSremittanceEmailsAction.Request();
            testReq.paymentRunId = paymentRunId;
            testReq.emailTemplateId = templateId;
            testReq.orgWideEmailAddress = OWA_VALUE;
            List<ZumzumBACSremittanceEmailsAction.Request> reqList = new List<ZumzumBACSremittanceEmailsAction.Request>();
            reqList.add(testReq);
            
            Boolean success = true;
            Test.startTest();
            Id batchId;
            Id batchContactNoEmailId;
            try {
                List<ZumzumBACSremittanceEmailsAction.Response> responses = ZumzumBACSremittanceEmailsAction.sendRemittanceEmails(reqList);
                batchId = responses[0].message;
            } catch (Exception e) {
                System.debug(e.getMessage());
                success = false;
            }
            Test.stopTest();
            
            if (success) {
                System.assertNotEquals(null, batchId, 'Batch was not started');
                AsyncApexJob a = [
                    SELECT Id, Status, NumberOfErrors, JobItemsProcessed
                    FROM AsyncApexJob WHERE Id =: batchId
                ];

                System.assertEquals('Completed', a.Status, 'Batch job was not completed succesfully');
                Integer itemsCount = [
                    SELECT count() 
                    FROM Payment_Run_Line_Item__c 
                    WHERE Payment_Run__c = :paymentRunId AND Is_Email_Sent__c = true
                ];
                Payment_Run__c paymentRun = [
                    SELECT Id, Status__c FROM Payment_Run__c WHERE Id =: paymentRunId
                ];
                System.assertEquals(itemsCount - sentCount, itemsToProcessCount, 'Some items were not processed by batch job');
                System.assertEquals('Closed', paymentRun.Status__c, 'The status was not updated to Closed');
            } else {
                System.assert(false, 'An exception occured. Probably Apex action was finished with error');
            }
        }
    }

	@isTest    
    static void testError() {
        List<OrgWideEmailAddress> orgEmailObject = [
            SELECT Id, Address 
            FROM OrgWideEmailAddress
            WHERE Address = :OWA_VALUE
            LIMIT 1
        ];
        Id paymentRunId = [
            SELECT Id FROM Payment_Run__c LIMIT 1
        ].Id;

        if (TestEmailUtility.emailsFeatureEnabled() && !orgEmailObject.isEmpty()) {
            Id templateId = [
                SELECT Id 
                FROM EmailTemplate 
                WHERE DeveloperName = :TEMPLATE_DEV_NAME
                    AND Name = :TEMPLATE_NAME
                LIMIT 1
            ].Id;
			Id orgWideAddressId = orgEmailObject[0].Id;
            ZumzumBACSremittanceEmailsAction.Request testReq = new ZumzumBACSremittanceEmailsAction.Request();
            testReq.paymentRunId = paymentRunId;
            testReq.emailTemplateId = templateId;
            testReq.orgWideEmailAddress = orgWideAddressId; //putting Id instead of Address
            List<ZumzumBACSremittanceEmailsAction.Request> reqList = new List<ZumzumBACSremittanceEmailsAction.Request>();
            reqList.add(testReq);
            
            Boolean success = true;
            Test.startTest();
            Id batchId;
            List<ZumzumBACSremittanceEmailsAction.Response> responses = ZumzumBACSremittanceEmailsAction.sendRemittanceEmails(reqList);
            success = responses[0].isSuccess;
            Test.stopTest();
            
            System.assertEquals(false, success, 'Exception was not thrown');
        }
    }
}