src/objects/Booking__c.object
<CustomObject>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Do_Not_Contact__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>To be ticked if there is to be no further communication in relation to this booking (this is separate from any marketing preferences)</inlineHelpText>
    <label>Do Not Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Email_Partner__c.field-meta.xml
<CustomField>
    <fullName>Email_Partner__c</fullName>
    <formula>Partner_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email (Partner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email__c</fullName>
    <formula>Primary_Contact__r.Email</formula>
    <label>Primary Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateBookingContactsEmailTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')

@isTest
public with sharing class UpdateBookingContactsEmailTest {
    private static final String CONTACT_EMAIL_PREFIX = '.donotcontact';
    private static final String PRIMARY_CONTACT_EMAIL = 'test1@test.com';
    private static final String PARTNER_CONTACT_EMAIL = 'test2@test.com';

    @TestSetup
    static void setupData(){
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc2')
                    .buildBranchAccount()
                    .createEnquiryPSA()
                    .buildBranchAccountWithEnquiryPSA()
                    .buildPractitioner('John')
                    .buildVenue()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildParentHost('Dina', PRIMARY_CONTACT_EMAIL)
                    .buildPartnertHost('Tim', PARTNER_CONTACT_EMAIL)
                    .buildRoom()
                    .buildBooking('Enquiry');
    }

    @isTest
    static void CreateBooking_SetValueDoNotContactToTrue_ReturnContactEmailWithPrefix() {

        Test.startTest();
            Booking__c bookingInstanceForUpdate = [SELECT Do_Not_Contact__c FROM Booking__c LIMIT 1];
            bookingInstanceForUpdate.Do_Not_Contact__c = true;
            update bookingInstanceForUpdate;
        Test.stopTest();

        Booking__c bookingInstance = [SELECT Primary_Contact_Email__c,Email_Partner__c FROM Booking__c LIMIT 1];

        System.assertEquals(bookingInstance.Primary_Contact_Email__c, PRIMARY_CONTACT_EMAIL + CONTACT_EMAIL_PREFIX, 'expecting email test1@test.com.donotcontact');
        System.assertEquals(bookingInstance.Email_Partner__c, PARTNER_CONTACT_EMAIL + CONTACT_EMAIL_PREFIX, 'expecting email test2@test.com.donotcontact');
    }

}