src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Reservation_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Expiry_Date__c</fullName>
    <label>Reservation Expiry Date</label>
    <type>Date</type>
</CustomField>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SetBookingReservationExpiryDateTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #74 - https://confluence.nct.org.uk:8443/x/EoSO
@IsTest
private class SetBookingReservationExpiryDateTest {
    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String HOST_EMAIL_ADDRESS = 'User@ncttest.com';
    private static final String HOST_LASTNAME = 'Black';

    @TestSetup 
    private static void TestSetup() {
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .createEnquiryPSA()
                    .buildBranchAccountWithEnquiryPSA()
                    .buildPractitioner(PRACTITIONER_LASTNAME)
                    .buildPractitionerFeeRate()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession()
                    .buildParentHost(HOST_LASTNAME, HOST_EMAIL_ADDRESS)
                    .buildPartnertHost(HOST_LASTNAME, HOST_EMAIL_ADDRESS)
                    .buildSessionWithTypeAndStatus('Reunion', 'Confirmed')
                    .buildBookingWithoutExpiryDate('Enquiry');
        List<Session__c> provisionalNonReunionSessions = [
            SELECT Id 
            FROM Session__c 
            WHERE Status__c = 'Provisional' 
                AND Type__c <> 'Reunion'
            ];    

        List<Course__c> listDraftCourses = [
            SELECT Id 
            FROM Course__c 
            WHERE Status__c = 'Draft'];

        dataFactory .SetSessionsToConfirmed(provisionalNonReunionSessions)
                    .SetCoursesToFinal(listDraftCourses);
    }

    @IsTest
    private static void SetBookingReservationExpiryDate_SolidsCourseStartsIn5Days_ExpirationDateCourseStartDateMinus1(){

        Course__c course = [
			SELECT Type__c, Start_Date__c, Sub_Type__c
			FROM Course__c
			LIMIT 1
        ];

        course.Type__c = 'Postnatal';
        course.Sub_Type__c = 'NCT Introducing Solid Foods workshop';
        update course;

		List<Booking__c> bookingsBeforeRecalculations = [
			SELECT Reservation_Expiry_Date__c, Status__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];

        Test.startTest();
        for (Booking__c booking : bookingsBeforeRecalculations) {
            booking.Status__c = 'Reserved';
        }
        update bookingsBeforeRecalculations;
        Test.stopTest();

        List<Booking__c> bookingsAfterRecalculations = [
			SELECT Reservation_Expiry_Date__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];
        
        System.assertEquals(null, bookingsBeforeRecalculations[0].Reservation_Expiry_Date__c);
        System.assertEquals(course.Start_Date__c - 1, bookingsAfterRecalculations[0].Reservation_Expiry_Date__c);
    }

    @IsTest
    private static void SetBookingReservationExpiryDate_SolidsCourseStartsIn7Days_ExpirationDateIn5Days(){

        Course__c course = [
			SELECT Type__c, Sub_Type__c
			FROM Course__c
			LIMIT 1
        ];

        course.Type__c = 'Postnatal';
        course.Sub_Type__c = 'NCT Introducing Solid Foods workshop';
        update course;

        List<Session__c> sessions = [
            SELECT Date__c 
            FROM Session__c 
            WHERE Course__c = :course.Id
            ];
        
        for (Session__c session : sessions) {
            session.Date__c = Date.today().addDays(7);                        
        }
        update sessions;

		List<Booking__c> bookingsBeforeRecalculations = [
			SELECT Reservation_Expiry_Date__c, Status__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];

        Test.startTest();
        for (Booking__c booking : bookingsBeforeRecalculations) {
            booking.Status__c = 'Reserved';
        }
        update bookingsBeforeRecalculations;
        Test.stopTest();

        List<Booking__c> bookingsAfterRecalculations = [
			SELECT Reservation_Expiry_Date__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];
        
        System.assertEquals(null, bookingsBeforeRecalculations[0].Reservation_Expiry_Date__c);
        System.assertEquals(Date.today().addDays(5), bookingsAfterRecalculations[0].Reservation_Expiry_Date__c);
    }

    @IsTest
    private static void SetBookingReservationExpiryDate_NonSolidsCourseStartsIn5Days_ExpirationDateCourseStartDateMinus1(){

        Course__c course = [
			SELECT Type__c, Start_Date__c, Sub_Type__c
			FROM Course__c
			LIMIT 1
        ];

		List<Booking__c> bookingsBeforeRecalculations = [
			SELECT Reservation_Expiry_Date__c, Status__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];

        Test.startTest();
        for (Booking__c booking : bookingsBeforeRecalculations) {
            booking.Status__c = 'Reserved';
        }
        update bookingsBeforeRecalculations;
        Test.stopTest();

        List<Booking__c> bookingsAfterRecalculations = [
			SELECT Reservation_Expiry_Date__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];
        
        System.assertEquals(null, bookingsBeforeRecalculations[0].Reservation_Expiry_Date__c);
        System.assertEquals(course.Start_Date__c - 1, bookingsAfterRecalculations[0].Reservation_Expiry_Date__c);
    }

    @IsTest
    private static void SetBookingReservationExpiryDate_NonSolidsCourseStartsIn12Days_ExpirationDateIn10Days(){

        Course__c course = [
			SELECT Type__c, Sub_Type__c
			FROM Course__c
			LIMIT 1
        ];

        List<Session__c> sessions = [
            SELECT Date__c 
            FROM Session__c 
            WHERE Course__c = :course.Id
            ];
        
        for (Session__c session : sessions) {
            session.Date__c = Date.today().addDays(12);                        
        }
        update sessions;

		List<Booking__c> bookingsBeforeRecalculations = [
			SELECT Reservation_Expiry_Date__c, Status__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];

        Test.startTest();
        for (Booking__c booking : bookingsBeforeRecalculations) {
            booking.Status__c = 'Reserved';
        }
        update bookingsBeforeRecalculations;
        Test.stopTest();

        List<Booking__c> bookingsAfterRecalculations = [
			SELECT Reservation_Expiry_Date__c
            FROM Booking__c 
            WHERE Course__c = :course.Id
		];
        
        System.assertEquals(null, bookingsBeforeRecalculations[0].Reservation_Expiry_Date__c);
        System.assertEquals(Date.today().addDays(10), bookingsAfterRecalculations[0].Reservation_Expiry_Date__c);
    }
}