src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>First_Baby__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Baby</label>
        <type>Checkbox</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Birth_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Due_Date__c</fullName>
    <label>Birth due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/How_Heard__c.field-meta.xml
<CustomField>
    <fullName>How_Heard__c</fullName>
    <label>How Heard</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email from NCT</fullName>
            </value>
            <value>
                <fullName>NCT website or event</fullName>
            </value>
            <value>
                <fullName>Online advert</fullName>
            </value>
            <value>
                <fullName>Social media</fullName>
            </value>
            <value>
                <fullName>Newspaper or magazine</fullName>
            </value>
            <value>
                <fullName>Healthcare professional</fullName>
            </value>
            <value>
                <fullName>Previously attended NCT course</fullName>
            </value>
            <value>
                <fullName>Friends and family</fullName>
            </value>
            <value>
                <fullName>Don&#39;t remember</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Multiple_Birth__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Birth__c</fullName>
    <label>Multiple Birth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Partner  Contact)</relationshipLabel>
    <relationshipName>BookingToPartnerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Remaining_Places__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Places__c</fullName>
    <formula>Number_of_places__c - (Reserved_Places__c + Confirmed_Places__c + Enquiries__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CourseCreateEnquiryUtility.cls
public with sharing class CourseCreateEnquiryUtility {

    public static void createEnquiry(String courseNumber, Map<String, String> requestParameters) {

        Boolean isPartnerPresent = requestParameters.containsKey('partner_email') && String.isNotBlank(requestParameters.get('partner_email'));

        if (String.isNotBlank(courseNumber) && !requestParameters.isEmpty()) {

            Booking__c booking = new Booking__c();
            Contact contact;
            Contact partner;

            List<Contact> contacts = [
                SELECT Salutation, FirstName, LastName, Email, MobilePhone, MailingAddress
                FROM Contact
                WHERE Email =: requestParameters.get('email')
                LIMIT 1
            ];

            if (contacts.isEmpty()) {
                contact = new Contact(
                    RecordTypeId = '0124E000000E44A',   //Contact record type
                    Salutation = requestParameters.get('title'),
                    FirstName = requestParameters.get('first_name'),
                    LastName = requestParameters.get('last_name'),
                    Email = requestParameters.get('email'),
                    Phone = requestParameters.get('mobile'),
                    MailingCity = requestParameters.get('town'),
                    MailingPostalCode = requestParameters.get('postcode'),
                    MailingCountry = requestParameters.get('county'),
                    MailingStreet = requestParameters.get('adress_line1') + requestParameters.get('address_line2')
                );
                System.debug(contact);
                insert contact;
            } else {
                contact = contacts[0];
            }

            if (isPartnerPresent) {
                List<Contact> partners = [
                    SELECT Name, FirstName, LastName
                    FROM Contact
                    WHERE Email =: requestParameters.get('partner_email')
                ];
                if (partners.isEmpty()) {
                    partner = new Contact(
                        FirstName = requestParameters.get('partner_first_name'),
                        LastName = requestParameters.get('partner_last_name'),
                        Email = requestParameters.get('partner_email')
                    );
                    insert partner;
                } else {
                    partner = contacts[0];
                }
                booking.Partner_Contact__c = partner.Id;
            }

            booking.Primary_Contact__c = contact.Id;
            booking.Birth_Due_Date__c = Date.parse((requestParameters.get('duedate')));
    
            booking.First_Baby__c = parseBooleanParameterToPicklistValue(requestParameters.get('firstbaby'));
            booking.Multiple_Birth__c = parseBooleanParameterToPicklistValue(requestParameters.get('twinsexpected'));
            booking.Course__c = courseNumber;
            booking.How_Heard__c = requestParameters.get('hearaboutus');

            insert booking;
        }
        
    }

    private static String parseBooleanParameterToPicklistValue(String value) {
        return Boolean.valueOf(value) ? 'Yes' : 'No';
    }

    public static String getCourseIdFromHeaders() {
        // String refererUrl = requestHeaders.get('Referer');
        // return refererUrl.substring(refererUrl.lastIndexOf('/') + 1);

        List<Course__c> availableCourses = [SELECT Id FROM Course__c WHERE Remaining_Places__c > 0];
        return availableCourses[0].Id;
    }
}