src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Payment_Method__c</fullName>
        <label>Course Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I wish to pay for the course fees in 2 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees in 3 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees in 4 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees by credit or debit card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Membership_Choice__c</fullName>
        <label>Membership Choice</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Membership_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Payment_Method__c</fullName>
        <label>Membership_Payment_Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I wish to pay my membership by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay my membership by credit or debit card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Membership__c</fullName>
        <label>Partner Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Joint membership for you and your partner</fullName>
                </value>
                <value>
                    <fullName>Individual membership just for you</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Payment_Date__c</fullName>
        <label>Preferred Payment Date</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>20th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BookCourseControllerTest.cls
@isTest
private class BookCourseControllerTest {

	private final static String clientRecordTypeName = 'Client';
	private final static String practitionerRecordTypeName = 'Practitioner';
	private final static Decimal courseFee = 180.00;

	private static Contact client;
	private static Contact practitioner;
	private static Course__c course;
	private static Booking__c booking;


	@isTest
	static void LoadingPage_WithBookingStatusEnquiry_ReturnsNotAvailableState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.InsertRecord(true)
								.Build();

		Test.startTest();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.stopTest();

		System.assertEquals('NotAvailable', model.status);
	}
	
	@isTest
	static void LoadingPage_WithBookingStatusConfirmed_ReturnsNotAvailableState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Confirmed')
								.InsertRecord(true)
								.Build();

		Test.startTest();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.stopTest();

		System.assertEquals('NotAvailable', model.status);
	}

	@isTest
	static void LoadingPage_WithBookingStatusLapsed_ReturnsNotAvailableState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Lapsed')
								.InsertRecord(true)
								.Build();

		Test.startTest();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.stopTest();

		System.assertEquals('NotAvailable', model.status);
	}

	@isTest
	static void LoadingPage_WithBookingStatusReserved_ReturnsAcceptState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.startTest();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.stopTest();

		System.assertEquals('Accept', model.status);
	}

	@isTest
	static void CallingNext_FromAcceptState_ReturnsNextState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.startTest();

		controller.next();

		Test.stopTest();

		System.assertEquals('Confirm', model.status);
	}

	@isTest
	static void CallingBack_FromPaymentState_ReturnsPreviousState() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		System.assertEquals('Accept', model.status);

		controller.next();
		controller.next();

		System.assertEquals('Payment', model.status);

		Test.startTest();

		controller.back();

		Test.stopTest();

		System.assertEquals('Confirm', model.status);
	}

	@isTest
	static void CheckingWhetherToDisplayNext_FromAcceptState_ReturnsTrue() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.startTest();

		Boolean displayNext = controller.getDisplayNext();

		Test.stopTest();

		System.assertEquals(true, displayNext);
	}

	@isTest
	static void CheckingWhetherToDisplayNext_FromFinalState_ReturnsFalse() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;
		model.status = 'Submit';

		Test.startTest();

		Boolean displayNext = controller.getDisplayNext();

		Test.stopTest();

		System.assertEquals(false, displayNext);
	}

	@isTest
	static void CheckingWhetherToDisplayBack_FromInitialState_ReturnsFalse() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.startTest();

		Boolean displayNext = controller.getDisplayBack();

		Test.stopTest();

		System.assertEquals(false, displayNext);
	}

	@isTest
	static void CheckingWhetherToDisplayBack_FromSecondState_ReturnsTrue() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;
		controller.next();

		Test.startTest();

		Boolean displayNext = controller.getDisplayBack();

		Test.stopTest();

		System.assertEquals(true, displayNext);
	}

	@isTest
	static void NavigateToDdPaymentPageAndSelectingPaymentDate_WithMembershipSelectedButCourseNotSelected_IndicatesThatMembershipDdScheduleIsValidAndCourseScheduleIsNotValid() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by Direct Debit';
		booking.Preferred_Payment_Date__c = '20th';

		Test.stopTest();

		System.assertEquals(true, controller.getHasMembershipDDSchedule());
		System.assertEquals(false, controller.getHasCourseDDSchedule());
	}

	@isTest
	static void NavigateToDdPaymentPageAndSelectingPaymentDate_WithMembershipAndCoursePaymentSelected_IndicatesThatMembershipAndCourseSchedulesAreValid() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		booking = [SELECT Id, Name, Course__c, Status__c, Client__c, Course__r.Fee__c FROM Booking__c WHERE Id=:booking.Id];

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by Direct Debit';
		booking.Course_Payment_Method__c = 'I wish to pay for the course fees in 4 monthly installments by Direct Debit';
		booking.Preferred_Payment_Date__c = '20th';

		Test.stopTest();

		System.assertEquals(true, controller.getMembershipPaymentOptionIsDd());
		System.assertEquals(true, controller.getCoursePaymentOptionisDd());
		System.assertEquals(true, controller.getHasMembershipDDSchedule());
		System.assertEquals(true, controller.getHasCourseDDSchedule());
	}

	@isTest
	static void SelectingMembership_ForOneYear_ReturnsCorrectMembershipAmount()
	{
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.startTest();

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';

		Test.stopTest();

		System.assertEquals(48.00, controller.getMembershipFee());
	}

	@isTest
	static void SelectingMembership_ForEighteenMonths_ReturnsCorrectMembershipAmountAndNumberOfMonths()
	{
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		Test.startTest();

		booking.Membership_Choice__c = 'Value 18-month single payment option - £57';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';

		Test.stopTest();

		System.assertEquals(57.00, controller.getMembershipFee());
	}

	@isTest
	static void NavigateToDdPaymentPage_WithMembershipAndCoursePaymentSelected_ReturnsValidDdMembershipSchedule() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		booking = [SELECT Id, Name, Course__c, Status__c, Client__c, Course__r.Fee__c FROM Booking__c WHERE Id=:booking.Id];

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by Direct Debit';
		booking.Course_Payment_Method__c = 'I wish to pay for the course fees in 4 monthly installments by Direct Debit';
		booking.Preferred_Payment_Date__c = '20th';
		DirectDebitModels.DdSchedule membershipSchedule = controller.getMembershipDdSchedule();

		Test.stopTest();

		System.assertEquals(4, membershipSchedule.Months);
		System.assertEquals(48.00, membershipSchedule.TotalAmount);
		System.assertEquals(20, membershipSchedule.PaymentDay);
		System.assertEquals(4, membershipSchedule.ScheduleItems.size());
		System.assertEquals(12.00, membershipSchedule.ScheduleItems.get(0).Amount);		
	}

	@isTest
	static void NavigateToDdPaymentPage_WithMembershipAndCoursePaymentSelected_ReturnsValidDdCourseSchedule() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		booking = [SELECT Id, Name, Course__c, Status__c, Client__c, Course__r.Fee__c FROM Booking__c WHERE Id=:booking.Id];

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by Direct Debit';
		booking.Course_Payment_Method__c = 'I wish to pay for the course fees in 2 monthly installments by Direct Debit';
		booking.Preferred_Payment_Date__c = '3rd';
		DirectDebitModels.DdSchedule courseSchedule = controller.getCourseDdSchedule();

		Test.stopTest();

		System.assertEquals(2, courseSchedule.Months);
		System.assertEquals(courseFee, courseSchedule.TotalAmount);
		System.assertEquals(3, courseSchedule.PaymentDay);
		System.assertEquals(2, courseSchedule.ScheduleItems.size());
		System.assertEquals(90.00, courseSchedule.ScheduleItems.get(0).Amount);	
	}

	@isTest
	static void NavigateToDdPaymentPage_WithMembershipDdAndCourseCardPaymentSelected_ReturnsCorrectCardPaymentAmount() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		booking = [SELECT Id, Name, Course__c, Status__c, Client__c, Course__r.Fee__c FROM Booking__c WHERE Id=:booking.Id];

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by Direct Debit';
		booking.Course_Payment_Method__c = 'I wish to pay for the course fees by credit or debit card';
		booking.Preferred_Payment_Date__c = '3rd';
		DirectDebitModels.DdSchedule courseSchedule = controller.getCourseDdSchedule();

		Test.stopTest();

		System.assertEquals(true, controller.getHasCardPayment());
		System.assertEquals('£' + String.valueOf(courseFee), controller.getCardPaymentTotal());
	}

	@isTest
	static void NavigateToDdPaymentPage_WithMembershipCardAndCourseDdPaymentSelected_ReturnsCorrectCardPaymentAmount() {
		
		setupTestData();

		TestBookingBuilder bookingBuilder = new TestBookingBuilder();
		booking = bookingBuilder.WithClient(client)
								.WithCourse(course)
								.WithStatus('Reserved')
								.InsertRecord(true)
								.Build();

		booking = [SELECT Id, Name, Course__c, Status__c, Client__c, Course__r.Fee__c FROM Booking__c WHERE Id=:booking.Id];

		Test.setCurrentPage(Page.BookCourse);
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);

		BookCourseController controller = new BookCourseController(stdController);
		BookCourseControllerModel model = controller.model;

		booking.Membership_Choice__c = 'Standard 1-year single payment option - £48';
		booking.Partner_Membership__c = 'Joint membership for you and your partner';
		controller.next();

		controller.next();

		Test.startTest();

		booking.Membership_Payment_Method__c = 'I wish to pay my membership by credit or debit card';
		booking.Course_Payment_Method__c = 'I wish to pay for the course fees in 2 monthly installments by Direct Debit';
		booking.Preferred_Payment_Date__c = '3rd';
		DirectDebitModels.DdSchedule courseSchedule = controller.getCourseDdSchedule();

		Test.stopTest();

		System.assertEquals(true, controller.getHasCardPayment());
		System.assertEquals('£48.00', controller.getCardPaymentTotal());
	}

	private static void setupTestData()
	{
		TestContactbuilder clientContactBuilder = new TestContactbuilder();
		client = clientContactBuilder.WithRecordType(clientRecordTypeName)
										.InsertRecord(true)
										.Build();

		TestContactbuilder practitionerContactBuilder = new TestContactbuilder();
		practitioner = practitionerContactBuilder.WithRecordType(practitionerRecordTypeName)
										.InsertRecord(true)
										.Build();

		TestCourseBuilder courseBuilder = new TestCourseBuilder();
		course = courseBuilder.WithPractitioner(practitioner)
										.WithFee(courseFee)
										.InsertRecord(true)
										.Build();
	}
}