src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course_Payment_Method__c</fullName>
        <label>Course Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I wish to pay for the course fees in 2 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees in 3 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees in 4 monthly installments by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay for the course fees by credit or debit card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Membership_Choice__c</fullName>
        <label>Membership Choice</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Membership_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Payment_Method__c</fullName>
        <label>Membership_Payment_Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I wish to pay my membership by Direct Debit</fullName>
                </value>
                <value>
                    <fullName>I wish to pay my membership by credit or debit card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Payment_Date__c</fullName>
        <label>Preferred Payment Date</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>20th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BookCourseController.cls
public with sharing class BookCourseController {

    private final ApexPages.StandardController controller;
	private final Booking__c booking;
    public BookCourseControllerModel model { get; set; }

    public BookCourseController(ApexPages.StandardController stdController) {
        
        controller = stdController;
        this.booking = (Booking__c)stdController.getRecord();
        //getSessions();

        model = new BookCourseControllerModel();
        
        if(isValidBooking())
        {
            model.Status = 'Accept';
        }
        else
        {
            model.Status = 'NotAvailable';
        }
    }

    public void next() {

        String newStatus = model.Statuses.get(0);

        for(integer i=0; i< model.Statuses.size()-1; i++)
        {
            if (model.Status == model.Statuses.get(i))
            {
                newStatus = model.Statuses.get(i+1);
                
                if(newStatus == 'DDConfirm' 
                    && !membershipDDScheduleValid()
                    && !courseDdScheduleValid())
                {
                    newStatus = model.Statuses.get(i+2);
                }
            }
        }

        model.Status = newStatus;
    }

    public void back() {

        String newStatus = model.Statuses.get(0);

        for(integer i=model.Statuses.size()-1; i > 0; i--)
        {
            if (model.Status == model.Statuses.get(i))
            {
                newStatus = model.Statuses.get(i-1);
                
                if(newStatus == 'DDConfirm' 
                    && !membershipDDScheduleValid()
                    && !courseDdScheduleValid())
                {
                    newStatus = model.Statuses.get(i-2);
                }
            }
        }

        model.Status = newStatus;
    }

    public void submitBooking()
    {
        booking.Status__c = 'Confirmed';
        controller.save();
        model.Status = 'Complete';
    }

    public void processCardPayment()
    {
        booking.Status__c = 'Confirmed';
        controller.save();
        model.Status = 'CardPayment';
    }

    public Boolean getDisplayNext()
    {
        Set<String> validProcessStatuses = new Set<String>(model.Statuses);
        Boolean displayNext = false;

        if(validProcessStatuses.contains(model.Status))
        {
            if(model.Status == model.Statuses.get(model.Statuses.size() - 1))
            {
                displayNext = false;
            }
            else
            {
                displayNext = true;
            }
        }

        return displayNext;
    }

    public Boolean getDisplayBack()
    {
        Set<String> validProcessStatuses = new Set<String>(model.Statuses);
        Boolean displayBack = false;

        if(validProcessStatuses.contains(model.Status))
        {
            if(model.Status == model.Statuses.get(0))
            {
                displayBack = false;
            }
            else
            {
                displayBack = true;
            }
        }

        return displayBack;
    }

    public DirectDebitModels.DdSchedule getMembershipDdSchedule()
    {
        if(membershipDDScheduleValid())
        {   
            Integer paymentDate = getPaymentDateFromString(booking.Preferred_Payment_Date__c);   
            return DirectDebitUtilities.calculateDdSchedule(getMembershipFee(), getMembershipPaymentMonths(), paymentDate);
        }

        return new DirectDebitModels.DdSchedule();
    }

    public DirectDebitModels.DdSchedule getCourseDdSchedule()
    {
        if(courseDdScheduleValid())
        {   
            Integer paymentDate = getPaymentDateFromString(booking.Preferred_Payment_Date__c);         
            return DirectDebitUtilities.calculateDdSchedule(booking.Course__r.Fee__c, getCourseSchedulePaymentMonths(booking.Course_Payment_Method__c), paymentDate);
        }

        return new DirectDebitModels.DdSchedule();
    }

    public Boolean getHasMembershipDDSchedule()
    {
        return membershipDDScheduleValid();
    }

    public Boolean getHasCourseDdSchedule()
    {
        return courseDdScheduleValid();
    }

    public Boolean getHasCardPayment(){
        return !getMembershipPaymentOptionIsDD() || !getCoursePaymentOptionIsDD();
    }

    public String getCardPaymentTotal()
    {
        Decimal cardPaymentTotal = 0.00;

        if(!membershipDDScheduleValid())
        {  
            cardPaymentTotal += getMembershipFee();
        }

        if(!courseDdScheduleValid())
        {
            cardPaymentTotal += booking.Course__r.Fee__c;
        }

        return '£' + String.valueOf(cardPaymentTotal.setScale(2));
    }

    public Boolean getCoursePaymentOptionIsDd()
    {
        if(booking.Course_Payment_Method__c !=  null
            && booking.Course_Payment_Method__c.contains('Direct Debit'))        
        {
            return true;
        }

        return false;
    }

    public Boolean getMembershipPaymentOptionIsDd()
    {
        if(booking.Membership_Payment_Method__c != null
            && booking.Membership_Payment_Method__c.contains('Direct Debit'))
        {
            return true;
        }

        return false;
    }

    public Decimal getMembershipFee()
    {
        Decimal membershipFeeToPay;

        if(booking.Membership_Choice__c != null && booking.Membership_Choice__c.contains('18-month'))
        {
            membershipFeeToPay = model.eighteenMonthMembershipFee;
        }
        else
        {
            membershipFeeToPay = model.oneYearMembershipFee;
        }
        
        return membershipFeeToPay.setScale(2);
    }

    private Boolean isValidBooking()
    {
        if(booking.Status__c == 'Reserved')
        {
            return true;
        }

        return false;
    }

    private Integer getMembershipPaymentMonths()
    {
        Integer scheduleMonths;

        if(booking.Membership_Choice__c != null && booking.Membership_Choice__c.contains('18-month'))
        {
            scheduleMonths = model.eighteenMonthPayments;
        }
        else
        {
            scheduleMonths = model.oneYearPayments;
        }
        
        return scheduleMonths;
    }

    private Boolean membershipDdScheduleValid()
    {
        if(getMembershipPaymentOptionIsDD()
            && booking.Preferred_Payment_Date__c != null)
        {
            return true;
        }

        return false;
    }

    private Boolean courseDdScheduleValid()
    {
        system.debug(getCoursePaymentOptionIsDd());
        system.debug(booking.Preferred_Payment_Date__c);
        system.debug(booking.Course__r.Fee__c);
        if(getCoursePaymentOptionIsDd()
            && booking.Preferred_Payment_Date__c != null
            && booking.Course__r.Fee__c != null)
        {
            return true;
        }

        return false;
    }

    private static Integer getCourseSchedulePaymentMonths(String coursePaymentMethodPicklistValue)
    {
        Integer monthlyStringIndex = coursePaymentMethodPicklistValue.indexOf('monthly');

        Integer paymentCount = Integer.valueOf(coursePaymentMethodPicklistValue.substring(monthlyStringIndex - 2, monthlyStringIndex-1));

        return paymentCount;
    }

    private static Integer getPaymentDateFromString(String preferredPaymentDate)
    {
        String numberOnly = preferredPaymentDate.replaceAll('[^0-9]', '');
            return Integer.valueOf(numberOnly);
    }
}