src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingStatusFlowHelper.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class BookingStatusFlowHelper {
    
    @InvocableMethod(Label='Update Bookings (Database)')
    global static void updateBookings(List<List<Booking__c>> bookingsToUpdate){
        String errorMessage;
        Database.SaveResult[] results;
        for (Booking__c booking : bookingsToUpdate[0]){
            booking.Status__c = String.valueOf(booking.Status__c);
        }
        results = Database.update(bookingsToUpdate[0], false);
        for(Database.saveResult sr :results){
            if(!sr.isSuccess()){
                for(Database.Error error : sr.getErrors()){
                    errorMessage = 'The following error has occurred. ' +
                        error.getStatusCode() + ': ' + error.getMessage() +
                        'Booking fields that affected this error: ' + error.getFields();
                    System.debug(errorMessage);
                }
            }
        }

    } 
}
//NOPMD
//Incident #15 - https://confluence.nct.org.uk:8443/x/EoSO