src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Clients</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Booking (First Contact)</relationshipLabel>
        <relationshipName>Course_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card(£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 10)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>Declaration_Number__c</fullName>
        <label>Declaration Number</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gaid__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gaid__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Gift Aid Declarations</relationshipLabel>
        <relationshipName>Gift_Aid_Declarations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gaid__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Single</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>CARE_Payment_Frequency__c</fullName>
        <label>CARE_Payment_Frequency</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Debit_Key__c</fullName>
        <label>Direct_Debit_Key</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Contact_Key__c</fullName>
        <label>First Contact Key</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Donations_Key__c</fullName>
        <label>Recurring Donations Key</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>Sets the installment period for your recurring donations.  WARNING: Changing the Installment Period for an existing open-ended Recurring Donation can cause open Opportunities to be deleted and recreated. Any associated data may not be retained.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp4hub__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/nctPaymentHubPageController.cls
public with sharing class NctPaymentHubPageController
{
    public Contact newCont {get;set;}
    public cpm__Payment_Profile__c pymtPrfl {get;set;}
    public npe03__Recurring_Donation__c recDon {get;set;}
    public gaid__Gift_Aid_Declaration__c gftAid {get;set;}
    public Booking__c corsBkng {get;set;}
    public string memberType {get;set;}
   
    public boolean pymSelSec  {get;set;}
    public boolean contInfoSec  {get;set;}
    public boolean pymtInfoSec  {get;set;}
    public boolean confmInfoSec {get;set;}
    public boolean thankYouSec {get;set;}
    public boolean feeFieldVisibility {get;set;}
    public string feeAmount {get;set;}
    public string membershipNumber {get;set;}
    public string courseBookingNo {get;set;}
    public string redirectURL {get;set;} 
    public Id courseId {get;set;}
    public Course__c cors;
    // added by MembershipFormController
    public String addressline1 {get; set;}
    public String textAddress2 {get; set;}
    public String textAddress3 {get; set;}
    public String textTown {get; set;} 
    public String county {get; set;} 
  
   public String postalCode {get; set;}
    public String firstName {get; set;}
    public String lastName {get; set;}
    public String email {get; set;}

    public NctPaymentHubPageController()
    {
        courseId = ApexPages.currentPage().getParameters().get('id');
        User u = new User();
         u.PostalCode = postalCode;
    
        newCont = new Contact();
        pymtPrfl = new cpm__Payment_Profile__c();
        recDon = new npe03__Recurring_Donation__c();
        gftAid = new gaid__Gift_Aid_Declaration__c();
        corsBkng = new Booking__c();
       
        contInfoSec = true;
        feeFieldVisibility = false;
        pymSelSec = false;
        pymtInfoSec = false;
        confmInfoSec = false;
        thankYouSec = false;
        if(courseId != null)
        {
            feeFieldVisibility = true;
            cors = [select Id, Fee__c from Course__c where Id=:courseId];
            if(cors != null)
            {
                feeAmount = '£'+string.valueOf(cors.Fee__c);
            }
        }
    }
    
    public PageReference contactSave()
    {
        PageReference redirecContUrl;
       
            newCont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
           
            contInfoSec = false;
            pymSelSec = true;
            redirecContUrl = null;
             
        return redirecContUrl;
    }
    public PageReference paymentSel()
    {        
        PageReference redirectUrl;
        contInfoSec = false;
        pymSelSec = false;
        if(memberType.contains('Direct Debit'))
        {
            pymtInfoSec = true;
            insert newCont;
            if(courseId != null)
            {                            
                corsBkng.First_Contact__c = newCont.Id;
                corsBkng.Status__c = 'Installment';
                corsBkng.Course__c = courseId;
                corsBkng.Payment_Date__c = system.today();
                corsBkng.Payment_Method__c = memberType;
                corsBkng.Cost__c = cors.Fee__c;
                corsBkng.Due_Date__c = system.today()-1;
                insert corsBkng;
            }            
            redirectUrl = null;
        }
        else if(memberType.contains('Credit/Debit Card'))
        {
            system.debug('*$*$**$* memberType  ' + memberType);
            redirectUrl = paymentHubCallout(); 
            if(courseId != null)
            {  
                newCont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
                insert newCont;
                corsBkng.First_Contact__c = newCont.Id;
                corsBkng.Status__c = 'Paid';
                corsBkng.Course__c = courseId;
                corsBkng.Payment_Date__c = system.today();
                corsBkng.Payment_Method__c = 'Credit/Debit Card(£57)';
                corsBkng.Cost__c = cors.Fee__c;
                corsBkng.Due_Date__c = system.today()-1;
                insert corsBkng;
            }
        }
        return redirectUrl;
    }
    public void paymentSave()
    {
        feeAmount = memberType.substringBetween('(', ')');
        pymtPrfl.RecordTypeId = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByName().get('Bank Account').getRecordTypeId();
        pymtPrfl.cpm__Contact__c = newCont.Id;
        insert pymtPrfl;
        
        gftAid.gaid__Contact__c= newCont.Id;
       
        gftAid.Method__c = 'Online';
        gftAid.gaid__Type__c = 'Single';
        gftAid.Declaration_Number__c = 56443323;
        gftAid.gaid__Active__c = true;
        insert gftAid;
        
        recDon.Name = memberType;
        recDon.npe03__Amount__c = 60;
        recDon.npe03__Contact__c = newCont.Id;
        recDon.CARE_Payment_Frequency__c = 'Monthly';
        recDon.Direct_Debit_Key__c = 432321323;
        recDon.First_Contact_Key__c = 12233342;
        recDon.Recurring_Donations_Key__c = 75664543;
        recDon.First_Contact__c = newCont.Id;
        recDon.npe03__Installment_Period__c = 'Monthly';
        recDon.npsp4hub__Payment_Method__c = 'Direct Debit';
        recDon.npsp4hub__Payment_Processor__c = 'PaymentHub-BACS';
        recDon.npsp4hub__Target__c = 'BACS Standard 18';
        recDon.npsp4hub__Payment_Profile__c = pymtPrfl.Id;
        Insert recDon;
        
        contInfoSec = false;
        pymSelSec = false;
        pymtInfoSec = false;
        confmInfoSec = true;
    }
    
    public void thankYouSec()
    {
        confmInfoSec = false;
        thankYouSec = true;
        system.debug('RECCURRING DONATION   ' + recDon.Id);
        if(recDon.Id != null)
        {
            
            npe03__Recurring_Donation__c reccDon = [select Id, Membership_Number__c from npe03__Recurring_Donation__c where Id =: recDon.Id];
            system.debug('RECCURRING DONATION record  ' + reccDon);
            if(reccDon != null)
            {
                membershipNumber = reccDon.Membership_Number__c;
                system.debug('membershipNumber  ' + membershipNumber);
            }
        }
        
        if(courseId != null && corsBkng != null)
        {
            Booking__c crsBkng = [select Id, Name from Booking__c where Id =: corsBkng.Id];
            if(crsBkng != null)
            {
                courseBookingNo = crsBkng.Name;
                system.debug('*$*$* courseBookingNo  ' + courseBookingNo);
            }
        }        
    }
    public PageReference paymentHubCallout()
    {
        if(memberType != '' && memberType != null)
        {
           feeAmount = memberType.substringBetween('(', ')'); 
        }
        
        string responseContent;
        
        HttpRequest tokenRequest = new HttpRequest();
        HttpResponse tokenResponse = new HttpResponse();
        Http tokenHttp = new Http();
        
        tokenRequest.setEndpoint('https://test.salesforce.com/services/oauth2/token?client_id=3MVG95AcBeaB55lVpFY_Rw8rGI.KUCG9dcqi1zRxbXuXhdoYYpgHOQUg01kQrJyfp_yYqnT6F.aEXC1U7n06J&client_secret=5804933462634405366&grant_type=password&username=payment.api@nct.org.uk.preuat&password=payment123rl3GtuRGUj15A1W6ysGuUAT3N');
  
        tokenRequest.setMethod('POST'); 
        tokenRequest.setTimeout(120000);    
        tokenResponse = tokenHttp.send(tokenRequest);

        AcessTokenResponseVo accessTokenVo = (AcessTokenResponseVo) JSON.deserialize(tokenResponse.getBody(),AcessTokenResponseVo.class);

        
        PaymentRequestVo paymentReq = new PaymentRequestVo();
        paymentReq.SuccessURL='https://preuat-mynct.cs102.force.com/nctPaymentHubSuccessMsgPage';
        paymentReq.FailureURL='https://preuat-mynct.cs102.force.com/nctPaymentHubErrorMsgPage';
        paymentReq.Origin='test';
 
        PaymentRequestVo.ContactVo cvo = new PaymentRequestVo.ContactVo();
        cvo.Email = newCont.Email;
        
        cvo.FirstName = newCont.Prefered_First_Name__c;
        cvo.LastName = newCont.LastName;
 
        PaymentRequestVo.PayerVo payerReq = new PaymentRequestVo.PayerVo();
        payerReq.AllowDeduplication=true;
        payerReq.contact = cvo;
        payerReq.ContactUpdate ='replace';
        paymentReq.Payer = payerReq;
 
        PaymentRequestVo.PaymentVo payment = new PaymentRequestVo.PaymentVo();
        system.debug('*$*$**$*$ feeAmount  ' + feeAmount);
        feeAmount = feeAmount.substring(feeAmount.lastIndexOf('£')+1, feeAmount.lastIndexOf('£')+2);        
        payment.Amount=decimal.valueOf(feeAmount);
        paymentReq.Payment = payment;
 
        PaymentRequestVo.PaymentMethodVo paymentMethod = new PaymentRequestVo.PaymentMethodVo();
        paymentMethod.Name='CreditCard';
        paymentReq.PaymentMethod = paymentMethod;
 
        PaymentRequestVo.SourceConnectorVo sourceConnector = new PaymentRequestVo.SourceConnectorVo();
        sourceConnector.Name='PaymentHub';
        paymentReq.SourceConnector = sourceConnector;
 
        System.Debug('*$*$*$*$* JSON  =   ' + JSON.serializePretty(paymentReq));
        
        HttpRequest paymentHubRequest = new HttpRequest();
        HttpResponse paymentHubResponse = new HttpResponse();
        Http paymentHubHttp = new Http(); 
        paymentHubRequest.setEndpoint('https://cs102.salesforce.com/services/apexrest/cpm/v1.0/Payment');        
        paymentHubRequest.setHeader('Authorization','Bearer '+accessTokenVo.access_token);  
        
        paymentHubRequest.setHeader('Content-Type','application/json; charset=UTF-8');
        paymentHubRequest.setHeader('Accept','application/json');
        paymentHubRequest.setHeader('api-token','IPy3Yvtin0aa2GPIke79Ewp24a0YSt6Daj5HJ9v9IGq2VTDYTWWkSx5jE2Pg54u02j0uHQZ3BwHfxFh8nKfXK4fiqZSQbZuXFQtQfAE926aFrwwVoOxPOJ6MiWSFpMc8b0UrOcbUD9pdcW7x8xNu3CtI5JfukTrRZqNByghsdTnWKLb79XrKpttmtHepMmVPv3QyPZYq');
        paymentHubRequest.setBody(JSON.serialize(paymentReq));
        paymentHubRequest.setMethod('POST'); 
        paymentHubRequest.setTimeout(120000);    
        paymentHubResponse = paymentHubHttp.send(paymentHubRequest);
        System.debug('*$*$*$*$*  RESPONSE =   ' + paymentHubResponse.getBody());
        responseContent = paymentHubResponse.getBody();
        system.debug('*$*$*$* responseContent ===   ' + responseContent);
        redirectURL = responseContent.subString(responseContent.IndexOf('PaymentHub')+28, responseContent.lastIndexOf('PaymentMethod')-3);
        system.debug('*$*$*$** redirectURL =   ' + redirectURL);
        //PageReference pageRefCrdDbt = new PageReference('https://ournct--preuat--c.cs102.visual.force.com/apex/phstr__stripecheckout?failureRedirectURL=https%253A%252F%252Fwww.example.com%252Ferror&id=a2b1j00000002s1AAA&successRedirectURL=https%253A%252F%252Fwww.example.com%252Fsuccess');
        redirectURL += '&nooverride=1';
        //PageReference pageRefCrdDbt = new PageReference('https://preuat-mynct.cs102.force.com/apex/phstr__stripecheckout?failureRedirectURL=https%3A%2F%2Fournct--preuat--c.cs102.visual.force.com%2Fapex%2FnctPaymentHubErrorMsgPage&id=a2b1j000000031FAAQ&successRedirectURL=https%3A%2F%2Fournct--preuat--c.cs102.visual.force.com%2Fapex%2FnctPaymentHubSuccessMsgPage');
        PageReference pageRefCrdDbt = new PageReference(redirectURL);
        pageRefCrdDbt.setRedirect(true);
        system.debug('  *$*$*$** pageRefCrdDbt =   ' + pageRefCrdDbt);
        return pageRefCrdDbt;
    }
/*test*/
}