src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&apos;Enquiry&apos;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Type</valueSetName>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Booking_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Book</fullName>
    </customValue>
    <masterLabel>Booking Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExistingBookingLocator.cls
public without sharing class ExistingBookingLocator {
    private static final List<String> LIVE_BOOKING_STATUSES = new List<String>{'Enquiry', 'Reserved', 'Confirmed'};
    private static final String BOOKING_SOURCE_QUICK_BOOK = 'Quick Book';
    
    @InvocableMethod(label='Find Existing Booking')
    public static List<Response> findExistingBooking(List<Request> requestList){
        Id contactId = requestList[0].contactId;
        Id courseId = requestList[0].courseId;

        @SuppressWarnings('PMD.ApexCRUDViolation')
        //Incident #118 - https://confluence.nct.org.uk:8443/x/EoSO
        List<Booking__c> existingBookings = [
            SELECT Id, Source__c
            FROM Booking__c
            WHERE Status__c IN :LIVE_BOOKING_STATUSES
                AND Course__c = :courseId 
                AND Primary_Contact__c = :contactId
            WITH SECURITY_ENFORCED
        ];

        Response response = new Response();

        if (existingBookings.size() == 1) {
            response.bookingId = existingBookings[0].Id;
        } else if (existingBookings.size() > 1) {
            setBookingId(existingBookings, response);
        }

        List<Response> responseWrapper= new List<Response>();
        responseWrapper.add(response);
        return responseWrapper;  
    }

    private static void setBookingId(List<Booking__c> bookings, Response response) {
        Integer quickBookCounter = 0;
        for (Booking__c booking : bookings) {
            if (booking.Source__c == BOOKING_SOURCE_QUICK_BOOK) {
                response.bookingId = booking.Id;
                quickBookCounter++;
            }
        }
        if (quickBookCounter > 1) {
            response.bookingId = null;
        }
    }

    public class Request {
        @invocableVariable (label='Contact Id' required=true)
        public Id contactId;

        @invocableVariable (label='Course Id' required=true)
        public Id courseId;
    }

    public class Response {
        @invocableVariable (label='Booking Id')
        public Id bookingId; 
    }
}