src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingPaymentDetailsControllerTest.cls
@IsTest
public with sharing class BookingPaymentDetailsControllerTest {
    private static final String BOOKING_STATUS_CONFIRMED = 'Confirmed';
    private static final String PROFILE_NAME = 'Enquiry PSA';
    private static final String PERMISSION_SET_NAME = 'Override_Booking_Validation';

    @TestSetup
    static void setupData(){
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc2')
                    .buildBranchAccount()
                    .createEnquiryPSA()
                    .buildBranchAccountWithEnquiryPSA()
                    .buildPractitioner('John')
                    .buildVenue()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildParentHost('Dina', 'test1@test.com')
                    .buildPartnertHost('Tim', 'test2@test.com')
                    .buildRoom()
                    .buildBooking('Reserved');
    }

    @IsTest
    public static void changeBookingStatus_bookingStatus_bookingStatusIsConfirmed() {
        Booking__c bookingRecord = [
            SELECT Id, Status__c 
            FROM Booking__c 
            LIMIT 1
        ];

        User user = [
            SELECT Id 
            FROM User
            WHERE Profile.Name = :PROFILE_NAME
            LIMIT 1
        ];

        System.runAs ( TestDataFactory.assignPermissionSetToUser(PERMISSION_SET_NAME, user) ) {
            bookingRecord.Status__c = BOOKING_STATUS_CONFIRMED;
            update bookingRecord;
        }

        Test.startTest();
            BookingPaymentDetailsController bookingPaymentDetailsControllerInstance = new BookingPaymentDetailsController();
            bookingPaymentDetailsControllerInstance.setBookingId(bookingRecord.Id);
        Test.stopTest();

        System.assertEquals(1, bookingPaymentDetailsControllerInstance.bookingList.size());
        System.assertEquals(bookingRecord.Id, bookingPaymentDetailsControllerInstance.bookingList.get(0).Id);
        System.assertEquals(BOOKING_STATUS_CONFIRMED, bookingPaymentDetailsControllerInstance.bookingList.get(0).Status__c);

    }
}