src/objects/Booking__c.object
<CustomObject>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/First_Name_Partner__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Partner__c</fullName>
    <formula>Partner_Contact__r.FirstName</formula>
    <label>First Name (partner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Primary_Contact__r.LastName</formula>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Last_Name_Partner__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_Partner__c</fullName>
    <formula>Partner_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name (partner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Partner  Contact)</relationshipLabel>
    <relationshipName>BookingToPartnerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <formula>PrimaryContact__r.MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>gaid__Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gaid__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gaid__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Gift Aid Declarations</relationshipLabel>
        <relationshipName>Gift_Aid_Declarations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gaid__Date_Made__c</fullName>
        <label>Date Made</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gaid__Housename_or_number__c</fullName>
        <label>House name or number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gaid__Postalcode__c</fullName>
        <label>Postal code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/gaid__Firstname__c.field-meta.xml
<CustomField>
    <fullName>gaid__Firstname__c</fullName>
    <inlineHelpText>This value overrides the default contact value.</inlineHelpText>
    <label>First Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/gaid__Lastname__c.field-meta.xml
<CustomField>
    <fullName>gaid__Lastname__c</fullName>
    <inlineHelpText>This overrides the contact default.</inlineHelpText>
    <label>Last Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GiftAidDetailController.cls
public with sharing class GiftAidDetailController {
    //GAD = Gift Aid Declaration;
    private static final String INDIVIDUAL_GAD_DECLARATION = 'individual';
    private static final String JOINT_GAD_DECLARATION = 'joint';
    private static final String ACQUISITION_METHOD = 'Digital';
    private static final String METHOD = 'GiftAid';

    @InvocableMethod
    public static void createGiftAidDeclaration(List<List<String>> flowParams) {
        String bookingId = flowParams[0][0];
        String giftAidDeclarationValue = flowParams[0][1];

        if (giftAidDeclarationValue == INDIVIDUAL_GAD_DECLARATION) {
            addIndividualDeclaration(bookingId);
        } else if (giftAidDeclarationValue == JOINT_GAD_DECLARATION) {
            addJointDeclaration(bookingId);
        }
    }

    private static void addIndividualDeclaration(Id bookingId) {
        Booking__c booking = [
            SELECT  Primary_Contact__c,
                    First_Name__c,
                    Last_Name__c,
                    Postcode__c,
                    Primary_Contact__r.MailingStreet
            FROM Booking__c
            WHERE ID = :bookingId
        ];

        List<gaid__Gift_Aid_Declaration__c> individualGiftAidDeclarationList = new List<gaid__Gift_Aid_Declaration__c> {
            new gaid__Gift_Aid_Declaration__c(
                gaid__Date_Made__c = Date.today(),
                gaid__Active__c = true,
                gaid__Contact__c = booking.Primary_Contact__c,
                gaid__FirstName__c = booking.First_Name__c,
                gaid__LastName__c = booking.Last_Name__c,
                gaid__Postalcode__c = booking.Postcode__c,
                gaid__Housename_or_number__c = booking.Primary_Contact__r.MailingStreet,
                gaid__Acquisition_Method__c = ACQUISITION_METHOD,
                Method__c = METHOD
            )
        };

        insertGiftAidDeclaration(individualGiftAidDeclarationList);
    }

    private static void addJointDeclaration(Id bookingId) {
        Booking__c booking = [
            SELECT  Partner_Contact__c,
                    Primary_Contact__c,
                    First_Name__c,
                    Last_Name__c,
                    First_Name_Partner__c,
                    Last_Name_Partner__c,
                    Postcode__c,
                    Primary_Contact__r.MailingStreet
            FROM Booking__c
            WHERE ID = :bookingId
        ];

        List<gaid__Gift_Aid_Declaration__c> jointGiftAidDeclarationList = new List<gaid__Gift_Aid_Declaration__c> {
            new gaid__Gift_Aid_Declaration__c (
                gaid__Date_Made__c = Date.today(),
                gaid__Active__c = true,
                gaid__Contact__c = booking.Primary_Contact__c,
                gaid__FirstName__c = booking.First_Name__c,
                gaid__LastName__c = booking.Last_Name__c,
                gaid__Postalcode__c = booking.Postcode__c,
                gaid__Housename_or_number__c = booking.Primary_Contact__r.MailingStreet,
                gaid__Acquisition_Method__c = ACQUISITION_METHOD,
                Method__c = METHOD
            ),
            new gaid__Gift_Aid_Declaration__c (
                gaid__Date_Made__c = Date.today(),
                gaid__Active__c = true,
                gaid__Contact__c = booking.Partner_Contact__c,
                gaid__FirstName__c = booking.First_Name_Partner__c,
                gaid__LastName__c = booking.Last_Name_Partner__c,
                gaid__Postalcode__c = booking.Postcode__c,
                gaid__Housename_or_number__c = booking.Primary_Contact__r.MailingStreet,
                gaid__Acquisition_Method__c = ACQUISITION_METHOD,
                Method__c = METHOD
            )
        };
        
        insertGiftAidDeclaration(jointGiftAidDeclarationList);
    }

    private static void insertGiftAidDeclaration(List<gaid__Gift_Aid_Declaration__c> giftAidDeclarationObject) {
        try {
            insert giftAidDeclarationObject;
        } catch (DmlException ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}