src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>First_Baby__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Baby</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Under_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Under 18</label>
        <type>Checkbox</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Birth_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Due_Date__c</fullName>
    <label>Birth due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Fee_Override__c.field-meta.xml
<CustomField>
    <fullName>Fee_Override__c</fullName>
    <label>Fee Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Fee_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fee_Override_Reason__c</fullName>
    <label>Fee Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No discount given</fullName>
            </value>
            <value>
                <fullName>Under 18</fullName>
            </value>
            <value>
                <fullName>Student (under 22)</fullName>
            </value>
            <value>
                <fullName>Income support</fullName>
            </value>
            <value>
                <fullName>Income based job seekers allowance</fullName>
            </value>
            <value>
                <fullName>Income related employment and support allowance</fullName>
            </value>
            <value>
                <fullName>Working tax credit</fullName>
            </value>
            <value>
                <fullName>Universal credit</fullName>
            </value>
            <value>
                <fullName>Household income &lt;£16.19k</fullName>
            </value>
            <value>
                <fullName>Household income &lt;£28.19k</fullName>
            </value>
            <value>
                <fullName>Booked after start of course</fullName>
            </value>
            <value>
                <fullName>Other - see notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/How_Heard__c.field-meta.xml
<CustomField>
    <fullName>How_Heard__c</fullName>
    <label>How Heard</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email from NCT</fullName>
            </value>
            <value>
                <fullName>NCT website or event</fullName>
            </value>
            <value>
                <fullName>Online advert</fullName>
            </value>
            <value>
                <fullName>Social media</fullName>
            </value>
            <value>
                <fullName>Newspaper or magazine</fullName>
            </value>
            <value>
                <fullName>Healthcare professional</fullName>
            </value>
            <value>
                <fullName>Previously attended NCT course</fullName>
            </value>
            <value>
                <fullName>Friends and family</fullName>
            </value>
            <value>
                <fullName>Don&#39;t remember</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Info_for_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Info_for_Practitioner__c</fullName>
    <label>Info for Practitioner</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Multiple_Birth__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Birth__c</fullName>
    <label>Multiple Birth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Partner  Contact)</relationshipLabel>
    <relationshipName>BookingToPartnerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Reservation_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Expiry_Date__c</fullName>
    <label>Reservation Expiry Date</label>
    <type>Date</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestBookingBuilder.cls
@IsTest
public class TestBookingBuilder {

    private Course__c course;
    private String status;
    private Contact primaryContact;
    private Contact partnerContact;
    private Date birthDueDate = System.today().addMonths(4);
    private String firstBaby = 'No';
    private String multipleBirth = 'No';
    private Date reservationExpiryDate;
    private String howHeard;
    private Decimal feeOverride;
    private String feeOverrideReason;
    private String infoForPractitioner = 'Test info';
    private Boolean under18 = false;
    private Boolean insertRecord = true;
    private Boolean ignoreDuplicateRules =  false;


    public TestBookingBuilder withCourse(Course__c course){
        this.course = course;
        return this;
    }

    public TestBookingBuilder withStatus(String status){
        this.status = status;
        return this;
    }

    public TestBookingBuilder withPrimaryContact(Contact contact){
        this.primaryContact = contact;
        return this;
    }

    public TestBookingBuilder withPartnerContact(Contact contact){
        this.partnerContact = contact;
        return this;
    }

    public TestBookingBuilder withBirthDueDate(Date birthDueDate){
        this.birthDueDate = birthDueDate;
        return this;
    }

    public TestBookingBuilder withFirstBaby(String firstBaby){
        this.firstBaby = firstBaby;
        return this;
    }

    public TestBookingBuilder withMultipleBirth(String multipleBirth){
        this.multipleBirth = multipleBirth;
        return this;
    }

    public TestBookingBuilder withBookingExpiryDate(Date expiryDate){
        this.reservationExpiryDate = expiryDate;
        return this;
    }

    public TestBookingBuilder withHowHeard(String howHeard){
        this.howHeard = howHeard;
        return this;
    }

    public TestBookingBuilder withFeeOverride(Decimal feeOverride){
        this.feeOverride = feeOverride;
        return this;
    }

    public TestBookingBuilder withFeeOverrideReason(String feeOverrideReason){
        this.feeOverrideReason = feeOverrideReason;
        return this;
    }

    public TestBookingBuilder withInfoForPractitioner(String infoForPactitioner){
        this.infoForPractitioner = infoForPractitioner;
        return this;
    }

    public TestBookingBuilder withUnder18(Boolean under18){
        this.under18 = under18;
        return this;
    }

    public TestBookingBuilder insertRecord(Boolean insertRecord){
        this.insertRecord = insertRecord;
        return this;
    }

    public TestBookingBuilder ignoreDuplicateRules(Boolean ignoreDuplicateRules) {
		this.ignoreDuplicateRules = true;
		return this;
	}

    public Booking__c build(){
        Booking__c booking = new Booking__c(
            Course__c = this.course.Id,
            Status__c = this.status,
            Primary_Contact__c = this.primaryContact.Id,
            Partner_Contact__c = this.partnerContact.Id,
            Birth_Due_Date__c = this.birthDueDate,
            First_Baby__c = this.firstBaby,
            Multiple_birth__c = this.multipleBirth,
            Reservation_Expiry_Date__c = this.reservationExpiryDate,
            How_Heard__c = this.howHeard,
            Fee_Override__c = this.feeOverride,
            Fee_Override_Reason__c = this.feeOverrideReason,
            Info_for_Practitioner__c = this.infoForPractitioner,
            Under_18__c = this.under18
        );
        if(ignoreDuplicateRules && insertRecord){
			Database.DMLOptions dmlOption = new Database.DMLOptions();
			dmlOption.DuplicateRuleHeader.AllowSave =  true;
			Database.insert(booking, dmlOption); 
			return booking;
		}
        if(this.insertRecord){
            insert booking;
        }
        return booking;

    }

}