src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Booking</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__BIC_Code__c</fullName>
        <description>The BIC code for the debitors bank.</description>
        <inlineHelpText>The BIC code for the debitors bank.</inlineHelpText>
        <label>BIC</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Holder_Name__c</fullName>
        <description>Name of the account/credit card holder.</description>
        <inlineHelpText>Name of the account/credit card holder.</inlineHelpText>
        <label>Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cpm__IBAN__c</fullName>
        <description>The bank account number in IBAN format.</description>
        <inlineHelpText>The bank account number in IBAN format.</inlineHelpText>
        <label>IBAN</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parentforce_Community_Settings__c/Parentforce_Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Parentforce Community Settings</label>
</CustomObject>

force-app/main/default/classes/StepOrangeHelper.cls
public class StepOrangeHelper {
    private static final String PAYER_CONTACT_UPDATE = 'none';
    private static final String PAYMENT_METHOD = 'Creditcard';
    private static final String SOURCE_CONNECTOR = 'PaymentHub-for-NPSP';
    private static final String SUCCESS_PAGE = Parentforce_Community_Settings__c.getOrgDefaults().Base_Url__c + 'success';
    private static final String ERROR_PAGE = Parentforce_Community_Settings__c.getOrgDefaults().Base_Url__c + 'error';
    private static final String API_TOKEN = Parentforce_Community_Settings__c.getOrgDefaults().API_Token__c;
    private static final String ORIGIN = 'BookingJourney';
    public static String getCardPaymentURL(Booking__c booking, Boolean isRecurring) {
        PaymentApiRequest paymentBody = createPaymentBody(booking, isRecurring);
        String installmentPayRequest = JSON.serialize(paymentBody, true);
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Step_Orange_Auth');
        req.setBody(installmentPayRequest);
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setHeader('api_token', API_TOKEN);
        req.setMethod('POST');
        req.setTimeout(120000);
        Http http = new Http();
        HttpResponse resp = http.send(req);
        system.debug('###getCardPaymentURL request' + JSON.serializePretty(paymentBody, true));
        cpm.API_Request_Response.PaymentPostRequest request = (cpm.API_Request_Response.PaymentPostRequest)JSON.deserializeStrict(resp.getBody(), cpm.API_Request_Response.PaymentPostRequest.class);
        return request.RedirectURL;
    }
    private static PaymentApiRequest createPaymentBody(Booking__c booking, Boolean isRecurring) {
        PaymentApiRequest.Contact contact = new PaymentApiRequest.Contact(booking.Primary_Contact__c);
        PaymentApiRequest.Payer payer = new PaymentApiRequest.Payer(contact, PAYER_CONTACT_UPDATE);
        PaymentApiRequest.Payment payment;
        PaymentApiRequest.PaymentMethod paymentMethod;
        PaymentApiRequest.Recurring recurring;
        if(isRecurring) {
            recurring = new PaymentApiRequest.Recurring('25', 'Monthly', '2099-12-01');
            //paymentMethod = new PaymentApiRequest.PaymentMethod(PAYMENT_METHOD, new Map<String, String>{'cpm__BIC_Code__c' => 'AEGONL2A', 'cpm__Holder_Name__c' => 'J. Smith', 'cpm__IBAN__c' => 'NL65AEGO0731729259'});
            cpm__Payment_Profile__c pProfile = [SELECT Id, cpm__BIC_Code__c, cpm__Holder_Name__c, cpm__IBAN__c FROM cpm__Payment_Profile__c WHERE cpm__Contact__c =: booking.Primary_Contact__c LIMIT 1];
            paymentMethod = new PaymentApiRequest.PaymentMethod(PAYMENT_METHOD, 
                new Map<String, String>{'cpm__BIC_Code__c' => pProfile.cpm__BIC_Code__c, 'cpm__Holder_Name__c' => pProfile.cpm__Holder_Name__c, 'cpm__IBAN__c' => pProfile.cpm__IBAN__c});
        } else {
            payment = new PaymentApiRequest.Payment(String.valueOf(booking.Course__r.Fee__c));
            paymentMethod = new PaymentApiRequest.PaymentMethod(PAYMENT_METHOD);
        }
        PaymentApiRequest.SourceConnector sourceConnector = new PaymentApiRequest.SourceConnector(SOURCE_CONNECTOR);
        PaymentApiRequest paymentBody = new PaymentApiRequest(SUCCESS_PAGE, ERROR_PAGE, ORIGIN, payer, payment, paymentMethod, recurring, sourceConnector);
        return paymentBody;
    }
}