src/objects/Booking__c.object
<CustomObject>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Birth_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Due_Date__c</fullName>
    <label>Birth due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Partner  Contact)</relationshipLabel>
    <relationshipName>BookingToPartnerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>BookingToPrimaryContact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Expected_Due_Date__c</fullName>
        <label>Expected Due Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/BOOKING_PopulateContactEDD_TDTM.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
//Incident #113 - https://confluence.nct.org.uk:8443/x/EoSO
global with sharing class BOOKING_PopulateContactEDD_TDTM extends npsp.TDTM_Runnable {
    @SuppressWarnings('PMD.ExcessiveParameterList')
    //Incident #114 - https://confluence.nct.org.uk:8443/x/EoSO
    global override npsp.TDTM_Runnable.DmlWrapper Run(List<SObject> triggerNew, List<SObject> triggerOld, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();

        List<Booking__c> newBookingList = (List<Booking__c>) triggerNew;
        List<Booking__c> oldBookingList = (List<Booking__c>) triggerOld;
        List<Contact> contactsToUpdate = new List<Contact>();
        
        if (triggerAction == npsp.TDTM_Runnable.Action.AfterInsert || triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
            contactsToUpdate.addAll(updateContactsExpectedDueDate(newBookingList, oldBookingList));
        }

        dmlWrapper.objectsToUpdate.addAll(contactsToUpdate);
        return dmlWrapper;
    }

    private List<Contact> updateContactsExpectedDueDate(List<Booking__c> newBookingList, List<Booking__c> oldBookingList) {
        Set<Id> contactIds = new Set<Id>();
        List<Contact> contactsToUpdate = new List<Contact>();
        Map<Id, Booking__c> oldBookingMap = new Map<Id, Booking__c>(oldBookingList);
        Map<Id, Date> contactsWithExpectedDueDates = new Map<Id, Date>();
        for (Booking__c booking : newBookingList) {
            if (!oldBookingMap.containsKey(booking.Id) || oldBookingMap.get(booking.Id).Birth_Due_Date__c != booking.Birth_Due_Date__c) {
                contactsWithExpectedDueDates.putAll(new Map<Id, Date>{
                    booking.Primary_Contact__c => booking.Birth_Due_Date__c,
                    booking.Partner_Contact__c => booking.Birth_Due_Date__c
                });
            }
        }

        for (Contact contact : [SELECT Expected_Due_Date__c FROM Contact WHERE Id IN :contactsWithExpectedDueDates.keySet() WITH SECURITY_ENFORCED]) {
            contact.Expected_Due_Date__c = contactsWithExpectedDueDates.get(contact.Id);
            contactsToUpdate.add(contact);
        }

        return contactsToUpdate;
    }
}