src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Enquiry - Parent has enquired about the course

Reserved - PSA has accepted the enquiry and reserves a place for the parent

Installment -  Parents are paying by installments as long as the first payment / deposit is made. 
In case of direct debits; as long as the direct debit is set up the status of booking shows confirmed even if the first payment is not taken

Paid - All the payments for the course have been paid.

Cancelled - Parent has cancelled their booking

Transferred - Parent has transferred the booking to different course

Lapsed - This is when the reserve by date for a booking has lapsed

Waiting - This is when parents are added onto a waiting list when their choice of course or the most suitable one is fully booked</description>
        <label>Booking Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Course Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Journey_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Booking_Journey_Payable_Amount__c</fullName>
    <label>Booking Journey Amount To Be Paid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Date__c</fullName>
    <label>Confirmed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Course_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Sub_Type__c</fullName>
    <formula>TEXT(  Course__r.Sub_Type__c  )</formula>
    <label>CourseSubType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Fee_Override__c.field-meta.xml
<CustomField>
    <fullName>Fee_Override__c</fullName>
    <label>Fee Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Next_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Collection_Date__c</fullName>
    <label>Next Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BookingPaymentDetailsController.cls
public without sharing class BookingPaymentDetailsController {
    public String bookingId { get; }
    public Booking__c booking { get; set; }

    public void setBookingId(String bookingId) {
        refreshBooking(bookingId);
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    //Incident #33 - https://confluence.nct.org.uk:8443/x/EoSO
    private void refreshBooking(Id bookingId) {
        booking = [
            SELECT Confirmed_Date__c, Course_Sub_Type__c, Status__c, Booking_Journey_Payable_Amount__c, Fee_Override__c, Next_Collection_Date__c
            FROM Booking__c
            WHERE Id = :bookingId 
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
}