src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__Bank_Account__c</fullName>
        <description>Pre-SEPA bank accounts. doesn&apos;t have the IBAN validation check.</description>
        <inlineHelpText>non IBAN bank account number. doesn&apos;t have the IBAN validation check.</inlineHelpText>
        <label>Bank Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Holder_Name__c</fullName>
        <description>Name of the account/credit card holder.</description>
        <inlineHelpText>Name of the account/credit card holder.</inlineHelpText>
        <label>Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paybacs__Sort_Code__c</fullName>
        <label>Sort Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPaymentProfileBuilder.cls
@isTest
public with sharing class TestPaymentProfileBuilder {

    private Contact primaryContact;
    private String sortCode;
    private String bankAccount;
    private String holderName;
    private Boolean insertRecord = false;

    public TestPaymentProfileBuilder withContact(Contact primaryContact)
    {
        this.primaryContact = primaryContact;
        return this;
    }

    public TestPaymentProfileBuilder withSortCode(String sortCode)
    {
        this.sortCode = sortCode;
        return this;
    }

    public TestPaymentProfileBuilder withBankAccount(String bankAccount)
    {
        this.bankAccount = bankAccount;
        return this;
    }

    public TestPaymentProfileBuilder withHolderName(String holderName)
    {
        this.holderName = holderName;
        return this;
    }

    public TestPaymentProfileBuilder insertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public cpm__Payment_Profile__c build()
    {
        cpm__Payment_Profile__c paymentProfile = new cpm__Payment_Profile__c(
            cpm__Contact__c = this.primaryContact.Id,
            paybacs__Sort_Code__c = this.sortCode,
            cpm__Bank_Account__c = this.bankAccount,
            cpm__Holder_Name__c = this.holderName
        );

        if(insertRecord)
        {
            insert paymentProfile;
        }

        return paymentProfile;
    }
}