src/objects/Contact.object
<CustomObject>
     <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>Intrabiz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
     <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>Intrabiz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Link__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Links</relationshipLabel>
        <relationshipName>Payment_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Link_Sent_Date__c</fullName>
        <label>Link Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Link_Status__c</fullName>
        <formula>IF((NOW() -  Link_Sent_Date__c ) &lt;= 20, &apos;Active&apos;, &apos;Expired&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Key__c</fullName>
        <label>Payment Key</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Link__c</fullName>
        <label>Payment Link</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Payment Link</label>
    <nameField>
        <displayFormat>PLE-{000000}</displayFormat>
        <label>Payment Link Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DirectPaymentLinkSendToParent.cls
public without sharing class DirectPaymentLinkSendToParent
{    
    
    public static Payment_Link__c paymentLink = new Payment_Link__c();
    @auraenabled
    public static void paymentHubCallout(Id contId)
    {     
        String redirectURL;

        paymentLink= [SELECT Id, Name, Contact__c,Contact__r.Email, Data_Source__c, Email__c, Link_Sent_Date__c, Link_Status__c, Payment_Key__c, Payment_Link__c, Contact_FirstName__c FROM Payment_Link__c where Contact__c =: contId limit 1];
        redirectURL = paymentLink.Payment_Link__c;
        sendPaymentLinkToParent(redirectURL, paymentLink);
     }
      public static void sendPaymentLinkToParent(string paymentLink, Payment_Link__c payLink)
      {   
        npe03__Recurring_Donation__c recurringdonationtwo;
        system.debug('*$*$* EMail Method was called   ' + paymentLink);
              if (!Schema.sObjectType.EmailTemplate.fields.Name.isAccessible()){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access'));
             }
        EmailTemplate emailTemplateId = [SELECT Id,Name,Subject, Body,HtmlValue FROM EmailTemplate WHERE Name ='NctMembershipPayment'];
        String emailBodyValue = emailTemplateId.HtmlValue;
        String emailSubjectValue = emailTemplateId.Subject;
        Messaging.SingleEmailMessage  mail = new Messaging.SingleEmailMessage ();
        emailBodyValue = emailBodyValue.replace('{!npe03__Recurring_Donation__c.First_Contact__c}',payLink.Contact_FirstName__c);
        emailBodyValue = emailBodyValue.replace('href=""', 'href="' + paymentLink +'"');
        system.debug('   *$*$* emailBodyValue   ' + emailBodyValue);
        mail.setHtmlBody(emailBodyValue);
        mail.setToAddresses(new String[] {payLink.Contact__r.Email});
        mail.setSubject(emailSubjectValue);
        Messaging.sendEmail(new Messaging.SingleEmailMessage [] {mail});  
       }

}