src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Care_Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Care_Error_Log__c</fullName>
    <label>CARE Error Log</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Care_Status__c.field-meta.xml
<CustomField>
    <fullName>Care_Status__c</fullName>
    <label>CARE Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Care_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Care_Error_Log__c</fullName>
    <label>CARE Error Log</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Membership_Added__c.field-meta.xml
<CustomField>
    <fullName>Care_Membership_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Care Membership Added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Status__c.field-meta.xml
<CustomField>
    <fullName>Care_Status__c</fullName>
    <label>CARE Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Care_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting</fullName>
        <default>true</default>
        <label>Waiting</label>
    </customValue>
    <masterLabel>Care Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddMembershipTest.cls
@isTest
public without sharing class AddMembershipTest {

    @testSetup static void createInstallment() {
        TestAccountBuilder accountBuilder = new TestAccountBuilder();
        Account account =  accountBuilder
            .withRecordType('Household Account')
            .insertRecord(true)
            .build();
        TestContactBuilder contactBuilder = new TestContactBuilder();
        Contact primaryContact = contactBuilder.withRecordType('Client')
            .withAccount(account)
            .withFirstName('John')
            .withLastName('Smith')
            .withRecordType('Client')
            .insertRecord(true)
            .build();
        TestPaymentProfileBuilder paymentProfileBuilder = new TestPaymentProfileBuilder();
        cpm__Payment_Profile__c paymentProfile = paymentProfileBuilder.withContact(primaryContact)
            .withSortCode('123456')
            .withBankAccount('1234567890')
            .withHolderName('John Smith')
            .insertRecord(true)
            .build();
        TestInstallmentBuilder installmentBuilder = new TestInstallmentBuilder();
        cpm__Installment__c installment = installmentBuilder.withPrimaryContact(primaryContact.Id)
            .withBankDetailsNumber('331257')
            .withPaymentProfile(paymentProfile.Id)
            .insertRecord(true)
            .build();
    }

    @isTest static void testAddMembershipBatch() {
        Test.startTest();
        CareRequestBodyUtil.MembershipOjbect membershipOjbect = new CareRequestBodyUtil.MembershipOjbect();
        membershipOjbect.status = 'Success';
        Test.setMock(HttpCalloutMock.class, new CareSendMembershipHttpResponseMock(JSON.serialize(membershipOjbect)));
        AddMembershipBatch camb = new AddMembershipBatch();
        Database.executeBatch(camb, 10);
        Test.stopTest();
        cpm__Installment__c installmentUpdated = [SELECT Care_Membership_Added__c, Care_Error_Log__c, Care_Status__c FROM cpm__Installment__c LIMIT 1];
        System.assertEquals(installmentUpdated.Care_Membership_Added__c, true);
        System.assertEquals(installmentUpdated.Care_Error_Log__c, null);
        System.assertEquals(installmentUpdated.Care_Status__c, 'Success');
    }

    @isTest static void testAddMembershipBatchError() {
        Test.startTest();
        CareRequestBodyUtil.MembershipOjbect membershipOjbect = new CareRequestBodyUtil.MembershipOjbect();
        membershipOjbect.status = 'Error';
        CareRequestBodyUtil.ErrorObject errorObject = new CareRequestBodyUtil.ErrorObject();
        errorObject.errorMessage = 'Error';
        errorObject.errorNumber = '400';
        membershipOjbect.error = new List<CareRequestBodyUtil.ErrorObject>();
        membershipOjbect.error.add(errorObject);
        Test.setMock(HttpCalloutMock.class, new CareSendMembershipHttpResponseMock(JSON.serialize(membershipOjbect)));
        AddMembershipBatch camb = new AddMembershipBatch();
        Database.executeBatch(camb, 10);
        Test.stopTest();
        cpm__Installment__c testInstallment = [SELECT Care_Membership_Added__c, Care_Error_Log__c FROM cpm__Installment__c LIMIT 1];
        System.assertEquals(testInstallment.Care_Membership_Added__c, false);
        System.assertEquals(testInstallment.Care_Error_Log__c, 'Error');
    }
}