src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Days (postnatal)</fullName>
                </value>
                <value>
                    <fullName>NCT Signature antenatal</fullName>
                </value>
                <value>
                    <fullName>NCT Baby Massage</fullName>
                </value>
                <value>
                    <fullName>NCT antenatal refresher</fullName>
                </value>
                <value>
                    <fullName>NCT Essentials antenatal</fullName>
                </value>
                <value>
                    <fullName>Twins and Multiples Workshop</fullName>
                </value>
                <value>
                    <fullName>Yoga for Pregnancy</fullName>
                </value>
                <value>
                    <fullName>Waterbirth</fullName>
                </value>
                <value>
                    <fullName>Introducing Solid Foods Workshop</fullName>
                </value>
                <value>
                    <fullName>NCT Parent</fullName>
                </value>
                <value>
                    <fullName>NCT Mother and Baby Yoga</fullName>
                </value>
                <value>
                    <fullName>Drop in</fullName>
                </value>
                <value>
                    <fullName>One to One</fullName>
                </value>
                <value>
                    <fullName>Combined Antenatal and Early Days (Postnatal)</fullName>
                </value>
                <value>
                    <fullName>Mantenatal</fullName>
                </value>
                <value>
                    <fullName>Birth and Beyond Antenatal</fullName>
                </value>
                <value>
                    <fullName>Early Pregnancy</fullName>
                </value>
                <value>
                    <fullName>Caesarean Workshop</fullName>
                </value>
                <value>
                    <fullName>Homebirth Workshop</fullName>
                </value>
                <value>
                    <fullName>Breathing and Relaxation</fullName>
                </value>
                <value>
                    <fullName>Breastfeeding – Antenatal</fullName>
                </value>
                <value>
                    <fullName>Breastfeeding – Postnatal</fullName>
                </value>
                <value>
                    <fullName>Relax, Stretch &amp; Breathe</fullName>
                </value>
                <value>
                    <fullName>Twins and Multiples</fullName>
                </value>
                <value>
                    <fullName>Introducing Solid Foods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Standard Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DisplayCourseDetailsControllerTest.cls
@isTest
private class DisplayCourseDetailsControllerTest {
	
	private final static String practitionerRecordTypeName = 'Practitioner';
	private static Contact practitioner;

	@isTest
	static void CourseQuery_WithValidCourseDataPresent_ReturnsCorrectData() {
		
		setupTestData();

		TestCourseBuilder courseBuilder = new TestCourseBuilder();
		Course__c course = courseBuilder.WithPractitioner(practitioner)
										.WithFee(200.00)
										.WithCourseType('NCT Signature')
										.InsertRecord(true)
										.Build();

		DisplayCourseDetailsController controller = new DisplayCourseDetailsController();
		controller.courseId = course.Id;

		Test.startTest();

		Course__c returnedCourse = controller.getCourse();

		Test.stopTest();

		System.assertEquals(200.00, returnedCourse.Fee__c);
		System.assertEquals('NCT Signature', returnedCourse.Course_Type__c);
	}

	private static void setupTestData()
	{
		TestContactbuilder practitionerContactBuilder = new TestContactbuilder();
		practitioner = practitionerContactBuilder.WithRecordType(practitionerRecordTypeName)
										.InsertRecord(true)
										.Build();
	}	
}