src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Is_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <formula>IF(NOT( ISBLANK(Purchase_Invoice__r.Zumzum__POP_Number__c) ), &#39;Your reference: &#39; + Purchase_Invoice__r.Zumzum__POP_Number__c + '. ', &#39;&#39;) +
&#39;Our reference: &#39; + Purchase_Invoice__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Unpaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Unpaid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Account__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Contact__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZumzumBACSremittanceEmailsBatch.cls
public class ZumzumBACSremittanceEmailsBatch implements Database.Batchable<Payment_Run_Line_Item__c> {
    
    private Id paymentRunId;
    private Id orgWideAddressId;
    private Id templateId;
    private String templateBody;
    
    public ZumzumBACSremittanceEmailsBatch(Id paymentRunId, Id templateId, Id orgWideAddressId) {
        this.paymentRunId = paymentRunId;
        this.templateId = templateId;
        this.orgWideAddressId = orgWideAddressId;
        this.templateBody = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Id =: templateId].HtmlValue;
    }
    
    public List<Payment_Run_Line_Item__c> start(Database.BatchableContext context) {
        return [
            SELECT Id, Name, Paid_Amount__c, Unpaid_Amount__c, Reference_Info__c,
                Purchase_Invoice__r.Zumzum__Contact__c, 
                Purchase_Invoice__r.Zumzum__Contact__r.Email, 
                Purchase_Invoice__r.Zumzum__Contact__r.FirstName,
                Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c
            FROM Payment_Run_Line_Item__c
            WHERE Payment_Run__c = :paymentRunId
            AND Is_Email_Sent__c = false
            AND (Purchase_Invoice__r.Zumzum__Contact__c != null OR Purchase_Invoice__r.Zumzum__Account__c != null)
        ];
    }
    
    public void execute(Database.BatchableContext context, List<Payment_Run_Line_Item__c> items) {
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        List<Payment_Run_Line_Item__c> itemsToUpdate = new List<Payment_Run_Line_Item__c>();
        for (Payment_Run_Line_Item__c prli : items) {
            if(prli.Purchase_Invoice__r.Zumzum__Contact__c != null) {
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                if(prli.Purchase_Invoice__r.Zumzum__Contact__r.Email != null) {
                    message.setTargetObjectId(prli.Purchase_Invoice__r.Zumzum__Contact__c);
                    message.setTemplateId(templateId);
                } else if(prli.Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c != null &&
                prli.Purchase_Invoice__r.Zumzum__Contact__r.FirstName != null &&
                prli.Paid_Amount__c != null &&
                prli.Reference_Info__c != null) {
                    message.setToAddresses(new List<String> {prli.Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c});
                    String mergedTemplateBody = templateBody
                        .replace('{!Contact.FirstName}', prli.Purchase_Invoice__r.Zumzum__Contact__r.FirstName)
                        .replace('{!Payment_Run_Line_Item__c.Paid_Amount__c}', String.valueOf(prli.Paid_Amount__c))
                        .replace('{!Payment_Run_Line_Item__c.Reference_Info__c}', prli.Reference_Info__c);
                    message.setHtmlBody(mergedTemplateBody);
                } else {
                    continue;
                }
                message.setWhatId(prli.Id);
                message.setOrgWideEmailAddressId(orgWideAddressId);
                messages.add(message);
                prli.Is_Email_Sent__c = true;
                if(prli.Purchase_Invoice__r.Zumzum__Contact__r.Email == null && prli.Purchase_Invoice__r.Zumzum__Account__r.Billing_Email__c != null) {
                    
                }
            }
        }
        update items;
        
        String error;

        Messaging.SendEmailResult[] emailResponse = Messaging.sendEmail(messages);
        System.debug('emailResponse is: ' + emailResponse);
    }
    
    public void finish(Database.BatchableContext context) {
        Payment_Run__c paymentRun = [
            SELECT Id, Status__c FROM Payment_Run__c 
            WHERE Id = :paymentRunId
        ];
        paymentRun.Status__c = 'Closed';
        update paymentRun;
    }
}