src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CareAddContactHandler.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
//Incident #14 - https://confluence.nct.org.uk:8443/x/EoSO
public with sharing class CareAddContactHandler {
    @InvocableMethod
    public static List<BookingJourneyInvocableResult> addContact(List<String> contactId) {
        try {
            Contact cont = [
                SELECT Id, FirstName, LastName, NCT_Number__c, Gender__c, MailingPostalCode, Email, MailingStreet, MailingCity, MailingCountry 
                FROM Contact 
                WHERE Id =: contactId
                WITH SECURITY_ENFORCED
            ];
            String contNumber = CareHelper.sendContact(cont);
            BookingJourneyInvocableResult result = new BookingJourneyInvocableResult();
            result.messageType = CareRequestBodyUtil.MESSAGE_TYPE_SUCCESS;
            result.messageText = contNumber;
            return new List<BookingJourneyInvocableResult> {result};
        } catch(Exception e) {
            BookingJourneyInvocableResult result = new BookingJourneyInvocableResult();
            result.messageType = CareRequestBodyUtil.MESSAGE_TYPE_ERROR;
            result.messageText = CareRequestBodyUtil.MESSAGE_TEXT_ERROR;
            return new List<BookingJourneyInvocableResult> {result};
        }
    }
    private class AddContactException extends Exception {}
}