src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Care_Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Care_Error_Log__c</fullName>
    <label>CARE Error Log</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Care_Status__c.field-meta.xml
<CustomField>
    <fullName>Care_Status__c</fullName>
    <label>CARE Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Care_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Individual.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual/fields/Has_Opted_In_Email__c.field-meta.xml
<CustomField>
    <fullName>Has_Opted_In_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Opted In Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Has_Opted_In_Post__c.field-meta.xml
<CustomField>
    <fullName>Has_Opted_In_Post__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Opted In Post</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Has_Opted_In_SMS__c.field-meta.xml
<CustomField>
    <fullName>Has_Opted_In_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Opted In SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Has_Opted_In_Telephone__c.field-meta.xml
<CustomField>
    <fullName>Has_Opted_In_Telephone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Opted In Telephone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Care_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting</fullName>
        <default>true</default>
        <label>Waiting</label>
    </customValue>
    <masterLabel>Care Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddMarketingPreferencesToCare.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
//Incident #64 - https://confluence.nct.org.uk:8443/x/EoSO
public without sharing class AddMarketingPreferencesToCare {

    private static final Map<String, String> MARKETING_PREFERENCES_DOCUMENT_MAP = new Map<String, String> {
        'Has_Opted_In_Email__c' => 'GDPR007',
        'Has_Opted_In_SMS__c' => 'GDPR008',
        'Has_Opted_In_Post__c' => 'GDPR009',
        'Has_Opted_In_Telephone__c' => 'GDPR010'
    };

    @InvocableMethod
    public static void addMarketingPreferencesAction(List<Params> paramInstance) {
        addMarketingPreferencesFuture(paramInstance[0].contactId);
    }

    public static List<MarketingPreferencesResult> addMarketingPreferencesForContact(Contact cont) {
        List<MarketingPreferencesResult> marketingPreferencesResultList = new List<MarketingPreferencesResult>();
        if(cont.NCT_Number__c != null && cont.Individual != null) {
            for(String individualField : MARKETING_PREFERENCES_DOCUMENT_MAP.keySet()) {
                CareHelper.MarketingPreferencesObject marketingPreferencesObject = CareHelper.sendMarketingPreferences(cont, MARKETING_PREFERENCES_DOCUMENT_MAP.get(individualField), (Boolean)cont.Individual.get(individualField));
                if(marketingPreferencesObject.error != null) {
                    marketingPreferencesResultList.add(new MarketingPreferencesResult(individualField, CareHelper.FAILURE_STATUS, marketingPreferencesObject.error[0].errorMessage));
                }
            }
        }
        return marketingPreferencesResultList;
    }

    public static String getErrorLog(List<AddMarketingPreferencesToCare.MarketingPreferencesResult> marketingPreferencesResultList) {
        String marketingPreferencesError = '';
        for(AddMarketingPreferencesToCare.MarketingPreferencesResult marketingPreferencesResult : marketingPreferencesResultList) {
            if(marketingPreferencesResult.status == CareHelper.FAILURE_STATUS) {
                marketingPreferencesError = marketingPreferencesError + marketingPreferencesResult.errorMessage + '\r\n\r\n';
            }
        }
        return marketingPreferencesError;
    }

    @future(callout=true)
    private static void addMarketingPreferencesFuture(Id contactId){
        List<Contact> contactList = [
            SELECT  Care_Error_Log__c,
                    Individual.Has_Opted_In_Email__c,
                    Individual.Has_Opted_In_Post__c,
                    Individual.Has_Opted_In_SMS__c,
                    Individual.Has_Opted_In_Telephone__c,
                    Nct_Number__c
            FROM Contact
            WHERE Id =: contactId
        ];
        if(!contactList.isEmpty()) {
            List<AddMarketingPreferencesToCare.MarketingPreferencesResult> marketingPreferencesResultList = addMarketingPreferencesForContact(contactList[0]);
            String marketingPreferencesError = AddMarketingPreferencesToCare.getErrorLog(marketingPreferencesResultList);
            if(marketingPreferencesError != '') {
                contactList[0].Care_Status__c = CareHelper.FAILURE_STATUS;
                contactList[0].Care_Error_Log__c = CareHelper.addErrorLog(marketingPreferencesError, contactList[0].Care_Error_Log__c);
                update contactList;
            }
        }
    }

    public class Params {
        @InvocableVariable public String contactId;
    }
    
    public class MarketingPreferencesResult {
        public String fieldName;
        public String status;
        public String errorMessage;
        public MarketingPreferencesResult(String fieldName, String status, String errorMessage) {
            this.fieldName = fieldName;
            this.status = status;
            this.errorMessage = errorMessage;
        }
    }
}