src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner_Licence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Practitioner_Licence__c.object
<CustomObject>
    <label>Practitioner Licence</label>
    <nameField>
        <label>Practitioner Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Licence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Licence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Venue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateRelatedSessionsFlowTest.cls
//@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #XX - https://confluence.nct.org.uk:8443/x/EoSO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@IsTest
private class UpdateRelatedSessionsFlowTest {

    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String ORGANIZATION_ACCOUNT_NAME = 'acc1';

    @TestSetup 
    private static void testSetup() {
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount(ORGANIZATION_ACCOUNT_NAME)
                    .createEnquiryPSA()
                    .buildBranchAccountWithEnquiryPSA()
                    .buildPractitioner(PRACTITIONER_LASTNAME)
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildSession();
    }

    @isTest
    static void UpdateSessionVenue_CourseMainVenueChanged_SessionVenueUpdated() {
        Course__c course = [
			SELECT Main_Venue__c
			FROM Course__c
			LIMIT 1
        ];

        Id oldMainVenue = course.Main_Venue__c;

        Session__c session = [
            SELECT Venue__c
            FROM Session__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        TestVenueBuilder venueBuilder = new TestVenueBuilder();
        Venue__c newVenue = venueBuilder
            .InsertRecord(true)
            .Build();

        Test.startTest();
        course.Main_Venue__c = newVenue.Id;
        update course;
        Test.stopTest();

        Session__c sessionToTest = [
            SELECT Venue__c
            FROM Session__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        Id newMainVenue = course.Main_Venue__c;

        System.assertEquals(oldMainVenue, session.Venue__c);
        System.assertEquals(newMainVenue, sessionToTest.Venue__c);
    }

    @isTest
    static void UpdateSessionPractitionerLicence_CourseMainPractitionerLicenceChanged_SessionLicenceUpdated() {
        Course__c course = [
			SELECT Main_Practitioner_Licence__c
			FROM Course__c
			LIMIT 1
        ];

        Id oldMainPractitionerLicence = course.Main_Practitioner_Licence__c;

        Session__c session = [
            SELECT Practitioner_Licence__c
            FROM Session__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        Contact practitioner = [
            SELECT Id, LastName
            FROM Contact
            WHERE LastName =:PRACTITIONER_LASTNAME
            LIMIT 1
        ];
        
        TestDataFactory.getInstance().buildLicenceToPractice(practitioner);

        Licence_To_Practice__c newLicence = [
            SELECT Id 
            FROM Licence_To_Practice__c 
            WHERE Id <> :course.Main_Practitioner_Licence__c
            LIMIT 1
        ];

        Test.startTest();
        course.Main_Practitioner_Licence__c = newLicence.Id;
        update course;
        Test.stopTest();

        Session__c sessionToTest = [
            SELECT Practitioner_Licence__c
            FROM Session__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        Id newMainPractitionerLicence = course.Main_Practitioner_Licence__c;

        System.assertEquals(oldMainPractitionerLicence, session.Practitioner_Licence__c);
        System.assertEquals(newMainPractitionerLicence, sessionToTest.Practitioner_Licence__c);
    }
}