src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practitioner?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Band__c/fields/Band__c.field-meta.xml
<CustomField>
    <fullName>Band__c</fullName>
    <label>Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practitioner_Band__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <label>Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Practitioner Bands</relationshipLabel>
    <relationshipName>Practitioner_Bands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Practitioner_Bands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A,</fullName>
    </customValue>
    <customValue>
        <fullName>B,</fullName>
    </customValue>
    <customValue>
        <fullName>C,</fullName>
    </customValue>
    <customValue>
        <fullName>D,</fullName>
    </customValue>
    <customValue>
        <fullName>ZERO</fullName>
    </customValue>
    <masterLabel>Practitioner Bands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPractitionerBandBuilder.cls
@isTest
public with sharing class TestPractitionerBandBuilder {
    private Boolean insertRecord = false;
    private Contact practitioner;
    private String band = 'A';
    private Integer daysBeforeToday = 50;
    private Date startDate = Date.today() - daysBeforeToday;
    private Date endDate = null;
    
    public TestPractitionerBandBuilder insertRecord(Boolean insertRecord) {
        this.insertRecord = insertRecord;
        return this;
    }

    public TestPractitionerBandBuilder withPractitionerContact(Contact practitioner) {
        this.practitioner = practitioner;
        return this;
    }

    public TestPractitionerBandBuilder withBand(String band) {
        this.band = band;
        return this;
    }

    public TestPractitionerBandBuilder withStartDate(Date startDate) {
        this.startDate = startDate;
        return this;
    }

    public TestPractitionerBandBuilder withEndDate(Date endDate) {
        this.endDate = endDate;
        return this;
    }

    public Practitioner_Band__c build(){
        Practitioner_Band__c testBand = new Practitioner_Band__c(
            Practitioner__c = this.practitioner.Id,
            Band__c = this.band,
            Start_Date__c = this.startDate,
            End_Date__c = this.endDate
        );

		if(insertRecord)
		{
			insert testBand;
		}

		return testBand;
    }
}