src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Bank_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Number__c</fullName>
    <description>This field is mapped from BankDetailsNumber (Care)</description>
    <externalId>true</externalId>
    <label>Bank Details Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Membership_Added__c.field-meta.xml
<CustomField>
    <fullName>Care_Membership_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Care Membership Added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>GiftAid</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Care Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/ga_decl_1__c.field-meta.xml
<CustomField>
    <fullName>ga_decl_1__c</fullName>
    <formula>IF (
AND ( NOT(ISNULL(cpm__Contact__c)), cpm__Contact__r.gaid__Active_Gift_Aid_Declarations__c &gt; 0 ),&#39;Y&#39;,&#39;N&#39;
)</formula>
    <label>Gift Aid Declaration 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/ga_decl_2__c.field-meta.xml
<CustomField>
    <fullName>ga_decl_2__c</fullName>
    <formula>IF (
AND ( NOT(ISNULL(Partner_Contact__c)), Partner_Contact__r.gaid__Active_Gift_Aid_Declarations__c &gt; 0 ), &#39;Y&#39;, &#39;N&#39;
)</formula>
    <label>Gift Aid Declaration 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Installments (Partner Contact)</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CareAddMembershipBatch.cls
global class CareAddMembershipBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id, ga_decl_1__c, ga_decl_2__c, Bank_Details_Number__c, cpm__Payment_Method__c, cpm__Contact__r.NCT_Number__c, Partner_Contact__r.NCT_Number__c, Membership_Type__c, cpm__Amount__c FROM cpm__Installment__c WHERE Care_Membership_Added__c = false AND Bank_Details_Number__c != null');
    }

    global void execute(Database.BatchableContext BC, List<cpm__Installment__c> scope){
        List<cpm__Installment__c> installmentUpdateList = new List<cpm__Installment__c>();
        for(cpm__Installment__c installment : scope) {
            List<MembershipResultObject> addMembershipResult = CareHelper.addMembership(installment);
            if(addMembershipResult[0].messageType != 'error') {
                installment.Care_Membership_Added__c = true;
                installmentUpdateList.add(installment);
            }
            system.debug(addMembershipResult);
        }
        update installmentUpdateList;
    }

   global void finish(Database.BatchableContext BC){
   }
}