src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practitioner?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Additional_information__c</fullName>
        <inlineHelpText>More information like drop in Category</inlineHelpText>
        <label>Additional information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <formula>IF(AND(Lunch_Break_Minutes__c != 0, !ISNULL(Lunch_Break_Minutes__c)), &#39; Includes a &#39; &amp; TEXT(Lunch_Break_Minutes__c) &amp; &#39; min break. &#39;, &#39; &#39;)
+ IF(OR( ISPICKVAL(Type__c, &#39;Reunion&#39;), ISPICKVAL(Type__c, &#39;Breastfeeding&#39;) ), TEXT(Type__c) &amp; &#39; session. &#39;, &#39; &#39;)
+ IF(ISPICKVAL(Specific_Attendee_Type__c, &#39;&#39;), &#39; &#39;, TEXT(Specific_Attendee_Type__c) &amp; &#39;. &#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Additional Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Contact_Hours__c.field-meta.xml
<CustomField>
    <fullName>Contact_Hours__c</fullName>
    <formula>(((End__c-Start__c)/60000) - Lunch_Break_Minutes__c )/60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_County__c.field-meta.xml
<CustomField>
    <fullName>Venue_County__c</fullName>
    <formula>IF( NOT( ISBLANK(Venue__c) ),
 IF( ISBLANK( Venue__r.Host__c ),
  Venue__r.County__c,
   Venue__r.Host__r.MailingState 
 ),
 Parent_Host__r.MailingState
)</formula>
    <label>Venue County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Name__c.field-meta.xml
<CustomField>
    <fullName>Venue_Name__c</fullName>
    <formula>IF( NOT( ISBLANK(Venue__c) ),
 IF( ISBLANK( Venue__r.Host__c ),
  Venue__r.Name,
  Venue__r.Host__r.FirstName + &#39; &#39; + Venue__r.Host__r.LastName + &quot;&#39;s home&quot;
 ),
 Parent_Host__r.FirstName + &#39; &#39; + Parent_Host__r.LastName + &quot;&#39;s home&quot;
)</formula>
    <label>Venue Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Venue_Postcode__c</fullName>
    <formula>IF( NOT( ISBLANK(Venue__c) ),
 IF( ISBLANK( Venue__r.Host__c ),
  Venue__r.Postcode__c,
  Venue__r.Host__r.MailingPostalCode
 ),
 Parent_Host__r.MailingPostalCode
)</formula>
    <label>Venue Postcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Street__c.field-meta.xml
<CustomField>
    <fullName>Venue_Street__c</fullName>
    <formula>IF( NOT( ISBLANK(Venue__c) ),
 IF( ISBLANK( Venue__r.Host__c ),
  Venue__r.Street_Address__c,
  Venue__r.Host__r.MailingStreet
 ),
 Parent_Host__r.MailingStreet
)</formula>
    <label>Venue Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Town__c.field-meta.xml
<CustomField>
    <fullName>Venue_Town__c</fullName>
    <formula>IF( NOT( ISBLANK(Venue__c) ),
 IF( ISBLANK( Venue__r.Host__c ),
  Venue__r.Town__c,
  Venue__r.Host__r.MailingCity
 ),
 Parent_Host__r.MailingCity
)</formula>
    <label>Venue Town</label>
    <type>Text</type>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfirmationEmailController.cls
public with sharing class ConfirmationEmailController {
    public List<LocationWrapper> locationListWrapper { get; set; }
    public List<SessionWrapper> sessionListWrapper { get; set; }
    public List<PractitionerWrapper> practitionerListWrapper{ get; set; }
    public SessionTypeWrapper sessionType { get; set; }
    public Course__c course { get; }
    private static String sessionDayTemplate = 'Session {0}';
    private static String sessionsTemplate = '(session{0} {1})';

    public void setCourse(Course__c course) {
        List<Session__c> sessionList = sessionFilterByStatus(getSessionsList(course.Id));
        getLocationWithSessionNumbers(sessionList);
        getPractitionerWithSessionNumbers(sessionList);
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    //Incident #11 - https://confluence.nct.org.uk:8443/x/EoSO
    public List<Session__c> getSessionsList(String courseId) {
        return  [
                SELECT  Date__c,
                        Start__c,
                        End__c,
                        Contact_Hours__c,
                        Additional_Information__c,
                        Status__c,
                        Type__c,
                        Venue_County__c,
                        Venue_Name__c,
                        Venue_Postcode__c,
                        Venue_Street__c,
                        Venue_Town__c,
                        Practitioner__c,
                        Practitioner__r.Name,
                        Practitioner__r.Phone,
                        Venue__c
                FROM Session__c
                WHERE Course__c = :courseId
                WITH SECURITY_ENFORCED
                ORDER BY Date__c, Start__c
        ];
    }

    private void getPractitionerWithSessionNumbers(List<Session__c> sessions){
        Map<Id, List<Integer>>  practitionerIdWithSessionNumbersMap = new Map<Id, List<Integer>>();
        Map<Id, Session__c> sessionMap = new Map<Id, Session__c>();
   
        for(Integer i = 0; i < sessions.size(); i++) {
            if(!practitionerIdWithSessionNumbersMap.containsKey(sessions[i].Practitioner__c)) {
                practitionerIdWithSessionNumbersMap.put(sessions[i].Practitioner__c, new List<Integer>());
            }
            practitionerIdWithSessionNumbersMap.get(sessions[i].Practitioner__c).add(i + 1);
            sessionMap.put(sessions[i].Practitioner__c, sessions[i]);
        }

        practitionerListWrapper = new List<PractitionerWrapper>();
        for (Session__c session : sessionMap.values()) {
            practitionerListWrapper.add(new PractitionerWrapper(session, practitionerIdWithSessionNumbersMap.get(session.Practitioner__c)));
        }
    }

    private void getLocationWithSessionNumbers(List<Session__c> sessions) {
        Map<Id, List<Integer>> venueIdWithSessionNumbersMap = new Map<Id, List<Integer>>();
        Map<Id, Session__c> sessionMap = new Map<Id, Session__c>();

        sessionListWrapper = new List<SessionWrapper>();
        for (Integer i = 0; i < sessions.size(); i++) {

            if (!venueIdWithSessionNumbersMap.containsKey(sessions[i].Venue__c)) {
                venueIdWithSessionNumbersMap.put(sessions[i].Venue__c, new List<Integer>());
            }
            
            venueIdWithSessionNumbersMap.get(sessions[i].Venue__c).add(i + 1);
            sessionMap.put(sessions[i].Venue__c, sessions[i]);
            sessionListWrapper.add(new SessionWrapper(sessions[i], i + 1));
        }

        locationListWrapper = new List<LocationWrapper>();
        for (Session__c session : sessionMap.values()) {
            locationListWrapper.add(new LocationWrapper(session, venueIdWithSessionNumbersMap.get(session.Venue__c)));
        }
    }

    private static String getNewFormatSessionTime(Time sessionTime) {
        Datetime sessionDateTime = Datetime.newInstance(Date.today(), sessionTime);
        return sessionDateTime.format('HH:mm');
    }

    private static String getFormattedSessionDaysList(List<Integer> sessionDays) {
        if (sessionDays.size() >= 3) {
            String days = String.join(sessionDays, ',');
            Integer index = days.lastIndexOf(',');
            return String.format(sessionsTemplate, new List<String> {
                    's', days.replace(days.substring(index - 1), days.substring(index - 1).replace(',', ' & '))
            });

        } else if (sessionDays.size() == 2) {
            return String.format(sessionsTemplate, new List<String> {
                    's', String.join(sessionDays, ',')
            });
        }

        return String.format(sessionsTemplate, new List<String>{
                '', String.join(sessionDays, '')
        });
    }

    private List<Session__c> sessionFilterByStatus(List<Session__c> sessions) {
        List<Session__c> newSessionFilterListByStatus = new List<Session__c>();
        sessionType = new SessionTypeWrapper();
        for (Session__c session : sessions) {
            if (session.Status__c != 'Provisional') {
                newSessionFilterListByStatus.add(session);

            } else if (session.Type__c == 'Standard') {
                sessionType.standardSession = new ProvisionTypeWrapper();
                sessionType.standardSession.provisionTime = String.valueOf(session.Contact_Hours__c);
                sessionType.standardSession.isSessionWithTypeProvisional = true;

            } else if (session.Type__c == 'Reunion') {
                sessionType.reunionSession = true;

            } else if (session.Type__c == 'Breastfeeding') {
                sessionType.breastfeedingSession = new ProvisionTypeWrapper();
                sessionType.breastfeedingSession.provisionTime = String.valueOf(session.Contact_Hours__c);
                sessionType.breastfeedingSession.isSessionWithTypeProvisional = true;
            }
        }

        return newSessionFilterListByStatus;
    }

    public class LocationWrapper {
        public Session__c locationOfSession {get; set;}
        public String sessionDays { get; set; }

        public LocationWrapper(Session__c session, List<Integer> sessionDays) {
            this.locationOfSession = session;
            this.sessionDays = getFormattedSessionDaysList(sessionDays);
        }
    }

    public class SessionWrapper {
        public String sessionDay { get; set; }
        public String sessionDate { get; set; }
        public String sessionStart { get; set; }
        public String sessionEnd { get; set; }
        public String sessionDescription { get; set; }

        public SessionWrapper(Session__c session, Integer sessionDay) {
            this.sessionDay = String.format(sessionDayTemplate, new List<String> {
                    String.valueOf(sessionDay)
            });
            this.sessionDate = String.valueOf(Datetime.newInstance(session.Date__c.year(), session.Date__c.month(), session.Date__c.day()).format('EEE dd MMM'));
            this.sessionStart = getNewFormatSessionTime(session.Start__c);
            this.sessionEnd = getNewFormatSessionTime(session.End__c);
            this.sessionDescription = session.Additional_Information__c;
        }
    }

    private class SessionTypeWrapper {
        public Boolean reunionSession { get; set; }
        public ProvisionTypeWrapper standardSession { get; set; }
        public ProvisionTypeWrapper breastfeedingSession { get; set; }
    }

    private class ProvisionTypeWrapper {
        public String provisionTime { get; set; }
        public Boolean isSessionWithTypeProvisional { get; set; }
    }

    private class PractitionerWrapper{
        public String name { get; set; }
        public String sessions { get; set; }
        public String preferPhone { get; set; }

        PractitionerWrapper(Session__c session, List<Integer> sessionDays){
        this.name = session.Practitioner__r.Name;
        this.sessions = getFormattedSessionDaysList(sessionDays);
        this.preferPhone = session.Practitioner__r.Phone;
        }
    }
}