src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>gaid__Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gaid__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Gift Aid Declarations</relationshipLabel>
        <relationshipName>Gift_Aid_Declarations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateGiftAidDeclarationHelperTest.cls
@IsTest
public with sharing class CreateGiftAidDeclarationHelperTest {

    @TestSetup
    static void makeData() {
        Account account = new Account(
            RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Household Account').getRecordTypeId(),
            Name = 'Lola Household'
        );

        insert account;

        TestContactBuilder contactBuilder = new TestContactBuilder();
        Contact primaryContact = contactBuilder.withRecordType('Client')
            .withAccount(account)
            .withFirstName('Lola')
            .withLastName('Primary')
            .insertRecord(true)
            .build();
    }

    @IsTest
    static void createGiftAidDeclaration_insertGiftAidDeclarationListWithOneRecord_returnOneRecord() {

        Contact cont = [SELECT Id FROM Contact LIMIT 1];

        List<gaid__Gift_Aid_Declaration__c> gadList = new List<gaid__Gift_Aid_Declaration__c>();

        gaid__Gift_Aid_Declaration__c gadInstance = new gaid__Gift_Aid_Declaration__c();
        gadInstance.Method__c = 'GiftAid';
        gadInstance.gaid__Acquisition_Method__c = 'Digital';
        gadInstance.gaid__Contact__c = cont.Id;

        gadList.add(gadInstance);

        Test.startTest();
            CreateGiftAidDeclarationHelper.CreateGiftAidDeclaration(new List<List<gaid__Gift_Aid_Declaration__c>>{gadList});
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM gaid__Gift_Aid_Declaration__c].size(), 'Return 1 record');

    }

    @IsTest
    static void createGiftAidDeclaration_insertEmptyGiftAidDeclarationList_returnEmptyList() {

        Contact cont = [SELECT Id FROM Contact LIMIT 1];

        List<gaid__Gift_Aid_Declaration__c> gadList = new List<gaid__Gift_Aid_Declaration__c>();

        gaid__Gift_Aid_Declaration__c gadInstance = new gaid__Gift_Aid_Declaration__c();

        Test.startTest();
            CreateGiftAidDeclarationHelper.CreateGiftAidDeclaration(new List<List<gaid__Gift_Aid_Declaration__c>>{gadList});
        Test.stopTest();

        System.assertEquals(0, [SELECT Id FROM gaid__Gift_Aid_Declaration__c].size(), 'Return empty list');

    }

}