src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Venue</relationshipLabel>
        <relationshipName>Venue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/Venue_Contact__c.object-meta.xml
<CustomObject>
    <label>Venue Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venue_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>Alternate Bookings</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Alternate Emergency</fullName>
            </value>
            <value>
                <fullName>Parent Host</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Venue Contacts</relationshipLabel>
    <relationshipName>Venue_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestVenueContactBuilder.cls
@isTest
public with sharing class TestVenueContactBuilder {

    private String name = 'TestVenueComtact';
    private String type = 'Emergency';
    private Venue__c venue;
	private Contact contact;
    private Boolean insertRecord = false;

    public TestVenueContactBuilder withName(String name) {

        this.name = name;

        return this;
    }

    public TestVenueContactBuilder withType(String type) {

        this.type = type;

        return this;
    }

    public TestVenueContactBuilder withContact(Contact contact)
	{
		this.contact = contact;
		return this;
	}


    public TestVenueContactBuilder withVenue(Venue__c venue)
	{
		this.venue = venue;
		return this;
	}


    public TestVenueContactBuilder insertRecord(Boolean insertRecord){
        this.insertRecord = insertRecord;
        return this;
    }

    public Venue_Contact__c build(){

        Venue_Contact__c testVenueContact = new Venue_Contact__c(
            Name = this.name,
            Type__c = this.type,
            Contact__c = this.contact.Id,
            Venue__c = this.venue.Id
        );

        if(this.insertRecord){
            insert testVenueContact;
        }

        return testVenueContact;
    }
}