src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Payment_Link__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Links</relationshipLabel>
        <relationshipName>Payment_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Payment_Link__c</fullName>
        <label>Payment Link</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Payment Link</label>
    <nameField>
        <displayFormat>PLE-{000000}</displayFormat>
        <label>Payment Link Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>IF( INCLUDES( Contact_Preference__c , &apos;Email&apos;) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DirectPaymentLinkSendToParentTest.cls
@isTest
private class DirectPaymentLinkSendToParentTest 
{
    @testSetup static void setup() {
        List<Contact> contact = new List<Contact>();
        for(Integer i=0;i<2;i++){
            contact.add(new Contact(
            LastName = 'NCT CHild'+i,
            FirstName = 'Childs'+i,
            Phone = '09876543212',
            Email = 'nctchild4555'+i+'@gmail.com'));
        }
        insert contact;
        System.debug('contact:'+contact);
        List<Payment_Link__c> paymentLink = new List<Payment_Link__c>();
        for(Integer j=0; j<2; j++){
            paymentLink.add(new Payment_Link__c(
                Contact__c = contact[j].id,
        		Email__c = 'nctchil@gmail.com'
            ));
        }
        insert paymentLink;
    }
    private static testMethod void directPaymentLinkTest()
    {
         List<Contact> cont =[SELECT Id,Email, Name FROM Contact where Phone = '09876543212'];
        List<Payment_Link__c> payment = [Select id,Email__c from Payment_Link__c where Email__c='nctchil@gmail.com'];
        DirectPaymentLinkSendToParent.paymentHubCallout(cont[0].Id);        
        
        system.assertEquals('nctchil@gmail.com', payment[0].Email__c);      
    } 
    private static testMethod void permissionCheck()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='Read Only'];
      	User u = new User(Alias = 'newUsers', Email='newusers@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newusers@testorg.com');

        List<Contact> cont =[SELECT Id,Email, Name FROM Contact where Phone = '09876543212'];
        List<Payment_Link__c> payment = [Select id,Email__c from Payment_Link__c where Email__c='nctchil@gmail.com'];
        System.runAs(u) {
            
            DirectPaymentLinkSendToParent.paymentHubCallout(cont[0].Id);
           
            system.assertEquals('nctchil@gmail.com', payment[0].Email__c);  
        }      
    } 

}