src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>Membership_Number__c</fullName>
        <displayFormat>M-{0}</displayFormat>
        <label>Membership Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MembershipStatusController.cls
public with sharing class MembershipStatusController {
	
    public String contId {get; set;}
    public npe03__Recurring_Donation__c recDonList {get; set;}
    
    public MembershipStatusController(){
        
        contId = ApexPages.currentPage().getParameters().get('Id');
	    System.debug('Contact Id: '+contId);  
        if(contId != '' || contId != null)
        {
            recDonList = [SELECT 
                              Id, 
                              Name,
                              npe03__Contact__c,
                      		  npe03__Contact__r.Email,
                       	      Membership_Number__c 
                      FROM 
                              npe03__Recurring_Donation__c
                      WHERE
                              npe03__Contact__c = :contId limit 1];
        	System.debug('recDonList: '+recDonList);
        }        
    }
}