src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Membership_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Membership Type</label>
    <pluralLabel>Membership Types</pluralLabel>
</CustomObject>

src/objects/PaymentAPISettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CLIENTID__c</fullName>
        <label>CLIENTID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLIENT_SECRET__c</fullName>
        <label>CLIENT_SECRET</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENDPOINTOAUTH__c</fullName>
        <label>ENDPOINTOAUTH</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENDPOINT_PASSWORD__c</fullName>
        <label>ENDPOINT_PASSWORD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENDPOINT_USERNAME__c</fullName>
        <label>ENDPOINT_USERNAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_INSTANCE__c</fullName>
        <label>SF_INSTANCE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment API Settings</label>
</CustomObject>

src/objects/PaymentHubApiSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Credit_Card_Payment_API_Token__c</fullName>
        <description>Token provided by StepOrange for credit card payment API</description>
        <label>Credit Card Payment API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status_Root_Url__c</fullName>
        <description>Root URL of site hosting success/failure pages for payment journey</description>
        <label>Payment Status Root Url</label>
        <type>Url</type>
    </fields>
    <label>Payment Hub API Settings</label>
</CustomObject>

src/classes/PaymentHubCalloutUtilities.cls
public without sharing class PaymentHubCalloutUtilities {
    
    
    private static PaymentHubApiSettings__c paymentHubApiSettings = PaymentHubApiSettings__c.getInstance();
    private static PaymentAPISettings__c paymentApiSettings = PaymentAPISettings__c.getInstance();
    
    public static String paymentHub(contact cont,Membership_Type__mdt membershipDetails, list<string> contactDetails){
        decimal instlmntAmt; 

        if(membershipDetails != null)
        {
           instlmntAmt = membershipDetails.Installment_Amount__c; 
        } 

        string responseContent;
        string redirectURL;
        
        HttpRequest tokenRequest = new HttpRequest();
        HttpResponse tokenResponse = new HttpResponse();
        Http tokenHttp = new Http();
        
        tokenRequest.setEndpoint(paymentApiSettings.ENDPOINTOAUTH__c+'client_id='+paymentApiSettings.CLIENTID__c+'&client_secret='+paymentApiSettings.CLIENT_SECRET__c+'&grant_type=password&username='+paymentApiSettings.ENDPOINT_USERNAME__c+'&password='+paymentApiSettings.ENDPOINT_PASSWORD__c);
        
        tokenRequest.setMethod('POST'); 
        tokenRequest.setTimeout(120000);    
        
        tokenResponse = tokenHttp.send(tokenRequest);

        AcessTokenResponseVo accessTokenVo = (AcessTokenResponseVo)JSON.deserialize(tokenResponse.getBody(),AcessTokenResponseVo.class);

        
        
        PaymentRequestVo paymentReq = new PaymentRequestVo();
        paymentReq.SuccessURL= paymentHubApiSettings.Payment_Status_Root_Url__c +'/nctPaymentHubSuccessMsgPage?contId='+ cont.Id;
        paymentReq.FailureURL= paymentHubApiSettings.Payment_Status_Root_Url__c +'/nctPaymentHubErrorMsgPage';
        paymentReq.Origin='test';
 
        PaymentRequestVo.ContactVo cvo = new PaymentRequestVo.ContactVo();
        if(cont != null)
        {
            cvo.Email = cont.Email;        
            cvo.FirstName = cont.FirstName;
            cvo.LastName = cont.LastName;
        }
        else if (cont == null)
        {
            cvo.Email = contactDetails[0];        
            cvo.FirstName = contactDetails[1];
            cvo.LastName = contactDetails[2];
        }
 
        PaymentRequestVo.PayerVo payerReq = new PaymentRequestVo.PayerVo();
        payerReq.AllowDeduplication=true;
        payerReq.contact = cvo;
        payerReq.ContactUpdate ='replace';
        paymentReq.Payer = payerReq;
 
        PaymentRequestVo.PaymentVo payment = new PaymentRequestVo.PaymentVo();
        if(cont!=null){       
            payment.Amount=instlmntAmt;
        }

        paymentReq.Payment = payment;
        PaymentRequestVo.PaymentMethodVo paymentMethod = new PaymentRequestVo.PaymentMethodVo();
        paymentMethod.Name='CreditCard';
        paymentReq.PaymentMethod = paymentMethod;
 
        PaymentRequestVo.SourceConnectorVo sourceConnector = new PaymentRequestVo.SourceConnectorVo();
        sourceConnector.Name='PaymentHub';
        paymentReq.SourceConnector = sourceConnector;
        
        HttpRequest paymentHubRequest = new HttpRequest();
        HttpResponse paymentHubResponse = new HttpResponse();
        Http paymentHubHttp = new Http(); 
        
        paymentHubRequest.setEndpoint(paymentApiSettings.SF_INSTANCE__c+'/services/apexrest/cpm/v1.0/Payment');
        paymentHubRequest.setHeader('Authorization','Bearer '+accessTokenVo.access_token);
        paymentHubRequest.setHeader('Content-Type','application/json; charset=UTF-8');
        paymentHubRequest.setHeader('api-token',paymentHubApiSettings.Credit_Card_Payment_API_Token__c);
        paymentHubRequest.setBody(JSON.serialize(paymentReq));
        paymentHubRequest.setMethod('POST'); 
        paymentHubRequest.setTimeout(120000);    
        paymentHubResponse = paymentHubHttp.send(paymentHubRequest);
        responseContent = paymentHubResponse.getBody();
        redirectURL = responseContent.subString(responseContent.IndexOf('PaymentHub')+28, responseContent.lastIndexOf('PaymentMethod')-3);
        redirectURL += '&nooverride=1';
        
        return redirectURL;
    }
}