src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Payment_Link__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Links</relationshipLabel>
        <relationshipName>Payment_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Link_Sent_Date__c</fullName>
        <label>Link Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Link_Status__c</fullName>
        <formula>IF((NOW() -  Link_Sent_Date__c ) &lt;= 20, &apos;Active&apos;, &apos;Expired&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Link__c</fullName>
        <label>Payment Link</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Payment Link</label>
    <nameField>
        <displayFormat>PLE-{000000}</displayFormat>
        <label>Payment Link Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentLinkProcessorControllerTest.cls
/**
*   @author: Mahanth Garlapati
*   @description: This is test class that covers code coverage to the 
*                 PaymentLinkProcessorController class.
**/

@isTest
private class PaymentLinkProcessorControllerTest {
	
	@testSetup static void setup() {
		List<Payment_Link__c> paymentLinkList = new List<Payment_Link__c>();
		List<Contact> contactList = new List<Contact>();

		for(Integer i = 0; i <= 30; i++){
			Contact cont = new Contact();
			cont.FirstName = 'Sony'+i;
			cont.LastName = 'Ericson'+i;
			cont.Email = 'sonyericson'+i+'@test.com';
			contactList.add(cont);
		}
		insert contactList;

		for(Integer i = 0; i <= 30; i++){
			Payment_Link__c paymentLink = new Payment_Link__c();
			paymentLink.Contact__c = contactList[i].Id;
			paymentLink.Email__c = contactList[i].Email;
			paymentLink.Link_Sent_Date__c = Date.today().addDays(-i);
			paymentLink.Payment_Link__c = 'https://cssdev4-mynct.cs100.force.com/apex/phstr__stripecheckout?failureRedirectURL=https%253A%252F%252Ftestdeploy-mynct.cs100.force.com%252FnctMembershipPaymentPage%252FnctPaymentHubErrorMsgPage&id=a2b1x0000004jJRAAY&successRedirectURL=https%253A%252F%252Ftestdeploy-mynct.cs100.force.com%252FnctMembershipPaymentPage%252FnctPaymentHubSuccessMsgPage%253FcontId%253D0031x000007rsQoAAI';
			paymentLinkList.add(paymentLink);
		}
		insert paymentLinkList;
	}
	
	@isTest static void testActivePaymentLink() {
		List<Payment_Link__c> paymentLinkList = [ 
                                                    SELECT 
                                                        Payment_Link__c,
                                                        Id,
                                                        Link_Status__c 
                                                    FROM 
                                                        Payment_Link__c 
                                                    WHERE 
                                                        Link_Status__c='Active' 
                                                ];
		Test.StartTest(); 
		ApexPages.currentPage().getParameters().put('paymentId', paymentLinkList[0].Id);
		PaymentLinkProcessorController paymentLinkProcessor = new PaymentLinkProcessorController();		
		PageReference pg = 	paymentLinkProcessor.redirect();
		Test.StopTest();
		System.assertNotEquals(null, pg);
		System.AssertEquals(pg.getUrl(), paymentLinkList[0].Payment_Link__c);										
	}
	
	@isTest static void testExpiredPaymentLink() {
		
				List<Payment_Link__c> paymentLinkList = [ 
                                                    		SELECT 
                                                        		Payment_Link__c,
                                                        		Id,
                                                        		Link_Status__c 
                                                    		FROM 
                                                        		Payment_Link__c 
                                                    		WHERE 
                                                        		Link_Status__c='Expired' 
                                                		];

		Test.StartTest(); 
		ApexPages.currentPage().getParameters().put('paymentId', paymentLinkList[0].Id); 
		PaymentLinkProcessorController paymentLinkProcessor = new PaymentLinkProcessorController();		
		PageReference pg = 	paymentLinkProcessor.redirect();
		Test.StopTest();
		System.assertEquals(null, pg);
										
	}
}