src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Prefered_First_Name__c</fullName>
        <label>Prefered First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Companion</fullName>
        <active>true</active>
        <description>A contact representing someone who will accompany a client on a course</description>
        <label>Companion</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Volunteer assigned to branches</description>
        <label>Volunteer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card(£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 10)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Membership_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                    <isActive>false</isActive>
                    <label>Practitioner</label>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                    <isActive>false</isActive>
                    <label>Volunteer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ET_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ET Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Gift_Aid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Gift Aid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>18 month membership</fullName>
                </value>
                <value>
                    <fullName>12 month membership</fullName>
                </value>
                <value>
                    <fullName>Reduced 12 month membership</fullName>
                </value>
                <value>
                    <fullName>4 year membership</fullName>
                </value>
                <value>
                    <fullName>10 year membership</fullName>
                </value>
                <value>
                    <fullName>Life Membership</fullName>
                </value>
                <value>
                    <fullName>Staff Membership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No. of Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card (£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£10)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£250)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£250)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£6.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Life Membership - Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recursive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recursive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Customer__c</fullName>
        <label>Target Customer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer/Practitioner</fullName>
                </value>
                <value>
                    <fullName>Parent on benefits</fullName>
                </value>
                <value>
                    <fullName>Staff only</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Parent, Companion</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Membership Type</label>
    <pluralLabel>Membership Types</pluralLabel>
</CustomObject>

src/objects/Practitioner_Licence__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Practitioner Licence</relationshipLabel>
        <relationshipName>Practitioner_Licence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>Expiry_Date__c  &gt;  TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Practitioner Licence</label>
    <nameField>
        <label>Practitioner Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Licence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MembershipUtilties.cls
/**
*   @author:  Mahanth Garlapati
*   @description: This class provides the utilities for membership functionality
*
*    19/11/2018 MG Initial Implementation
*    29/11/2018 MG W001166 - Added Method isPractitioner()
**/

public with sharing class MembershipUtilties {

 
    /**
    *   @contactType : This is contact type and can be Individual,Joint, Volunteer, Practitioner
    *   returns valid Memberships as map.
    *   @targetCustomer : This is a target customer and should have Parent, (Parent, Companion), Volunteer/Practitioner,
    *   Parent on benefits, Staff only --> Updated on 29/11/2018 added by ujwal
    *    
    **/
    public static Map<String, List<sObject>> getMembershipTypeMap(String contactType, String targetCustomer){

        Map<String, List<Membership_Type__mdt>> membershipTypeMap = new Map<String, List<Membership_Type__mdt>>();

        List<Membership_Type__mdt> membershipTypeList = [
                                                            SELECT 
                                                                Id, 
                                                                MasterLabel, 
                                                                Eligible_for_Gift_Aid__c, 
                                                                Installment_Amount__c, 
                                                                No_of_Installments__c,
                                                                Payment_Type__c, 
                                                                Payment_Method__c, 
                                                                Recursive__c, 
                                                                Total_Amount__c, 
                                                                Contact_Type__c,
                                                                Target_Customer__c, 
                                                                Membership__c 
                                                            FROM 
                                                                Membership_Type__mdt 
                                                            WHERE 
                                                                ET_Specific__c = false AND Contact_Type__c = :contactType AND Target_Customer__c = :targetCustomer
                                                        ];

        for (Membership_Type__mdt membershipType : membershipTypeList ){
            if (membershipTypeMap.get(membershipType.Membership__c) == null){
                List<Membership_Type__mdt> tempMembershipTypeList = new List<Membership_Type__mdt>();
                tempMembershipTypeList.add(membershipType);
                membershipTypeMap.put(membershipType.Membership__c,tempMembershipTypeList);
            }else{
                membershipTypeMap.get(membershipType.Membership__c).add(membershipType);
            }

        }
        return membershipTypeMap;   
    }

    //This method takes payment type value as parameters and returns mem
    public List<Membership_Type__mdt> paymentTypeMethod(String payType){

        List<Membership_Type__mdt> paymentType = [
                                                    SELECT 
                                                        MasterLabel, 
                                                        Eligible_for_Gift_Aid__c, 
                                                        Installment_Amount__c, 
                                                        No_of_Installments__c, 
                                                        Payment_Method__c, 
                                                        Recursive__c, 
                                                        Total_Amount__c 
                                                    FROM 
                                                        Membership_Type__mdt 
                                                    WHERE 
                                                        Payment_Method__c =: payType
                                                 ];

        return paymentType; 
    }
    
    /**
    *  This method validates the contact is Practitioner or not.    
    *  @firstName : This is the FirstName of the contact 
    *  @lastName  : This should the LastName of the contact
    *  @email     : This should be email value of the contact
    *  and returns the boolean value if contact has valid practitioner license. 
    *  Story:  W001166 
    */
    public static Boolean isPractitioner(String firstName, String lastName, String email){


        

        List<Contact> contactList  = [
                                        SELECT
                                            Id,
                                            Prefered_First_Name__c,
                                            LastName,
                                            Email,
                                            (
                                                SELECT
                                                    Id
                                                FROM
                                                    Practitioner_Licence__r
                                                WHERE
                                                    Is_Active__c = True
                                            )
                                        FROM
                                            Contact
                                        WHERE
                                            Prefered_First_Name__c = :firstName AND 
                                            LastName = :lastName AND
                                            Email = :email
                                    ];

            if(contactList.size()>0 && contactList[0].Practitioner_Licence__r != null && contactList[0].Practitioner_Licence__r.size() > 0){
                System.debug('Practitioner License is : '+contactList[0].Practitioner_Licence__r.size());
        		//if (contactList[0] != null ){//&& contactList[0].Practitioner_Licence__r != null && contactList[0].Practitioner_Licence__r.size() > 0){
                    return true;
                //}
            }
            

        return false;
    }

}