src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Branch)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
     <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>Intrabiz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prefered_First_Name__c</fullName>
        <label>Prefered First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/classes/MembershipConditionCheckUtilities.cls
public without sharing class MembershipConditionCheckUtilities {
        
    public static Boolean receiveInputPermissionCheck(){
        return !Schema.sObjectType.Contact.fields.Data_Source__c.isCreateable() && !Schema.sObjectType.Contact.fields.Data_Source__c.isAccessible();
    }
    public static Boolean receiveInputSecondContactPermissionCheck(Boolean twomems,Id primaryContactId,String secondContactFirstName){
        return twomems == true && primaryContactId != null && (secondContactFirstName != null || secondContactFirstName != '');      
    }
	public static boolean isNotExistingContactCheck(Boolean isContactExisting, Contact primaryContact){
    	return isContactExisting == false && primaryContact == null;
    }
    public static boolean isExistingContactCheck(Id contId, Boolean isContactExisting){
    	return contId != null || isContactExisting == true;
    }
    public static boolean dateFormatCheck(String eDate){
    	return eDate != null && eDate != '';
    }
   	public static boolean secondContactRequiredCheck(Boolean twomems,Id primaryContactId,String secondContactFirstName){
        if(receiveInputPermissionCheck()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,MembershipConstants.INSUFFICIENT_ACCESS));
        }
        List<Contact> contactList =[SELECT Id,Salutation,Gender__c,Parent_Contact__c,Branch__c, LastName, FirstName, Email,MailingStreet,MailingState,MailingCity, Phone,MailingPostalCode,Prefered_First_Name__c,AccountId FROM Contact WHERE Parent_Contact__c = :primaryContactId];
        if(!contactList.isEmpty()){
    	    return receiveInputSecondContactPermissionCheck(twomems,primaryContactId,secondContactFirstName) && contactList.isEmpty();
        }else{
            return receiveInputSecondContactPermissionCheck(twomems,primaryContactId,secondContactFirstName);
        }
    }
}