src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practitioner?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Band__c/fields/Band__c.field-meta.xml
<CustomField>
    <fullName>Band__c</fullName>
    <label>Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practitioner_Band__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <label>Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Practitioner Bands</relationshipLabel>
    <relationshipName>Practitioner_Bands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Practitioner_Fee_Rate__c/Practitioner_Fee_Rate__c.object-meta.xml
<CustomObject>
    <label>Practitioner Fee Rate</label>
    <nameField>
        <displayFormat>PF{000000}</displayFormat>
        <label>Practitioner Fee Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Fee Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Practitioner_Band__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Band__c</fullName>
    <label>Practitioner Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Fee_Rate__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Fee_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Fee Rate</label>
    <referenceTo>Practitioner_Fee_Rate__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Practitioner_Bands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A,</fullName>
    </customValue>
    <customValue>
        <fullName>B,</fullName>
    </customValue>
    <customValue>
        <fullName>C,</fullName>
    </customValue>
    <customValue>
        <fullName>D,</fullName>
    </customValue>
    <customValue>
        <fullName>ZERO</fullName>
    </customValue>
    <masterLabel>Practitioner Bands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PractitionerBandFeeHelperTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #27 - https://confluence.nct.org.uk:8443/x/EoSO
@isTest
public with sharing class PractitionerBandFeeHelperTest {

    private static final String PRACTITIONER_LAST_NAME = 'Smith';
    private static final String PRACTITIONER_RECORDTYPE_NAME = 'Practitioner';
    private static final String PRACTITIONER_PROMOTED_BAND ='B';
    private static final Date promotionDate = Date.today() + 7;

    @TestSetup
    private static void setupTestData(){
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .buildBranchAccount()
                    .buildPractitioner(PRACTITIONER_LAST_NAME)
                    .buildPractitionerFeeRateSet()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildSession();
                                                
    }
    @isTest
    private static void PractitionerHasExistingSession_GetsPromoted_SessionAfterPromotionGetsAssignedToNewRate(){
        Contact practitioner = getPractitioner();
        Practitioner_Band__c practitionerOriginalBand = getOriginalPractitionerBand(practitioner);

        Session__c sessionToMoveAfterPromotionDate = [SELECT    Id,
                                                                Practitioner_Fee_Rate__r.Practitioner_Band__c 
                                                            FROM Session__c 
                                                            WHERE Practitioner__c = :practitioner.Id 
                                                            LIMIT 1];

        sessionToMoveAfterPromotionDate.Date__c = promotionDate.addDays(5);
        update sessionToMoveAfterPromotionDate;

        test.startTest();

        practitionerOriginalBand.End_Date__c = promotionDate;
        update practitionerOriginalBand;

        Practitioner_Band__c practitionerNewBand = new Practitioner_Band__c(Start_Date__c = promotionDate,
                                                                                Band__c = PRACTITIONER_PROMOTED_BAND,
                                                                                Practitioner__c = practitioner.Id);

        insert practitionerNewBand;

        List<Practitioner_Band__c> bandsToProcess = new List<Practitioner_Band__c>{practitionerOriginalBand, practitionerNewBand};

        PractitionerBandFeeHelper.updateFeesOnAffectedSessions(bandsToProcess);                                                                            

        test.stopTest();

        Session__c sessionAfterPractitionerPromoted = [SELECT  Id,
                                                                Practitioner_Fee_Rate__r.Practitioner_Band__c 
                                                            FROM Session__c 
                                                            WHERE Practitioner__c = :practitioner.Id 
                                                            LIMIT 1];
        
        System.assertEquals(PRACTITIONER_PROMOTED_BAND, sessionAfterPractitionerPromoted.Practitioner_Fee_Rate__r.Practitioner_Band__c);

    }

    @isTest
    private static void PractitionerHasExistingSession_GetsFutureDatedPromotion_SessionRemainsOnExistingBand(){
        Contact practitioner = getPractitioner();
        Practitioner_Band__c practitionerOriginalBand = getOriginalPractitionerBand(practitioner);

        test.startTest();

        practitionerOriginalBand.End_Date__c = promotionDate;
        update practitionerOriginalBand;

        Practitioner_Band__c practitionerNewBand = new Practitioner_Band__c(Start_Date__c = promotionDate,
                                                                                Band__c = PRACTITIONER_PROMOTED_BAND,
                                                                                Practitioner__c = practitioner.Id);

        insert practitionerNewBand;  

        List<Practitioner_Band__c> bandsToProcess = new List<Practitioner_Band__c>{practitionerOriginalBand, practitionerNewBand};

        PractitionerBandFeeHelper.updateFeesOnAffectedSessions(bandsToProcess);                                                                                  

        test.stopTest();

        Session__c sessionAfterPractitionerPromoted = [SELECT  Id,
                                                                Practitioner_Fee_Rate__r.Practitioner_Band__c 
                                                            FROM Session__c 
                                                            WHERE Practitioner__c = :practitioner.Id 
                                                            LIMIT 1];
        
        System.assertEquals(practitionerOriginalBand.Band__c, sessionAfterPractitionerPromoted.Practitioner_Fee_Rate__r.Practitioner_Band__c);

    }
    @isTest
    private static void PractitionerHasExistingSession_ExistingBandRecordGetsBackEndDated_SessionGetsAssignedToNullRate(){
        Date bandEndDate = Date.today() - 50;
        Contact practitioner = getPractitioner();
        Practitioner_Band__c practitionerOriginalBand = getOriginalPractitionerBand(practitioner);

        test.startTest();

        practitionerOriginalBand.End_Date__c = bandEndDate;
        update practitionerOriginalBand;    

        List<Practitioner_Band__c> bandsToProcess = new List<Practitioner_Band__c>{practitionerOriginalBand};

        PractitionerBandFeeHelper.updateFeesOnAffectedSessions(bandsToProcess);                                                                              

        test.stopTest();

        Session__c sessionAfterPractitionerBandEnded = [SELECT  Id,
                                                                Practitioner_Fee_Rate__c 
                                                            FROM Session__c 
                                                            WHERE Practitioner__c = :practitioner.Id 
                                                            LIMIT 1];
        
        System.assertEquals(null, sessionAfterPractitionerBandEnded.Practitioner_Fee_Rate__c);

    }

    private static Contact getPractitioner(){
        return [SELECT Id
                    FROM Contact
                    WHERE RecordType.DeveloperName = :PRACTITIONER_RECORDTYPE_NAME
                        AND LastName = :PRACTITIONER_LAST_NAME
                    LIMIT 1];
    }

    private static Practitioner_Band__c getOriginalPractitionerBand(Contact practitioner){
        return [SELECT  Id,
                        Band__c,
                        Start_Date__c,
                        End_Date__c,
                        Practitioner__c
                    FROM Practitioner_Band__c
                    WHERE Practitioner__c = :practitioner.Id
                        AND Start_Date__c <= TODAY
                        AND End_Date__c = null
                    LIMIT 1];
    }
}