src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>gaid__Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gaid__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gaid__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Gift Aid Declarations</relationshipLabel>
        <relationshipName>Gift_Aid_Declarations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gaid__Housename_or_number__c</fullName>
        <label>House name or number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gaid__Postalcode__c</fullName>
        <label>Postal code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

force-app/main/default/objects/gaid__Gift_Aid_Declaration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestGiftAidDeclarationBuilder.cls
@isTest
public with sharing class TestGiftAidDeclarationBuilder {

    private Contact contact;
    private String acquisitionMethod = 'Digital';
    private String method = 'GiftAid';
    private String postalcode;
    private String housenameOrNumber;
    private Boolean active = false;
    private Boolean insertRecord = false;

    public TestGiftAidDeclarationBuilder withContact(Contact contactInstance) {
        this.contact = contactInstance;
        return this;
    }

    public TestGiftAidDeclarationBuilder withHousenameOrNumber(String housenameOrNumber) {
        this.housenameOrNumber = housenameOrNumber;
        return this;
    }

    public TestGiftAidDeclarationBuilder withMethod(String method) {
        this.method = method;
        return this;
    }

    public TestGiftAidDeclarationBuilder withActive(Boolean isActive) {
        this.active = isActive;
        return this;
    }

    public TestGiftAidDeclarationBuilder withaAcquisitionMethod(String acquisitionMethod) {
        this.acquisitionMethod = acquisitionMethod;
        return this;
    }

    public TestGiftAidDeclarationBuilder withaPostalcode(String postalcode) {
        this.postalcode = postalcode;
        return this;
    }

    public TestGiftAidDeclarationBuilder insertRecord(Boolean insertRecord) {
        this.insertRecord = insertRecord;
        return this;
    }

    public gaid__Gift_Aid_Declaration__c build() {
        gaid__Gift_Aid_Declaration__c giftAidDeclaration = new gaid__Gift_Aid_Declaration__c (
            gaid__Contact__c = this.contact.Id,
            Method__c = this.method,
            gaid__Active__c = this.active,
            gaid__Acquisition_Method__c = this.acquisitionMethod,
            gaid__Postalcode__c = contact.MailingPostalCode,
            gaid__Housename_or_number__c = contact.MailingStreet
        );

        if(insertRecord) {
            insert giftAidDeclaration;
        }

        return giftAidDeclaration;
    }

}