src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>CARE_Payment_Frequency__c</fullName>
        <label>CARE_Payment_Frequency</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Payment__c</fullName>
        <label>First Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_type__c</fullName>
        <label>Membership type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 year standard - Individual</fullName>
                </value>
                <value>
                    <fullName>1 year standard - Joint</fullName>
                </value>
                <value>
                    <fullName>18 month - Individual</fullName>
                </value>
                <value>
                    <fullName>18 month - Joint</fullName>
                </value>
                <value>
                    <fullName>4 year - Individual</fullName>
                </value>
                <value>
                    <fullName>4 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>Life Joint Membership</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Ind</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Individual</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Joint</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Individual</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Joint</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Ind</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Jnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>Sets the installment period for your recurring donations.  WARNING: Changing the Installment Period for an existing open-ended Recurring Donation can cause open Opportunities to be deleted and recreated. Any associated data may not be retained.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddToMembershipCompControllerTest.cls
@isTest
private class AddToMembershipCompControllerTest {
    @isTest
    private static void addToMembership(){
        contact cont = new contact();
        cont.LastName = 'NCT CHild';
        cont.Phone = '0987654321234';
        cont.Email = 'nctchild4555@gmail.com';
        insert cont;
        
        list<npe03__Recurring_Donation__c> recurrDonList = new list<npe03__Recurring_Donation__c>();
        for(Integer i=0;i<6;i++){
        npe03__Recurring_Donation__c recDon = new npe03__Recurring_Donation__c();
        recDon.Name = 'NCT Child';
        recDon.npe03__Amount__c = 10000;
        recDon.npe03__Installment_Period__c = 'Monthly';
        recDon.CARE_Payment_Frequency__c = 'NCT CHILD TRUST';
        recDon.First_Payment__c = system.today();
        recDon.First_Contact__c = cont.id; 
        recDon.Membership_Status__c = 'Confirmed'; 
        recDon.Membership_type__c = '18 month - Joint';
        recDon.npe03__Contact__c = cont.id;
        recurrDonList.add(recDon);  
        }
        insert recurrDonList;
        
        try{
        AddToMembershipCompController.addToMembershipValidation(cont.id);
        AddToMembershipCompController.recurrDonList = recurrDonList;
         system.assertEquals(1, recurrDonList.size());
        } catch (AuraHandledException e){
        }


    }

}