src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership_Number__c</fullName>
        <displayFormat>M-{0}</displayFormat>
        <label>Membership Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddToMembershipCompController.cls
public with sharing class AddToMembershipCompController {
    public static list<npe03__Recurring_Donation__c> recurrDonList{set;get;}
	@auraenabled    
    public static void addToMembershipValidation(Id contId){  
        system.debug('addToMembershipValidation : contId : '+contId);
        if (!Schema.sObjectType.npe03__Recurring_Donation__c.fields.Membership_Number__c.isAccessible()){
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Insufficient Access'));
        }
       recurrDonList = [select Id, Membership_Number__c,First_Contact__r.Email from npe03__Recurring_Donation__c where First_Contact__c =: contId];
        if(!recurrDonList.isEmpty()) {
            for(npe03__Recurring_Donation__c row : recurrDonList){
                system.debug('row.Membership_Number__c : '+row.Membership_Number__c);
            }
            AuraHandledException e = new AuraHandledException('You Cant Add Membership, hence already membership exists for this contact');
            e.setMessage('You Cant Add Membership, hence already membership exists for this contact');
            system.debug(e);
            throw e;
        }
      }
    }