src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Duration_Formatted__c</fullName>
        <formula>TEXT(FLOOR(Duration__c)) &amp; &apos; hours &apos; &amp; IF((Duration__c - FLOOR(Duration__c)) &gt; 0, &apos;and &apos; &amp; TEXT((Duration__c - FLOOR(Duration__c)) * 60) &amp; &apos; minutes&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration Formatted</label>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Duration_Formatted__c</fullName>
        <formula>TEXT(FLOOR(Duration__c)) &amp; &apos; hours &apos; &amp; IF((Duration__c - FLOOR(Duration__c)) &gt; 0, &apos;and &apos; &amp; TEXT((Duration__c - FLOOR(Duration__c)) * 60) &amp; &apos; minutes&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DisplayCourseSessionsControllerTest.cls
@isTest
private class DisplayCourseSessionsControllerTest {
	
	private static Course__c course;

	@isTest static void GetSessions_WhenValidSessionsExist_ReturnsListOfSessions() {
		
		setupTestData();

		Datetime initialStartTime = (Datetime.newInstance(2017, 3, 20, 18, 0, 0));

		TestSessionBuilder sessionBuilder = new TestSessionBuilder();
		sessionBuilder.WithCourse(course.Id)
					.WithStartTime(initialStartTime)
					.WithEndTime(initialStartTime.addHours(2))
					.InsertRecord(true).Build();

		sessionBuilder.WithCourse(course.Id)
					.WithStartTime(initialStartTime.addDays(7))
					.WithEndTime(initialStartTime.addDays(7).addHours(2).addMinutes(30))
					.InsertRecord(true).Build();

		DisplayCourseSessionsController controller = new DisplayCourseSessionsController();
		controller.courseId = course.Id;

		Test.startTest();

		List<Session__c> sessions = controller.getSessions();

		Test.stopTest();

		System.assertEquals(2, sessions.size());
		System.assertEquals('2 hours', sessions.get(0).Duration_Formatted__c);
		System.assertEquals(initialStartTime, sessions.get(0).Start__c);
		System.assertEquals('2 hours and 30 minutes', sessions.get(1).Duration_Formatted__c);
	}

	private static void setupTestData()
	{
		String practitionerRecordTypeName = 'Practitioner';

		TestContactbuilder practitionerContactBuilder = new TestContactbuilder();
		Contact practitioner = practitionerContactBuilder.WithRecordType(practitionerRecordTypeName)
										.InsertRecord(true)
										.Build();

		TestCourseBuilder courseBuilder = new TestCourseBuilder();
		course = courseBuilder.WithPractitioner(practitioner)
										.WithFee(200.00)
										.WithCourseType('NCT Signature')
										.InsertRecord(true)
										.Build();
	}
	
}