src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Practitioner</fullName>
        <active>true</active>
        <description>A contact representing a course practitioner</description>
        <label>Practitioner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Licence__c/Licence__c.object-meta.xml
<CustomObject>
    <label>Licence</label>
    <nameField>
        <label>Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Licences can only be applied to Practitioners.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licences To Practice</relationshipLabel>
    <relationshipName>Licences_To_Practice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <label>Licence</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Signature Antenatal Teacher</fullName>
            </value>
            <value>
                <fullName>Essentials Antenatal Teacher</fullName>
            </value>
            <value>
                <fullName>Breastfeeding Counsellor</fullName>
            </value>
            <value>
                <fullName>Postnatal Practitioner</fullName>
            </value>
            <value>
                <fullName>Baby Massage Practitioner</fullName>
            </value>
            <value>
                <fullName>Twins and Multiples</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Returning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLicenceToPracticeBuilder.cls
@isTest
public with sharing class TestLicenceToPracticeBuilder {

    private Contact contact;
    private Date startDate = Date.Today();
    private String status = 'Full';
    private String licence = 'Postnatal Practitioner';
    private Boolean insertRecord = false;

    public TestLicenceToPracticeBuilder withContact(Contact contact)
    {
        this.contact = contact;
        return this;
    }

    public TestLicenceToPracticeBuilder withStartDate(Date startDate)
    {
        this.startDate = startDate;
        return this;
    }

    public TestLicenceToPracticeBuilder withStatus(String status)
    {
        this.status = status;
        return this;
    }

    public TestLicenceToPracticeBuilder withLicence(String licence)
    {
        this.licence = licence;
        return this;
    }

    public TestLicenceToPracticeBuilder insertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public Licence_To_Practice__c build()
    {
        Licence_To_Practice__c licenceToPractice = new Licence_To_Practice__c(
            Contact__c = this.contact.Id,
            Start_Date__c = this.startDate,
            Status__c = this.status,
            Licence__c = this.licence
        );

        if(insertRecord)
        {
            insert licenceToPractice;
        }

        return licenceToPractice;
    }

}