src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CareAddContactBatch.cls
public class CareAddContactBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, FirstName, LastName, NCT_Number__c, Gender__c, Email, MailingPostalCode, MailingStreet, MailingCity, MailingCountry FROM Contact WHERE RecordType.Name = \'Client\' AND NCT_Number__c = null');
    }

    public void execute(Database.BatchableContext bc, List<Contact> scope){
        for(Contact cont : scope) {
            String contNumber = CareHelper.sendContact(cont);
        }
        CareHelper.updateContacts();
    }

   public void finish(Database.BatchableContext bc){
   }
}