src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Prefered_First_Name__c</fullName>
        <label>Prefered First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__Bank_Account__c</fullName>
        <description>Pre-SEPA bank accounts. doesn&apos;t have the IBAN validation check.</description>
        <inlineHelpText>non IBAN bank account number. doesn&apos;t have the IBAN validation check.</inlineHelpText>
        <label>Bank Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Holder_Name__c</fullName>
        <description>Name of the account/credit card holder.</description>
        <inlineHelpText>Name of the account/credit card holder.</inlineHelpText>
        <label>Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paybacs__Sort_Code__c</fullName>
        <label>Sort Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>gaid__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

src/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card(£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 10)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Membership_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                    <isActive>false</isActive>
                    <label>Practitioner</label>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                    <isActive>false</isActive>
                    <label>Volunteer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Gift_Aid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Gift Aid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GiftAid_Acquisition_Method__c</fullName>
        <label>GiftAid Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oral</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GiftAid_Type__c</fullName>
        <label>GiftAid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
                <value>
                    <fullName>99 Years</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <label>Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>18 month membership</fullName>
                </value>
                <value>
                    <fullName>12 month membership</fullName>
                </value>
                <value>
                    <fullName>Reduced 12 month membership</fullName>
                </value>
                <value>
                    <fullName>4 year membership</fullName>
                </value>
                <value>
                    <fullName>10 year membership</fullName>
                </value>
                <value>
                    <fullName>Life Membership</fullName>
                </value>
                <value>
                    <fullName>Staff Membership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No. of Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <label>Payment Processor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentHub-BACS</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-Stripe</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-WorldPay</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-GiftAid</fullName>
                    <isActive>false</isActive>
                    <label>PaymentHub-GiftAid</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Target__c</fullName>
        <label>Payment Target</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NCT Membership Collections - S18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card (£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£10)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£250)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£250)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£6.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Life Membership - Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recursive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recursive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Multiply By</fullName>
                    <default>true</default>
                    <label>Multiply By</label>
                </value>
                <value>
                    <fullName>Divide By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Customer__c</fullName>
        <label>Target Customer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer/Practitioner</fullName>
                </value>
                <value>
                    <fullName>Parent on benefits</fullName>
                </value>
                <value>
                    <fullName>Staff only</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Parent, Companion</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Membership Type</label>
    <pluralLabel>Membership Types</pluralLabel>
</CustomObject>

src/classes/MembershipCrudHelperTest.cls
@isTest
private class MembershipCrudHelperTest {
    private npe03__Recurring_Donation__c recDonation;
    @isTest
    private static void membershipCrudTest(){
        Membership_Type__mdt  membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c,
                                                No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,
                                                Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c, 
                                                GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt limit 1];
        
        npe03__Recurring_Donation__c recDonation = new npe03__Recurring_Donation__c();
        gaid__Gift_Aid_Declaration__c gftAid = new gaid__Gift_Aid_Declaration__c();
        String isGiftAid = 'true';
        account acct = new account();
        acct.name = 'account details';
        insert acct;
        
        contact con = new contact();
        con.FirstName = 'NCT Child';
        con.LastName = 'Trust';
        con.Email = 'nct@gmail.com';
        con.Prefered_First_Name__c = 'NCT';
        con.AccountId = acct.Id;
        insert con;
        
        Membership_Type__mdt  membershipInformation = new Membership_Type__mdt();
        
        
        cpm__Payment_Profile__c paymntProfl = new cpm__Payment_Profile__c();
        paymntProfl.cpm__Contact__c = con.id;
        paymntProfl.cpm__Bank_Account__c = 'NCT Bank';
        paymntProfl.cpm__Holder_Name__c  = 'NCT CHILD CUSTOMER';
        paymntProfl.paybacs__Sort_Code__c = 'CD-1234';
        insert paymntProfl;
        
        list<String> accountDetails = new list<String>{'145263777','Santhosh','CD-1234','Text','Enquiry by phone - main NCT'};
        MembershipCrudHelper memCrud = new MembershipCrudHelper();
 
        paymntProfl = memCrud.paymentProfile(accountDetails);
        system.assertEquals(accountDetails[2],paymntProfl.paybacs__Sort_Code__c);      
        
         gftAid = memCrud.giftAid(isGiftAid,membershipDetails,accountDetails);
         system.assertEquals(true,gftAid.gaid__Active__c);
        
        recDonation = memCrud.recDonation(membershipDetails,paymntProfl,accountDetails);
        system.assertEquals('confirmed',recDonation.Membership_Status__c);

    }  
}