src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Duration_Formatted__c</fullName>
        <formula>TEXT(FLOOR(Duration__c)) &amp; &apos; hours &apos; &amp; IF((Duration__c - FLOOR(Duration__c)) &gt; 0, &apos;and &apos; &amp; TEXT((Duration__c - FLOOR(Duration__c)) * 60) &amp; &apos; minutes&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>Based on start date</description>
        <formula>CASE( MOD(  DATEVALUE(End__c)  - DATE(1900, 1, 7), 7), 0, &quot;Sunday&quot;, 1, &quot;Monday&quot;, 2, &quot;Tuesday&quot;, 3,&quot;Wednesday&quot;, 4, &quot;Thursday&quot;, 5, &quot;Friday&quot;, 6, &quot;Saturday&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration_Formatted__c</fullName>
        <formula>TEXT(FLOOR(Duration__c)) &amp; &apos; hours &apos; &amp; IF((Duration__c - FLOOR(Duration__c)) &gt; 0, &apos;and &apos; &amp; TEXT((Duration__c - FLOOR(Duration__c)) * 60) &amp; &apos; minutes&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DisplayCourseSessionsController.cls
public with sharing class DisplayCourseSessionsController {

	public Id courseId { get; set; }

    public DisplayCourseSessionsController() {}

    public List<Session__c> getSessions() {

    	system.debug('Getting sessions for ' + courseId);
        return [SELECT Name, Day__c, Start__c, End__c, Notes__c, Duration_Formatted__c, Confirmed__c 
                FROM Session__c 
                WHERE Course__c = :courseId
                ORDER BY Start__c];

    }
}