src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Count_of_Sessions_Without_Fee_Rates__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Sessions_Without_Fee_Rates__c</fullName>
    <label>Count of Sessions Without Fee Rates</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/dlrs_SessionTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@SuppressWarnings('PMD.ClassNamingConventions')
//Incident #46 - https://confluence.nct.org.uk:8443/x/EoSO
@IsTest
private class dlrs_SessionTest
{

    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String PRACTITIONER_EMAIL_ADDRESS = 'partnerCommunityUser@ncttest.com';

    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_SessionTrigger to be invoked, fails the test if org config or other Apex code prevents this.

        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .buildBranchAccount()
                    .buildPractitioner(PRACTITIONER_LASTNAME, PRACTITIONER_EMAIL_ADDRESS)
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession()
                    .buildReunion();


        List<Session__c> sessions = [
            SELECT id
            FROM Session__c
        ];

        Test.startTest();
        for (Session__c session : sessions) {
            dlrs.RollupService.testHandler(session);
        }
        Test.stopTest();

        List<Course__c> courses = [
            SELECT Count_of_Sessions_Without_Fee_Rates__c  
            FROM Course__c
        ];

        System.assertEquals(2, courses[0].Count_of_Sessions_Without_Fee_Rates__c);

    }
}