src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Licence_To_Practice__c/Licence_To_Practice__c.object-meta.xml
<CustomObject>
    <label>Licence To Practice</label>
    <nameField>
        <label>Licence To Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences To Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence_To_Practice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Returning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Practitioner_Licence__c.object
<CustomObject>
    <label>Practitioner Licence</label>
    <nameField>
        <label>Practitioner Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Licence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Licence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.Venue__c</field>
            <operation>equals</operation>
            <valueField>$Source.Venue__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Specific_Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Specific_Attendee_Type__c</fullName>
    <label>Specific Attendee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>--None--</fullName>
                <default>true</default>
                <label>--None--</label>
            </value>
            <value>
                <fullName>Women Only</fullName>
            </value>
            <value>
                <fullName>Pregnant Women Only</fullName>
            </value>
            <value>
                <fullName>Birth Partners Only</fullName>
            </value>
            <value>
                <fullName>Birth Partners Welcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestSessionBuilder.cls
@isTest
public with sharing class TestSessionBuilder {

	private String name = 'testSession2';
	private String type = 'Standard';
	private Date sessionDate  = Date.today() + 5;
	private Time startTime = Time.newInstance(18, 30, 0, 0);
	private Time endTime = Time.newInstance(18, 30, 2, 20);
	private String specificAttendeeType = 'Women only';
	private String status = 'Confirmed';
	private Licence_To_Practice__c practitionerLicence;
	private Venue__c venue;
	private Course__c course;
	private Room__c room;
	private Boolean insertRecord = false;

	public TestSessionBuilder WithName(String name)
	{
		this.name = name;
		return this;
	}

	public TestSessionBuilder WithType(String type)
	{
		this.type = type;
		return this;
	}

	public TestSessionBuilder WithDate(Date sessionDate)
	{
		this.sessionDate = sessionDate;
		return this;
	}

	public TestSessionBuilder WithStartTime(Time startTime)
	{
		this.startTime = startTime;
		return this;
	}

	public TestSessionBuilder WithEndTime(Time endTime)
	{
		this.endTime = endTime;
		return this;
	}

	public TestSessionBuilder WithSpecificAttendeeType(String specificAttendeeType)
	{
		this.specificAttendeeType = specificAttendeeType;
		return this;
	}

	public TestSessionBuilder WithStatus(String status)
	{
		this.status = status;
		return this;
	}

	public TestSessionBuilder WithPractitionerLicence(Licence_To_Practice__c practitionerLicence)
	{
		this.practitionerLicence = practitionerLicence;
		return this;
	}

	public TestSessionBuilder WithVenue(Venue__c venue)
	{
		this.venue = venue;
		return this;
	}

	public TestSessionBuilder WithCourse(Course__c course)
	{
		this.course = course;
		return this;
	}

	public TestSessionBuilder WithRoom(Room__c room)
	{
		this.room = room;
		return this;
	}

	public TestSessionBuilder InsertRecord(Boolean insertRecord)
	{
		this.insertRecord = insertRecord;
		return this;
	}

	public Session__c Build()
	{
		Session__c session = new Session__c(
			Course__c = this.course.Id,
			Name = this.name,
			Type__c = this.type,
			Date__c = this.sessionDate,
			Start__c = this.startTime,
			End__c = this.endTime,
			Specific_Attendee_Type__c = this.specificAttendeeType,
			Practitioner_Licence__c = this.practitionerLicence.Id,
			Venue__c = this.venue.Id,
			Room__c = this.room.Id,
			Status__c = this.status
		);

		if(insertRecord)
		{
			insert session;
		}

		return session;
	}
}