src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSessionBuilder.cls
@isTest
public with sharing class TestSessionBuilder {
	
	private Id courseId;
	private Datetime startTime = system.now();
	private Datetime endTime = system.now().addHours(2);

	private Boolean insertRecord = false;

	public TestSessionBuilder() {}

	public TestSessionBuilder withCourse(Id courseId)
	{
		this.courseId = courseId;
		return this;
	}

	public TestSessionBuilder withStartTime(Datetime startTime)
	{
		this.startTime = startTime;
		return this;
	}

	public TestSessionBuilder withEndTime(Datetime endTime)
	{
		this.endTime = endTime;
		return this;
	}


	public TestSessionBuilder insertRecord(Boolean insertRecord)
	{
		this.insertRecord = insertRecord;
		return this;
	}


	public Session__c build()
	{
		Session__c session = new Session__c(Course__c = courseId,
											Start__c = startTime,
											End__c = endTime);

		if(insertRecord)
		{
			insert session;
		}

		return session;
	}
}