src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Venue</relationshipLabel>
        <relationshipName>Venue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Street_address__c.field-meta.xml
<CustomField>
    <fullName>Street_address__c</fullName>
    <label>Street address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>Town</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/Venue_Contact__c.object-meta.xml
<CustomObject>
    <label>Venue Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Venues</relationshipLabel>
    <relationshipName>Venue_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>Alternate Bookings</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Alternate Emergency</fullName>
            </value>
            <value>
                <fullName>Parent Host</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue_Contact__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Venue Contacts</relationshipLabel>
    <relationshipName>Venue_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VenueDetailsControllerTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #44 - https://confluence.nct.org.uk:8443/x/EoSO
@isTest
public with sharing class VenueDetailsControllerTest {

    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String HOST_EMAIL_ADDRESS = 'User@ncttest.com';
    private static final String HOST_LASTNAME = 'Black';

    @TestSetup
    private static void SetupTestData() {
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                .buildBranchAccount()
                .buildPractitioner(PRACTITIONER_LASTNAME)
                .buildPractitionerFeeRate()
                .buildVenue()
                .buildRoom()
                .buildLicenceToPractice()
                .buildCourse()
                .buildEstimatedCosts()
                .buildSession()
                .buildSessionWithTypeAndStatus('Reunion', 'Confirmed')
                .buildVenueContact();
    }

    @IsTest
    public static void getVenues_oneVenueCreated_componentShowsOneVenue() {

        Course__c course = [
                SELECT Id
                FROM Course__c
                LIMIT 1
        ];

        List<Venue__c> venues = [
                SELECT Name, Street_Address__c, Town__c, Postcode__c
                FROM Venue__c
                WHERE Id
                        IN (
                                SELECT Venue__c
                                FROM Session__c
                                WHERE Course__c = :course.Id
                        )
        ];

        VenueDetailsController.venueContactFieldSetName = 'CourseSummaryEmergencyContactFields';
        VenueDetailsController venueDetailsController = new VenueDetailsController();
        venueDetailsController.courseRecord = course;

        Test.startTest();

        List<VenueDetailsController.VenueResult> venuesToTest = venueDetailsController.getVenues();

        Test.stopTest();

        System.assertEquals(venuesToTest[0].venue.Id, venues[0].Id);
    }

    @IsTest
    public static void getVenues_componentLoadsOneVenue_correctEmergencyContactLoaded() {

        Course__c course = [
                SELECT Id
                FROM Course__c
                LIMIT 1
        ];

        List<Venue__c> venues = [
                SELECT Name, Street_Address__c, Town__c, Postcode__c
                FROM Venue__c
                WHERE Id
                        IN (
                                SELECT Venue__c
                                FROM Session__c
                                WHERE Course__c = :course.Id
                        )
        ];

        Set<Id> result = new Set<Id>();

        for (Venue_Contact__c venueCont : [
                SELECT Contact__c
                FROM Venue_Contact__c
                WHERE Venue__c = :venues[0].Id
                AND Type__c = 'Emergency'
                WITH SECURITY_ENFORCED
        ]) {
            result.add(venueCont.Contact__c);
        }

        List<Id> contactIds = new List<Id>(result);

        VenueDetailsController.venueContactFieldSetName = 'CourseSummaryEmergencyContactFields';
        VenueDetailsController venueDetailsController = new VenueDetailsController();
        venueDetailsController.courseRecord = course; 

        Test.startTest();

        List<VenueDetailsController.VenueResult> venuesToTest = venueDetailsController.getVenues();

        Test.stopTest();
        
        System.assertEquals(venuesToTest[0].emergencyContacts[0].Id, contactIds[0]);

    }
}