src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Group__c</fullName>
        <label>Target Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Break_Even_Number_Of_Places__c.field-meta.xml
<CustomField>
    <fullName>Break_Even_Number_Of_Places__c</fullName>
    <formula>IF( Include_Additional_Admin_Cost__c,MCEILING((Total_Estimated_Costs__c +( MCEILING(Total_Estimated_Costs__c/Course_Fee__c)*10))/Course_Fee__c),MCEILING(Total_Estimated_Costs__c/Course_Fee__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Break Even Number Of Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Confirmed_Places__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Places__c</fullName>
    <label>Confirmed Places</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Enquiries__c.field-meta.xml
<CustomField>
    <fullName>Enquiries__c</fullName>
    <label>Enquiries</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Enquiry</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Final_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Session_Date__c</fullName>
    <description>End Date field excludes reunions. This field does not.</description>
    <label>Final Session Date</label>
    <summarizedField>Session__c.Date__c</summarizedField>
    <summaryForeignKey>Session__c.Course__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Main_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Remaining_Places__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Places__c</fullName>
    <formula>Number_of_places__c - (Reserved_Places__c + Confirmed_Places__c + Enquiries__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Reserved_Places__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Places__c</fullName>
    <label>Reserved Places</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Reserved</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Course_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Course_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Early Days</fullName>
    </customValue>
    <customValue>
        <fullName>Introducing Solids</fullName>
    </customValue>
    <customValue>
        <fullName>Baby Massage</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Signature Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Essentials Antenatal</fullName>
    </customValue>
    <customValue>
        <fullName>NCT Antenatal Refresher</fullName>
    </customValue>
    <customValue>
        <fullName>Twins and Multiples</fullName>
    </customValue>
    <customValue>
        <fullName>Waterbirth</fullName>
    </customValue>
    <customValue>
        <fullName>One to One</fullName>
    </customValue>
    <masterLabel>Course Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateListViewUtility.cls
public with sharing class CreateListViewUtility {
    public static void createListsView(Map<String, Object> arguments) {

        String regExp = '[ -]+';
        String replacement = '_';

        for (String listViewName : (Set<String>)arguments.get('listViewNameSet')) {
            for (String psaAreaName : (Set<String>)arguments.get('psaAreaNameSet')) {
                HTTPRequest req = new HTTPRequest();
                req.setMethod('POST');
                req.setHeader('Content-Type', 'text/xml');
                req.setHeader('SOAPAction', 'create');

                List<String> bodyItems = new List<String>{
                    '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">',
                    '<soapenv:Header>',
                    '<ns1:SessionHeader soapenv:mustUnderstand="0" xmlns:ns1="http://soap.sforce.com/2006/04/metadata">',
                    '<ns1:sessionId>' + UserInfo.getSessionId() + '</ns1:sessionId>',
                    '</ns1:SessionHeader>',
                    '</soapenv:Header>',
                    '<soapenv:Body>',
                    '<create xmlns="http://soap.sforce.com/2006/04/metadata">',
                    '<metadata xsi:type="ns2:ListView" xmlns:ns2="http://soap.sforce.com/2006/04/metadata">',
                    '<fullName>' + (String)arguments.get('objectName') + '.X' + psaAreaName + '_' + listViewName.replaceAll(regExp, replacement) + '</fullName>',
                    '<columns>PSA_Area__c</columns>',
                    '<columns>NAME</columns>',
                    '<columns>Sub_Type__c</columns>',
                    '<columns>Branch__c</columns>',
                    '<columns>Start_Date__c</columns>',
                    '<columns>End_Date__c</columns>',
                    '<columns>Target_Group__c</columns>',
                    '<columns>Main_Practitioner__c</columns>',
                    '<columns>Status__c</columns>',
                    '<columns>Break_Even_Number_Of_Places__c</columns>',
                    '<columns>Confirmed_Places__c</columns>',
                    '<columns>Reserved_Places__c</columns>',
                    '<columns>Enquiries__c</columns>',
                    '<columns>Remaining_Places__c</columns>',
                    '<filterScope>Everything</filterScope>'
                };
                for (Map<String, String> criterionMap : ((Map<String, List<Map<String, String>>>)arguments.get('filterCriteriaMap')).get(listViewName)) {
                    bodyItems.addAll(new List<String>{
                        '<filters>',
                        '<field>' + criterionMap.get('field') + '</field>',
                        '<operation>' + criterionMap.get('operation') + '</operation>',
                        '<value>' + criterionMap.get('value') + '</value>',
                        '</filters>'
                    });
                }
                bodyItems.addAll(new List<String>{
                    '<filters>',
                    '<field>PSA_Area__c</field>',
                    '<operation>equals</operation>',
                    '<value>' + psaAreaName + '</value>',
                    '</filters>',
                    '<label>' + psaAreaName + ' - ' + listViewName + '</label>',
                    '<sharedTo>',
                    '<group>X' + psaAreaName + '_PSA_Area</group>',
                    '</sharedTo>',
                    '</metadata>',
                    '</create>',
                    '</soapenv:Body>',
                    '</soapenv:Envelope>'
                });

                String body = String.join(bodyItems, '');

                req.setBody(body);
                req.setCompressed(false);
                req.setEndpoint('https://parentforce--dev6.cs85.my.salesforce.com/services/Soap/m/48.0');
                HTTPResponse resp = (new HTTP()).send(req);
                System.debug(resp.getBody());
            }
        }
    }
}

/**************************************************************
Set this to org endpoint and add to the remote site settings:
Endpoint: 'YourInstance/services/Soap/m/48.0'
***************************************************************
Bear in mind 100 callouts limit from per transaction
Callouts number = PSA_Areas_Number x Lists_View_Number
***************************************************************
Examples of data structures for feeding:

Map<String, List<Map<String, String>>> filterCriteriaMap = new Map<String, List<Map<String, String>>>{
    'All' => new List<Map<String, String>>{
    },
    'Completed' => new List<Map<String, String>>{
        new Map<String, String>{
            'field' => 'Status__c',
            'operation' => 'equals',
            'value' => 'Final'
        },
        new Map<String, String>{
            'field' => 'End_Date__c',
            'operation' => 'lessThan',
            'value' => 'Today'
        }
    },
    'Complete - Reunion Not Taken Place' => new List<Map<String, String>>{
        new Map<String, String>{
            'field' => 'Status__c',
            'operation' => 'equals',
            'value' => 'Final'
        },
        new Map<String, String>{
            'field' => 'End_Date__c',
            'operation' => 'lessThan',
            'value' => 'TODAY'
        },
        new Map<String, String>{
            'field' => 'Final_Session_Date__c',
            'operation' => 'greaterOrEqual',
            'value' => 'TODAY'
        }
    },
    'Currently Running' => new List<Map<String, String>>{
        new Map<String, String>{
            'field' => 'Status__c',
            'operation' => 'equals',
            'value' => 'Final'
        },
        new Map<String, String>{
            'field' => 'Start_Date__c',
            'operation' => 'lessOrEqual',
            'value' => 'TODAY'
        },
        new Map<String, String>{
            'field' => 'End_Date__c',
            'operation' => 'greaterOrEqual',
            'value' => 'TODAY'
        }
    },
    'Not Started' => new List<Map<String, String>>{
        new Map<String, String>{
            'field' => 'Status__c',
            'operation' => 'equals',
            'value' => 'Draft,Final'
        },
        new Map<String, String>{
            'field' => 'Start_Date__c',
            'operation' => 'greaterOrEqual',
            'value' => 'TODAY'
        }
    }
};

Set<String> psaAreaNameSet = new Set<String>{
    '1C','1W',
	'2A','2B','2C',
	'3A','3B','3D','3E','3F',
	'4A','4B','4C','4D','4E','4F','4G','4H','4I','4J','4K','4L','4M','4N','4P','4Q','4R','4S',
	'5A','5B','5C','5D','5E','5F','5G','5H','5I','5J','5K','5L','5M','5N','5O','5R','5S','5T','5U','5VL',
	'6A','6B','6C','6D','6E',
	'7A','7B','7C'
};

Set<String> listViewNameSet = new Set<String>{
    'All',
    'Completed',
    'Complete - Reunion Not Taken Place',
    'Currently Running',
    'Not Started'
};               
    
String objectName = 'Course__c';

Map<String, Object> arguments = new Map<String, Object>{
    'psaAreaNameSet' => psaAreaNameSet,
    'listViewNameSet' => listViewNameSet,
    'filterCriteriaMap' => filterCriteriaMap,
    'objectName' => objectName
};
*/