src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Count_of_Estimated_Travel_Costs__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Estimated_Travel_Costs__c</fullName>
    <label>Count of Estimated Travel Costs</label>
    <summaryFilterItems>
        <field>Estimated_Costs__c.Type__c</field>
        <operation>equals</operation>
        <value>Travel</value>
    </summaryFilterItems>
    <summaryForeignKey>Estimated_Costs__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Count_of_Estimated_Venue_Costs__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Estimated_Venue_Costs__c</fullName>
    <label>Count of Estimated Venue Costs</label>
    <summaryFilterItems>
        <field>Estimated_Costs__c.Type__c</field>
        <operation>equals</operation>
        <value>Venue</value>
    </summaryFilterItems>
    <summaryForeignKey>Estimated_Costs__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Estimated_Travel_Costs__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Travel_Costs__c</fullName>
    <label>Estimated Travel Costs</label>
    <summaryFilterItems>
        <field>Estimated_Costs__c.Type__c</field>
        <operation>equals</operation>
        <value>Travel</value>
    </summaryFilterItems>
    <summaryForeignKey>Estimated_Costs__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Estimated_Venue_Costs__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Venue_Costs__c</fullName>
    <label>Estimated Venue Costs</label>
    <summaryFilterItems>
        <field>Estimated_Costs__c.Type__c</field>
        <operation>equals</operation>
        <value>Venue</value>
    </summaryFilterItems>
    <summaryForeignKey>Estimated_Costs__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/Estimated_Costs__c.object-meta.xml
<CustomObject>
    <label>Estimated Costs</label>
    <nameField>
        <displayFormat>EC{000000}</displayFormat>
        <label>Estimated Costs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimated_Costs__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Estimated Costs</relationshipLabel>
    <relationshipName>Estimated_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Practitioner Fee</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Estimated_Costs_Rollups_TDTM_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #133 - https://confluence.nct.org.uk:8443/x/EoSO

@IsTest
public with sharing class Estimated_Costs_Rollups_TDTM_Test {

    private static final String PRACTITIONER_LASTNAME = 'Smith';

    private static final Map<String, String> TRIGGER_PARAMS = new Map<String, String> {
        'triggerHandlerName' => 'Estimated_Costs_Rollups_TDTM',
        'className' => 'Estimated_Costs_Rollups_TDTM',
        'objectAPIName' => 'Estimated_Costs__c',
        'triggerActions' => 'AfterInsert;AfterUpdate;AfterDelete;AfterUndelete',
        'isActive' => 'true',
        'loadOrder' => '0',
        'isAsynchronous' => 'false'
    };

    @TestSetup
    private static void testSetup() {
        TestDataFactory.createTriggerSystemHandlerRecord(TRIGGER_PARAMS);

        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .buildBranchAccount()
                    .buildPractitioner(PRACTITIONER_LASTNAME)
                    .buildPractitionerFeeRate()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession();
    }

    @IsTest
    public static void EstimatedCostsCheckInserting_CreatedTwoEstimatedCostsRecords_CostsShouldBeEquals() {

        List<Course__c> courses = [
            SELECT Count_of_Estimated_Travel_Costs__c, Count_of_Estimated_Venue_Costs__c
            FROM Course__c
        ];

        System.assertEquals(1, courses[0].Count_of_Estimated_Travel_Costs__c, 'Should be equals 1');
        System.assertEquals(1, courses[0].Count_of_Estimated_Venue_Costs__c, 'Should be equals 1');
    }

    @IsTest
    public static void EstimatedCostsCheckUpdating_CreatedTwoEstimatedCostsRecordAndUpdate_CostsShouldBeEquals() {

        List<Course__c> coursesBeforeUpdate = [
            SELECT Estimated_Travel_Costs__c, Estimated_Venue_Costs__c
            FROM Course__c
        ];

        Estimated_Costs__c estimatedCostsTypeTravel = [
            SELECT Amount__c
            FROM Estimated_Costs__c
            WHERE Course__c = :coursesBeforeUpdate[0].Id AND Type__c = 'Travel'
        ];

        Estimated_Costs__c estimatedCostsTypeVenue = [
            SELECT Amount__c
            FROM Estimated_Costs__c
            WHERE Course__c = :coursesBeforeUpdate[0].Id AND Type__c = 'Venue'
        ];

        System.assertEquals(coursesBeforeUpdate[0].Estimated_Travel_Costs__c, estimatedCostsTypeTravel.Amount__c, 'Should be equals');
        System.assertEquals(coursesBeforeUpdate[0].Estimated_Venue_Costs__c, estimatedCostsTypeVenue.Amount__c, 'Should be equals');

        estimatedCostsTypeTravel.Amount__c = 200;
        estimatedCostsTypeVenue.Amount__c = 200;

        Test.startTest();
            update new List<Estimated_Costs__c> { estimatedCostsTypeTravel, estimatedCostsTypeVenue };
        Test.stopTest();

        List<Course__c> coursesAfterUpdate = [
            SELECT Estimated_Travel_Costs__c, Estimated_Venue_Costs__c
            FROM Course__c
        ];

        System.assertEquals(coursesAfterUpdate[0].Estimated_Travel_Costs__c, estimatedCostsTypeTravel.Amount__c, 'Should be equals');
        System.assertEquals(coursesAfterUpdate[0].Estimated_Venue_Costs__c, estimatedCostsTypeVenue.Amount__c, 'Should be equals');
    }

}