src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session_Practitioner__c.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Session Practitioner</relationshipLabel>
        <relationshipName>Session_Practitioner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Practitioner</relationshipLabel>
        <relationshipName>Session_Practitioner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Practitioner</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Practitioner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SESSION_ParentCourseSharing_TDTM.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
//Incident #150 - https://confluence.nct.org.uk:8443/x/EoSO
global with sharing class SESSION_ParentCourseSharing_TDTM extends npsp.TDTM_Runnable {  
    private static final String APEX_SHARING_REASON_SESSION_PRACTITIONER = 'Session_Practitioner__c';
    private static final String ACCESS_LEVEL_READ = 'Read';
    private Map<Id, Id> userIdsByPractitionerIds = new Map<Id,Id>();

    @SuppressWarnings('PMD.ExcessiveParameterList')
    //Incident #151 - https://confluence.nct.org.uk:8443/x/EoSO
    global override npsp.TDTM_Runnable.DmlWrapper Run(List<SObject> triggerNew, List<SObject> triggerOld, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();

        List<Session__c> newSessions = (List<Session__c>) triggerNew;
        List<Session__c> oldSessions = (List<Session__c>) triggerOld;
        List<Course__Share> courseSharesToInsert = new List<Course__Share>();
        List<Course__Share> courseSharesToDelete = new List<Course__Share>();
        Map<String, List<Session__c>> changedSessions = new Map<String, List<Session__c>>();

        if (triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {
            courseSharesToInsert.addAll(insertCourseSharesSessionInserted(newSessions));
        } else if (triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
            changedSessions = getChangedSessionsSessionUpdated(newSessions, oldSessions);
            courseSharesToInsert.addAll(insertCourseSharesSessionInserted(changedSessions.get('NewSessions')));
            courseSharesToDelete.addAll(deleteCourseSharesSessionDeleted(changedSessions.get('OldSessions')));
        } else if (triggerAction == npsp.TDTM_Runnable.Action.AfterDelete) {
            courseSharesToDelete.addAll(deleteCourseSharesSessionDeleted(oldSessions));
        }

        dmlWrapper.objectsToInsert.addAll(courseSharesToInsert);
        dmlWrapper.objectsToDelete.addAll(courseSharesToDelete);
        return dmlWrapper;
    }


    private List<Course__Share> insertCourseSharesSessionInserted(List<Session__c> newSessions) {
        List<Course__Share> courseSharesToInsert = new List<Course__Share>();
        Map<Id, Set<Id>> userIdsByCourseIds = getCoursesToShareWithUsers(newSessions);
        userIdsByCourseIds = removeUsersWithExistingCourseSharing(userIdsByCourseIds);
        courseSharesToInsert = createShareRecords(userIdsByCourseIds);
        return courseSharesToInsert;
    }


    private List<Course__Share> deleteCourseSharesSessionDeleted(List<Session__c> oldSessions) {
        List<Course__Share> courseSharesToDelete = new List<Course__Share>();
        Map<Id, Set<Id>> userIdsByCourseIds = getCoursesToShareWithUsers(oldSessions);
        courseSharesToDelete = getCourseSharesToDelete(userIdsByCourseIds, oldSessions);
        return courseSharesToDelete;
    }


    private  Map<String, List<Session__c>> getChangedSessionsSessionUpdated(List<Session__c> newSessions, List<Session__c> oldSessions) {
        Map<String, List<Session__c>> changedSessions = new Map<String, List<Session__c>>{
            'NewSessions' => new List<Session__c>(),
            'OldSessions' => new List<Session__c>()
        };
        Map<Id, Session__c> oldSessionsMap = new Map<Id, Session__c>(oldSessions);

        for (Session__c session : newSessions) {
            if (oldSessionsMap.get(session.Id).Practitioner__c != session.Practitioner__c) {
                changedSessions.get('NewSessions').add(session);
                changedSessions.get('OldSessions').add(oldSessionsMap.get(session.Id));
            }            
        }
        return changedSessions;
    }


    private Map<Id, Set<Id>> getCoursesToShareWithUsers(List<Session__c> sessionsToCheck) {
        Map<Id, Set<Id>> userIdsByCourseIds = new Map<Id, Set<Id>>();
        Set<Id> courseIds = new Set<Id>();
        Set<Id> practitionerIds = new Set<Id>();

        for (Session__c session : sessionsToCheck) {
            courseIds.add(session.Course__c);
            practitionerIds.add(session.Practitioner__c);
        }

        List<Course__c> coursesWithSessions = [
            SELECT Id, (
                SELECT Practitioner__c 
                FROM Sessions__r 
                WHERE Practitioner__c IN :practitionerIds
                )
            FROM Course__c
            WHERE Id IN :courseIds
                AND Main_Practitioner__c NOT IN :practitionerIds
            WITH SECURITY_ENFORCED
        ];

        userIdsByPractitionerIds = getPractitionersWithUserIds(practitionerIds);

        if (!userIdsByPractitionerIds.isEmpty()) {
            for (Course__c course : coursesWithSessions) {
                for (Session__c session : course.Sessions__r) {
                    if (userIdsByCourseIds.containsKey(course.Id)) {
                        userIdsByCourseIds.get(course.Id).add(userIdsByPractitionerIds.get(session.Practitioner__c));        
                    } else {
                        userIdsByCourseIds.put(course.Id, new Set<Id>{userIdsByPractitionerIds.get(session.Practitioner__c)});
                    } 
                }
            }
        }
        return userIdsByCourseIds;
    }


    private Map<Id, Id> getPractitionersWithUserIds(Set<Id> practitionerIds) {
        Map<Id, Id> userIdsByPractitionerIds = new Map<Id, Id>();
        List<User> usersWithContactIds = [
            SELECT ContactId
            FROM User
            WHERE ContactId IN :practitionerIds
            WITH SECURITY_ENFORCED
        ];

        for (User user : usersWithContactIds) {
            userIdsByPractitionerIds.put(user.ContactId, user.Id);
        }
        return userIdsByPractitionerIds;
    }


    private Map<Id, Set<Id>> removeUsersWithExistingCourseSharing(Map<Id, Set<Id>> userIdsByCourseIds) {
        Set<Id> userIds = new Set<Id>();

        for (Id courseId : userIdsByCourseIds.keySet()) {
            for (Id userId : userIdsByCourseIds.get(courseId)) {
                userIds.add(userId);
            }
        }

        for (Course__Share courseShare : [
            SELECT ParentId, UserOrGroupId
            FROM Course__Share
            WHERE ParentId IN :userIdsByCourseIds.keySet() 
                AND UserOrGroupId IN :userIds
            WITH SECURITY_ENFORCED
        ]) {
            if (userIdsByCourseIds.containsKey(courseShare.ParentId) && userIdsByCourseIds.get(courseShare.ParentId).contains(courseShare.UserOrGroupId)) {
                for (Id userId : userIdsByCourseIds.get(courseShare.ParentId)) {
                    if (userId == courseShare.UserOrGroupId) {
                        userIdsByCourseIds.get(courseShare.ParentId).remove(userId);
                        if (userIdsByCourseIds.get(courseShare.ParentId).isEmpty()) {
                            userIdsByCourseIds.remove(courseShare.ParentId);
                        }
                    }
                }
            }
        }
        return userIdsByCourseIds;
    }


    private List<Course__Share> createShareRecords(Map<Id, Set<Id>> userIdsByCourseIds) {
        List<Course__Share> courseSharesToInsert = new List<Course__Share>();

        for (Id courseId : userIdsByCourseIds.keySet()) {
            for (Id userId : userIdsByCourseIds.get(courseId)) {
                Course__Share courseShr = new Course__Share();
                courseShr.ParentId = courseId;
                courseShr.UserOrGroupId = userId;
                courseShr.AccessLevel = ACCESS_LEVEL_READ;
                courseShr.RowCause = APEX_SHARING_REASON_SESSION_PRACTITIONER;
                courseSharesToInsert.add(courseShr);
            }
        }
        return courseSharesToInsert;
    }


    @SuppressWarnings('PMD.ApexCRUDViolation')
    //Incident #152 - https://confluence.nct.org.uk:8443/x/EoSO
    private List<Course__Share> getCourseSharesToDelete(Map<Id, Set<Id>> userIdsByCourseIds, List<Session__c> sessionsToCheck) {
        Map<Id, Set<Id>> practitionerIdsByCourseIds = new Map<Id,Set<Id>>();
        
        for (Session__c session : sessionsToCheck) {
            if (practitionerIdsByCourseIds.containsKey(session.Course__c)) {
                practitionerIdsByCourseIds.get(session.Course__c).add(session.Practitioner__c);        
            } else {
                practitionerIdsByCourseIds.put(session.Course__c, new Set<Id>{session.Practitioner__c});
            } 
        }

        for (Id courseId : userIdsByCourseIds.keySet()) {
            for (Id userId : userIdsByCourseIds.get(courseId)) {
                for (Id practitionerId : practitionerIdsByCourseIds.get(courseId)) {
                    if (userIdsByPractitionerIds.get(practitionerId) == userId) {
                        userIdsByPractitionerIds.remove(practitionerId);
                    }
                }
            }
        }

        return [
            SELECT ParentId, UserOrGroupId 
            FROM Course__Share
            WHERE ParentId IN :practitionerIdsByCourseIds.keySet() 
                AND UserOrGroupId IN :userIdsByPractitionerIds.values()
            WITH SECURITY_ENFORCED
        ];
    }    
}