src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Practitioner_Licence__c.object
<CustomObject>
    <label>Practitioner Licence</label>
    <nameField>
        <label>Practitioner Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Licence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Lunch_Break_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Lunch_Break_Minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lunch Break Minutes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Practitioner_Licence__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Licence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Licence</label>
    <referenceTo>Licence_To_Practice__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SESSION_RevertCourseToDraft_TDTM.cls
global class SESSION_RevertCourseToDraft_TDTM extends npsp.TDTM_Runnable{
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> triggerNew, List<SObject> triggerOld, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();

        List<Session__c> newSessionList = (List<Session__c>)triggerNew;
        List<Session__c> oldSessionList = (List<Session__c>) triggerOld;
        List<Course__c> courseToUpdate = new List<Course__c>();

        Set<Id> courseIds = new Set<Id>();

        if (triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {
            for(Session__c aSession : newSessionList) {
                courseIds.add(aSession.Course__c);
            }
        } else if (triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
            for(Integer i = 0; i<newSessionList.size(); i++) {
                if (newSessionList[i].Date__c != oldSessionList[i].Date__c ||
                    newSessionList[i].Start__c != oldSessionList[i].Start__c ||
                    newSessionList[i].End__c != oldSessionList[i].End__c ||
                    newSessionList[i].Lunch_Break_Minutes__c != oldSessionList[i].Lunch_Break_Minutes__c ||
                    newSessionList[i].Practitioner_Licence__c != oldSessionList[i].Practitioner_Licence__c ||
                    newSessionList[i].Venue__c != oldSessionList[i].Venue__c) {
                    courseIds.add(newSessionList[i].Course__c);
                }
            }
        } else if (triggerAction == npsp.TDTM_Runnable.Action.afterDelete) {
            for(Session__c aSession : oldSessionList){
                courseIds.add(aSession.Course__c);
            }
        }

        for(Course__c aCourse : [SELECT Id, Status__c FROM Course__c WHERE Id IN :courseIds]){
            aCourse.Status__c = 'Draft';
            courseToUpdate.add(aCourse);
        }
        dmlWrapper.objectsToUpdate.addAll((List<Course__c>)courseToUpdate);
        return dmlWrapper;
    }
}