src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/Estimated_Costs__c.object-meta.xml
<CustomObject>
    <label>Estimated Costs</label>
    <nameField>
        <displayFormat>EC{000000}</displayFormat>
        <label>Estimated Costs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimated_Costs__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Estimated Costs</relationshipLabel>
    <relationshipName>Estimated_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimated_Costs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Practitioner Fee</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestEstimatedCostsBuilder.cls
public with sharing class TestEstimatedCostsBuilder {

    private String type = 'Travel';
    private Course__c course;
    private Integer amount = 100;
    private Boolean insertRecord = false;

    public TestEstimatedCostsBuilder WithType(String type)
    {
        this.type = type;
        return this;
    }

    public TestEstimatedCostsBuilder WithCourse(Course__c course)
    {
        this.course = course;
        return this;
    }

    public TestEstimatedCostsBuilder WithAmount(Integer amount)
    {
        this.amount = amount;
        return this;
    }

    public TestEstimatedCostsBuilder InsertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public Estimated_Costs__c Build()
    {
        Estimated_Costs__c estimatedCosts = new Estimated_Costs__c(
            Type__c = this.type,
            Course__c = this.course.Id,
            Amount__c = this.amount
        );

        if(insertRecord)
        {
            insert estimatedCosts;
        }

        return estimatedCosts;
    }
}