src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Course</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Venue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Street_address__c.field-meta.xml
<CustomField>
    <fullName>Street_address__c</fullName>
    <label>Street address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>Town</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VenueDetailsController.cls
public without sharing class VenueDetailsController {

    public Course__c courseRecord {get; set;}


    public class VenueResult {
        public String name {get; set;}
        public Boolean isMainVenue {get; set;}
        public String address {get; set;}

        public VenueResult(Venue__c venue, Course__c courseRecord) {
            this.name = venue.Name;
            this.isMainVenue = (venue.Id == courseRecord.Main_venue__c);
            this.address = venue.Street_Address__c + ', ' + venue.Town__c + ', ' + venue.Postcode__c;
        }
    }

    public Course__c getCourseMainVenue() {
        return [
                SELECT Main_venue__c
                FROM Course__c
                WHERE Id = :courseRecord.Id
        ];
    } 
    

    public List<VenueResult> getVenues() {

        List<VenueResult> result = new List<VenueResult>();

        courseRecord = getCourseMainVenue();

        for (Venue__c venue : [
            SELECT Name, Street_Address__c, Town__c, Postcode__c 
            FROM Venue__c 
            WHERE Id 
                IN (SELECT Venue__c 
                    FROM Session__c 
                    WHERE Course__c = :courseRecord.Id)
            WITH SECURITY_ENFORCED
        ]) {
            result.add(new VenueResult(venue, courseRecord));            
        }

        return result;

        /*return [
            SELECT Name, Street_Address__c, Postcode__c 
            FROM Venue__c 
            WHERE Id 
                IN (SELECT Venue__c 
                    FROM Session__c 
                    WHERE Course__c = :courseRecord.Id)
            WITH SECURITY_ENFORCED
        ];*/
    }
}