src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Group__c</fullName>
        <label>Target Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Break_Even_Number_Of_Places__c.field-meta.xml
<CustomField>
    <fullName>Break_Even_Number_Of_Places__c</fullName>
    <formula>IF( Include_Additional_Admin_Cost__c,MCEILING((Total_Estimated_Costs__c +( MCEILING(Total_Estimated_Costs__c/Course_Fee__c)*10))/Course_Fee__c),MCEILING(Total_Estimated_Costs__c/Course_Fee__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Break Even Number Of Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Confirmed_Places__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Places__c</fullName>
    <label>Confirmed Places</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Enquiries__c.field-meta.xml
<CustomField>
    <fullName>Enquiries__c</fullName>
    <label>Enquiries</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Enquiry</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Final_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Session_Date__c</fullName>
    <description>End Date field excludes reunions. This field does not.</description>
    <label>Final Session Date</label>
    <summarizedField>Session__c.Date__c</summarizedField>
    <summaryForeignKey>Session__c.Course__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Main_Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Main_Practitioner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/PSA_Area__c.field-meta.xml
<CustomField>
    <fullName>PSA_Area__c</fullName>
    <formula>TEXT(Branch__r.PSA_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PSA Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Remaining_Places__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Places__c</fullName>
    <formula>Number_of_places__c - (Reserved_Places__c + Confirmed_Places__c + Enquiries__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Reserved_Places__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Places__c</fullName>
    <label>Reserved Places</label>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Reserved</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CreateListViewUtilityTest.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #85 - https://confluence.nct.org.uk:8443/x/EoSO
@IsTest
private class CreateListViewUtilityTest {
    private static final Map<String, List<Map<String, String>>> FILTER_CRITERIA_MAP = new Map<String, List<Map<String, String>>>{
        'All' => new List<Map<String, String>>{
            new Map<String, String>{
                'field' => 'PSA_Area__c',
                'operation' => 'equals',
                'value' => 'psaAreaName'
            }
        },
        'Completed' => new List<Map<String, String>>{
            new Map<String, String>{
                'field' => 'Status__c',
                'operation' => 'equals',
                'value' => 'Final'
            },
            new Map<String, String>{
                'field' => 'End_Date__c',
                'operation' => 'lessThan',
                'value' => 'Today'
            },
            new Map<String, String>{
                'field' => 'PSA_Area__c',
                'operation' => 'equals',
                'value' => 'psaAreaName'
            }
        },
        'Complete - Reunion Not Taken Place' => new List<Map<String, String>>{
            new Map<String, String>{
                'field' => 'Status__c',
                'operation' => 'equals',
                'value' => 'Final'
            },
            new Map<String, String>{
                'field' => 'End_Date__c',
                'operation' => 'lessThan',
                'value' => 'TODAY'
            },
            new Map<String, String>{
                'field' => 'Final_Session_Date__c',
                'operation' => 'greaterOrEqual',
                'value' => 'TODAY'
            },
            new Map<String, String>{
                'field' => 'PSA_Area__c',
                'operation' => 'equals',
                'value' => 'psaAreaName'
            }
        },
        'Currently Running' => new List<Map<String, String>>{
            new Map<String, String>{
                'field' => 'Status__c',
                'operation' => 'equals',
                'value' => 'Final'
            },
            new Map<String, String>{
                'field' => 'Start_Date__c',
                'operation' => 'lessOrEqual',
                'value' => 'TODAY'
            },
            new Map<String, String>{
                'field' => 'End_Date__c',
                'operation' => 'greaterOrEqual',
                'value' => 'TODAY'
            },
            new Map<String, String>{
                'field' => 'PSA_Area__c',
                'operation' => 'equals',
                'value' => 'psaAreaName'
            }
        },
        'Not Started' => new List<Map<String, String>>{
            new Map<String, String>{
                'field' => 'Status__c',
                'operation' => 'equals',
                'value' => 'Draft,Final'
            },
            new Map<String, String>{
                'field' => 'Start_Date__c',
                'operation' => 'greaterOrEqual',
                'value' => 'TODAY'
            },
            new Map<String, String>{
                'field' => 'PSA_Area__c',
                'operation' => 'equals',
                'value' => 'psaAreaName'
            }
        }
    };

    private static final Map<String, String> FILTER_LOGIC_MAP = new Map<String, String>{
        'Completed' => '1 AND (2 OR 3)'
    };

    private static final Set<String> PSA_AREA_NAME_SET = new Set<String>{
        '1C','1W',
        '2A','2B','2C',
        '3A','3B','3D',
        '4A','4B','4C',
        '5A','5B','5C',
        '6A','6B','6C',
        '7A','7B','7C'
    };

    private static final Set<String> LIST_VIEW_NAME_SET = new Set<String>{
        'All',
        'Completed',
        'Complete - Reunion Not Taken Place',
        'Currently Running',
        'Not Started'
    };

    private static final Set<String> COLUMN_NAME_SET = new Set<String>{
        'PSA_Area__c',
        'Completed',
        'Branch__c',
        'Start_Date__c',
        'End_Date__c',
        'Target_Group__c',
        'Main_Practitioner__c',
        'Status__c',
        'Break_Even_Number_Of_Places__c',
        'Confirmed_Places__c',
        'Reserved_Places__c',
        'Enquiries__c',
        'Remaining_Places__c'
    };
    
    private static final String OBJECT_NAME = 'Course__c';

    private static final Map<String, Object> ARGUMENTS = new Map<String, Object>{
        'psaAreaNameSet' => PSA_AREA_NAME_SET,
        'listViewNameSet' => LIST_VIEW_NAME_SET,
        'filterCriteriaMap' => FILTER_CRITERIA_MAP,
        'filterLogicMap' => FILTER_LOGIC_MAP,
        'columnNameSet' => COLUMN_NAME_SET,
        'objectName' => OBJECT_NAME
    };

    @IsTest
    private static void CreateListsViewForPSAAreas_ListsViewCreated(){
        Test.setMock(HttpCalloutMock.class, new CreateListViewUtilityMock());
        Boolean hasError = false;

        Test.startTest();
        try{
            CreateListViewUtility.createListViews(ARGUMENTS);
        }catch(Exception e){
            hasError = true;
        }
        Test.stopTest();

        System.assert(!hasError);
    }
}