src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low bookings - 0 bookings</fullName>
                </value>
                <value>
                    <fullName>Low bookings - 1 booking</fullName>
                </value>
                <value>
                    <fullName>Low bookings - 2 bookings</fullName>
                </value>
                <value>
                    <fullName>Low bookings - 3 bookings</fullName>
                </value>
                <value>
                    <fullName>Low bookings - 4 or more bookings</fullName>
                </value>
                <value>
                    <fullName>Low bookings - client not happy with small group size</fullName>
                </value>
                <value>
                    <fullName>Practitioner on time out - no replacement available</fullName>
                </value>
                <value>
                    <fullName>Practitioner resigned - no replacement available</fullName>
                </value>
                <value>
                    <fullName>Practitioner withdrew - no LtP</fullName>
                </value>
                <value>
                    <fullName>Practitioner withdrew - other</fullName>
                </value>
                <value>
                    <fullName>Newly Qualified practitioner withdrew - no LtP</fullName>
                </value>
                <value>
                    <fullName>Newly Qualified practitioner withdrew - other</fullName>
                </value>
                <value>
                    <fullName>Over capacity</fullName>
                </value>
                <value>
                    <fullName>Service withdrawn</fullName>
                </value>
                <value>
                    <fullName>Course added in error</fullName>
                </value>
                <value>
                    <fullName>Private sessions cancelled by client</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft - Course setup is in progress
Confirmed - Course setup completed, can be shared with Website and start accepting bookings.
In Progress - Course has been started by practitioner, hence no changes to PSA assignment allowed
Completed - All the session of course have been completed by the practitioner.
Closed - PSA is happy to close the course
Cancelled - Course has been cancelled, no more updates.
Cancelling - PSA is aware they would cancel the course but they need to complete more actions such as transferring/cancelling already existing bookings on that course and other off the system actions 
Completed - All the session of course have been completed by the practitioner.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antenatal</fullName>
            </value>
            <value>
                <fullName>Postnatal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Assignment__c/Course_Assignment__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CA{000000}</displayFormat>
        <label>Course Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Assignment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Assignments</relationshipLabel>
    <relationshipName>Course_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Invalidated</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Course_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Course_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Assignment</label>
    <referenceTo>Course_Assignment__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Session_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Session_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Breastfeeding</fullName>
        <label>Breast feeding</label>
    </customValue>
    <customValue>
        <fullName>Reunion</fullName>
    </customValue>
    <masterLabel>Session Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvalidateWithdrawCADFlowTest.cls
// @SuppressWarnings('PMD.MethodNamingConventions')
// //Incident #42 - https://confluence.nct.org.uk:8443/x/EoSO
@IsTest
private class InvalidateWithdrawCADFlowTest {

    private static final String PRACTITIONER_LASTNAME = 'Smith';
    private static final String CANCELLATION_REASON = 'Low bookings - 0 bookings';
    private static final String COURSE_ASSIGNMENT_DRAFT_STATUS = 'Draft';
    private static final String COURSE_ASSIGNMENT_WITHDRAWN_STATUS = 'Withdrawn';

    @TestSetup 
    private static void testSetup() {
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildOrganizationAccount('acc1')
                    .createEnquiryPSA()
                    .buildBranchAccountWithEnquiryPSA()
                    .buildPractitioner(PRACTITIONER_LASTNAME)
                    .buildPractitionerFeeRate()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession();
        List<Session__c> provisionalNonReunionSessions = [
            SELECT Id 
            FROM Session__c 
            WHERE Status__c = 'Provisional' 
                AND Type__c <> 'Reunion'
            ];    

        List<Course__c> listDraftCourses = [
            SELECT Id 
            FROM Course__c 
            WHERE Status__c = 'Draft'];

        dataFactory .SetSessionsToConfirmed(provisionalNonReunionSessions)
                    .SetCoursesToFinal(listDraftCourses)
                    .buildCourseAssignment();

        User practitionerCommunityUser = TestDataFactory.convertPractitionerToPartnerCommunityUser();
        TestDataFactory.changeOwnerOfAllCourseAssignments(practitionerCommunityUser);
    }

    @isTest
    static void InvalidateWithdrawCAD_CourseCancelled_CADWithdrawn() {

        Course__c course = [
			SELECT Id, Status__c
			FROM Course__c
			LIMIT 1
        ];
        
        Course_Assignment__c courseAssignment = [
            SELECT Status__c
            FROM Course_Assignment__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        Test.startTest();
            course.Status__c = 'Cancelled';
            course.Cancellation_Reason__c = CANCELLATION_REASON;
            update course;
        Test.stopTest();

        Course_Assignment__c courseAssignmentToTest = [
            SELECT Status__c, Course__r.Status__c
            FROM Course_Assignment__c
            WHERE Course__c = :course.Id
            LIMIT 1
        ];

        System.assertEquals(COURSE_ASSIGNMENT_DRAFT_STATUS, courseAssignment.Status__c);
        System.assertEquals(COURSE_ASSIGNMENT_WITHDRAWN_STATUS, courseAssignmentToTest.Status__c);
    }
}