src/objects/gaid__Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>gaid__Acquisition_Method__c</fullName>
        <label>Acquisition Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Written</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GAD-{0}</displayFormat>
        <label>Gift Aid Declaration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>   
</CustomObject>

force-app/main/default/classes/CreateGiftAidDeclarationHelper.cls
public without sharing class CreateGiftAidDeclarationHelper {
    @InvocableMethod
    public static void createGiftAidDeclaration(List<List<gaid__Gift_Aid_Declaration__c>> giftAidDeclarationList) {
        if(!giftAidDeclarationList.isEmpty() || !giftAidDeclarationList[0].isEmpty()) { 
            try {

                for(gaid__Gift_Aid_Declaration__c gad : giftAidDeclarationList[0]) {
                    gad.gaid__Acquisition_Method__c = String.valueOf(gad.gaid__Acquisition_Method__c);
                }

            insert giftAidDeclarationList[0];

            } catch(DMLException ex) {
                throw new CreateGiftAidDeclarationException();
            }
        }

    }

    public class CreateGiftAidDeclarationException extends Exception {}
}