src/objects/Individual.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/SMS__c.field-meta.xml
<CustomField>
    <fullName>SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Telephone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestIndividualBuilder.cls
@IsTest
public class TestIndividualBuilder {

    private Boolean emailOptOut = true;
    private Boolean phoneOptOut = true;
    private Boolean smsOptOut = true;
    private Boolean postOptOut = true;
    private String lastName = 'LastName';
    private String firstName;
    private String salutation;
    private Boolean insertRecord = true;

    public TestIndividualBuilder withLastName(String lastName){
        this.lastName = lastName;
        return this;
    }

    public TestIndividualBuilder withFirstName(String firstName){
        this.firstName = firstName;
        return this;
    }

    public TestIndividualBuilder withSalutation(String salutation){
        this.salutation = salutation;
        return this;
    }

    public TestIndividualBuilder withHasOptedOutEmail(Boolean emailOptOut){
        this.emailOptOut = emailOptOut;
        return this;
    }

    public TestIndividualBuilder withHasOptedOutPost(Boolean postOptOut){
        this.postOptOut = postOptOut;
        return this;
    }

    public TestIndividualBuilder withHasOptedOutSms(Boolean smsOptOut){
        this.smsOptOut = smsOptOut;
        return this;
    }

    public TestIndividualBuilder withHasOptedOutTelephone(Boolean phoneOptOut){
        this.phoneOptOut = phoneOptOut;
        return this;
    }

    public TestIndividualBuilder insertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public Individual build(){
        Individual individual = new Individual (
            LastName = this.lastName,
            FirstName = this.firstName,
            Salutation = this.salutation,
            Email__c = this.emailOptOut,
            Post__c = this.postOptOut,
            SMS__c = this.smsOptOut,
            Telephone__c = this.phoneOptOut
        );
        if(this.insertRecord){
            insert individual;
        }
        return individual;        
    }


}