src/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Membership (First Contact)</relationshipLabel>
        <relationshipName>Membership1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card(£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit card(£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit(£ 10)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Membership_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                    <isActive>false</isActive>
                    <label>Practitioner</label>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                    <isActive>false</isActive>
                    <label>Volunteer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Gift_Aid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Gift Aid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GiftAid_Type__c</fullName>
        <label>GiftAid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
                <value>
                    <fullName>99 Years</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No. of Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Target__c</fullName>
        <label>Payment Target</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NCT Membership Collections - S18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit/Debit Card (£57)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£9.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£57)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£48)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£12 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£48)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£10)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£2.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£10)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£120)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£120)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£250)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£250)</fullName>
                </value>
                <value>
                    <fullName>Credit/Debit Card (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£26)</fullName>
                </value>
                <value>
                    <fullName>Direct Debit (£6.50 per quarter)</fullName>
                </value>
                <value>
                    <fullName>Life Membership - Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recursive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recursive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Multiply By</fullName>
                    <default>true</default>
                    <label>Multiply By</label>
                </value>
                <value>
                    <fullName>Divide By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Membership Type</label>
    <pluralLabel>Membership Types</pluralLabel>
</CustomObject>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations with no end date.</description>
    <fields>
        <fullName>CARE_Payment_Frequency__c</fullName>
        <label>CARE_Payment_Frequency</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>First Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Donations (First Contact)</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Payment__c</fullName>
        <label>First Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Cancelling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_type__c</fullName>
        <label>Membership type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 year standard - Individual</fullName>
                </value>
                <value>
                    <fullName>1 year standard - Joint</fullName>
                </value>
                <value>
                    <fullName>18 month - Individual</fullName>
                </value>
                <value>
                    <fullName>18 month - Joint</fullName>
                </value>
                <value>
                    <fullName>4 year - Individual</fullName>
                </value>
                <value>
                    <fullName>4 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>Life Joint Membership</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Ind</fullName>
                </value>
                <value>
                    <fullName>Reduced rate 1 year - Joint</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Individual</fullName>
                </value>
                <value>
                    <fullName>Staff Membership - Joint</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Individual</fullName>
                </value>
                <value>
                    <fullName>Ten Year - Joint</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Ind</fullName>
                </value>
                <value>
                    <fullName>1 year volunteer/practitioner - Jnt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>Sets the installment period for your recurring donations.  WARNING: Changing the Installment Period for an existing open-ended Recurring Donation can cause open Opportunities to be deleted and recreated. Any associated data may not be retained.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Donations</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThankYouHelperTest.cls
@isTest
private class ThankYouHelperTest {   
    @testSetup static void setup() {
       Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
        acc.Name ='Test Branch';
        insert acc;
        List<Contact> firstContact = new List<Contact>();
        for(Integer i=0;i<2;i++){
            firstContact.add(new Contact(
            LastName = 'NCT CHild'+i,
            FirstName = 'Childs'+i,
            Phone = '09876543212',
            Email = 'nctchild4555'+i+'@gmail.com'));
        }
        insert firstContact;
        
         List<npe03__Recurring_Donation__c> recDonation = new List<npe03__Recurring_Donation__c>();
        for(Integer j=0; j<2; j++){
            recDonation.add(new npe03__Recurring_Donation__c(
                Name = 'NCT Childs',
                npe03__Amount__c = 10000,
                npe03__Installment_Period__c = 'Monthly',
                CARE_Payment_Frequency__c = 'NCT CHILD TRUST',
                First_Payment__c = system.date.today(),
                First_Contact__c = firstContact[j].id, 
                Membership_Status__c = 'Pending', 
                Membership_type__c = '18 month - Joint',
                npe03__Contact__c = firstContact[j].id
            ));
        }
        insert recDonation;
    } 
    @isTest static void recurringExists(){
         String membershipNumber;
         Membership_Type__mdt membershipDetails;
        List<npe03__Recurring_Donation__c> recDonation = [Select id,Membership_Status__c, Name from npe03__Recurring_Donation__c where Name = 'NCT Childs'];
        recDonation[0].Membership_Status__c ='Confirmed';
        upsert recDonation;
        List<Contact> firstContact = [Select id, Name from Contact where phone='09876543212'];
        Test.startTest();
        pagereference page = page.NctETMembershipPaymentPage;
        Test.setCurrentPage(page);
        ID contID = ApexPages.currentPage().getParameters().put('contID',String.valueOf(firstContact[0].ID));
        membershipNumber =  ThankYouHelper.membershipNumberCreation(firstContact[0],recDonation[0]); 
        system.assertEquals('Confirmed',recDonation[0].Membership_Status__c);
        Test.stopTest();
     }
     @isTest static void recurringNotExists(){

        List<npe03__Recurring_Donation__c> recDonation = [Select id,Membership_Status__c, Name from npe03__Recurring_Donation__c where Name = 'NCT Childs'];
        recDonation[0].Membership_Status__c ='Confirmed';
        upsert recDonation;
      	List<Contact> firstContact = [Select id, Name from Contact where phone='09876543212'];

        Membership_Type__mdt membershipDetails;
        Test.startTest();
        pagereference page = page.NctETMembershipPaymentPage;
        Test.setCurrentPage(page);
        ApexPages.currentPage().getParameters().put('contID',String.valueOf(firstContact[0].ID));
        
        ThankYouHelper.reccDonList = recDonation;
        ThankYouHelper.membershipNumberCreation(firstContact[0],recDonation[0]);  
        system.assertEquals('Confirmed', recDonation[0].Membership_Status__c);
        Test.stopTest();
    }
    
    @isTest
    private static void isStaffExists(){
           
         npe03__Recurring_Donation__c recDon1 = new npe03__Recurring_Donation__c();
        npe03__Recurring_Donation__c recDonation = new npe03__Recurring_Donation__c();
        List<Contact> firstContact = [Select id, Name from Contact where phone='09876543212'];
        Membership_Type__mdt membershipDetails = [SELECT Id, MasterLabel, Eligible_for_Gift_Aid__c,Installment_Amount__c, Payment_Target__c,Schedule_Type__c, No_of_Installments__c,Payment_Type__c,  Payment_Method__c, Recursive__c, GiftAid_Type__c,Total_Amount__c, Contact_Type__c, Membership__c,Installment_Period__c,GiftAid_Acquisition_Method__c,Target_Customer__c, Payment_Processor__c FROM  Membership_Type__mdt WHERE 
													Payment_Type__c='Life Membership - Free' limit 1];
        
        String membershipNumber;
		Test.startTest();
        ThankYouHelper thankYou = new ThankYouHelper();
        membershipNumber = ThankYouHelper.membershipNumberCreation(firstContact[0],recDon1);  
        system.assertNotEquals('Confirmed', membershipNumber);
        Test.stopTest();
    }
    @isTest static void permissionCheck(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Read Only'];
      	User u = new User(Alias = 'newUsers', Email='newusers@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newusers@testorg.com');
        List<Contact> firstContact = [Select id, Name from Contact where phone='09876543212'];
        System.runAs(u) {
            list<npe03__Recurring_Donation__c> recDonation = new list<npe03__Recurring_Donation__c>();
            npe03__Recurring_Donation__c recDon = new npe03__Recurring_Donation__c();
            
            Membership_Type__mdt membershipDetails;
            Test.startTest();
            pagereference page = page.NctETMembershipPaymentPage;
            Test.setCurrentPage(page);
            ApexPages.currentPage().getParameters().put('contID',String.valueOf(firstContact[0].ID));
            
            ThankYouHelper.reccDonList = recDonation;
            ThankYouHelper.membershipNumberCreation(firstContact[0],recDon); 
            system.assertEquals(null, recDon.Membership_Status__c);
            Test.stopTest();
        }
    }
    @isTest static void recurringExistsNegativeTesting(){
         String membershipNumber;
         Membership_Type__mdt membershipDetails;

        List<npe03__Recurring_Donation__c> recDonation = [Select id,Membership_Status__c, Name from npe03__Recurring_Donation__c where Name = 'NCT Childs'];
        List<Contact> firstContact = [Select id, Name from Contact where phone='09876543212'];
        Test.startTest();
        pagereference page = page.NctETMembershipPaymentPage;
        Test.setCurrentPage(page);
        ID contID = ApexPages.currentPage().getParameters().put('contID',String.valueOf(firstContact[0].ID));
        membershipNumber =  ThankYouHelper.membershipNumberCreation(firstContact[0],recDonation[0]); 
        system.assertEquals('Pending',recDonation[0].Membership_Status__c);
        Test.stopTest();
     }
    
}