src/objects/PostCode_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PostCode Allocation</relationshipLabel>
        <relationshipName>PostCode_Allocation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Roles__c</fullName>
        <label>PSA Roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity PSA</fullName>
                </value>
                <value>
                    <fullName>Enquiry PSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PostCode Allocation</label>
    <nameField>
        <label>PostalCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PostCode Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DupOutCodeTest.cls
@isTest
public class DupOutCodeTest {
	
    static testMethod Void outcodeDuplicate(){
        Boolean result = false;
        PostCode_Allocation__c firstPA = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Capacity PSA',Branch__c =Label.DupOutCodeTestID);
        insert firstPA;
        
        PostCode_Allocation__c firstPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c =Label.DupOutCodeTestID);
        insert firstPA1;
        
        try{
            PostCode_Allocation__c secPA = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Capacity PSA',Branch__c =Label.DupOutCodeTestID);
            insert secPA;
            PostCode_Allocation__c secPA1 = new PostCode_Allocation__c(Name = 'Test',PSA_Roles__c = 'Enquiry PSA',Branch__c =Label.DupOutCodeTestID);
            insert secPA1;
        }
        catch(DmlException ex){ 
            
            result = true;
        }

      	System.assert(result);

    }

}