src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venue__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Street_address__c.field-meta.xml
<CustomField>
    <fullName>Street_address__c</fullName>
    <label>Street address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Subtype</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Reunion</fullName>
            </value>
            <value>
                <fullName>One off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>Town</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Venue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial/Community</fullName>
            </value>
            <value>
                <fullName>Practitioner Home</fullName>
            </value>
            <value>
                <fullName>Volunteer Home</fullName>
            </value>
            <value>
                <fullName>Parent Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestVenueBuilder.cls
@isTest
public with sharing class TestVenueBuilder {

    private String name = 'TestVenue';
    private String streetAddress = '221B Baker Street';
    private String town = 'London';
    private String postcode = 'NW1 6XE';
    private String type = 'Commercial';
    private String subtype = 'Primary';
    private Boolean insertRecord = false;

    public TestVenueBuilder withName(String name) {

        this.name = name;

        return this;
    }

    public TestVenueBuilder withStreetAddress(String streetAddress) {

        this.streetAddress = streetAddress;

        return this;
    }

    public TestVenueBuilder withTown(String town) {

        this.town = town;

        return this;
    }

    public TestVenueBuilder withPostcode(String postcode) {

        this.postcode = postcode;

        return this;
    }

    public TestVenueBuilder withType(String type) {

        this.type = type;

        return this;
    }

    public TestVenueBuilder withSubtype(String subtype) {

        this.subtype = subtype;

        return this;
    }

    public TestVenueBuilder insertRecord(Boolean insertRecord){
        this.insertRecord = insertRecord;
        return this;
    }

    public Venue__c build(){

        Venue__c testVenue = new Venue__c(
            Name = this.Name,
            Street_Address__c = this.StreetAddress,
            Postcode__c = this.Postcode,
            Type__c = this.Type,
            Town__c = this.Town,
            Subtype__c = this.Subtype
        );

        if(this.insertRecord){
            insert testVenue;
        }

        return testVenue;
    }
}