force-app/main/default/objects/Financial_Settings__c/Financial_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Financial Settings</label>
</CustomObject>

force-app/main/default/objects/Financial_Settings__c/fields/Payment_Run_Line_Item_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run_Line_Item_Batch_Size__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Used in the BatchOutboundBACSPayment job.</description>
    <label>Payment Run Line Item Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Unpaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Unpaid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/Zumzum__Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <label>PI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Purchase_Invoice__c/fields/Zumzum__Paid__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Paid__c</fullName>
    <defaultValue>&#39;N&#39;</defaultValue>
    <label>Paid</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchOutboundBACSpayment.cls
@SuppressWarnings('PMD.EmptyStatementBlock')
//Incident #63 - https://confluence.nct.org.uk:8443/x/EoSO
public with sharing class BatchOutboundBACSpayment implements Database.Batchable<sObject>{
    public Id paymentRunId;

    private static final String PAYMENT_RUN_RESULT_STATUS_ERROR = 'Error';
    private static final String PAYMENT_RUN_STATUS_READY = 'Ready';
    private static final String PAYMENT_RUN_STATUS_FAILED = 'Failed To Create Transactions';

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Name, Payment_Run__c, Payment_Run__r.Name, Account__c, Purchase_Invoice__c, Status__c, Unpaid_Amount__c ' + 
            'FROM Payment_Run_Line_Item__c ' + 
            'WHERE Payment_Run__c = \'' + paymentRunId + '\' AND Payment_Run__r.Status__c = \'Processing\' AND Purchase_Invoice__r.Zumzum__Paid__c <> \'Y\''
        );
    }

    public void execute(Database.BatchableContext bc, List<Payment_Run_Line_Item__c> paymentRunLineItems) {
        OutboundBACSpaymentHelper.processPaymentRunLineItems(paymentRunLineItems);
    }

    public void finish(Database.BatchableContext bc) {
        Payment_Run__c paymentRun = [SELECT Id FROM Payment_Run__c WHERE Id = :paymentRunId];
        AsyncApexJob batchOutboundBACSPaymentJob = [SELECT Id, Status, NumberOfErrors
                                                    FROM AsyncApexJob WHERE Id =
                                                    :BC.getJobId()];
        
        if(batchOutboundBACSPaymentJob.NumberOfErrors > 0){
            paymentRun.Status__c = PAYMENT_RUN_STATUS_FAILED;
        }else{
            paymentRun.Status__c = PAYMENT_RUN_STATUS_READY;
        }

        update paymentRun;
    }

    public BatchOutboundBACSpayment(Id paymentRunId) {
        this.paymentRunId = paymentRunId;
    }

    @InvocableMethod(
        label='Create Bank Supplier Payments'
        description='ZZ API is called for each Purchase Invoice Line Item'
        category='Payment_Run__c'
    )
    public static void runBatch(List<Id> paymentRunIds) {
        Integer batchSize = Financial_Settings__c.getInstance().Payment_Run_Line_Item_Batch_Size__c == null ? 10 : Integer.valueOf(Financial_Settings__c.getInstance().Payment_Run_Line_Item_Batch_Size__c);
        BatchOutboundBACSpayment myBatchObject = new BatchOutboundBACSpayment(paymentRunIds[0]);
        Id batchId = Database.executeBatch(myBatchObject, batchSize);
    }
}