force-app/main/default/objects/Zumzum__Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/Zumzum__Batch_Bank_Payment__c.object-meta.xml
<CustomObject>
    <label>Batch Bank Payment</label>
    <nameField>
        <displayFormat>BBPUID-{0000000000}</displayFormat>
        <label>Batch Bank Payment UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Bank Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Batch_Bank_Payment__c/fields/Zumzum__Status__c.field-meta.xml
<CustomField>
    <fullName>Zumzum__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>File Generated</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBankPaymentBuilder.cls
@IsTest
public class TestBankPaymentBuilder {

	private Double amount;
	private Id batchBankPaymentId;
	private Boolean insertRecord = false;
	private String status;
	private Id supplierId;

	public TestBankPaymentBuilder withAmount(Double amount) {
		this.amount = amount;
		return this;
	}

	public TestBankPaymentBuilder withBatchBankPayment(Id batchBankPaymentId) {
		this.batchBankPaymentId = batchBankPaymentId;
		return this;
	}

	public TestBankPaymentBuilder withStatus(String status) {
		this.status = status;
		return this;
	}

	public TestBankPaymentBuilder withSupplier(Id supplierId) {
		this.supplierId = supplierId;
		return this;
	}

	public TestBankPaymentBuilder insertRecord(Boolean insertRecord) {
		this.insertRecord = insertRecord;
		return this;
	}

	public Zumzum__Bank_Payment__c build(){
		Zumzum__Bank_Payment__c testBankPayment = new Zumzum__Bank_Payment__c(
				Zumzum__Supplier__c = this.supplierId,
				Zumzum__Amount__c = this.amount,
				Zumzum__Status__c = this.status,
				Zumzum__Batch_Bank_Payment__c = this.batchBankPaymentId
		);

		if(insertRecord) {
			insert testBankPayment;
		}

		return testBankPayment;
	}
}