force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/Practitioner_Fee_Rate__c.object-meta.xml
<CustomObject>
    <label>Practitioner Fee Rate</label>
    <nameField>
        <displayFormat>PF{000000}</displayFormat>
        <label>Practitioner Fee Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Fee Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Geographical_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Geographical_Weighting__c</fullName>
    <label>Geographical Weighting</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geographical_Weightings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Practitioner_Band__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Band__c</fullName>
    <label>Practitioner Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Practitioner_Fee_Rate__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Fee_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner Fee Rate</label>
    <referenceTo>Practitioner_Fee_Rate__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Geographical_Weightings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>London,</fullName>
    </customValue>
    <customValue>
        <fullName>Fringe,</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Geographical Weightings</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practitioner_Bands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A,</fullName>
    </customValue>
    <customValue>
        <fullName>B,</fullName>
    </customValue>
    <customValue>
        <fullName>C,</fullName>
    </customValue>
    <customValue>
        <fullName>D,</fullName>
    </customValue>
    <customValue>
        <fullName>ZERO</fullName>
    </customValue>
    <masterLabel>Practitioner Bands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PractitionerFeeRateHelper.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
//Incident #55 - https://confluence.nct.org.uk:8443/x/EoSO
public with sharing class PractitionerFeeRateHelper {

    @InvocableMethod
    public static void updateFeesOnAffectedSessions(List<Practitioner_Fee_Rate__c> updatedAndNewRates){

        Set<String> affectedBands = getAffectedBands(updatedAndNewRates);
        Set<String> affectedWeightings = getAffectedWeightings(updatedAndNewRates);
        Date earliestFeeRateStartDate = getEarliestFeeRateStartDate(updatedAndNewRates);
        List<Session__c> potentialSessionsToProcess = getPotentialSessionsToProcess(affectedBands, affectedWeightings, earliestFeeRateStartDate);

        if(potentialSessionsToProcess.size() > 0){
            List<Session__c> sessionsToProcess = refinePotentialSessionList(potentialSessionsToProcess, updatedAndNewRates);

            SessionFeeHelper.assignFeeRatesToSessions(sessionsToProcess);
        }
    }

    private static Set<String> getAffectedBands(List<Practitioner_Fee_Rate__c> updatedAndNewRates){

        Set<String> affectedBands = new Set<String>();
        for(Practitioner_Fee_Rate__c feeRate : updatedAndNewRates){
            affectedBands.add(feeRate.Practitioner_Band__c);
        }

        return affectedBands;
    }

    private static Set<String> getAffectedWeightings(List<Practitioner_Fee_Rate__c> updatedAndNewRates){

        Set<String> affectedWeightings = new Set<String>();
        for(Practitioner_Fee_Rate__c feeRate : updatedAndNewRates){
            affectedWeightings.add(feeRate.Geographical_Weighting__c);
        }

        return affectedWeightings;        
    }

    private static Date getEarliestFeeRateStartDate(List<Practitioner_Fee_Rate__c> updatedAndNewRates){

        Date earliestFeeRateStartDate;
        for(Practitioner_Fee_Rate__c feeRate : updatedAndNewRates){
            if(earliestFeeRateStartDate == null || earliestFeeRateStartDate > feeRate.Start_Date__c){
                earliestFeeRateStartDate = feeRate.Start_Date__c;
            }
        }

        return earliestFeeRateStartDate;
    } 
 
    private static List<Session__c> getPotentialSessionsToProcess(Set<String> affectedBands, Set<String> affectedWeightings, Date earliestFeeRateStartDate){

        return [SELECT  Id,
                        Practitioner_Fee_Rate__r.Practitioner_Band__c,
                        Practitioner_Fee_Rate__r.Geographical_Weighting__c,
                        Date__c
                FROM Session__c
                WHERE Date__c >= :earliestFeeRateStartDate
                    AND ((Practitioner_Fee_Rate__r.Practitioner_Band__c IN :affectedBands
                            AND Practitioner_Fee_Rate__r.Geographical_Weighting__c IN :affectedWeightings)
                        OR Practitioner_Fee_Rate__c = null)
                WITH SECURITY_ENFORCED];
    }

    private static List<Session__c> refinePotentialSessionList(List<Session__c> potentialSessionsToProcess, List<Practitioner_Fee_Rate__c> updatedAndNewRates){

        Set<Session__c> sessionsToProcess = new Set<Session__c>();
        
        for(Session__c potentialSession : potentialSessionsToProcess){
            for(Practitioner_Fee_Rate__c feeRate : updatedAndNewRates){
                if(potentialSession.Date__c > feeRate.Start_Date__c
                    && ((potentialSession.Practitioner_Fee_Rate__r.Practitioner_Band__c == feeRate.Practitioner_Band__c
                            && potentialSession.Practitioner_Fee_Rate__r.Geographical_Weighting__c == feeRate.Geographical_Weighting__c)
                        || potentialSession.Practitioner_Fee_Rate__c == null)){    
                    sessionsToProcess.add(potentialSession);
                }
            }
        }

        return new List<Session__c>(sessionsToProcess);
    }
}