force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/Practitioner_Fee_Rate__c.object-meta.xml
<CustomObject>
    <label>Practitioner Fee Rate</label>
    <nameField>
        <displayFormat>PF{000000}</displayFormat>
        <label>Practitioner Fee Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Fee Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Geographical_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Geographical_Weighting__c</fullName>
    <label>Geographical Weighting</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Geographical_Weightings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Practitioner_Fee_Rate__c/fields/Practitioner_Band__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Band__c</fullName>
    <label>Practitioner Band</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practitioner_Bands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Geographical_Weightings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>London,</fullName>
    </customValue>
    <customValue>
        <fullName>Fringe,</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Geographical Weightings</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practitioner_Bands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A,</fullName>
    </customValue>
    <customValue>
        <fullName>B,</fullName>
    </customValue>
    <customValue>
        <fullName>C,</fullName>
    </customValue>
    <customValue>
        <fullName>D,</fullName>
    </customValue>
    <customValue>
        <fullName>ZERO</fullName>
    </customValue>
    <masterLabel>Practitioner Bands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPractitionerFeeRateBuilder.cls
@isTest
public with sharing class TestPractitionerFeeRateBuilder {
    private Boolean insertRecord = false;
    private String geographicalWeighting = 'Standard';
    private String practitionerBand = 'A';
    private Decimal hourlyRate = 30.00;

    public Practitioner_Fee_Rate__c build(){
        Practitioner_Fee_Rate__c testFeeRate = new Practitioner_Fee_Rate__c(
            Geographical_Weighting__c = this.geographicalWeighting,
            Practitioner_Band__c = this.practitionerBand,
            Hourly_Rate__c = this.hourlyRate
        );
		if(insertRecord){
			insert testFeeRate;
		}
    	return testFeeRate;
    }
}