force-app/main/default/objects/Practitioner_Band__c/Practitioner_Band__c.object-meta.xml
<CustomObject>
    <label>Practitioner Band</label>
    <nameField>
        <displayFormat>PB{00000}</displayFormat>
        <label>Practitioner Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practitioner Bands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Practitioner_Band__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <label>Practitioner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Practitioner Bands</relationshipLabel>
    <relationshipName>Practitioner_Bands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Practitioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practitioner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PractitionerBandFeeHelper.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
//Incident #54 - https://confluence.nct.org.uk:8443/x/EoSO
public with sharing class PractitionerBandFeeHelper {

    @InvocableMethod
    public static void updateFeesOnAffectedSessions(List<Practitioner_Band__c> updatedAndNewBands){
        Set<Id> practitionerIds = getPractitionerIDs(updatedAndNewBands);

        Date earliestBandStartDate = getEarliestBandStartDate(updatedAndNewBands);

        List<Session__c> sessionsToProcess = getPotentiallyAffectedSessions(practitionerIds, earliestBandStartDate);

        SessionFeeHelper.assignFeeRatesToSessions(sessionsToProcess);
    }

    private static Set<Id> getPractitionerIDs(List<Practitioner_Band__c> updatedAndNewBands){
        Set<Id> practitionerIds = new Set<Id>();

        for(Practitioner_Band__c band : updatedAndNewBands){
            practitionerIds.add(band.practitioner__c);
        }

        return practitionerIds;
    }

    private static Date getEarliestBandStartDate(List<Practitioner_Band__c> updatedAndNewBands){
        Date earliestBandStartDate;
        for(Practitioner_Band__c band : updatedAndNewBands){
            if(earliestBandStartDate == null || earliestBandStartDate > band.Start_Date__c){
                earliestBandStartDate = band.Start_Date__c;
            }
        }
        return earliestBandStartDate;
    }

    private static List<Session__c> getPotentiallyAffectedSessions(Set<Id> practitionerIds, Date earliestBandStartDate){
        return [SELECT Id 
                FROM Session__c 
                WHERE Practitioner__c IN :practitionerIds
                    AND Date__c >= :earliestBandStartDate];
    }
}