force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <formula>Purchase_Invoice__r.Zumzum__Total_Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <formula>IF(NOT( ISBLANK(Purchase_Invoice__r.Zumzum__POP_Number__c) ), &#39;Your reference: &#39; + Purchase_Invoice__r.Zumzum__POP_Number__c + '. ', &#39;&#39;) +
&#39;Our reference: &#39; + Purchase_Invoice__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BacsSendRemittanceEmailsHelper.cls
public with sharing class BacsSendRemittanceEmailsHelper {
    @InvocableMethod
    public static void sendEmails(List<List<Payment_Run_Line_Item__c>> prliList) {
        BacsSendRemittanceEmailsBatch bacsSendRemittanceEmailsBatch = new BacsSendRemittanceEmailsBatch(prliList[0]);
        Database.executeBatch(bacsSendRemittanceEmailsBatch, 500);
    }
    private static String createEmailBody(String body, Payment_Run_Line_Item__c prli) {
        return String.format(body, new List<String> {String.valueOf(prli.Paid_Amount__c), prli.Reference_Info__c});
    }
}