force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>In Active</fullName>
                    <isActive>false</isActive>
                    <label>In Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Session</relationshipLabel>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Lunch_Break_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Lunch_Break_Minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lunch Break Minutes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.Venue__c</field>
            <operation>equals</operation>
            <valueField>$Source.Venue__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Venue__c.object
<CustomObject>
    <description>Venues used for courses or events</description>
    <label>Venue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SESSION_RevertToProvisional_TDTM_TEST.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #9 - https://confluence.nct.org.uk:8443/x/EoSO
@isTest
public with sharing class SESSION_RevertToProvisional_TDTM_TEST {

    private static final String SESSION_PROVISIONAL_STATUS = 'Provisional';
    private static final String PRACTITIONER_LASTNAME_ONE = 'Smith';
    private static final String VENUE_NAME = 'Public Venue';
    private static final Integer COURSES_TO_CREATE = 5;
    private static final Integer SESSIONS_TO_CREATE = 10;

    private static Venue__c venue;

    @TestSetup
    private static void SetupTestData() {
        TestDataFactory dataFactory = TestDataFactory.getInstance();
        dataFactory .buildBranchAccount()
                    .buildOrganizationAccount('acc1')
                    .buildPractitioner(PRACTITIONER_LASTNAME_ONE)
                    .buildPractitionerFeeRate()
                    .buildVenue()
                    .buildRoom()
                    .buildLicenceToPractice()
                    .buildCourse()
                    .buildEstimatedCosts()
                    .buildSession()
                    .buildCoursesWithSessions(COURSES_TO_CREATE, SESSIONS_TO_CREATE)
                    .buildVenueWithName(VENUE_NAME);
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1000];
        dataFactory .setSessionsToConfirmed(sessions);
    }

    @isTest
    static void ChangeSessionToProvisional_DateUpdatedOnSession_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1];

        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.Date__c = Date.today()+10;
        }
        update sessions;
        Test.stopTest();

        Session__c sessionToTest = [SELECT Status__c FROM Session__c WHERE Id = :sessions LIMIT 1];
        System.assertEquals(SESSION_PROVISIONAL_STATUS, sessionToTest.Status__c);
    }

    @isTest
    static void ChangeSessionToProvisional_StartTimeUpdatedOnSession_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1];

        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.Start__c =  Time.newInstance(18, 00, 0, 0);
        }
        update sessions;
        Test.stopTest();

        Session__c sessionToTest = [SELECT Status__c FROM Session__c WHERE Id = :sessions LIMIT 1];
        System.assertEquals(SESSION_PROVISIONAL_STATUS, sessionToTest.Status__c);
    }

    @isTest
    static void ChangeSessionToProvisional_EndTimeUpdatedOnSession_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1];

        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.End__c =  Time.newInstance(21, 00, 0, 0);
        }
        update sessions;
        Test.stopTest();

        Session__c sessionToTest = [SELECT Status__c FROM Session__c WHERE Id = :sessions LIMIT 1];
        System.assertEquals(SESSION_PROVISIONAL_STATUS, sessionToTest.Status__c);
    }

    @isTest
    static void ChangeSessionToProvisional_LunchBreakUpdatedOnSession_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1];

        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.Lunch_Break_Minutes__c =  11;
        }
        update sessions;
        Test.stopTest();

        Session__c sessionToTest = [SELECT Status__c FROM Session__c WHERE Id = :sessions LIMIT 1];
        System.assertEquals(SESSION_PROVISIONAL_STATUS, sessionToTest.Status__c);
    }

    @isTest
    static void ChangeSessionToProvisional_VenueUpdatedOnSession_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1];
        Venue__c venue = [SELECT Id FROM Venue__c WHERE Name = :VENUE_NAME LIMIT 1];
        
        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.Venue__c =  venue.Id;
            aSession.Room__c =  NULL;
        }
        update sessions;
        Test.stopTest();

        Session__c sessionToTest = [SELECT Status__c FROM Session__c WHERE Id = :sessions LIMIT 1];
        System.assertEquals(SESSION_PROVISIONAL_STATUS, sessionToTest.Status__c);
    }

    @isTest
    static void ChangeSessionToProvisional_BulkUpdatesOnSessions_SessionStatusIsChangedToProvisional() {
        CreateTriggerSystemHandlerRecord();
        List<Session__c> sessions = [SELECT Id FROM Session__c LIMIT 1000];
        Set<Id> sessionIds = new Set<Id>();

        Test.startTest();
        for(Session__c aSession : sessions) {
            aSession.Lunch_Break_Minutes__c =  11;
            sessionIds.add(aSession.Id);
        }
        update sessions;
        Test.stopTest();

        List<Session__c> sessionsWithProvisionalStatus = [SELECT Status__c FROM Session__c WHERE Status__c =: SESSION_PROVISIONAL_STATUS AND Id IN :sessionIds LIMIT 1000];
        System.assertEquals(sessions.size(), sessionsWithProvisionalStatus.size());
    }

    private static void CreateTriggerSystemHandlerRecord() {
        List<npsp__Trigger_Handler__c> triggerHandlers = npsp.TDTM_Config_API.getCachedRecords();
        npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
        th.Name = 'SessionTriggerHandler';
        th.npsp__Class__c = 'SESSION_RevertToProvisional_TDTM';
        th.npsp__Object__c = 'Session__c';
        th.npsp__Trigger_Action__c = 'BeforeUpdate';
        th.npsp__Active__c = true;
        th.npsp__Load_Order__c = 0;
        th.npsp__Asynchronous__c = false;
        triggerHandlers.add(th);
    }
}