force-app/main/default/objects/Care_Settings__c/Care_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Care Settings</label>
</CustomObject>

force-app/main/default/objects/Care_Settings__c/fields/Auth_Key__c.field-meta.xml
<CustomField>
    <fullName>Auth_Key__c</fullName>
    <label>Auth Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Care_Settings__c/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <label>Branch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Care_Settings__c/fields/SF_Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>SF_Environment_Name__c</fullName>
    <description>Name of page / system calling the service for fault tracking information
Can contain the value: SalesforceSBASandbox</description>
    <label>SF Environment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Care_Settings__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Should contain the value: SALESFORCE</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Care_Settings__c/fields/User_Log_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Log_Name__c</fullName>
    <label>User Log Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Profile</label>
        <referenceTo>cpm__Payment_Profile__c</referenceTo>
        <relationshipLabel>Contact</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <externalId>true</externalId>
    <label>NCT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Used for general contacts such as those who are the bookings or emergency contact at a venue.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Bank_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Number__c</fullName>
    <description>This field is mapped from BankDetailsNumber (Care)</description>
    <externalId>true</externalId>
    <label>Bank Details Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>GiftAid</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Care Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/ga_decl_1__c.field-meta.xml
<CustomField>
    <fullName>ga_decl_1__c</fullName>
    <formula>IF (
AND ( NOT(ISNULL(cpm__Contact__c)), cpm__Contact__r.gaid__Active_Gift_Aid_Declarations__c &gt; 0 ),&#39;Y&#39;,&#39;N&#39;
)</formula>
    <label>Gift Aid Declaration 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/ga_decl_2__c.field-meta.xml
<CustomField>
    <fullName>ga_decl_2__c</fullName>
    <formula>IF (
AND ( NOT(ISNULL(Partner_Contact__c)), Partner_Contact__r.gaid__Active_Gift_Aid_Declarations__c &gt; 0 ), &#39;Y&#39;, &#39;N&#39;
)</formula>
    <label>Gift Aid Declaration 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Installments (Partner Contact)</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                 <value>
                    <fullName>Paper Form</fullName>
                </value>
                 <value>
                    <fullName>Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpm__Bank_Account__c</fullName>
        <description>Pre-SEPA bank accounts. doesn&apos;t have the IBAN validation check.</description>
        <inlineHelpText>non IBAN bank account number. doesn&apos;t have the IBAN validation check.</inlineHelpText>
        <label>Bank Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Holder_Name__c</fullName>
        <description>Name of the account/credit card holder.</description>
        <inlineHelpText>Name of the account/credit card holder.</inlineHelpText>
        <label>Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paybacs__Sort_Code__c</fullName>
        <label>Sort Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CareRequestBodyUtil.cls
public with sharing class CareRequestBodyUtil {
    public static final String AUTH_KEY = Care_Settings__c.getOrgDefaults().Auth_Key__c;//'p1Fm0Y48P4iCehUKyzbsxY9-i78gdx7rG2Iu';
    public static final String SF_ENVIRONMENT_NAME = Care_Settings__c.getOrgDefaults().SF_Environment_Name__c;//'SalesforceSBASandbox';
    public static final String SOURCE = Care_Settings__c.getOrgDefaults().Source__c;//'SALESFORCE';
    private static final String BRANCH_NUMBER = Care_Settings__c.getOrgDefaults().Branch_Number__c;//'240';
    private static final String USER_LOG_NAME = Care_Settings__c.getOrgDefaults().User_Log_Name__c;//'xSalesforce';
    private static final String CLAIM_DAY = '3';
    public static final String MESSAGE_TYPE_SUCCESS = 'success';
    public static final String MESSAGE_TYPE_ERROR = 'error';
    public static final String MESSAGE_TEXT_ERROR = 'error!';
    public static final String URL = 'https://careforce.nct.org.uk:1443/AuthParentForceTest/';
    public static String createSendContactBody(Contact cont) {
        AddUpdateContactRequest addUpdateContactRequest = new AddUpdateContactRequest();
        addUpdateContactRequest.authKey = AUTH_KEY;
        addUpdateContactRequest.pagename = SF_ENVIRONMENT_NAME;
        addUpdateContactRequest.source = SOURCE;
        addUpdateContactRequest.branch = BRANCH_NUMBER;
        addUpdateContactRequest.userLogname = USER_LOG_NAME;
        addUpdateContactRequest.surname = cont.LastName;
        addUpdateContactRequest.firstName = cont.FirstName;
        addUpdateContactRequest.contactNumber = cont.NCT_Number__c;
        addUpdateContactRequest.gender = cont.Gender__c;
        addUpdateContactRequest.postcode = cont.MailingPostalCode;
        addUpdateContactRequest.email = cont.Email;
        addUpdateContactRequest.address = cont.MailingStreet;
        addUpdateContactRequest.town = cont.MailingCity;
        addUpdateContactRequest.country = cont.MailingCountry;
        return JSON.serialize(addUpdateContactRequest, true);
    }
    public static String createSendBankDetailsBody(cpm__Payment_Profile__c paymentProfile, Contact cont) {
        AddBankDetailsRequest addBankDetailsRequest = new AddBankDetailsRequest();
        addBankDetailsRequest.authKey = AUTH_KEY;
        addBankDetailsRequest.pagename = SF_ENVIRONMENT_NAME;
        addBankDetailsRequest.source = SOURCE;
        addBankDetailsRequest.branch = BRANCH_NUMBER;
        addBankDetailsRequest.userLogname = USER_LOG_NAME;
        addBankDetailsRequest.sortCode = paymentProfile.paybacs__Sort_Code__c;
        addBankDetailsRequest.acctNumber = paymentProfile.cpm__Bank_Account__c;
        addBankDetailsRequest.acctName = paymentProfile.cpm__Holder_Name__c;
        addBankDetailsRequest.contactKey = cont.NCT_Number__c;
        return JSON.serialize(addBankDetailsRequest, true);
    }
    public static String createAddMembershipBody(cpm__Installment__c installment) {
        Map<String, String> paymentMethodMap = new Map<String, String> {
            'CreditCard' => 'CC',
            'Care Membership' => 'DDQ'
        };
        String paymentMethod = paymentMethodMap.get(installment.cpm__Payment_Method__c);
        AddMembership addMembership = new AddMembership();
        addMembership.authKey = AUTH_KEY;
        addMembership.pagename = SF_ENVIRONMENT_NAME;
        addMembership.source = SOURCE;
        addMembership.branch = BRANCH_NUMBER;
        addMembership.userLogname = USER_LOG_NAME;
        addMembership.paymentMethod = paymentMethod;
        addMembership.bankDetailNumber = installment.Bank_Details_Number__c;
        addMembership.claimDay = CLAIM_DAY;
        addMembership.ga_decl_1 = installment.ga_decl_1__c;
        addMembership.ga_decl_2 = installment.ga_decl_2__c;
        addMembership.contactKey1 = installment.cpm__Contact__r.NCT_Number__c;
        addMembership.contactKey2 = installment.Partner_Contact__r.NCT_Number__c;
        addMembership.mType = installment.Membership_Type__c;
        addMembership.amount = String.valueOf(installment.cpm__Amount__c);
        addMembership.txCode = installment.Id;
        return JSON.serialize(addMembership, true);
    }
    private abstract class CareBaseRequest {
        private String authKey {get;set;}
        private String pagename {get;set;}
        private String source {get;set;}
        private String branch {get;set;}
        private String userLogname {get;set;}
    }
    private class AddUpdateContactRequest extends CareBaseRequest {
        private String surname {get;set;}
        private String firstName {get;set;}
        private String contactNumber {get;set;}
        private String gender {get;set;}
        private String postcode {get;set;}
        private String email {get;set;}
        private String address {get;set;}
        private String town {get;set;}
        private String country {get;set;}
    }
    private class AddBankDetailsRequest extends CareBaseRequest {
        private String sortCode {get;set;}
        private String acctNumber {get;set;}
        private String acctName {get;set;}
        private String contactKey {get;set;}
    }
    private class AddMembership extends CareBaseRequest {
        private String paymentMethod {get;set;}
        private String bankDetailNumber {get;set;}
        private String claimDay {get;set;}
        private String ga_decl_1 {get;set;}
        private String ga_decl_2 {get;set;}
        private String contactKey1 {get;set;}
        private String contactKey2 {get;set;}
        private String mType {get;set;}
        private String amount {get;set;}
        private String txCode {get;set;}
    }
    private abstract class CareBaseResponse {
        public List<Map<String, String>> error {get;set;}
    }
    public class ContactOjbect extends CareBaseResponse {
        public ContactDetails contact {get;set;}
    }
    public class ContactDetails {
        public String contactKey {get;set;}
        public String contactNumber {get;set;}
    }
    public class ContactBankAccountObject extends CareBaseResponse {
        public ContactBankAccountDetails contactBankAccount {get;set;}
    }
    public class ContactBankAccountDetails {
        public String contactNumber {get;set;}
        public String bankDetailNumber {get;set;}
        public String information {get;set;}
    }
    public class MembershipOjbect extends CareBaseResponse {
        public String status {get;set;}
    }
}