force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Is_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Invoice</label>
    <referenceTo>Zumzum__Purchase_Invoice__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPaymentRunBuilder.cls
public with sharing class TestPaymentRunBuilder {
    
    private List<Payment_Run_Line_Item__c> lineItems {get; private set;}
    private Boolean insertRecord = true;

    public TestPaymentRunBuilder() {
        this.lineItems = new List<Payment_Run_Line_Item__c>();
    }

    
    public TestPaymentRunBuilder insertLineItem(Id purchaseInvoiceId, Boolean isEmailSent) {
        lineItems.add(new Payment_Run_Line_Item__c(
            Purchase_Invoice__c = purchaseInvoiceId,
            Is_Email_Sent__c = isEmailSent
        ));
        return this;
    }

    public TestPaymentRunBuilder insertLineItem(Id purchaseInvoiceId) {
        return insertLineItem(purchaseInvoiceId, false);
    }

    public Payment_Run__c build() {
        Payment_Run__c pr = new Payment_Run__c();
        insert pr;
        
        this.linkLineItems(pr);
        insert lineItems;

        lineItems.clear();
        return pr;
    }

    private void linkLineItems(Payment_Run__c pr) {
        for (Payment_Run_Line_Item__c item : lineItems) {
            item.Payment_Run__c = pr.Id;
        }
    }
}