force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRLineItem_PreventDeletion_TDTM_Test.cls
@SuppressWarnings('PMD.MethodNamingConventions')
//Incident #121 - https://confluence.nct.org.uk:8443/x/EoSO

@IsTest
public with sharing class PRLineItem_PreventDeletion_TDTM_Test {
    private static final String PAYMENT_RUN_STATUS_READY = 'Ready';
    private static final String PAYMENT_RUN_STATUS_CLOSED = 'Closed';
    private static final Integer COUNT_RECORDS = 2;

    private static final Map<String, String> TRIGGER_PARAMS = new Map<String, String> {
        'triggerHandlerName' => 'PRLineItem_PreventDeletion_TDTM',
        'className' => 'PRLineItem_PreventDeletion_TDTM',
        'objectAPIName' => 'Payment_Run_Line_Item__c',
        'triggerActions' => 'BeforeDelete',
        'isActive' => 'true',
        'loadOrder' => '0',
        'isAsynchronous' => 'false'
    };

    @TestSetup
    static void SetupTestData() {

        List<Payment_Run__c> paymentRunList = new List<Payment_Run__c>();
        for (Integer i = 0; i < COUNT_RECORDS; i++) {
            Payment_Run__c paymentRun = new Payment_Run__c();

            if (i > 0) {
                paymentRun.Status__c = PAYMENT_RUN_STATUS_READY;
            } else {
                paymentRun.Status__c = PAYMENT_RUN_STATUS_CLOSED;
            }

            paymentRunList.add(paymentRun);
        }

        insert paymentRunList;

        List<Payment_Run_Line_Item__c> paymentRunLineItemList = new List<Payment_Run_Line_Item__c>();
        for(Integer i = 0; i < COUNT_RECORDS; i++) {
            Payment_Run_Line_Item__c paymentRunLineItem = new Payment_Run_Line_Item__c();
            if ( i > 0) {
                paymentRunLineItem.Payment_Run__c = paymentRunList[i].Id;

            } else {
                paymentRunLineItem.Payment_Run__c = paymentRunList[i].Id;
            }

            paymentRunLineItemList.add(paymentRunLineItem);
        }

        insert paymentRunLineItemList;

        TestDataFactory.createTriggerSystemHandlerRecord(TRIGGER_PARAMS);
    }

    @IsTest
    public static void PreventDeletePRLineItems_SetRunPaymentStatusToReady_PreventedDeletingPRLineItemsRecord() {
        Payment_Run_Line_Item__c paymentRunLineItem = [SELECT Id, Payment_Run__r.Status__c FROM Payment_Run_Line_Item__c WHERE Payment_Run__r.Status__c = :PAYMENT_RUN_STATUS_READY LIMIT 1];
        Database.DeleteResult dataBaseResult;

        Test.startTest();
            dataBaseResult = Database.delete(paymentRunLineItem, false);
        Test.stopTest();

        System.assertEquals(System.Label.Delete_Payment_Run_Line_Item_Error_Text, dataBaseResult.getErrors()[0].getMessage(), 'Should be error message');
    }

    @IsTest
    public static void PreventDeletePRLineItems_SetRunPaymentStatusToClosed_PreventedDeletingPRLineItemsRecord() {
        Payment_Run_Line_Item__c paymentRunLineItem = [SELECT Id, Payment_Run__r.Status__c FROM Payment_Run_Line_Item__c WHERE Payment_Run__r.Status__c = :PAYMENT_RUN_STATUS_CLOSED LIMIT 1];
        Database.DeleteResult dataBaseResult;

        Test.startTest();
            dataBaseResult = Database.delete(paymentRunLineItem, false);
        Test.stopTest();

        System.assertEquals(System.Label.Delete_Payment_Run_Line_Item_Error_Text, dataBaseResult.getErrors()[0].getMessage(), 'Should be error message');
    }
}