force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Payment_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Bank Payment Line Items</relationshipLabel>
    <relationshipName>Bank_Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeneratePaymentFilePaymentRunExtension.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
//Incident #11 - https://confluence.nct.org.uk:8443/x/EoSO
public with sharing class GeneratePaymentFilePaymentRunExtension {

	// public Boolean showError { get; set;}
	// public String pageContent;
	// public String contentType;

    // private Id recordId;
    // private Payment_Run__c paymentRun;
	// private final String VALID_PAYMENT_RUN_STATUS = 'Ready';
	// private final String TXT_CONTENT_TYPE = 'text/plain#';
	// private final String HTML_CONTENT_TYPE = 'text/html';

	// public GeneratePaymentFilePaymentRunExtension(ApexPages.StandardController stdController){
	// 	this.recordId = stdController.getId();
	// }

	// public virtual void init(){
	// 	Payment_Run__c paymentRun = [
    //         SELECT Id, Status__c,
    //         (
    //             SELECT Id, Payment_Run__c, Zumzum__Bank_Payment__c, Zumzum__Purchase_Invoice__r.Name
    //             FROM Bank_Payment_Line_Items__r
    //         )
    //         FROM Payment_Run__c
    //         WHERE Id =: recordId
    //     ];

    //     this.paymentRun = paymentRun;
        
	// 	this.showError = paymentRun.Status__c != VALID_PAYMENT_RUN_STATUS;

	// 	if(this.showError) {
	// 		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Payment Run should be ready to generate Payment File'));
	// 	}
	// }

	// public String getPageContent(){
	// 	return this.showError ? '' : GeneratePaymentFileUtil.generatePaymentFileContent(paymentRun);
	// }

	// public String getContentType(){
	// 	return this.showError ? HTML_CONTENT_TYPE : TXT_CONTENT_TYPE + GeneratePaymentFileUtil.generatePaymentFileName();
	// }

}