force-app/main/default/objects/Payment_Run__c/Payment_Run__c.object-meta.xml
<CustomObject>
    <label>Payment Run</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/Payment_Run_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Run Line Item</label>
    <nameField>
        <displayFormat>PRLI{000000}</displayFormat>
        <label>Payment Run Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Run Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Payment_Run__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run__c</fullName>
    <label>Payment Run</label>
    <referenceTo>Payment_Run__c</referenceTo>
    <relationshipLabel>Payment Run Line Items</relationshipLabel>
    <relationshipName>Payment_Run_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Purchase_Invoice__r.Zumzum__Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRLineItem_PreventDeletion_TDTM.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
//Incident #119 - https://confluence.nct.org.uk:8443/x/EoSO
global with sharing class PRLineItem_PreventDeletion_TDTM extends npsp.TDTM_Runnable {
    @SuppressWarnings('PMD.ExcessiveParameterList')
    //Incident #120 - https://confluence.nct.org.uk:8443/x/EoSO

    private static final String PAYMENT_RUN_STATUS_DRAFT = 'Draft';
    private static final String PAYMENT_RUN_STATUS_FAILED = 'Failed To Create Transactions';

    global override npsp.TDTM_Runnable.DmlWrapper Run(List<SObject> triggerNew, List<SObject> triggerOld, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        List<Payment_Run_Line_Item__c> oldPaymentRunLineItemList = (List<Payment_Run_Line_Item__c>) triggerOld;

        if ( triggerAction == npsp.TDTM_Runnable.Action.BeforeDelete ) {
            preventPaymentRunLineItemDeletion(oldPaymentRunLineItemList);
        }

        return dmlWrapper;
    }

    private void preventPaymentRunLineItemDeletion(List<Payment_Run_Line_Item__c> oldPaymentRunLineItemList) {
        Set<Id> paymentRunLineItemPreventDeleteIds = getPaymentRunLineItemPreventDeleteIds(oldPaymentRunLineItemList);

        for (Payment_Run_Line_Item__c paymentRunLineItem : oldPaymentRunLineItemList) {

            if (paymentRunLineItemPreventDeleteIds.contains(paymentRunLineItem.Id)) {
                paymentRunLineItem.addError(System.Label.Delete_Payment_Run_Line_Item_Error_Text);
            }

        }
    }

    private Set<Id> getPaymentRunLineItemPreventDeleteIds(List<Payment_Run_Line_Item__c> oldPaymentRunLineItemList) {
        Map<Id, Payment_Run_Line_Item__c> paymentRunLineItemMap = new Map<Id, Payment_Run_Line_Item__c>( oldPaymentRunLineItemList );

        return new Map<Id, Payment_Run_Line_Item__c> (
            [
                SELECT Id, Payment_Run__r.Status__c 
                FROM Payment_Run_Line_Item__c
                WHERE  Id IN :paymentRunLineItemMap.keySet()
                       AND
                       Payment_Run__r.Status__c IN (:PAYMENT_RUN_STATUS_DRAFT, :PAYMENT_RUN_STATUS_FAILED)
                WITH SECURITY_ENFORCED
            ]
        ).keySet();
    }

}