force-app/main/default/objects/Branch_Weighting__c/Branch_Weighting__c.object-meta.xml
<CustomObject>
    <label>Branch Weighting</label>
    <nameField>
        <displayFormat>BW{00000}</displayFormat>
        <label>Branch Weighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branch Weightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Weighting__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branch Weightings</relationshipLabel>
    <relationshipName>Branch_Weightings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the branch record</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course (Branch)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BranchWeightingHelper.cls
public with sharing class BranchWeightingHelper {
   private static Date earliestWeightingStartDate;

   @InvocableMethod
   public static void updateFeesOnAffectedSessions(List<Branch_Weighting__c> updatedAndNewWeightings){
       getEarliestWeightingStartDate(updatedAndNewWeightings);

       Set<Id> branchIds = getBranchIds(updatedAndNewWeightings);
       List<Session__c> sessionsToProcess = getPotentiallyAffectedSessions(branchIds, earliestWeightingStartDate);
       SessionFeeHelper.assignFeeRatesToSessions(sessionsToProcess);
   }

   private static Set<Id> getBranchIds(List<Branch_Weighting__c> updatedAndNewWeightings){
       Set<Id> branchIds = new Set<Id>();
       for(Branch_Weighting__c weighting : updatedAndNewWeightings){
           branchIds.add(weighting.Branch__c);
       }
       return branchIds;
   }

   private static void getEarliestWeightingStartDate(List<Branch_Weighting__c> updatedAndNewWeightings){
       Date earliestWeightingStartDate;
       for(Branch_Weighting__c weighting : updatedAndNewWeightings){
           if(earliestWeightingStartDate == null || earliestWeightingStartDate > weighting.Start_Date__c){
               earliestWeightingStartDate = weighting.Start_Date__c;
           }
       }
   }

   private static List<Session__c> getPotentiallyAffectedSessions(Set<Id> branchIds, Date earliestWeightingStartDate){
       return [SELECT Id
               FROM Session__c
               WHERE Course__r.Branch__c IN :branchIds
                   AND Date__c >= :earliestWeightingStartDate];
   }
}