force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/Bank_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Number__c</fullName>
    <description>This field is mapped from BankDetailsNumber (Care)</description>
    <externalId>true</externalId>
    <label>Bank Details Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Add_Membership_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Care_Add_Membership_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CARE Add Membership Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Care_Status__c.field-meta.xml
<CustomField>
    <fullName>Care_Status__c</fullName>
    <label>CARE Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>GiftAid</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Care Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>The status of this Installment.</description>
    <inlineHelpText>The status of this Installment.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending recollection</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Recurring_Payment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Recurring Payments</relationshipLabel>
    <relationshipName>Recurring_Payments_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInstallmentBuilder.cls
@isTest
public with sharing class TestInstallmentBuilder {

    private Id accountId;
    private Id primaryContactId;
    private Id salesInvoiceId;
    private Id recurringPaymentId;
    private String bankDetailsNumber;
    private String paymentProfileId;
    private String status = 'Collected';
    private String careStatus = 'Waiting';
    private String paymentProcessor = 'PaymentHub-WorldPay';
    private String paymentMethod = 'CreditCard';
    private Boolean insertRecord = false;
    private Decimal amount = 1;
    private Integer careAddMembershipAttempts = 0;

    public TestInstallmentBuilder withAccount(Id accountId)
    {
        this.accountId = accountId;
        return this;
    }
    
    public TestInstallmentBuilder withAmount(Decimal amount)
    {
        this.amount = amount;
        return this;
    }

    public TestInstallmentBuilder withPrimaryContact(String primaryContactId)
    {
        this.primaryContactId = primaryContactId;
        return this;
    }

    public TestInstallmentBuilder withBankDetailsNumber(String bankDetailsNumber)
    {
        this.bankDetailsNumber = bankDetailsNumber;
        return this;
    }

    public TestInstallmentBuilder withStatus(String status)
    {
        this.status = status;
        return this;
    }

    public TestInstallmentBuilder withCareStatus(String careStatus)
    {
        this.careStatus = careStatus;
        return this;
    }

    public TestInstallmentBuilder withPaymentProfile(String paymentProfileId)
    {
        this.paymentProfileId = paymentProfileId;
        return this;
    }

    public TestInstallmentBuilder withPaymentProcessor(String paymentProcessor)
    {
        this.paymentProcessor = paymentProcessor;
        return this;
    }

    public TestInstallmentBuilder withPaymentMethod(String paymentMethod)
    {
        this.paymentMethod = paymentMethod;
        return this;
    }

    public TestInstallmentBuilder withSalesInvoice(Id salesInvoiceId)
    {
        this.salesInvoiceId = salesInvoiceId;
        return this;
    }

    public TestInstallmentBuilder withRecurringPayment(Id recurringPaymentId)
    {
        this.recurringPaymentId = recurringPaymentId;
        return this;
    }

    public TestInstallmentBuilder withCareAddMembershipAttempts(Integer careAddMembershipAttempts) {
        this.careAddMembershipAttempts = careAddMembershipAttempts;
        return this;
    }

    public TestInstallmentBuilder insertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public cpm__Installment__c build()
    {
        cpm__Installment__c installment = new cpm__Installment__c(
            cpm__Amount__c = this.amount,
            cpm__Payment_Profile__c = this.paymentProfileId,
            cpm__Contact__c = this.primaryContactId,
            Bank_Details_Number__c = this.bankDetailsNumber,
            cpm__Status__c = this.status,
            cpm__Payment_Method__c = this.paymentMethod,
            cpm__Payment_Processor__c = this.paymentProcessor,
            Sales_Invoice__c = salesInvoiceId,
            cpm__Recurring_Payment__c = recurringPaymentId,
            Care_Add_Membership_Attempts__c = this.careAddMembershipAttempts,
            Care_Status__c = this.careStatus
        );

        if(insertRecord)
        {
            insert installment;
        }

        return installment;
    }
}