force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>GiftAid</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Care Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/cpm__Payment__c.object
<CustomObject>
    <description>Payments are actual amounts of money transfered to our organisation, either spontaneously or as the result of a Recurring Payment.</description>
    <fields>
        <fullName>cpm__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Amount__c</fullName>
        <description>The amount of the payment.</description>
        <inlineHelpText>The amount of this payment.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cpm__Collection_Date__c</fullName>
        <description>The date this payment was collected.</description>
        <inlineHelpText>The date the Payment was collected.</inlineHelpText>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Installment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The installment this payment originated from.</description>
        <inlineHelpText>The installment this payment originated from.</inlineHelpText>
        <label>Installment</label>
        <referenceTo>cpm__Installment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
                <value>
                    <fullName>GiftAid</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>CASH</fullName>
                </value>
                <value>
                    <fullName>CHQ</fullName>
                </value>
                <value>
                    <fullName>SAGE</fullName>
                </value>
                <value>
                    <fullName>SO</fullName>
                </value>
                <value>
                    <fullName>DCR</fullName>
                </value>
                <value>
                    <fullName>CCCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpm__Payment_Processor__c</fullName>
        <label>Payment Processor</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>cpm__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentHub-Stripe</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-GiftAid</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-BACS</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpm__Payment_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The payment profile (IBAN) used to collect this payment.</description>
        <inlineHelpText>The payment profile (IBAN) used to collect this payment.</inlineHelpText>
        <label>Payment Profile</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>cpm__Payment_Profile__c.cpm__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>By default only active records are shown.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>cpm__Payment_Profile__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0}</displayFormat>
        <label>Payment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cpm__Payment_Profile__c.object
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <fields>
        <fullName>cpm__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor organization.</description>
        <inlineHelpText>The debitor organization.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Profiles</relationshipLabel>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The debitor.</description>
        <inlineHelpText>The debitor.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Payment_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPaymentBuilder.cls
@isTest
public with sharing class TestPaymentBuilder {

    private Id accountId;
    private Id primaryContactId;
    private Id paymentProfileId;
    private Id installmentId;
    private String paymentProcessor = 'PaymentHub-WorldPay';
    private String paymentMethod = 'CreditCard';
    private Boolean insertRecord = false;
    private Decimal amount = 1;
    private Date collectionDate = Date.today();

    public TestPaymentBuilder withAccount(Id accountId)
    {
        this.accountId = accountId;
        return this;
    }

    public TestPaymentBuilder withAmount(Decimal amount)
    {
        this.amount = amount;
        return this;
    }

    public TestPaymentBuilder withCollectionDate(Date collectionDate)
    {
        this.collectionDate = collectionDate;
        return this;
    }

    public TestPaymentBuilder withPrimaryContact(String primaryContactId)
    {
        this.primaryContactId = primaryContactId;
        return this;
    }

    public TestPaymentBuilder withPaymentProfile(String paymentProfileId)
    {
        this.paymentProfileId = paymentProfileId;
        return this;
    }

    public TestPaymentBuilder withPaymentProcessor(String paymentProcessor)
    {
        this.paymentProcessor = paymentProcessor;
        return this;
    }

    public TestPaymentBuilder withPaymentMethod(String paymentMethod)
    {
        this.paymentMethod = paymentMethod;
        return this;
    }

    public TestPaymentBuilder withInstallment(Id installmentId)
    {
        this.installmentId = installmentId;
        return this;
    }

    public TestPaymentBuilder insertRecord(Boolean insertRecord)
    {
        this.insertRecord = insertRecord;
        return this;
    }

    public cpm__Payment__c build()
    {
        cpm__Payment__c payment = new cpm__Payment__c(
            cpm__Account__c = this.accountId,
            cpm__Amount__c = this.amount,
            cpm__Collection_Date__c = this.collectionDate,
            cpm__Contact__c = this.primaryContactId,
            cpm__Installment__c = this.installmentId,
            cpm__Payment_Method__c = this.paymentMethod,
            cpm__Payment_Processor__c = this.paymentProcessor,
            cpm__Payment_Profile__c = this.paymentProfileId          
        );

        if(insertRecord)
        {
            insert payment;
        }

        return payment;
    }
}