force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>The status of this Installment.</description>
    <inlineHelpText>The status of this Installment.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending recollection</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/cpm__Payment__c.object
<CustomObject>
    <description>Payments are actual amounts of money transfered to our organisation, either spontaneously or as the result of a Recurring Payment.</description>
    <fields>
        <fullName>cpm__Amount__c</fullName>
        <description>The amount of the payment.</description>
        <inlineHelpText>The amount of this payment.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cpm__Installment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The installment this payment originated from.</description>
        <inlineHelpText>The installment this payment originated from.</inlineHelpText>
        <label>Installment</label>
        <referenceTo>cpm__Installment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpm__Payment_Processor__c</fullName>
        <label>Payment Processor</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>cpm__Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PaymentHub-Stripe</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-GiftAid</fullName>
                </value>
                <value>
                    <fullName>PaymentHub-BACS</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpm__Recurring_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Recurring Payment that resulted in this payment.</description>
        <inlineHelpText>The Recurring Payment that resulted in this payment.</inlineHelpText>
        <label>Recurring Payment</label>
        <referenceTo>cpm__Recurring_Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0}</displayFormat>
        <label>Payment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Recurring_Payment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Zumzum__Sales_Invoice__c</referenceTo>
    <relationshipLabel>Recurring Payments</relationshipLabel>
    <relationshipName>Recurring_Payments_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/Zumzum__Bank_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Receipt</label>
    <nameField>
        <displayFormat>BRUID-{0000000000}</displayFormat>
        <label>Bank Receipt UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zumzum__Bank_Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cpm__Payment__c</referenceTo>
    <relationshipLabel>Bank Receipts</relationshipLabel>
    <relationshipName>Bank_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddBankReceiptForWorldpayPaymentBatch.cls
//@SuppressWarnings('PMD.EmptyStatementBlock')
//Incident #XX - https://confluence.nct.org.uk:8443/x/EoSO
public class AddBankReceiptForWorldpayPaymentBatch implements Database.Batchable<sObject> {
    private static final String INSTALLMENT_STATUS = 'Collected';
    private static final String PAYMENT_PROCESSOR = 'PaymentHub-WorldPay';

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, cpm__Amount__c, cpm__Installment__r.Sales_Invoice__c, cpm__Installment__r.cpm__Recurring_Payment__r.Sales_Invoice__c FROM cpm__Payment__c WHERE cpm__Installment__r.cpm__Status__c =\'' +  INSTALLMENT_STATUS + '\' AND cpm__Installment__r.cpm__Payment_Processor__c =\'' + PAYMENT_PROCESSOR + '\' AND Id NOT IN (SELECT Payment__c FROM Zumzum__Bank_Receipt__c)');
    }

    public void execute(Database.BatchableContext bc, List<cpm__Payment__c> scope){
        AddBankReceiptForPaymentHandler.addBankReceipts(scope);
    }

    public void finish(Database.BatchableContext bc){
    
    }
}